import type {
  AnyRecord,
  WritingCockpitRole,
  WritingCockpitActionKey,
  WritingReadinessStatus,
  WritingReadinessCheck,
  WritingCockpitChapter,
  WritingQueueItemStatus,
  WritingQueueItem,
  WritingQueueModel,
  ChapterPlanningReadiness,
  ChapterContextPackageStatus,
  ChapterScenePlanStatus,
  ChapterPlanningDeskSceneCard,
  ChapterQualityContinuitySceneMapItem,
  ChapterWritePreparationBrief,
  ChapterPlanningDeskModel,
  ChapterAcceptanceStatus,
  DeslopGateDiagnosticsModel,
  ChapterAcceptanceDeskModel,
  ChapterHandoffStatus,
  ChapterHandoffDeskModel,
  LongformWorkflowStageKey,
  LongformWorkflowStageStatus,
  LongformWorkflowStageModel,
  LongformWorkflowModel,
  WritingCockpitModel,
  BuildWritingCockpitModelInput,
} from './types'
import { parseWorkspacePayload } from '../../payloadParseCache'


import {
  ACTION_LABELS,
  QUALITY_PASS_THRESHOLD,
  arrayValue,
  buildApprovalBlockerSummary,
  buildBlueprintReceiptSummary,
  buildDeliveryRiskReceiptSummary,
  buildDeslopGateDiagnosticsSummary,
  buildPlatformRubricSummary,
  buildQualityAuditSummary,
  buildRevisionReceiptSummary,
  buildSceneCardReceiptSummary,
  compareReviewRefs,
  countArray,
  createdTime,
  deliveryReceiptsFrom,
  firstNonEmpty,
  hasProse,
  issueText,
  latestReviewRef,
  parsedTime,
  proseQualityReviewMatchesCurrentChapter,
  qualityPayload,
  reportPayload,
  reviewPayload,
  reviewType,
  revisionPayload,
  storylineSyncPayload,
  stringArray,
  text,
  uniqueObjects,
  uniqueStrings,
} from './cockpit-basics'
import {
  buildAssetIntakeSummary,
  buildBenchmarkRecallSyncSummary,
  buildChapterAttractionSummary,
  buildChapterBenchmarkSyncSummary,
  buildChapterHandoffSyncSummary,
  buildCharacterArcSyncSummary,
  buildCoreDriftSummary,
  buildDeliveryRiskQueue,
  buildFirst30RetentionRecheckSummary,
  buildInnovationSyncSummary,
  buildIntentConfirmationSyncSummary,
  buildIpSceneIntakeSummary,
  buildPreDraftExecutionSyncSummary,
  buildQualityAuditRepairReceiptSyncSummary,
  buildQualityAuditSyncSummary,
  buildQualityCheckSummary,
  buildReadabilityReviewSummary,
  buildReaderExpectationSyncSummary,
  buildReaderPayoffSyncSummary,
  buildReaderRetentionSyncSummary,
  buildRunwaySyncSummary,
  buildSceneCardDirectiveSummary,
  buildSignatureSceneSyncSummary,
  buildStoryDriveSyncSummary,
  buildStoryUnitSyncSummary,
  buildStorylineSyncSummary,
  buildStyleSampleSyncSummary,
  buildVolumeBeatSyncSummary,
  mergeContractSyncSummary,
} from './cockpit-acceptance'

import {
  buildDeliveryRiskConvergenceSummary,
  buildGovernanceRecheckSyncSummary,
  extractQualityScore,
  resolveProseAdmission,
  normalizedAdmissionWarnings,
  normalizedPostCommitWarnings,
  hasUsableProseQualityReview,
  extractMustFix,
  extractOptionalImprovements,
  reportBelongsToCurrentQualityCycle,
  storyStateFailureMessages
} from './cockpit-acceptance-desk-utils'

export function buildHiddenAcceptanceDesk(): ChapterAcceptanceDeskModel {
  return {
    visible: false,
    acceptanceStatus: 'hidden',
    admissionStatus: '',
    qualityWarnings: [],
    storyStateStatus: '',
    storyStatePanel: null,
    postCommitWarnings: [],
    statusLabel: '等待正文',
    acceptanceReasons: ['本章还没有正文，先完成章节计划和初稿。'],
    storylineSync: null,
    storyUnitSync: null,
    assetIntake: null,
    ipSceneIntake: null,
    signatureSceneSync: null,
    readabilityReview: null,
    deslopGateDiagnostics: null,
    coreDrift: null,
    runwaySync: null,
    readerPayoffSync: null,
    readerExpectationSync: null,
    qualityAuditSync: null,
    qualityAuditRepairReceiptSync: null,
    chapterHandoffSync: null,
    chapterHandoffDeltaSync: null,
    writePreparation: null,
    intentConfirmationSync: null,
    benchmarkRecallSync: null,
    sourceReadiness: null,
    stateTracking: null,
    styleBoundary: null,
    informationFlow: null,
    expectationThreshold: null,
    storyLoop: null,
    emotionalArc: null,
    chapterHook: null,
    paragraphHook: null,
    suspense: null,
    assetLinkage: null,
    dialogue: null,
    plotDynamics: null,
    characterRelation: null,
    characterBehavior: null,
    conflictStructure: null,
    bridgeUnit: null,
    reversal: null,
    showdown: null,
    opening: null,
    proseCraft: null,
    punctuationTone: null,
    contentRubric: null,
    targetReader: null,
    genrePositioning: null,
    femaleAudience: null,
    upgradeRhythm: null,
    chapterStructure: null,
    chapterProgression: null,
    informationLoad: null,
    longformContinuity: null,
    coreContractCheck: null,
    continuityHeat: null,
    revisionReceiptCheck: null,
    deslopRepairCheck: null,
    proseMeta: null,
    serialRiskRepair: null,
    chapterHookQuality: null,
    readerRetentionCheck: null,
    readerRetentionSync: null,
    chapterAttraction: null,
    storyDriveSync: null,
    characterArcSync: null,
    chapterBenchmarkSync: null,
    styleSampleSync: null,
    first30RetentionRecheck: null,
    innovationSync: null,
    volumeBeatSync: null,
    blueprintReceipt: null,
    revisionReceipt: null,
    deliveryRiskReceipt: null,
    sceneCardReceipt: null,
    qualityAudit: null,
    platformRubric: null,
    approvalBlocker: null,
    governanceRecheckSync: null,
    deliveryRiskQueue: null,
    deliveryRiskConvergence: null,
    qualityScore: null,
    qualityStatus: '',
    mustFix: [],
    optionalImprovements: [],
    latestQualityReviewId: null,
    latestEditorReportId: null,
    latestRevisionReviewId: null,
    latestEditorReportSummary: '',
    latestRevisionSummary: '',
    storyStateSynced: false,
    recommendedAcceptanceAction: { key: 'write_draft', label: ACTION_LABELS.write_draft },
    secondaryActions: [],
    shouldAutoExpandAcceptance: false,
  }
}

