import { readFile, writeFile } from 'fs/promises'
import { join } from 'path'
import { Database } from 'bun:sqlite'

export type NovelProjectRecord = { id: number; title: string; genre?: string; sub_genres?: string[]; length_target?: string; target_audience?: string; style_tags?: string[]; commercial_tags?: string[]; status?: string; updated_at: string }
export type NovelWorldbuildingRecord = { id: number; project_id: number; world_summary?: string; rules?: string[]; factions?: any[]; locations?: any[]; systems?: any[]; timeline_anchor?: string; known_unknowns?: string[]; version?: number; created_at: string; updated_at: string }
export type NovelCharacterRecord = { id: number; project_id: number; name: string; role_type?: string; archetype?: string; motivation?: string; goal?: string; conflict?: string; updated_at: string }
export type NovelOutlineRecord = { id: number; project_id: number; outline_type?: string; title: string; summary?: string; conflict_points?: string[]; turning_points?: string[]; hook?: string; parent_id?: number | null; updated_at: string }
export type NovelChapterRecord = { id: number; project_id: number; chapter_no: number; title: string; chapter_goal?: string; chapter_summary?: string; conflict?: string; ending_hook?: string; chapter_text?: string; scene_breakdown?: any[]; continuity_notes?: string[]; status?: string; outline_id?: number | null; updated_at: string }
export type NovelChapterVersionRecord = { id: number; chapter_id: number; project_id: number; version_no: number; chapter_text: string; scene_breakdown: any[]; continuity_notes: string[]; source: 'manual_edit' | 'agent_execute' | 'repair' | 'rollback'; created_at: string }
export type NovelReviewRecord = { id: number; project_id: number; review_type: string; status: string; summary: string; issues: string[]; created_at: string; payload?: string }
export type NovelRunRecord = { id: number; project_id: number; run_type: string; step_name: string; status: string; input_ref?: string; output_ref?: string; duration_ms?: number; error_message?: string; created_at: string }

type NovelStore = { projects: NovelProjectRecord[]; worldbuilding: NovelWorldbuildingRecord[]; characters: NovelCharacterRecord[]; outlines: NovelOutlineRecord[]; chapters: NovelChapterRecord[]; chapter_versions: NovelChapterVersionRecord[]; reviews: NovelReviewRecord[]; runs: NovelRunRecord[] }

function nowIso() { return new Date().toISOString() }
function getNovelStorePath(activeWorkspace: string) { return join(activeWorkspace, 'novel-store.json') }
function toStringArray(value: any, fallback: string[] = []) { return Array.isArray(value) ? value.map(item => String(item)).filter(Boolean) : fallback }
function toAnyArray(value: any, fallback: any[] = []) { return Array.isArray(value) ? value : fallback }
function normalizeStore(store: Partial<NovelStore> | null | undefined): NovelStore { return { projects: Array.isArray(store?.projects) ? store!.projects : [], worldbuilding: Array.isArray(store?.worldbuilding) ? store!.worldbuilding : [], characters: Array.isArray(store?.characters) ? store!.characters : [], outlines: Array.isArray(store?.outlines) ? store!.outlines : [], chapters: Array.isArray(store?.chapters) ? store!.chapters : [], chapter_versions: Array.isArray(store?.chapter_versions) ? store!.chapter_versions : [], reviews: Array.isArray(store?.reviews) ? store!.reviews : [], runs: Array.isArray(store?.runs) ? store!.runs : [] } }
async function readJsonStore(activeWorkspace: string): Promise<NovelStore> { try { return normalizeStore(JSON.parse(await readFile(getNovelStorePath(activeWorkspace), 'utf8')) as Partial<NovelStore>) } catch { return normalizeStore(null) } }
async function writeJsonStore(activeWorkspace: string, store: NovelStore) { await writeFile(getNovelStorePath(activeWorkspace), `${JSON.stringify(normalizeStore(store), null, 2)}\n`, 'utf8') }
function dbPathFromEnv() { const raw = process.env.SQLITE_DATABASE_URL || process.env.DATABASE_URL || ''; if (!raw) return ''; if (raw.startsWith('file:')) return raw.slice(5).split('?', 1)[0]; return raw }
function openDb() { const dbPath = dbPathFromEnv(); return dbPath ? new Database(dbPath) : null }
function parseDbArray(value: any) { try { return value ? JSON.parse(String(value)) : [] } catch { return [] } }
function loadStoreFromDb(activeWorkspace: string): NovelStore {
  const db = openDb(); if (!db) return normalizeStore(null)
  try {
    const projects = db.query('SELECT * FROM projects ORDER BY updated_at DESC').all() as any[]
    const worldbuilding = db.query('SELECT * FROM worldbuilding').all() as any[]
    const characters = db.query('SELECT * FROM characters').all() as any[]
    const outlines = db.query('SELECT * FROM outlines').all() as any[]
    const chapters = db.query('SELECT * FROM chapters ORDER BY chapter_no ASC').all() as any[]
    const chapterVersions = db.query('SELECT * FROM chapter_versions ORDER BY created_at DESC').all() as any[]
    const reviews = db.query('SELECT * FROM reviews').all() as any[]
    const runs = db.query('SELECT * FROM runs ORDER BY created_at DESC').all() as any[]
    return {
      projects: projects.map(item => ({ ...item, sub_genres: parseDbArray(item.sub_genres), style_tags: parseDbArray(item.style_tags), commercial_tags: parseDbArray(item.commercial_tags) })),
      worldbuilding: worldbuilding.map(item => ({ ...item, rules: parseDbArray(item.rules), factions: parseDbArray(item.factions), locations: parseDbArray(item.locations), systems: parseDbArray(item.systems), known_unknowns: parseDbArray(item.known_unknowns) })),
      characters,
      outlines: outlines.map(item => ({ ...item, conflict_points: parseDbArray(item.conflict_points), turning_points: parseDbArray(item.turning_points) })),
      chapters: chapters.map(item => ({ ...item, scene_breakdown: parseDbArray(item.scene_breakdown), continuity_notes: parseDbArray(item.continuity_notes) })),
      chapter_versions: chapterVersions.map(item => ({ ...item, scene_breakdown: parseDbArray(item.scene_breakdown), continuity_notes: parseDbArray(item.continuity_notes) })),
      reviews: reviews.map(item => ({ ...item, issues: parseDbArray(item.issues), payload: item.payload || '' })),
      runs,
    }
  } finally { db.close() }
}
async function readStore(activeWorkspace: string): Promise<NovelStore> { const db = openDb(); if (db) return loadStoreFromDb(activeWorkspace); return readJsonStore(activeWorkspace) }
async function writeStore(activeWorkspace: string, store: NovelStore) { const db = openDb(); if (!db) return writeJsonStore(activeWorkspace, store); try { db.exec('BEGIN'); for (const table of ['projects','worldbuilding','characters','outlines','chapters','chapter_versions','reviews','runs']) db.exec(`DELETE FROM ${table}`); const insert = (sql: string, params: any[]) => db.query(sql).run(...params)
    for (const p of store.projects) insert('INSERT INTO projects (id,title,genre,sub_genres,length_target,target_audience,style_tags,commercial_tags,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)', [p.id,p.title,p.genre||'',JSON.stringify(p.sub_genres||[]),p.length_target||'medium',p.target_audience||'',JSON.stringify(p.style_tags||[]),JSON.stringify(p.commercial_tags||[]),p.status||'draft',p.created_at||nowIso(),p.updated_at||nowIso()])
    for (const w of store.worldbuilding) insert('INSERT INTO worldbuilding (id,project_id,world_summary,rules,factions,locations,systems,timeline_anchor,known_unknowns,version,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)', [w.id,w.project_id,w.world_summary||'',JSON.stringify(w.rules||[]),JSON.stringify(w.factions||[]),JSON.stringify(w.locations||[]),JSON.stringify(w.systems||[]),w.timeline_anchor||'',JSON.stringify(w.known_unknowns||[]),w.version||1,w.created_at||nowIso(),w.updated_at||nowIso()])
    for (const c of store.characters) insert('INSERT INTO characters (id,project_id,name,role_type,archetype,motivation,goal,conflict,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)', [c.id,c.project_id,c.name,c.role_type||'',c.archetype||'',c.motivation||'',c.goal||'',c.conflict||'',c.updated_at||nowIso(),c.updated_at||nowIso()])
    for (const o of store.outlines) insert('INSERT INTO outlines (id,project_id,outline_type,title,summary,conflict_points,turning_points,hook,parent_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)', [o.id,o.project_id,o.outline_type||'master',o.title,o.summary||'',JSON.stringify(o.conflict_points||[]),JSON.stringify(o.turning_points||[]),o.hook||'',o.parent_id ?? null,nowIso(),o.updated_at||nowIso()])
    for (const c of store.chapters) insert('INSERT INTO chapters (id,project_id,outline_id,chapter_no,title,chapter_goal,chapter_summary,conflict,ending_hook,chapter_text,scene_breakdown,continuity_notes,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)', [c.id,c.project_id,c.outline_id ?? null,c.chapter_no,c.title,c.chapter_goal||'',c.chapter_summary||'',c.conflict||'',c.ending_hook||'',c.chapter_text||'',JSON.stringify(c.scene_breakdown||[]),JSON.stringify(c.continuity_notes||[]),c.status||'draft',nowIso(),c.updated_at||nowIso()])
    for (const v of store.chapter_versions) insert('INSERT INTO chapter_versions (id,chapter_id,project_id,version_no,chapter_text,scene_breakdown,continuity_notes,source,created_at) VALUES (?,?,?,?,?,?,?,?,?)', [v.id,v.chapter_id,v.project_id,v.version_no,v.chapter_text||'',JSON.stringify(v.scene_breakdown||[]),JSON.stringify(v.continuity_notes||[]),v.source||'manual_edit',v.created_at||nowIso()])
    for (const r of store.reviews) insert('INSERT INTO reviews (id,project_id,review_type,status,summary,issues,payload,created_at) VALUES (?,?,?,?,?,?,?,?)', [r.id,r.project_id,r.review_type,r.status,r.summary||'',JSON.stringify(r.issues||[]),r.payload||'',r.created_at||nowIso()])
    for (const r of store.runs) insert('INSERT INTO runs (id,project_id,run_type,step_name,status,input_ref,output_ref,duration_ms,error_message,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)', [r.id,r.project_id,r.run_type,r.step_name,r.status,r.input_ref||'',r.output_ref||'',r.duration_ms||0,r.error_message||'',r.created_at||nowIso()])
    db.exec('COMMIT') } catch (e) { db.exec('ROLLBACK'); throw e } finally { db.close() } }
function normalizeProjectRecord(data: Partial<NovelProjectRecord>, existing?: Partial<NovelProjectRecord>): NovelProjectRecord { return { id: Number(existing?.id || data.id || 0), title: String(data.title ?? existing?.title ?? '未命名小说'), genre: String(data.genre ?? existing?.genre ?? ''), sub_genres: toStringArray(data.sub_genres ?? existing?.sub_genres), length_target: String(data.length_target ?? existing?.length_target ?? 'medium'), target_audience: String(data.target_audience ?? existing?.target_audience ?? ''), style_tags: toStringArray(data.style_tags ?? existing?.style_tags), commercial_tags: toStringArray(data.commercial_tags ?? existing?.commercial_tags), status: String(data.status ?? existing?.status ?? 'draft'), updated_at: String(existing?.updated_at ?? data.updated_at ?? nowIso()) } }
function normalizeWorldbuildingRecord(data: Partial<NovelWorldbuildingRecord>, existing?: Partial<NovelWorldbuildingRecord>): NovelWorldbuildingRecord { return { id: Number(existing?.id || data.id || 0), project_id: Number(data.project_id ?? existing?.project_id ?? 0), world_summary: String(data.world_summary ?? existing?.world_summary ?? ''), rules: toStringArray(data.rules ?? existing?.rules), factions: toAnyArray(data.factions ?? existing?.factions), locations: toAnyArray(data.locations ?? existing?.locations), systems: toAnyArray(data.systems ?? existing?.systems), timeline_anchor: String(data.timeline_anchor ?? existing?.timeline_anchor ?? ''), known_unknowns: toStringArray(data.known_unknowns ?? existing?.known_unknowns), version: Number(data.version ?? existing?.version ?? 1), created_at: String(existing?.created_at ?? data.created_at ?? nowIso()), updated_at: String(existing?.updated_at ?? data.updated_at ?? nowIso()) } }
function normalizeCharacterRecord(data: Partial<NovelCharacterRecord>, existing?: Partial<NovelCharacterRecord>): NovelCharacterRecord { return { id: Number(existing?.id || data.id || 0), project_id: Number(data.project_id ?? existing?.project_id ?? 0), name: String(data.name ?? existing?.name ?? '未命名角色'), role_type: String(data.role_type ?? existing?.role_type ?? ''), archetype: String(data.archetype ?? existing?.archetype ?? ''), motivation: String(data.motivation ?? existing?.motivation ?? ''), goal: String(data.goal ?? existing?.goal ?? ''), conflict: String(data.conflict ?? existing?.conflict ?? ''), updated_at: String(existing?.updated_at ?? data.updated_at ?? nowIso()) } }
function normalizeOutlineRecord(data: Partial<NovelOutlineRecord>, existing?: Partial<NovelOutlineRecord>): NovelOutlineRecord { return { id: Number(existing?.id || data.id || 0), project_id: Number(data.project_id ?? existing?.project_id ?? 0), outline_type: String(data.outline_type ?? existing?.outline_type ?? 'master'), title: String(data.title ?? existing?.title ?? '未命名大纲'), summary: String(data.summary ?? existing?.summary ?? ''), conflict_points: toStringArray(data.conflict_points ?? existing?.conflict_points), turning_points: toStringArray(data.turning_points ?? existing?.turning_points), hook: String(data.hook ?? existing?.hook ?? ''), parent_id: data.parent_id ?? existing?.parent_id ?? null, updated_at: String(existing?.updated_at ?? data.updated_at ?? nowIso()) } }
function normalizeChapterRecord(data: Partial<NovelChapterRecord>, existing?: Partial<NovelChapterRecord>): NovelChapterRecord { return { id: Number(existing?.id || data.id || 0), project_id: Number(data.project_id ?? existing?.project_id ?? 0), chapter_no: Number(data.chapter_no ?? existing?.chapter_no ?? 1), title: String(data.title ?? existing?.title ?? '第一章'), chapter_goal: String(data.chapter_goal ?? existing?.chapter_goal ?? ''), chapter_summary: String(data.chapter_summary ?? existing?.chapter_summary ?? ''), conflict: String(data.conflict ?? existing?.conflict ?? ''), ending_hook: String(data.ending_hook ?? existing?.ending_hook ?? ''), chapter_text: String(data.chapter_text ?? existing?.chapter_text ?? ''), scene_breakdown: toAnyArray(data.scene_breakdown ?? existing?.scene_breakdown), continuity_notes: toStringArray(data.continuity_notes ?? existing?.continuity_notes), status: String(data.status ?? existing?.status ?? 'draft'), outline_id: data.outline_id ?? existing?.outline_id ?? null, updated_at: String(existing?.updated_at ?? data.updated_at ?? nowIso()) } }
function normalizeReviewRecord(data: Partial<NovelReviewRecord>, existing?: Partial<NovelReviewRecord>): NovelReviewRecord { return { id: Number(existing?.id || data.id || 0), project_id: Number(data.project_id ?? existing?.project_id ?? 0), review_type: String(data.review_type ?? existing?.review_type ?? 'continuity'), status: String(data.status ?? existing?.status ?? 'ok'), summary: String(data.summary ?? existing?.summary ?? ''), issues: toStringArray(data.issues ?? existing?.issues), created_at: String(existing?.created_at ?? data.created_at ?? nowIso()), payload: String(data.payload ?? existing?.payload ?? '') } }
function normalizeRunRecord(data: Partial<NovelRunRecord>, existing?: Partial<NovelRunRecord>): NovelRunRecord { return { id: Number(existing?.id || data.id || 0), project_id: Number(data.project_id ?? existing?.project_id ?? 0), run_type: String(data.run_type ?? existing?.run_type ?? 'plan'), step_name: String(data.step_name ?? existing?.step_name ?? 'step'), status: String(data.status ?? existing?.status ?? 'pending'), input_ref: String(data.input_ref ?? existing?.input_ref ?? ''), output_ref: String(data.output_ref ?? existing?.output_ref ?? ''), duration_ms: Number(data.duration_ms ?? existing?.duration_ms ?? 0), error_message: String(data.error_message ?? existing?.error_message ?? ''), created_at: String(existing?.created_at ?? data.created_at ?? nowIso()) } }
export async function listNovelProjects(activeWorkspace: string) { const store = await readStore(activeWorkspace); return store.projects.sort((a, b) => b.updated_at.localeCompare(a.updated_at)) }
export async function createNovelProject(activeWorkspace: string, data: Partial<NovelProjectRecord>) { const store = await readStore(activeWorkspace); const project = normalizeProjectRecord(data, { id: store.projects.reduce((max, item) => Math.max(max, item.id), 0) + 1 }); store.projects.push(project); await writeStore(activeWorkspace, store); return project }
export async function getNovelProject(activeWorkspace: string, id: number) { const store = await readStore(activeWorkspace); return store.projects.find(item => item.id === id) || null }
export async function listNovelWorldbuilding(activeWorkspace: string, projectId: number) { const store = await readStore(activeWorkspace); return store.worldbuilding.filter(item => item.project_id === projectId) }
export async function createNovelWorldbuilding(activeWorkspace: string, data: Partial<NovelWorldbuildingRecord>) { const store = await readStore(activeWorkspace); const record = normalizeWorldbuildingRecord(data, { id: store.worldbuilding.reduce((max, item) => Math.max(max, item.id), 0) + 1 }); store.worldbuilding.push(record); await writeStore(activeWorkspace, store); return record }
export async function listNovelCharacters(activeWorkspace: string, projectId: number) { const store = await readStore(activeWorkspace); return store.characters.filter(item => item.project_id === projectId) }
export async function createNovelCharacter(activeWorkspace: string, data: Partial<NovelCharacterRecord>) { const store = await readStore(activeWorkspace); const record = normalizeCharacterRecord(data, { id: store.characters.reduce((max, item) => Math.max(max, item.id), 0) + 1 }); store.characters.push(record); await writeStore(activeWorkspace, store); return record }
export async function listNovelOutlines(activeWorkspace: string, projectId: number) { const store = await readStore(activeWorkspace); return store.outlines.filter(item => item.project_id === projectId) }
export async function createNovelOutline(activeWorkspace: string, data: Partial<NovelOutlineRecord>) { const store = await readStore(activeWorkspace); const record = normalizeOutlineRecord(data, { id: store.outlines.reduce((max, item) => Math.max(max, item.id), 0) + 1 }); store.outlines.push(record); await writeStore(activeWorkspace, store); return record }
export async function listNovelChapters(activeWorkspace: string, projectId: number) { const store = await readStore(activeWorkspace); return store.chapters.filter(item => item.project_id === projectId).sort((a, b) => a.chapter_no - b.chapter_no) }
export async function createNovelChapter(activeWorkspace: string, data: Partial<NovelChapterRecord>) { const store = await readStore(activeWorkspace); const record = normalizeChapterRecord(data, { id: store.chapters.reduce((max, item) => Math.max(max, item.id), 0) + 1 }); store.chapters.push(record); await writeStore(activeWorkspace, store); return record }
function createChapterVersionRecord(store: NovelStore, data: Partial<NovelChapterVersionRecord>): NovelChapterVersionRecord { return { id: store.chapter_versions.reduce((max, item) => Math.max(max, item.id), 0) + 1, chapter_id: Number(data.chapter_id || 0), project_id: Number(data.project_id || 0), version_no: Number(data.version_no || 1), chapter_text: String(data.chapter_text || ''), scene_breakdown: toAnyArray(data.scene_breakdown), continuity_notes: toStringArray(data.continuity_notes), source: data.source || 'manual_edit', created_at: String(data.created_at || nowIso()) } }
async function appendChapterVersion(activeWorkspace: string, data: Partial<NovelChapterVersionRecord>) { const store = await readStore(activeWorkspace); const record = createChapterVersionRecord(store, data); store.chapter_versions.push(record); await writeStore(activeWorkspace, store); return record }
export async function listChapterVersions(activeWorkspace: string, chapterId: number) { const store = await readStore(activeWorkspace); return store.chapter_versions.filter(item => item.chapter_id === chapterId).sort((a, b) => b.version_no - a.version_no) }
export async function rollbackChapterVersion(activeWorkspace: string, chapterId: number, versionId: number) { const store = await readStore(activeWorkspace); const idx = store.chapters.findIndex(item => item.id === chapterId); const version = store.chapter_versions.find(item => item.id === versionId && item.chapter_id === chapterId); if (idx < 0 || !version) return null; const current = store.chapters[idx]; store.chapter_versions.push(createChapterVersionRecord(store, { chapter_id: current.id, project_id: current.project_id, version_no: store.chapter_versions.filter(v => v.chapter_id === current.id).length + 1, chapter_text: current.chapter_text || '', scene_breakdown: current.scene_breakdown || [], continuity_notes: current.continuity_notes || [], source: 'rollback' })); store.chapters[idx] = { ...current, chapter_text: version.chapter_text, scene_breakdown: version.scene_breakdown || [], continuity_notes: version.continuity_notes || [], updated_at: nowIso() }; await writeStore(activeWorkspace, store); return store.chapters[idx] }
export async function updateNovelChapter(activeWorkspace: string, chapterId: number, data: Partial<NovelChapterRecord>) { const store = await readStore(activeWorkspace); const idx = store.chapters.findIndex(item => item.id === chapterId); if (idx < 0) return null; const current = store.chapters[idx]; store.chapter_versions.push(createChapterVersionRecord(store, { chapter_id: current.id, project_id: current.project_id, version_no: store.chapter_versions.filter(v => v.chapter_id === current.id).length + 1, chapter_text: current.chapter_text || '', scene_breakdown: current.scene_breakdown || [], continuity_notes: current.continuity_notes || [], source: 'manual_edit' })); const updated = normalizeChapterRecord(data, { ...current, id: current.id, updated_at: nowIso() }); store.chapters[idx] = { ...current, ...updated, updated_at: nowIso() }; await writeStore(activeWorkspace, store); return store.chapters[idx] }
export async function deleteNovelChapter(activeWorkspace: string, chapterId: number) { const store = await readStore(activeWorkspace); const chapter = store.chapters.find(item => item.id === chapterId); if (!chapter) return false; store.chapters = store.chapters.filter(item => item.id !== chapterId); store.chapter_versions = store.chapter_versions.filter(item => item.chapter_id !== chapterId); await writeStore(activeWorkspace, store); return true }
export async function deleteNovelOutline(activeWorkspace: string, outlineId: number) { const store = await readStore(activeWorkspace); const outline = store.outlines.find(item => item.id === outlineId); if (!outline) return false; store.outlines = store.outlines.filter(item => item.id !== outlineId); store.chapters = store.chapters.map(chapter => chapter.outline_id === outlineId ? { ...chapter, outline_id: null } : chapter); await writeStore(activeWorkspace, store); return true }
export async function deleteNovelProject(activeWorkspace: string, projectId: number) { const store = await readStore(activeWorkspace); const project = store.projects.find(item => item.id === projectId); if (!project) return false; store.projects = store.projects.filter(item => item.id !== projectId); store.worldbuilding = store.worldbuilding.filter(item => item.project_id !== projectId); store.characters = store.characters.filter(item => item.project_id !== projectId); store.outlines = store.outlines.filter(item => item.project_id !== projectId); store.chapters = store.chapters.filter(item => item.project_id !== projectId); store.chapter_versions = store.chapter_versions.filter(item => item.project_id !== projectId); store.reviews = store.reviews.filter(item => item.project_id !== projectId); store.runs = store.runs.filter(item => item.project_id !== projectId); await writeStore(activeWorkspace, store); return true }
export async function listNovelReviews(activeWorkspace: string, projectId: number) { const store = await readStore(activeWorkspace); return store.reviews.filter(item => item.project_id === projectId) }
export async function createNovelReview(activeWorkspace: string, data: Partial<NovelReviewRecord>) { const store = await readStore(activeWorkspace); const record = normalizeReviewRecord(data, { id: store.reviews.reduce((max, item) => Math.max(max, item.id), 0) + 1 }); store.reviews.push(record); await writeStore(activeWorkspace, store); return record }
export async function listNovelRuns(activeWorkspace: string, projectId: number) { const store = await readStore(activeWorkspace); return store.runs.filter(item => item.project_id === projectId).sort((a, b) => b.created_at.localeCompare(a.created_at)) }
export async function appendNovelRun(activeWorkspace: string, data: Partial<NovelRunRecord>) { const store = await readStore(activeWorkspace); const record = normalizeRunRecord(data, { id: store.runs.reduce((max, item) => Math.max(max, item.id), 0) + 1 }); store.runs.push(record); await writeStore(activeWorkspace, store); return record }
