import { buildWebnovelDraftPersonaBlock } from '../../novel-writing/webnovel-author-personas'
import {
  OH_STORY_BEAT_DENSITY_RULE,
} from '../quality/outline-blueprint-contracts'
import {
  buildWritingPrecisionPlan,
  formatWritingPrecisionPrompt,
} from '../../novel-writing/writing-precision-prompt'
import {
  buildAssetLinkagePromptSection,
  buildBenchmarkRecallPromptSection,
  buildBridgeUnitPromptSection,
  buildChapterBlueprintPromptSection,
  buildChapterHookPromptSection,
  buildChapterLaunchGatePromptSection,
  buildCharacterBehaviorPromptSection,
  buildCharacterRelationPromptSection,
  buildConflictStructurePromptSection,
  buildContentRubricPromptSection,
  buildContinuityHeatPromptSection,
  buildCoreContractRadarPromptSection,
  buildDeliveryRiskCarryOverPromptSection,
  buildDialoguePromptSection,
  buildEmotionalArcPromptSection,
  buildExpectationThresholdPromptSection,
  buildFemaleAudiencePromptSection,
  buildGenrePositioningPromptSection,
  buildGenreProseCardPromptSection,
  buildReaderContractProgressionPromptSection,
  buildGovernanceRecheckPromptSection,
  buildInformationFlowPromptSection,
  buildIntentConfirmationPromptSection,
  buildLongformBattleContextPromptSection,
  buildLongformCompassPromptSection,
  buildOpeningPromptSection,
  buildParagraphHookPromptSection,
  buildPlatformRubricPromptSection,
  buildPlotDynamicsPromptSection,
  buildPlotFrameworkPromptSection,
  buildPlotSpecialTopicsPromptSection,
  buildProseCraftPromptSection,
  buildPunctuationTonePromptSection,
  buildQualityAuditPromptSection,
  buildReversalPromptSection,
  buildShowdownPromptSection,
  buildStateTrackingPromptSection,
  buildStoryLoopPromptSection,
  buildStoryPowerPromptSection,
  buildStyleBoundaryPromptSection,
  buildSuspensePromptSection,
  buildTargetReaderPromptSection,
  buildTitleUniquenessPromptSection,
  buildUpgradeRhythmPromptSection,
  buildWritePreparationPromptSection,
} from '../../novel-writing/prose-generation-prompt-sections'
import {
  compactProseSceneCard,
} from '../../novel-writing/prose-prompt-context'

export function buildParagraphProsePromptLeadSections(ctx: any) {
  const {
    sceneBriefs,
    chapterPositioningBrief,
    longformCompass,
    longformBattleContext,
    chapterLaunchGate,
    governanceRecheckMemory,
    coreContractRadar,
    chapterBlueprint,
    beatDensityContract,
    smallOutlineContract,
    outlineMethodsContract,
    mainlineDefinitionContract,
    benchmarkRecallBrief,
    styleBoundaryContract,
    platformRubric,
    contentRubric,
    targetReaderContract,
    readerContractProgression,
    genreProseCardContract,
    genrePositioningContract,
    plotSpecialTopicsContract,
    femaleAudienceContract,
    upgradeRhythmContract,
    conflictStructureContract,
    storyLoopContract,
    emotionalArcContract,
    chapterHookContract,
    paragraphHookContract,
    suspenseContract,
    reversalContract,
    showdownContract,
    bridgeUnitContract,
    plotFrameworkContract,
    openingContract,
    proseCraftContract,
    punctuationToneContract,
    qualityAuditContract,
    dialogueContract,
    plotDynamicsContract,
    storyPowerContract,
    continuityHeatContract,
    characterRelationContract,
    characterBehaviorContract,
    assetLinkageContract,
    assetRelationshipGraphRisks,
    stateTrackingContract,
    intentConfirmationContract,
    informationFlowContract,
    expectationThresholdContract,
    deliveryRiskCarryOver,
    writePreparationBrief,
    previousHandoff,
    titleUniquenessReport,
    duplicateTitleRows,
    ohStoryDirectorPromptBlock,
    project,
    chapterDraft,
    contextPackage,
  } = ctx
  const writingPrecisionPlan = buildWritingPrecisionPlan({
    contextPackage,
    chapterDraft,
    wordTarget: contextPackage?.chapter_target?.word_target,
    modelRuntime: contextPackage?.runtime_model || contextPackage?.model_runtime || null,
    modelFamilyStrategy: contextPackage?.model_family_strategy || null,
  })
  return [
    buildWebnovelDraftPersonaBlock(ctx?.project || ctx?.novelProject || null),

    '任务：按场景卡生成章节正文。请先在心中按场景组织段落，再输出完整正文。',
    '硬性语言要求：chapter_text 必须使用简体中文，按中文网文“一句一段”为主的自然分段和中文引号输出；不得输出葡萄牙语、英语或拼音正文，外语只允许作为故事内必要专名少量出现。',
    `作品标题：${project.title}`,
    chapterDraft?.chapter_no ? `目标章节：第${chapterDraft.chapter_no}章《${chapterDraft.title || '无标题'}》` : '',
    chapterDraft?.chapter_no ? `只允许输出这一章的正文，不得混入其他章节内容。chapter_no 必须严格等于 ${chapterDraft.chapter_no}` : '',
    ...formatWritingPrecisionPrompt(writingPrecisionPlan),
    chapterPositioningBrief ? '【章节定位与对标结构坐标】' : '',
    chapterPositioningBrief ? '硬性要求：执行 chapter_target.chapter_positioning_brief；按章节定位决定冲突烈度、爽点密度、详略和章尾拉力。高压/推进章要有明确升级或回报；低压/过场章可弱钩子，但必须保留阶段目标、微好奇或关系期待。' : '',
    chapterPositioningBrief ? `chapter_target.chapter_positioning_brief：${JSON.stringify(chapterPositioningBrief).slice(0, 1800)}` : '',
    sceneBriefs.length ? `scene_cards.chapter_positioning：${sceneBriefs.map((scene: any) => `${scene.scene_no || ''}.${scene.title || '场景'}=${scene.chapter_positioning || chapterPositioningBrief.chapter_positioning || '推进'}${scene.pressure_level ? `/P${scene.pressure_level}` : ''}${scene.chapter_positioning_role ? `/${scene.chapter_positioning_role}` : ''}`).join('；')}` : '',
    chapterPositioningBrief?.benchmark_structure_coordinates?.length ? `对标结构坐标：${JSON.stringify(chapterPositioningBrief.benchmark_structure_coordinates).slice(0, 1600)}；只迁移结构功能位和节奏位置，不复制对标桥段、设定、人物或原句。` : '',
    sceneBriefs.length ? '【场景卡执行摘要】' : '',
    sceneBriefs.length ? JSON.stringify({ scene_cards: sceneBriefs.slice(0, 8).map(compactProseSceneCard) }, null, 2).slice(0, 3600) : '',
    ...buildTitleUniquenessPromptSection(titleUniquenessReport, duplicateTitleRows),
    '必须以 chapter_target.summary、chapter_target.conflict、chapter_target.ending_hook 和 scene_cards 为准；如果已有正文或旧场景分解与目标不一致，不得沿用。',
    'oh-story 日更工作流：生成正文前按 Step 2.1 标题预检、Step 2.2 状态筛选、Step 2.3 文风召回、Step 2.4 意图确认、章节蓝图/场景卡门禁执行；继续/续写/日更只表示继续当前日更批量流程，不得跳过 Step 2.2 状态筛选或 Step 2.3 文风召回；状态筛选只保留不知道就会写错的信息；正文后用回执闭环，不用任务书自述替代正文证据。',
    ohStoryDirectorPromptBlock,
    'oh-story 自然写作底线：正文按“动作 -> 对话 -> 情绪反应 -> 动作”循环推进，单写心理活动不得连续超过 2 段；情绪用身体动作、行为选择、对话反应或代价表现，不直接写“他很紧张/她很伤心”。',
    '句式节奏：打斗/紧张用 3-8 字短句制造速度，日常用 8-15 字承载动作和信息，描写句必须读起来不卡；长短句交错，不要通篇同长度、同语气、同段落密度。',
    '对白口吻：对话必须口语化，符合角色身份和关系阶段；不要把“我认为此事不妥”这类书面语塞进角色嘴里，能用动作或半句话表达的，不用旁白说明。',
    '章尾收束：章尾用动作、对话或悬念收束，让情节本身制造余韵；不得用总结性感悟、哲理升华或作者预告收尾，例如“他终于明白”“这一夜注定”“更大的风暴即将来临”。',
    '外部事实查证：如果写作涉及历史年代、地理方位、职业细节、法律/医疗/技术流程、真实机构或真实地名且当前上下文没有可靠来源，必须按 oh-story 资料研究流程标记待查证、改成架空/模糊表达，或把信息留作角色待验证线索；不得编造确定事实。',
    '',
    previousHandoff ? '【上一章尾段原文承接】' : '',
    previousHandoff ? '硬性要求：按 oh-story 日更串行流程，先读取上一章刚写入正文尾段再续写。前300字必须接住上一章最后一幕、动作链、角色反应、钩子、危机、欠账或未解问题；不能只复述摘要或改写成新的开场，也不得重新从泛环境描写、空泛醒来或无关解释开场。' : '',
    previousHandoff ? previousHandoff : '',
    '',
    ...buildWritePreparationPromptSection(writePreparationBrief),
    ...buildChapterBlueprintPromptSection({
      chapterBlueprint,
      beatDensityContract,
      smallOutlineContract,
      outlineMethodsContract,
      mainlineDefinitionContract,
      beatDensityFallbackRule: OH_STORY_BEAT_DENSITY_RULE,
    }),
    ...buildPlatformRubricPromptSection(platformRubric),
    ...buildContentRubricPromptSection(contentRubric),
    ...buildTargetReaderPromptSection(targetReaderContract),
    ...buildReaderContractProgressionPromptSection(readerContractProgression),
    ...buildGenreProseCardPromptSection(genreProseCardContract),
    ...buildGenrePositioningPromptSection(genrePositioningContract),
    ...buildPlotSpecialTopicsPromptSection(plotSpecialTopicsContract),
    ...buildFemaleAudiencePromptSection(femaleAudienceContract),
    ...buildUpgradeRhythmPromptSection(upgradeRhythmContract),
    ...buildConflictStructurePromptSection(conflictStructureContract),
    ...buildStoryLoopPromptSection(storyLoopContract),
    ...buildEmotionalArcPromptSection(emotionalArcContract),
    ...buildChapterHookPromptSection(chapterHookContract),
    ...buildParagraphHookPromptSection(paragraphHookContract),
    ...buildSuspensePromptSection(suspenseContract),
    ...buildReversalPromptSection(reversalContract),
    ...buildShowdownPromptSection(showdownContract),
    ...buildBridgeUnitPromptSection(bridgeUnitContract),
    ...buildPlotFrameworkPromptSection(plotFrameworkContract),
    ...buildOpeningPromptSection(openingContract),
    ...buildProseCraftPromptSection(proseCraftContract),
    ...buildPunctuationTonePromptSection(punctuationToneContract),
    ...buildQualityAuditPromptSection(qualityAuditContract),
    ...buildDialoguePromptSection(dialogueContract),
    ...buildPlotDynamicsPromptSection(plotDynamicsContract),
    ...buildStoryPowerPromptSection(storyPowerContract),
    ...buildContinuityHeatPromptSection(continuityHeatContract),
    ...buildCharacterRelationPromptSection(characterRelationContract),
    ...buildCharacterBehaviorPromptSection(characterBehaviorContract),
    ...buildAssetLinkagePromptSection(assetLinkageContract, assetRelationshipGraphRisks),
    ...buildStateTrackingPromptSection(stateTrackingContract),
    ...buildIntentConfirmationPromptSection(intentConfirmationContract),
    ...buildBenchmarkRecallPromptSection(benchmarkRecallBrief),
    ...buildStyleBoundaryPromptSection(styleBoundaryContract),
    ...buildInformationFlowPromptSection(informationFlowContract),
    ...buildExpectationThresholdPromptSection(expectationThresholdContract),
    ...buildDeliveryRiskCarryOverPromptSection(deliveryRiskCarryOver),
    ...buildLongformCompassPromptSection(longformCompass),
    ...buildLongformBattleContextPromptSection(longformBattleContext),
    ...buildChapterLaunchGatePromptSection(chapterLaunchGate),
    ...buildGovernanceRecheckPromptSection(governanceRecheckMemory),
    ...buildCoreContractRadarPromptSection(coreContractRadar),
  ]
}
