import {
  chapterNosBrief,
} from '../quality/memory-longform-contracts'
import {
  compactBriefText,
} from '../quality/text-utils'


export function buildParagraphProsePromptBodySections(ctx: any) {
  const {
    nextBatchBrief,
    expansionStructureDecision,
    defaultFiveChapterLaneRedesign,
    expansionStructureVerification,
    defaultFiveChapterRegression,
    defaultFiveChapterLaneTemplate,
    defaultFiveChapterLaneTemplateRequirementLabels,
    defaultFiveChapterLaneTemplateRepairSummaries,
    defaultFiveChapterLaneTemplateRepairActions,
    defaultFiveChapterLaneTemplateRedesignSource,
    defaultFiveChapterLaneTemplateTopFailed,
    defaultFiveChapterLaneTemplateRedesignLines,
    defaultFiveChapterLaneTemplateValidationStandard,
    defaultFiveChapterLaneTemplateRequiredReceipts,
    defaultFiveChapterLaneTemplateVersionId,
    defaultFiveChapterLaneTemplateProductionRelapseCount,
    defaultFiveChapterLaneTemplateProductionRelapseReview,
    defaultFiveChapterLaneTemplateProductionRelapseChapterNos,
    defaultFiveChapterLaneTemplateProductionRelapseRestoreNos,
    defaultFiveChapterLaneTemplateProductionRelapseValidationNos,
    defaultFiveChapterLaneTemplateProductionFailureReasons,
    defaultFiveChapterLaneTemplateProductionFailedRequirements,
    batchPreflight,
    batchDeliveryRiskCarryOver,
    batchCreationContractCarryOver,
    batchChapterHandoffContract,
    longformMemoryAnchor,
    longformMemoryCapsule,
    layeredMemoryContext,
    progressSummary,
    dailyContextSnapshot,
    foreshadowingConsistencyRadar,
    millionWordRunway,
    styleSampleStrategy,
    styleFingerprintHandoff,
    chapterBenchmarkStrategy,
    first30RetentionBrief,
    readerDropRiskBrief,
    goldenThreeBrief,
    storyPressureBrief,
    storyDriveBrief,
    serialRhythmBrief,
    pageTurnHookBrief,
    volumeClimaxBrief,
    recentFatigueBrief,
    readerExpectationDebtContext,
    storyUnitContext,
    signatureSceneBrief,
    innovationBrief,
    characterArcBrief,
  } = ctx
  return [
    nextBatchBrief ? '【本批连载任务书】' : '',
    nextBatchBrief ? '硬性要求：本章必须服务批次目标和当前章角色；不得提前消费后续章节爆点，不得跳过本章读者回报，不得抢跑批次后段的主线兑现。' : '',
    nextBatchBrief?.start_checklist?.length ? `批次开工清单：${nextBatchBrief.start_checklist.map((item: any) => `${item.label || item.key}：${item.detail || item.status}`).join('；')}` : '',
    nextBatchBrief?.workflow_rules?.length ? `批量流程规则：${nextBatchBrief.workflow_rules.join('；')}` : '',
    nextBatchBrief ? JSON.stringify(nextBatchBrief, null, 2).slice(0, 4000) : '',
    '',
    expansionStructureDecision ? '【扩批结构决策】' : '',
    expansionStructureDecision ? '硬性要求：执行 next_batch_brief.expansion_structure_decision；这是结构修复有效性对本批规模、段位职责和观察指标的最终判断。正文必须按 recommendation 执行，不得因为恢复扩批而淡化结构约束，也不得在小批验证或单章重构时抢跑后续批次。' : '',
    expansionStructureDecision?.recommendation ? `决策：${expansionStructureDecision.recommendation}` : '',
    expansionStructureDecision?.mode_label ? `模式：${expansionStructureDecision.mode_label}` : '',
    expansionStructureDecision?.target_chapter_count ? `目标批次：${expansionStructureDecision.target_chapter_count}章` : '',
    expansionStructureDecision?.segment_label ? `观察段位：${expansionStructureDecision.segment_label}` : '',
    expansionStructureDecision?.summary ? `有效性摘要：${expansionStructureDecision.summary}` : '',
    expansionStructureDecision?.instruction ? `执行口径：${expansionStructureDecision.instruction}` : '',
    expansionStructureDecision?.observation_metrics?.length ? `观察指标：${expansionStructureDecision.observation_metrics.join('；')}` : '',
    defaultFiveChapterLaneRedesign ? '默认5章档位结构重构：连续恢复判定失效后，本章不得只修单章句子，必须先重写默认 5 章档位的段位职责、冲突轮换、回报密度和章末追读模板。' : '',
    defaultFiveChapterLaneRedesign?.reason ? `重构来源：${defaultFiveChapterLaneRedesign.reason}` : '',
    defaultFiveChapterLaneRedesign?.relapse_count ? `连续恢复判定失效：${defaultFiveChapterLaneRedesign.relapse_count}次` : '',
    defaultFiveChapterLaneRedesign?.repeated_failure_reasons?.length ? `同维复发：${defaultFiveChapterLaneRedesign.repeated_failure_reasons.join('、')}` : '',
    defaultFiveChapterLaneRedesign?.segment_duty_rewrite ? `段位职责重写：${defaultFiveChapterLaneRedesign.segment_duty_rewrite}` : '',
    defaultFiveChapterLaneRedesign?.conflict_rotation ? `冲突轮换：${defaultFiveChapterLaneRedesign.conflict_rotation}` : '',
    defaultFiveChapterLaneRedesign?.payoff_density ? `回报密度：${defaultFiveChapterLaneRedesign.payoff_density}` : '',
    defaultFiveChapterLaneRedesign?.ending_hook_template ? `章末追读模板：${defaultFiveChapterLaneRedesign.ending_hook_template}` : '',
    defaultFiveChapterLaneRedesign ? '默认档位回执字段：expansion_structure_decision_execution 必须额外回填 default_lane_segment_duty_delivered(boolean)、default_lane_conflict_rotation_delivered(boolean)、default_lane_payoff_density_delivered(boolean)、default_lane_ending_hook_template_delivered(boolean)，并在 evidence 中说明四项模板如何落到正文。' : '',
    expansionStructureDecision ? '执行回执：scene_breakdown 中承担结构职责的场景必须回填 expansion_structure_decision_execution，字段包含 segment_role_delivered(boolean)、observation_metrics_delivered(boolean)、redesign_principles_delivered(boolean)、evidence(array)。' : '',
    expansionStructureDecision ? JSON.stringify(expansionStructureDecision, null, 2).slice(0, 3000) : '',
    '',
    expansionStructureVerification ? '【扩批结构验证】' : '',
    expansionStructureVerification ? '硬性要求：执行 next_batch_brief.expansion_structure_verification；这是已修复的5章扩批热区进入本轮2-3章验证，正文必须证明结构修复真的落地，而不是只声明已经修好。' : '',
    expansionStructureVerification?.repeated_hotspot_segment ? `${expansionStructureVerification.repeated_hotspot_segment.label || '复发段位'}连续 ${expansionStructureVerification.repeated_hotspot_segment.count || 0} 次成为扩批热区，本批必须反证同一段位不会再次只铺垫、掉回报或丢章末追读。` : '',
    expansionStructureVerification?.validation_chapter_nos?.length ? `验证章节：${expansionStructureVerification.validation_chapter_nos.map((chapterNo: number) => `第${chapterNo}章`).join('、')}` : '',
    expansionStructureVerification?.fixed_segment_role ? `固定段落职责：${expansionStructureVerification.fixed_segment_role}` : '',
    expansionStructureVerification?.conflict_rotation ? `冲突换源：${expansionStructureVerification.conflict_rotation}` : '',
    expansionStructureVerification?.explicit_payoff ? `显性回报：${expansionStructureVerification.explicit_payoff}` : '',
    expansionStructureVerification?.ending_hook_requirement ? `章末追读：${expansionStructureVerification.ending_hook_requirement}` : '',
    expansionStructureVerification?.structure_actions?.length ? `结构动作：${expansionStructureVerification.structure_actions.join('；')}` : '',
    defaultFiveChapterLaneTemplate ? `默认5章档位模板回检：${defaultFiveChapterLaneTemplate.summary || defaultFiveChapterLaneTemplate.label}` : '',
    defaultFiveChapterLaneTemplateRequirementLabels.length ? `四项模板：${defaultFiveChapterLaneTemplateRequirementLabels.join('、')}` : '',
    defaultFiveChapterLaneTemplate?.segment_duty_rewrite ? `段位职责重写：${defaultFiveChapterLaneTemplate.segment_duty_rewrite}` : '',
    defaultFiveChapterLaneTemplate?.conflict_rotation ? `冲突轮换：${defaultFiveChapterLaneTemplate.conflict_rotation}` : '',
    defaultFiveChapterLaneTemplate?.payoff_density ? `回报密度：${defaultFiveChapterLaneTemplate.payoff_density}` : '',
    defaultFiveChapterLaneTemplate?.ending_hook_template ? `章末追读模板：${defaultFiveChapterLaneTemplate.ending_hook_template}` : '',
    defaultFiveChapterLaneTemplateRedesignSource ? `模板重构来源：${defaultFiveChapterLaneTemplateRedesignSource}` : '',
    defaultFiveChapterLaneTemplateVersionId ? `模板版本：${defaultFiveChapterLaneTemplateVersionId}` : '',
    defaultFiveChapterLaneTemplateProductionRelapseCount ? `生产复发次数：${defaultFiveChapterLaneTemplateProductionRelapseCount}` : '',
    defaultFiveChapterLaneTemplateProductionRelapseChapterNos ? `生产复发章节：${defaultFiveChapterLaneTemplateProductionRelapseChapterNos}` : '',
    defaultFiveChapterLaneTemplateProductionRelapseValidationNos ? `生产复发前验证：${defaultFiveChapterLaneTemplateProductionRelapseValidationNos}` : '',
    defaultFiveChapterLaneTemplateProductionRelapseRestoreNos ? `生产恢复依据：${defaultFiveChapterLaneTemplateProductionRelapseRestoreNos}` : '',
    defaultFiveChapterLaneTemplateProductionFailureReasons.length ? `真实生产失败维度：${defaultFiveChapterLaneTemplateProductionFailureReasons.join('、')}` : '',
    defaultFiveChapterLaneTemplateProductionFailedRequirements.length ? `生产复发模板缺项：${defaultFiveChapterLaneTemplateProductionFailedRequirements.join('；')}` : '',
    defaultFiveChapterLaneTemplateProductionRelapseReview ? `模板版本后验验证：本轮3章验证批必须逐章对照 template_version_id ${defaultFiveChapterLaneTemplateVersionId || defaultFiveChapterLaneTemplateProductionRelapseReview.template_version_id || '当前版本'}${defaultFiveChapterLaneTemplateProductionRelapseChapterNos ? ` 和真实生产复发章节 ${defaultFiveChapterLaneTemplateProductionRelapseChapterNos}` : ''}，证明新版模板能修掉生产后验问题。` : '',
    defaultFiveChapterLaneTemplateTopFailed ? `高频缺项：${compactBriefText(defaultFiveChapterLaneTemplateTopFailed.label || defaultFiveChapterLaneTemplateTopFailed.key || '模板缺项')}失败 ${Number(defaultFiveChapterLaneTemplateTopFailed.failed_count ?? defaultFiveChapterLaneTemplateTopFailed.failedCount ?? 0)} 次` : '',
    ...defaultFiveChapterLaneTemplateRedesignLines.map(item => `重构模板：${item}`),
    defaultFiveChapterLaneTemplateValidationStandard.length ? `下一轮验证标准：${defaultFiveChapterLaneTemplateValidationStandard.join('；')}` : '',
    defaultFiveChapterLaneTemplateRequiredReceipts.length ? `逐章回填字段：${defaultFiveChapterLaneTemplateRequiredReceipts.join('、')}` : '',
    defaultFiveChapterLaneTemplateRepairSummaries.length ? `模板缺项修复：${defaultFiveChapterLaneTemplateRepairSummaries.join('；')}` : '',
    defaultFiveChapterLaneTemplateRepairActions.length ? `缺项修复动作：${defaultFiveChapterLaneTemplateRepairActions.join('；')}` : '',
    defaultFiveChapterLaneTemplate ? '默认档位模板验证要求：下一轮验证批逐章继承段位职责、冲突轮换、回报密度和章末追读模板，并逐章证明四项模板没有复发。' : '',
    defaultFiveChapterRegression ? `默认5章档位回退：${defaultFiveChapterRegression.summary || defaultFiveChapterRegression.label || '默认档位复发，需要回到3章验证批。'}` : '',
    defaultFiveChapterRegression?.default_batch_chapter_nos?.length ? `失效批次：${chapterNosBrief(defaultFiveChapterRegression.default_batch_chapter_nos)}` : '',
    defaultFiveChapterRegression?.restore_chapter_nos?.length ? `恢复依据：${chapterNosBrief(defaultFiveChapterRegression.restore_chapter_nos)}` : '',
    defaultFiveChapterRegression?.validation_chapter_nos?.length ? `前置3章验证：${chapterNosBrief(defaultFiveChapterRegression.validation_chapter_nos)}` : '',
    defaultFiveChapterRegression?.failure_reasons?.length ? `失败维度：${defaultFiveChapterRegression.failure_reasons.join('、')}` : '',
    defaultFiveChapterRegression ? '默认档位验证要求：本批每章都必须逐章证明核心守恒、显性回报和章末追读已经重新稳定；不能只修复单章句子，也不能把中段继续写成铺垫、转场或弱钩子。' : '',
    expansionStructureVerification ? JSON.stringify(expansionStructureVerification, null, 2).slice(0, 3000) : '',
    '',
    longformMemoryAnchor ? '【长篇正史锚点】' : '',
    longformMemoryAnchor ? '硬性要求：这是本批连续生产的压缩正史。角色状态、开放悬念、回报债务和核心承诺不得被改写、遗忘或绕开；新增情节必须从这些锚点自然推进。' : '',
    longformMemoryAnchor ? JSON.stringify(longformMemoryAnchor, null, 2).slice(0, 3000) : '',
    '',
    longformMemoryCapsule ? '【长篇记忆胶囊】' : '',
    longformMemoryCapsule ? '硬性要求：执行 chapter_target.longform_memory_capsule；这是本章必须召回的压缩正史。核心承诺、主线进度、角色状态、开放悬念、回报债务、正史事实和红线不得被遗忘、矛盾改写或跳过。' : '',
    '硬性要求：执行 chapter_target.established_events_contract；已锁正史事件（死亡方式、规则触发、能力代价等）在闪回或复述时不得改写 cause/mechanism/constraints，只能同义转述。',
    longformMemoryCapsule ? JSON.stringify(longformMemoryCapsule, null, 2).slice(0, 4000) : '',
    '',
    layeredMemoryContext ? '【长篇分层记忆】' : '',
    layeredMemoryContext ? '硬性要求：执行 chapter_target.layered_memory_context；近5章详记保留细节承接，十章概要只守阶段正史，卷级总览只守卷级方向。不得把近期状态、十章压缩事实和卷级红线互相覆盖。' : '',
    layeredMemoryContext?.recent_chapter_details?.length ? `近5章详记：${layeredMemoryContext.recent_chapter_details.join('；')}` : '',
    layeredMemoryContext?.ten_chapter_summaries?.length ? `十章概要：${layeredMemoryContext.ten_chapter_summaries.join('；')}` : '',
    layeredMemoryContext?.volume_overview?.length ? `卷级总览：${layeredMemoryContext.volume_overview.join('；')}` : '',
    layeredMemoryContext?.archive_refs?.length ? `归档索引：${layeredMemoryContext.archive_refs.join('；')}` : '',
    layeredMemoryContext?.red_lines?.length ? `分层记忆红线：${layeredMemoryContext.red_lines.join('；')}` : '',
    layeredMemoryContext ? JSON.stringify(layeredMemoryContext, null, 2).slice(0, 4000) : '',
    '',
    progressSummary ? '【日更进度断点】' : '',
    progressSummary ? '硬性要求：执行 story_state.progress_summary；这是 oh-story Step 4 从追踪/上下文.md 沉淀的续写断点。开篇必须承接最后完成章节后的状态，优先保留注意事项，不要把详细伏笔表、时间线表或角色状态表复制进正文。' : '',
    progressSummary?.last_completed_chapter ? `最后完成章节：第${progressSummary.last_completed_chapter}章` : '',
    progressSummary?.completed_chapter_count ? `本期完成：${progressSummary.completed_chapter_count}章` : '',
    progressSummary?.completed_word_count ? `本期字数：${progressSummary.completed_word_count}字` : '',
    progressSummary?.active_foreshadowing_count ? `活跃伏笔：${progressSummary.active_foreshadowing_count}条` : '',
    progressSummary?.recent_changed_characters?.length ? `最近变更角色：${progressSummary.recent_changed_characters.join('、')}` : '',
    progressSummary?.next_outline_status ? `下一章细纲状态：${progressSummary.next_outline_status}` : '',
    progressSummary?.notes?.length ? `注意事项：${progressSummary.notes.join('；')}` : '',
    progressSummary ? JSON.stringify(progressSummary, null, 2).slice(0, 2000) : '',
    '',
    dailyContextSnapshot ? '【日更上下文快照】' : '',
    dailyContextSnapshot ? '硬性要求：执行 story_state.daily_context_snapshot；这是 oh-story 完成后自动更新的追踪/上下文.md 快照。开篇必须接住当前位置、场景和情绪目标；写作变更要成为本章事实约束，待处理线索要么推进要么保持清晰债务。' : '',
    dailyContextSnapshot?.current_chapter ? `当前位置/章：第${dailyContextSnapshot.current_chapter}章` : '',
    dailyContextSnapshot?.current_scene ? `当前位置/场景：${dailyContextSnapshot.current_scene}` : '',
    dailyContextSnapshot?.current_emotion_target ? `当前位置/情绪目标：${dailyContextSnapshot.current_emotion_target}` : '',
    dailyContextSnapshot?.writing_changes?.length ? `本次写作变更：${dailyContextSnapshot.writing_changes.join('；')}` : '',
    dailyContextSnapshot?.pending_clues?.length ? `待处理线索：${dailyContextSnapshot.pending_clues.join('；')}` : '',
    dailyContextSnapshot ? JSON.stringify(dailyContextSnapshot, null, 2).slice(0, 2000) : '',
    '',
    foreshadowingConsistencyRadar ? '【伏笔一致性雷达】' : '',
    foreshadowingConsistencyRadar ? '硬性要求：执行 oh-story consistency-checker 的伏笔状态扫描；这是事实一致性债务，不是文学评价。活跃伏笔必须保持存在感，超期伏笔要推进、暂缓说明或进入回收路径；回收时不得改写角色知识边界、时间线、物品归属或后续新增设定。' : '',
    foreshadowingConsistencyRadar?.active_count ? `活跃伏笔：${foreshadowingConsistencyRadar.active_count}条` : '',
    foreshadowingConsistencyRadar?.overdue_count ? `超期伏笔：${foreshadowingConsistencyRadar.overdue_count}条` : '',
    foreshadowingConsistencyRadar?.active?.length ? `活跃伏笔清单：${foreshadowingConsistencyRadar.active.join('；')}` : '',
    foreshadowingConsistencyRadar?.overdue?.length ? `超期伏笔清单：${foreshadowingConsistencyRadar.overdue.join('；')}` : '',
    foreshadowingConsistencyRadar?.density_warnings?.length ? `伏笔密度提醒：${foreshadowingConsistencyRadar.density_warnings.join('；')}` : '',
    foreshadowingConsistencyRadar?.scope_rules?.length ? `伏笔盘点范围：${foreshadowingConsistencyRadar.scope_rules.join('；')}` : '',
    foreshadowingConsistencyRadar?.status_rules?.length ? `伏笔状态语义：${foreshadowingConsistencyRadar.status_rules.join('；')}` : '',
    foreshadowingConsistencyRadar?.guardrails?.length ? `一致性红线：${foreshadowingConsistencyRadar.guardrails.join('；')}` : '',
    foreshadowingConsistencyRadar ? JSON.stringify(foreshadowingConsistencyRadar, null, 2).slice(0, 2400) : '',
    '',
    styleFingerprintHandoff ? '【文风指纹断点】' : '',
    styleFingerprintHandoff ? '硬性要求：执行 story_state.style_fingerprint；这是 oh-story 追踪/上下文.md 的文风指纹锚。续写只承接剧情、状态和情绪债，不继承可能已漂移的上一章句式节奏。写完后按目标句长带检查碎句、逗号结巴和中长句呼吸。' : '',
    styleFingerprintHandoff?.target_sentence_band ? `目标句长带：${styleFingerprintHandoff.target_sentence_band}` : '',
    styleFingerprintHandoff?.style_fingerprint ? `文风指纹：${styleFingerprintHandoff.style_fingerprint}` : '',
    styleFingerprintHandoff?.policy ? `防漂移策略：${styleFingerprintHandoff.policy}` : '',
    styleFingerprintHandoff?.source_excerpt ? `来源摘录：${styleFingerprintHandoff.source_excerpt}` : '',
    styleFingerprintHandoff ? JSON.stringify(styleFingerprintHandoff, null, 2).slice(0, 1600) : '',
    '',
    storyUnitContext ? '【剧情单元任务】' : '',
    storyUnitContext ? '硬性要求：执行 chapter_target.story_unit_context；本章只完成 current_chapter_role，并服务 unit_goal。可以铺垫 pressure_escalation 和 setup_and_storyline，但不得提前消费 mini_climax_payoff、exit_hook 或 forbidden_advance 中的后段爆点。' : '',
    storyUnitContext ? JSON.stringify(storyUnitContext, null, 2).slice(0, 4000) : '',
    '',
    storyPressureBrief ? '【故事压力阶梯】' : '',
    storyPressureBrief ? '硬性要求：执行 chapter_target.story_pressure_brief；本章必须把压力源、冲突升级、赌注升级和反转逼迫写成可见事件。不得只平铺过场、复述设定或让主角无代价通关。' : '',
    storyPressureBrief?.pressure_sources?.length ? `压力源：${storyPressureBrief.pressure_sources.join('；')}` : '',
    storyPressureBrief?.conflict_escalation_guardrail ? `冲突升级：${storyPressureBrief.conflict_escalation_guardrail}` : '',
    storyPressureBrief?.stakes_growth_guardrail ? `赌注升级：${storyPressureBrief.stakes_growth_guardrail}` : '',
    storyPressureBrief?.reversal_pressure_guardrail ? `反转逼迫：${storyPressureBrief.reversal_pressure_guardrail}` : '',
    storyPressureBrief?.required_actions?.length ? `执行动作：${storyPressureBrief.required_actions.join('；')}` : '',
    storyPressureBrief ? JSON.stringify(storyPressureBrief, null, 2).slice(0, 4000) : '',
    '',
    storyDriveBrief ? '【主角能动性】' : '',
    storyDriveBrief ? '硬性要求：执行 chapter_target.story_drive_brief；本章必须让主角在压力下做出主动选择，并写清阻碍、选择代价、状态变化和下一步因果。不得让主角只听解释、等别人推动或无代价通关。' : '',
    storyDriveBrief?.obstacle ? `明确阻碍：${storyDriveBrief.obstacle}` : '',
    storyDriveBrief?.protagonist_choice ? `主角选择：${storyDriveBrief.protagonist_choice}` : '',
    storyDriveBrief?.choice_cost ? `选择代价：${storyDriveBrief.choice_cost}` : '',
    storyDriveBrief?.state_change ? `状态变化：${storyDriveBrief.state_change}` : '',
    storyDriveBrief?.causal_next_step ? `下一步因果：${storyDriveBrief.causal_next_step}` : '',
    storyDriveBrief?.required_actions?.length ? `执行动作：${storyDriveBrief.required_actions.join('；')}` : '',
    storyDriveBrief ? JSON.stringify(storyDriveBrief, null, 2).slice(0, 4000) : '',
    '',
    serialRhythmBrief ? '【连载节奏与回报密度】' : '',
    serialRhythmBrief ? '硬性要求：执行 chapter_target.serial_rhythm_brief；开篇钩子、中段回报密度、场景回报预算和章末追读必须写成正文中的可见行动、信息变化、反转、爽点或未解问题。不得用长解释、纯环境、心理总结或无效对话拖字数。' : '',
    serialRhythmBrief?.opening_hook_deadline ? `开篇钩子：${serialRhythmBrief.opening_hook_deadline}` : '',
    serialRhythmBrief?.payoff_interval ? `回报密度：${serialRhythmBrief.payoff_interval}` : '',
    serialRhythmBrief?.middle_guardrail ? `中段节奏：${serialRhythmBrief.middle_guardrail}` : '',
    serialRhythmBrief?.ending_hook_guardrail ? `章末追读：${serialRhythmBrief.ending_hook_guardrail}` : '',
    serialRhythmBrief?.scene_payoff_budget?.length ? `场景回报预算：${serialRhythmBrief.scene_payoff_budget.map((item: any) => `${item.scene_no || ''}.${item.title || '场景'}：${item.required_payoff || item.turn || item.ending_hook_seed || '必须有可见回报'}`).join('；')}` : '',
    serialRhythmBrief?.anti_drag_rules?.length ? `防水规则：${serialRhythmBrief.anti_drag_rules.join('；')}` : '',
    serialRhythmBrief ? JSON.stringify(serialRhythmBrief, null, 2).slice(0, 4000) : '',
    '',
    pageTurnHookBrief ? '【章末翻页钩子】' : '',
    pageTurnHookBrief ? '硬性要求：执行 chapter_target.page_turn_hook_brief；最后 300 字必须形成清晰翻页冲动。可见触发要落成角色现场看见、听见、拿到、失去、被迫选择或被反转击中；读者问题必须留到下一章推动；禁提前解答项不得在本章解释完。' : '',
    pageTurnHookBrief?.hook_type ? `钩子类型：${pageTurnHookBrief.hook_type}` : '',
    pageTurnHookBrief?.core_question ? `读者问题：${pageTurnHookBrief.core_question}` : '',
    pageTurnHookBrief?.visible_trigger ? `可见触发：${pageTurnHookBrief.visible_trigger}` : '',
    pageTurnHookBrief?.final_image ? `最后画面：${pageTurnHookBrief.final_image}` : '',
    pageTurnHookBrief?.next_chapter_pull ? `下一章拉力：${pageTurnHookBrief.next_chapter_pull}` : '',
    pageTurnHookBrief?.forbidden_resolution?.length ? `禁提前解答：${pageTurnHookBrief.forbidden_resolution.join('；')}` : '',
    pageTurnHookBrief?.required_actions?.length ? `执行动作：${pageTurnHookBrief.required_actions.join('；')}` : '',
    pageTurnHookBrief ? JSON.stringify(pageTurnHookBrief, null, 2).slice(0, 4000) : '',
    '',
    volumeClimaxBrief ? '【卷级高潮预算】' : '',
    volumeClimaxBrief ? '硬性要求：执行 chapter_target.volume_climax_brief；本章只兑现 current_chapter_role、required_beats 和 climax_promise，不得提前消费 forbidden_payoff 标注的卷末爆点、身份答案、终局反转或后续大回报。' : '',
    volumeClimaxBrief?.current_volume_title ? `当前卷：${volumeClimaxBrief.current_volume_title}` : '',
    volumeClimaxBrief?.chapter_range ? `卷区间：${volumeClimaxBrief.chapter_range}` : '',
    volumeClimaxBrief?.current_chapter_role ? `本章职责：${volumeClimaxBrief.current_chapter_role}` : '',
    volumeClimaxBrief?.volume_goal ? `卷目标：${volumeClimaxBrief.volume_goal}` : '',
    volumeClimaxBrief?.climax_promise ? `高潮承诺：${volumeClimaxBrief.climax_promise}` : '',
    volumeClimaxBrief?.required_beats?.length ? `必须兑现：${volumeClimaxBrief.required_beats.join('；')}` : '',
    volumeClimaxBrief?.forbidden_payoff?.length ? `禁提前消费：${volumeClimaxBrief.forbidden_payoff.join('；')}` : '',
    volumeClimaxBrief?.nearby_beats?.length ? `邻近爆点：${volumeClimaxBrief.nearby_beats.map((item: any) => `${item.chapter_no ? `第${item.chapter_no}章` : ''}${item.type ? `${item.type}` : ''}${item.label ? `《${item.label}》` : ''}${item.detail ? `：${item.detail}` : ''}`).join('；')}` : '',
    volumeClimaxBrief?.next_actions?.length ? `执行动作：${volumeClimaxBrief.next_actions.join('；')}` : '',
    volumeClimaxBrief ? JSON.stringify(volumeClimaxBrief, null, 2).slice(0, 4000) : '',
    '',
    recentFatigueBrief ? '【近章连载动能与疲劳规避】' : '',
    recentFatigueBrief ? '硬性要求：执行 chapter_target.recent_fatigue_brief，并逐条执行 next_actions；本章必须主动修复最近章节暴露的连载动能、冲突来源、回报形态、章末问题或可视化场面风险。不得为了稳妥继续复刻同一种压迫、同一种打脸、同一种悬念，也不得跳过两章/五章窗口里的写前预警。' : '',
    recentFatigueBrief?.chapter_range_label ? `观察区间：${recentFatigueBrief.chapter_range_label}` : '',
    Number.isFinite(Number(recentFatigueBrief?.score)) ? `疲劳分：${recentFatigueBrief.score}` : '',
    recentFatigueBrief?.summary ? `疲劳概览：${recentFatigueBrief.summary}` : '',
    recentFatigueBrief?.fatigue_risks?.length ? `疲劳风险：${recentFatigueBrief.fatigue_risks.join('；')}` : '',
    recentFatigueBrief?.conflict_variation ? `冲突换源：${recentFatigueBrief.conflict_variation}` : '',
    recentFatigueBrief?.payoff_variation ? `回报换形：${recentFatigueBrief.payoff_variation}` : '',
    recentFatigueBrief?.hook_variation ? `钩子换题：${recentFatigueBrief.hook_variation}` : '',
    recentFatigueBrief?.scene_freshness ? `场面新鲜度：${recentFatigueBrief.scene_freshness}` : '',
    recentFatigueBrief?.next_actions?.length ? `执行动作：${recentFatigueBrief.next_actions.join('；')}` : '',
    recentFatigueBrief ? JSON.stringify(recentFatigueBrief, null, 2).slice(0, 4000) : '',
    '',
    signatureSceneBrief ? '【本章标志性场面补位】' : '',
    signatureSceneBrief ? '硬性要求：必须把 signature_scene 写成正文核心场面；scene_repair_target 是本章要修复的强场面缺口；reader_payoff 和 storyline_service 必须落成可见爽点、冲突结果或主线推进。不能只在旁白里声明“场面很震撼”。' : '',
    signatureSceneBrief ? JSON.stringify(signatureSceneBrief, null, 2).slice(0, 3000) : '',
    '',
    characterArcBrief && Object.keys(characterArcBrief).length ? '【人物成长承接】' : '',
    characterArcBrief && Object.keys(characterArcBrief).length ? '硬性要求：执行 chapter_target.character_arc_brief；本章必须把角色欲望、缺陷受压、关系变化、成长节点和口吻锚点写成可见选择、行动后果、对话反馈或关系反应。不得只在旁白里说人物成长，不得提前揭露 forbidden_reveal。' : '',
    characterArcBrief && Object.keys(characterArcBrief).length ? JSON.stringify(characterArcBrief, null, 2).slice(0, 4000) : '',
    '',
    batchPreflight ? '【安全连写预执行门禁】' : '',
    batchPreflight ? '硬性要求：本章必须服从安全连写预执行门禁；若存在近10章疲劳、批次任务书缺口、被拦截章节或 caution/warn 风险，本章必须主动换冲突来源、回报形态、章末问题或可视化场面，不能沿用上一批同质化写法。' : '',
    batchPreflight ? JSON.stringify(batchPreflight, null, 2).slice(0, 4000) : '',
    '',
    batchChapterHandoffContract ? '【安全连写章节交接契约】' : '',
    batchChapterHandoffContract ? '硬性要求：执行 batch_preflight.chapter_handoff_contract；这是安全连写启动时从上一章交接单和读者期待账提炼出的连续性契约。开篇前 300 字必须承接 previous_handoff 和 opening_obligations；must_deliver 必须写成可见回报；keep_alive 必须保持存在感；overdue 必须优先推进，不能被新剧情覆盖。' : '',
    batchChapterHandoffContract?.from_chapter_no ? `交接来源：第${batchChapterHandoffContract.from_chapter_no}章` : '',
    batchChapterHandoffContract?.apply_to_chapter_no ? `优先落点：第${batchChapterHandoffContract.apply_to_chapter_no}章` : '',
    batchChapterHandoffContract?.previous_handoff ? `上一章最后一幕：${batchChapterHandoffContract.previous_handoff}` : '',
    batchChapterHandoffContract?.opening_obligations?.length ? `开篇义务：${batchChapterHandoffContract.opening_obligations.join('；')}` : '',
    batchChapterHandoffContract?.expectation_carry_over?.length ? `期待承接：${batchChapterHandoffContract.expectation_carry_over.join('；')}` : '',
    batchChapterHandoffContract?.must_deliver?.length ? `必须兑现：${batchChapterHandoffContract.must_deliver.join('；')}` : '',
    batchChapterHandoffContract?.keep_alive?.length ? `继续悬念：${batchChapterHandoffContract.keep_alive.join('；')}` : '',
    batchChapterHandoffContract?.overdue?.length ? `逾期优先：${batchChapterHandoffContract.overdue.join('；')}` : '',
    batchChapterHandoffContract ? JSON.stringify(batchChapterHandoffContract, null, 2).slice(0, 3000) : '',
    '',
    batchDeliveryRiskCarryOver ? '【安全连写交稿风险承接】' : '',
    batchDeliveryRiskCarryOver ? '硬性要求：执行 batch_preflight.delivery_risk_carry_over；这是安全连写启动时从上一章交稿状态带来的风险债务，本章必须把它们写成开篇承接、中段推进和章末追读动作，不能只在旁白中宣布已修复。' : '',
    batchDeliveryRiskCarryOver?.source_chapter_no ? `风险来源：第${batchDeliveryRiskCarryOver.source_chapter_no}章` : '',
    batchDeliveryRiskCarryOver?.apply_to_chapter_no ? `优先落点：第${batchDeliveryRiskCarryOver.apply_to_chapter_no}章` : '',
    batchDeliveryRiskCarryOver?.priority_label ? `优先级：${batchDeliveryRiskCarryOver.priority_label}` : '',
    batchDeliveryRiskCarryOver?.items?.length ? `风险项：${batchDeliveryRiskCarryOver.items.join('；')}` : '',
    batchDeliveryRiskCarryOver?.required_actions?.length ? `修复动作：${batchDeliveryRiskCarryOver.required_actions.join('；')}` : '',
    batchDeliveryRiskCarryOver?.opening_actions?.length ? `开篇动作：${batchDeliveryRiskCarryOver.opening_actions.join('；')}` : '',
    batchDeliveryRiskCarryOver?.middle_actions?.length ? `中段动作：${batchDeliveryRiskCarryOver.middle_actions.join('；')}` : '',
    batchDeliveryRiskCarryOver?.ending_actions?.length ? `章末动作：${batchDeliveryRiskCarryOver.ending_actions.join('；')}` : '',
    batchDeliveryRiskCarryOver ? JSON.stringify(batchDeliveryRiskCarryOver, null, 2).slice(0, 3000) : '',
    batchCreationContractCarryOver ? '【安全连写创作契约承接】' : '',
    batchCreationContractCarryOver ? '硬性要求：执行 batch_preflight.delivery_risk_carry_over.creation_contract_carry_over；这是安全连写第一章必须优先修复的长篇创作契约债务，不能只在旁白中声明契约已修复。' : '',
    batchCreationContractCarryOver?.priority_label ? `契约优先级：${batchCreationContractCarryOver.priority_label}` : '',
    batchCreationContractCarryOver?.checklist?.length ? `契约清单：${batchCreationContractCarryOver.checklist.join('、')}` : '',
    batchCreationContractCarryOver?.items?.length ? `契约缺口：${batchCreationContractCarryOver.items.join('；')}` : '',
    batchCreationContractCarryOver?.required_actions?.length ? `契约动作：${batchCreationContractCarryOver.required_actions.join('；')}` : '',
    batchCreationContractCarryOver?.policy ? `契约策略：${batchCreationContractCarryOver.policy}` : '',
    batchCreationContractCarryOver ? '执行口径：目标读者、题材定位、核心承诺、追读留存必须分别写成可定位正文证据；开篇先补读者压力，中段兑现题材长板和核心承诺，章末留下追读问题。' : '',
    '',
    millionWordRunway ? '【百万字航线守门】' : '',
    millionWordRunway ? '硬性要求：本章必须回答航线中的本章四问，遵守不可偏移红线，兑现追读燃料；如果 safeModeLabel 为仅单章或禁止连写，不得抢跑后续章节内容。' : '',
    millionWordRunway ? JSON.stringify(millionWordRunway, null, 2).slice(0, 5000) : '',
    '',
    goldenThreeBrief ? '【黄金三章启动守门】' : '',
    goldenThreeBrief ? '硬性要求：执行 chapter_target.golden_three_brief；前三章必须快速交付钩子、主角、事件、升级/追读理由、前三章至少两个爽点和每章结尾悬念，不得用大段世界观说明开局。' : '',
    goldenThreeBrief ? JSON.stringify(goldenThreeBrief, null, 2).slice(0, 3000) : '',
    '',
    first30RetentionBrief ? '【本章前30章留存修复】' : '',
    first30RetentionBrief ? '硬性要求：本章必须修复前30章诊断指出的目标、章末钩子、爽点/悬念和试读闭环风险；修复要落成可见行动、信息增量、回报或章末未解问题。' : '',
    first30RetentionBrief ? JSON.stringify(first30RetentionBrief, null, 2).slice(0, 4000) : '',
    '',
    readerDropRiskBrief ? '【读者弃读预警】' : '',
    readerDropRiskBrief ? '硬性要求：执行 chapter_target.reader_drop_risk_brief；drop_points 是试读读者可能离开的原因，必须分别在开篇 300 字、中段场景推进和章末翻页处补抓手。不得用设定说明、模板热血或空泛总结糊过去。' : '',
    readerDropRiskBrief?.opening_guardrail ? `开篇防弃读：${readerDropRiskBrief.opening_guardrail}` : '',
    readerDropRiskBrief?.middle_guardrail ? `中段防掉速：${readerDropRiskBrief.middle_guardrail}` : '',
    readerDropRiskBrief?.ending_guardrail ? `章末防流失：${readerDropRiskBrief.ending_guardrail}` : '',
    readerDropRiskBrief ? JSON.stringify(readerDropRiskBrief, null, 2).slice(0, 4000) : '',
    '',
    readerExpectationDebtContext.must_carry.length || readerExpectationDebtContext.keep_alive.length ? '【期待债务承接】' : '',
    readerExpectationDebtContext.must_carry.length || readerExpectationDebtContext.keep_alive.length ? '硬性要求：上一章或最近章节欠下的期待必须在本章可见推进；overdue/逾期待补项必须优先处理成动作、信息增量、冲突结果或章末升级。可延迟完全兑现，但不得遗忘、换线或矛盾改写。' : '',
    readerExpectationDebtContext.must_carry.length || readerExpectationDebtContext.keep_alive.length ? JSON.stringify(readerExpectationDebtContext, null, 2).slice(0, 3000) : '',
    '',
    innovationBrief ? '【本章创新执行】' : '',
    innovationBrief ? '硬性要求：执行 chapter_target.innovation_brief；chapter_angle 必须写成选择、规则、机制、反差或场面，execution_points 必须落成可见动作，differentiation_guardrails 不得越线，ip_adaptation_hooks 尽量转成可视化镜头。' : '',
    innovationBrief?.chapter_angle ? `创新角度：${innovationBrief.chapter_angle}` : '',
    innovationBrief?.execution_points?.length ? `执行点：${innovationBrief.execution_points.join('；')}` : '',
    innovationBrief?.differentiation_guardrails?.length ? `差异护栏：${innovationBrief.differentiation_guardrails.join('；')}` : '',
    innovationBrief?.ip_adaptation_hooks?.length ? `IP化场面：${innovationBrief.ip_adaptation_hooks.join('；')}` : '',
    innovationBrief ? JSON.stringify(innovationBrief, null, 2).slice(0, 3000) : '',
    '',
    styleSampleStrategy?.enabled ? '【本章风格样章策略】' : '',
    styleSampleStrategy?.enabled ? '硬性要求：只学习叙述节奏、句式密度、对白比例和情绪转折；原句不能照搬，不得复制样章桥段、专有设定、角色名和核心梗。' : '',
    styleSampleStrategy?.enabled ? JSON.stringify(styleSampleStrategy, null, 2).slice(0, 5000) : '',
    '',
    chapterBenchmarkStrategy?.enabled ? '【本章质量基准样例】' : '',
    chapterBenchmarkStrategy?.enabled ? '硬性要求：只学习章节结构、信息密度、冲突节拍、爽点兑现和章末钩子；不得复制样例桥段、角色名、专有设定和原句，不得把样例剧情替换成本章剧情。' : '',
    chapterBenchmarkStrategy?.enabled ? JSON.stringify(chapterBenchmarkStrategy, null, 2).slice(0, 5000) : '',
    '',
  ]
}
