import {
  normalizeChapterPositioningBrief,
} from '../../novel-writing/chapter-positioning-brief'
import {
  normalizeGoldenThreeBrief,
} from '../../novel-writing/golden-three-brief'
import {
  normalizeInnovationBrief,
} from '../../novel-writing/innovation-basics'
import {
  longformCompassFromContext,
  normalizeLongformCompass,
} from '../../novel-writing/longform-compass'
import {
  buildAssetLinkagePromptSection,
  buildBenchmarkRecallPromptSection,
  buildBenchmarkRecallReceiptPromptSection,
  buildBridgeUnitPromptSection,
  buildChapterBlueprintPromptSection,
  buildChapterHookPromptSection,
  buildChapterLaunchGatePromptSection,
  buildCharacterBehaviorPromptSection,
  buildCharacterRelationPromptSection,
  buildConflictStructurePromptSection,
  buildContentRubricPromptSection,
  buildContinuityHeatPromptSection,
  buildCoreContractRadarPromptSection,
  buildDeliveryRiskCarryOverPromptSection,
  buildDialoguePromptSection,
  buildEmotionalArcPromptSection,
  buildExpectationThresholdPromptSection,
  buildFemaleAudiencePromptSection,
  buildGenrePositioningPromptSection,
  buildGovernanceRecheckPromptSection,
  buildInformationFlowPromptSection,
  buildIntentConfirmationPromptSection,
  buildIntentConfirmationReceiptPromptSection,
  buildLongformBattleContextPromptSection,
  buildLongformCompassPromptSection,
  buildOpeningPromptSection,
  buildParagraphHookPromptSection,
  buildPlatformRubricPromptSection,
  buildPlotDynamicsPromptSection,
  buildPlotFrameworkPromptSection,
  buildPlotSpecialTopicsPromptSection,
  buildProseCraftPromptSection,
  buildPunctuationTonePromptSection,
  buildQualityAuditPromptSection,
  buildReversalPromptSection,
  buildShowdownPromptSection,
  buildStateTrackingPromptSection,
  buildStateTrackingReceiptPromptSection,
  buildStoryLoopPromptSection,
  buildStoryPowerPromptSection,
  buildStyleBoundaryPromptSection,
  buildSuspensePromptSection,
  buildTargetReaderPromptSection,
  buildTitleUniquenessPromptSection,
  buildUpgradeRhythmPromptSection,
  buildWritePreparationPromptSection,
} from '../../novel-writing/prose-generation-prompt-sections'
import {
  buildBoundedProsePrompt,
  buildOhStoryDirectorPromptBlock,
  buildProsePromptContextSnapshot,
  compactProseSceneCard,
  prosePromptJson,
  prosePromptText,
} from '../../novel-writing/prose-prompt-context'
import {
  buildReaderRetentionBrief,
  first30RetentionBriefFromContext,
  normalizeReaderDropRiskBrief,
} from '../../novel-writing/reader-retention-brief'
import {
  normalizeRecentFatigueBrief,
} from '../../novel-writing/rolling-rhythm-preflight'
import {
  sceneBriefFromCard,
} from '../../novel-writing/scene-briefs'
import {
  normalizePageTurnHookBrief,
  normalizeSerialRhythmBrief,
} from '../../novel-writing/serial-rhythm-brief'
import {
  normalizeSignatureSceneBrief,
} from '../../novel-writing/signature-scene-basics'
import {
  normalizeStoryDriveBrief,
} from '../../novel-writing/story-drive-brief'
import {
  normalizeStoryPressureBrief,
} from '../../novel-writing/story-pressure-brief'
import {
  buildStyleFingerprintPromptHandoff,
} from '../../novel-writing/style-fingerprint'
import {
  normalizeVolumeClimaxBrief,
} from '../../novel-writing/volume-climax-brief'
import {
  asArray,
} from '../../routes/novel-route-utils'
import {
  applyReaderExpectationDebtAging,
  normalizeReaderExpectationDebtContext,
} from '../batch-serial/serial-momentum'
import {
  buildPreviousChapterHandoff,
  normalizeBatchChapterHandoffContract,
  normalizeGovernanceRecheckMemoryContext,
} from '../post-delivery/chapter-handoff-contracts'
import {
  normalizeDeliveryRiskCarryOverContext,
} from '../post-delivery/delivery-risk-core'
import {
  characterArcBriefFromContext,
  millionWordRunwayFromContext,
  plotSpecialTopicsContractForSync,
  storyUnitContextFromContext,
} from '../post-delivery/quality-sync-reports'
import {
  normalizeSceneCardsPayload,
} from '../post-delivery/scene-cards'
import {
  buildConflictStructureContract,
  buildExpectationThresholdContract,
  buildFemaleAudienceContract,
  buildGenrePositioningContract,
  buildInformationFlowContract,
  buildQualityAuditContract,
  buildStoryLoopContract,
  buildTargetReaderContract,
  buildUpgradeRhythmContract,
} from '../quality/audience-quality-contracts'
import {
  assetText,
  buildAssetLinkageContract,
  buildCharacterBehaviorContract,
  buildCharacterRelationContract,
} from '../quality/character-asset-contracts'
import {
  buildContinuityHeatContract,
  buildDialogueContract,
  buildPlotDynamicsContract,
  buildStoryPowerContract,
} from '../quality/continuity-dialogue-contracts'
import {
  buildCoreContractRadar,
  chapterLaunchGateFromContext,
} from '../quality/core-contract-radar'
import {
  buildBridgeUnitContract,
  buildChapterHookContract,
  buildEmotionalArcContract,
  buildParagraphHookContract,
  buildReversalContract,
  buildShowdownContract,
  buildSuspenseContract,
} from '../quality/craft-tension-contracts'
import {
  benchmarkRecallGapsFromContext,
  benchmarkRecallIsNoBenchmark,
  buildBenchmarkRecallBrief,
  buildIntentConfirmationContract,
} from '../quality/intent-benchmark-contracts'
import {
  chapterNosBrief,
  longformBattleContextFromContext,
  nextBatchBriefFromContext,
  normalizeDailyContextSnapshot,
  normalizeDailyProgressSummary,
  normalizeForeshadowingConsistencyRadar,
  normalizeLayeredMemoryContext,
  normalizeLongformBattleContext,
  normalizeLongformMemoryCapsule,
  normalizeNextBatchBrief,
} from '../quality/memory-longform-contracts'
import {
  OH_STORY_BEAT_DENSITY_RULE,
} from '../quality/outline-blueprint-contracts'
import {
  mergedContextChapterTargetPreferRuntime,
} from '../quality/paragraph-prose-context'
import {
  buildContentRubric,
  buildPlatformRubric,
} from '../quality/platform-content-rubrics'
import {
  buildOpeningContract,
  buildPlotFrameworkContract,
  buildProseCraftContract,
  buildPunctuationToneContract,
} from '../quality/plot-opening-prose-contracts'
import {
  buildStateTrackingContract,
} from '../quality/state-tracking-contracts'
import {
  buildChapterBenchmarkStrategy,
  buildStyleBoundaryContract,
  buildStyleSampleStrategy,
} from '../quality/style-sample-strategy'
import {
  compactBriefText,
  uniqueBriefStrings,
} from '../quality/text-utils'
import {
  buildWritePreparationBrief,
} from '../quality/write-preparation-contracts'

export function buildParagraphProsePromptSections(ctx: any) {
  const {
    chapterTarget,
    preDraftBrief,
    chapterSceneCards,
    preDraftSceneBriefs,
    sceneBriefs,
    chapterPositioningBrief,
    readerRetentionBrief,
    longformCompass,
    longformBattleContext,
    chapterLaunchGate,
    governanceRecheckMemory,
    coreContractRadar,
    nextBatchBrief,
    expansionStructureDecision,
    defaultFiveChapterLaneRedesign,
    expansionStructureVerification,
    defaultFiveChapterRegression,
    defaultFiveChapterLaneTemplate,
    defaultFiveChapterLaneTemplateRequirementLabels,
    defaultFiveChapterLaneTemplateRepairSummaries,
    defaultFiveChapterLaneTemplateRepairActions,
    defaultFiveChapterLaneTemplateRedesignSource,
    defaultFiveChapterLaneTemplateTopFailed,
    defaultFiveChapterLaneTemplateRedesignLines,
    defaultFiveChapterLaneTemplateValidationStandard,
    defaultFiveChapterLaneTemplateRequiredReceipts,
    defaultFiveChapterLaneTemplateVersionId,
    defaultFiveChapterLaneTemplateProductionRelapseCount,
    defaultFiveChapterLaneTemplateProductionRelapseReview,
    defaultFiveChapterLaneTemplateProductionRelapseChapterNos,
    defaultFiveChapterLaneTemplateProductionRelapseRestoreNos,
    defaultFiveChapterLaneTemplateProductionRelapseValidationNos,
    defaultFiveChapterLaneTemplateProductionFailureReasons,
    defaultFiveChapterLaneTemplateProductionFailedRequirements,
    batchPreflight,
    batchDeliveryRiskCarryOver,
    batchCreationContractCarryOver,
    batchChapterHandoffContract,
    longformMemoryAnchor,
    longformMemoryCapsule,
    layeredMemoryContext,
    progressSummary,
    dailyContextSnapshot,
    foreshadowingConsistencyRadar,
    millionWordRunway,
    styleSampleStrategy,
    styleFingerprintHandoff,
    chapterBenchmarkStrategy,
    first30RetentionBrief,
    readerDropRiskBrief,
    goldenThreeBrief,
    storyPressureBrief,
    storyDriveBrief,
    serialRhythmBrief,
    pageTurnHookBrief,
    chapterBlueprint,
    beatDensityContract,
    smallOutlineContract,
    outlineMethodsContract,
    mainlineDefinitionContract,
    skipBenchmarkRecall,
    benchmarkRecallBrief,
    styleBoundaryContract,
    platformRubric,
    contentRubric,
    targetReaderContract,
    genrePositioningContract,
    plotSpecialTopicsContract,
    femaleAudienceContract,
    upgradeRhythmContract,
    conflictStructureContract,
    storyLoopContract,
    emotionalArcContract,
    chapterHookContract,
    paragraphHookContract,
    suspenseContract,
    reversalContract,
    showdownContract,
    bridgeUnitContract,
    plotFrameworkContract,
    openingContract,
    proseCraftContract,
    punctuationToneContract,
    qualityAuditContract,
    dialogueContract,
    plotDynamicsContract,
    storyPowerContract,
    continuityHeatContract,
    characterRelationContract,
    characterBehaviorContract,
    assetLinkageContract,
    assetRelationshipGraphRisks,
    stateTrackingContract,
    intentConfirmationContract,
    informationFlowContract,
    expectationThresholdContract,
    volumeClimaxBrief,
    recentFatigueBrief,
    deliveryRiskCarryOver,
    writePreparationBrief,
    readerExpectationDebtContext,
    previousHandoff,
    storyUnitContext,
    signatureSceneBrief,
    innovationBrief,
    characterArcBrief,
    titleUniquenessReport,
    duplicateTitleRows,
    ohStoryDirectorPromptBlock,
    project,
    chapterDraft,
    migrationPlan,
    contextPackage,
  } = ctx
  return buildBoundedProsePrompt([
    '任务：按场景卡生成章节正文。请先在心中按场景组织段落，再输出完整正文。',
    '硬性语言要求：chapter_text 必须使用简体中文，按中文网文自然分段和中文引号输出；不得输出葡萄牙语、英语或拼音正文，外语只允许作为故事内必要专名少量出现。',
    `作品标题：${project.title}`,
    chapterDraft?.chapter_no ? `目标章节：第${chapterDraft.chapter_no}章《${chapterDraft.title || '无标题'}》` : '',
    chapterDraft?.chapter_no ? `只允许输出这一章的正文，不得混入其他章节内容。chapter_no 必须严格等于 ${chapterDraft.chapter_no}` : '',
    contextPackage?.chapter_target?.word_target ? `本章目标字数：约 ${contextPackage.chapter_target.word_target.target} 字；可接受范围：${contextPackage.chapter_target.word_target.min}-${contextPackage.chapter_target.word_target.max} 字；类型：${contextPackage.chapter_target.word_target.label}。` : '',
    contextPackage?.chapter_target?.word_target ? '字数执行要求：每个场景分配明确字数预算，正文不得只写剧情摘要；如果低于目标范围，必须扩写动作过程、选择代价、对话交锋和章末钩子铺垫，而不是堆砌环境描写。' : '',
    chapterPositioningBrief ? '【章节定位与对标结构坐标】' : '',
    chapterPositioningBrief ? '硬性要求：执行 chapter_target.chapter_positioning_brief；按章节定位决定冲突烈度、爽点密度、详略和章尾拉力。高压/推进章要有明确升级或回报；低压/过场章可弱钩子，但必须保留阶段目标、微好奇或关系期待。' : '',
    chapterPositioningBrief ? `chapter_target.chapter_positioning_brief：${JSON.stringify(chapterPositioningBrief).slice(0, 1800)}` : '',
    sceneBriefs.length ? `scene_cards.chapter_positioning：${sceneBriefs.map((scene: any) => `${scene.scene_no || ''}.${scene.title || '场景'}=${scene.chapter_positioning || chapterPositioningBrief.chapter_positioning || '推进'}${scene.pressure_level ? `/P${scene.pressure_level}` : ''}${scene.chapter_positioning_role ? `/${scene.chapter_positioning_role}` : ''}`).join('；')}` : '',
    chapterPositioningBrief?.benchmark_structure_coordinates?.length ? `对标结构坐标：${JSON.stringify(chapterPositioningBrief.benchmark_structure_coordinates).slice(0, 1600)}；只迁移结构功能位和节奏位置，不复制对标桥段、设定、人物或原句。` : '',
    sceneBriefs.length ? '【场景卡执行摘要】' : '',
    sceneBriefs.length ? JSON.stringify({ scene_cards: sceneBriefs.slice(0, 8).map(compactProseSceneCard) }, null, 2).slice(0, 3600) : '',
    ...buildTitleUniquenessPromptSection(titleUniquenessReport, duplicateTitleRows),
    '必须以 chapter_target.summary、chapter_target.conflict、chapter_target.ending_hook 和 scene_cards 为准；如果已有正文或旧场景分解与目标不一致，不得沿用。',
    'oh-story 日更工作流：生成正文前按 Step 2.1 标题预检、Step 2.2 状态筛选、Step 2.3 文风召回、Step 2.4 意图确认、章节蓝图/场景卡门禁执行；继续/续写/日更只表示继续当前日更批量流程，不得跳过 Step 2.2 状态筛选或 Step 2.3 文风召回；状态筛选只保留不知道就会写错的信息；正文后用回执闭环，不用任务书自述替代正文证据。',
    ohStoryDirectorPromptBlock,
    'oh-story 自然写作底线：正文按“动作 -> 对话 -> 情绪反应 -> 动作”循环推进，单写心理活动不得连续超过 2 段；情绪用身体动作、行为选择、对话反应或代价表现，不直接写“他很紧张/她很伤心”。',
    '句式节奏：打斗/紧张用 3-8 字短句制造速度，日常用 8-15 字承载动作和信息，描写句必须读起来不卡；长短句交错，不要通篇同长度、同语气、同段落密度。',
    '对白口吻：对话必须口语化，符合角色身份和关系阶段；不要把“我认为此事不妥”这类书面语塞进角色嘴里，能用动作或半句话表达的，不用旁白说明。',
    '章尾收束：章尾用动作、对话或悬念收束，让情节本身制造余韵；不得用总结性感悟、哲理升华或作者预告收尾，例如“他终于明白”“这一夜注定”“更大的风暴即将来临”。',
    '外部事实查证：如果写作涉及历史年代、地理方位、职业细节、法律/医疗/技术流程、真实机构或真实地名且当前上下文没有可靠来源，必须按 oh-story 资料研究流程标记待查证、改成架空/模糊表达，或把信息留作角色待验证线索；不得编造确定事实。',
    '',
    previousHandoff ? '【上一章尾段原文承接】' : '',
    previousHandoff ? '硬性要求：按 oh-story 日更串行流程，先读取上一章刚写入正文尾段再续写。前300字必须接住上一章最后一幕、动作链、角色反应、钩子、危机、欠账或未解问题；不能只复述摘要或改写成新的开场，也不得重新从泛环境描写、空泛醒来或无关解释开场。' : '',
    previousHandoff ? previousHandoff : '',
    '',
    ...buildWritePreparationPromptSection(writePreparationBrief),
    ...buildChapterBlueprintPromptSection({
      chapterBlueprint,
      beatDensityContract,
      smallOutlineContract,
      outlineMethodsContract,
      mainlineDefinitionContract,
      beatDensityFallbackRule: OH_STORY_BEAT_DENSITY_RULE,
    }),
    ...buildPlatformRubricPromptSection(platformRubric),
    ...buildContentRubricPromptSection(contentRubric),
    ...buildTargetReaderPromptSection(targetReaderContract),
    ...buildGenrePositioningPromptSection(genrePositioningContract),
    ...buildPlotSpecialTopicsPromptSection(plotSpecialTopicsContract),
    ...buildFemaleAudiencePromptSection(femaleAudienceContract),
    ...buildUpgradeRhythmPromptSection(upgradeRhythmContract),
    ...buildConflictStructurePromptSection(conflictStructureContract),
    ...buildStoryLoopPromptSection(storyLoopContract),
    ...buildEmotionalArcPromptSection(emotionalArcContract),
    ...buildChapterHookPromptSection(chapterHookContract),
    ...buildParagraphHookPromptSection(paragraphHookContract),
    ...buildSuspensePromptSection(suspenseContract),
    ...buildReversalPromptSection(reversalContract),
    ...buildShowdownPromptSection(showdownContract),
    ...buildBridgeUnitPromptSection(bridgeUnitContract),
    ...buildPlotFrameworkPromptSection(plotFrameworkContract),
    ...buildOpeningPromptSection(openingContract),
    ...buildProseCraftPromptSection(proseCraftContract),
    ...buildPunctuationTonePromptSection(punctuationToneContract),
    ...buildQualityAuditPromptSection(qualityAuditContract),
    ...buildDialoguePromptSection(dialogueContract),
    ...buildPlotDynamicsPromptSection(plotDynamicsContract),
    ...buildStoryPowerPromptSection(storyPowerContract),
    ...buildContinuityHeatPromptSection(continuityHeatContract),
    ...buildCharacterRelationPromptSection(characterRelationContract),
    ...buildCharacterBehaviorPromptSection(characterBehaviorContract),
    ...buildAssetLinkagePromptSection(assetLinkageContract, assetRelationshipGraphRisks),
    ...buildStateTrackingPromptSection(stateTrackingContract),
    ...buildIntentConfirmationPromptSection(intentConfirmationContract),
    ...buildBenchmarkRecallPromptSection(benchmarkRecallBrief),
    ...buildStyleBoundaryPromptSection(styleBoundaryContract),
    ...buildInformationFlowPromptSection(informationFlowContract),
    ...buildExpectationThresholdPromptSection(expectationThresholdContract),
    ...buildDeliveryRiskCarryOverPromptSection(deliveryRiskCarryOver),
    ...buildLongformCompassPromptSection(longformCompass),
    ...buildLongformBattleContextPromptSection(longformBattleContext),
    ...buildChapterLaunchGatePromptSection(chapterLaunchGate),
    ...buildGovernanceRecheckPromptSection(governanceRecheckMemory),
    ...buildCoreContractRadarPromptSection(coreContractRadar),
    nextBatchBrief ? '【本批连载任务书】' : '',
    nextBatchBrief ? '硬性要求：本章必须服务批次目标和当前章角色；不得提前消费后续章节爆点，不得跳过本章读者回报，不得抢跑批次后段的主线兑现。' : '',
    nextBatchBrief?.start_checklist?.length ? `批次开工清单：${nextBatchBrief.start_checklist.map((item: any) => `${item.label || item.key}：${item.detail || item.status}`).join('；')}` : '',
    nextBatchBrief?.workflow_rules?.length ? `批量流程规则：${nextBatchBrief.workflow_rules.join('；')}` : '',
    nextBatchBrief ? JSON.stringify(nextBatchBrief, null, 2).slice(0, 4000) : '',
    '',
    expansionStructureDecision ? '【扩批结构决策】' : '',
    expansionStructureDecision ? '硬性要求：执行 next_batch_brief.expansion_structure_decision；这是结构修复有效性对本批规模、段位职责和观察指标的最终判断。正文必须按 recommendation 执行，不得因为恢复扩批而淡化结构约束，也不得在小批验证或单章重构时抢跑后续批次。' : '',
    expansionStructureDecision?.recommendation ? `决策：${expansionStructureDecision.recommendation}` : '',
    expansionStructureDecision?.mode_label ? `模式：${expansionStructureDecision.mode_label}` : '',
    expansionStructureDecision?.target_chapter_count ? `目标批次：${expansionStructureDecision.target_chapter_count}章` : '',
    expansionStructureDecision?.segment_label ? `观察段位：${expansionStructureDecision.segment_label}` : '',
    expansionStructureDecision?.summary ? `有效性摘要：${expansionStructureDecision.summary}` : '',
    expansionStructureDecision?.instruction ? `执行口径：${expansionStructureDecision.instruction}` : '',
    expansionStructureDecision?.observation_metrics?.length ? `观察指标：${expansionStructureDecision.observation_metrics.join('；')}` : '',
    defaultFiveChapterLaneRedesign ? '默认5章档位结构重构：连续恢复判定失效后，本章不得只修单章句子，必须先重写默认 5 章档位的段位职责、冲突轮换、回报密度和章末追读模板。' : '',
    defaultFiveChapterLaneRedesign?.reason ? `重构来源：${defaultFiveChapterLaneRedesign.reason}` : '',
    defaultFiveChapterLaneRedesign?.relapse_count ? `连续恢复判定失效：${defaultFiveChapterLaneRedesign.relapse_count}次` : '',
    defaultFiveChapterLaneRedesign?.repeated_failure_reasons?.length ? `同维复发：${defaultFiveChapterLaneRedesign.repeated_failure_reasons.join('、')}` : '',
    defaultFiveChapterLaneRedesign?.segment_duty_rewrite ? `段位职责重写：${defaultFiveChapterLaneRedesign.segment_duty_rewrite}` : '',
    defaultFiveChapterLaneRedesign?.conflict_rotation ? `冲突轮换：${defaultFiveChapterLaneRedesign.conflict_rotation}` : '',
    defaultFiveChapterLaneRedesign?.payoff_density ? `回报密度：${defaultFiveChapterLaneRedesign.payoff_density}` : '',
    defaultFiveChapterLaneRedesign?.ending_hook_template ? `章末追读模板：${defaultFiveChapterLaneRedesign.ending_hook_template}` : '',
    defaultFiveChapterLaneRedesign ? '默认档位回执字段：expansion_structure_decision_execution 必须额外回填 default_lane_segment_duty_delivered(boolean)、default_lane_conflict_rotation_delivered(boolean)、default_lane_payoff_density_delivered(boolean)、default_lane_ending_hook_template_delivered(boolean)，并在 evidence 中说明四项模板如何落到正文。' : '',
    expansionStructureDecision ? '执行回执：scene_breakdown 中承担结构职责的场景必须回填 expansion_structure_decision_execution，字段包含 segment_role_delivered(boolean)、observation_metrics_delivered(boolean)、redesign_principles_delivered(boolean)、evidence(array)。' : '',
    expansionStructureDecision ? JSON.stringify(expansionStructureDecision, null, 2).slice(0, 3000) : '',
    '',
    expansionStructureVerification ? '【扩批结构验证】' : '',
    expansionStructureVerification ? '硬性要求：执行 next_batch_brief.expansion_structure_verification；这是已修复的5章扩批热区进入本轮2-3章验证，正文必须证明结构修复真的落地，而不是只声明已经修好。' : '',
    expansionStructureVerification?.repeated_hotspot_segment ? `${expansionStructureVerification.repeated_hotspot_segment.label || '复发段位'}连续 ${expansionStructureVerification.repeated_hotspot_segment.count || 0} 次成为扩批热区，本批必须反证同一段位不会再次只铺垫、掉回报或丢章末追读。` : '',
    expansionStructureVerification?.validation_chapter_nos?.length ? `验证章节：${expansionStructureVerification.validation_chapter_nos.map((chapterNo: number) => `第${chapterNo}章`).join('、')}` : '',
    expansionStructureVerification?.fixed_segment_role ? `固定段落职责：${expansionStructureVerification.fixed_segment_role}` : '',
    expansionStructureVerification?.conflict_rotation ? `冲突换源：${expansionStructureVerification.conflict_rotation}` : '',
    expansionStructureVerification?.explicit_payoff ? `显性回报：${expansionStructureVerification.explicit_payoff}` : '',
    expansionStructureVerification?.ending_hook_requirement ? `章末追读：${expansionStructureVerification.ending_hook_requirement}` : '',
    expansionStructureVerification?.structure_actions?.length ? `结构动作：${expansionStructureVerification.structure_actions.join('；')}` : '',
    defaultFiveChapterLaneTemplate ? `默认5章档位模板回检：${defaultFiveChapterLaneTemplate.summary || defaultFiveChapterLaneTemplate.label}` : '',
    defaultFiveChapterLaneTemplateRequirementLabels.length ? `四项模板：${defaultFiveChapterLaneTemplateRequirementLabels.join('、')}` : '',
    defaultFiveChapterLaneTemplate?.segment_duty_rewrite ? `段位职责重写：${defaultFiveChapterLaneTemplate.segment_duty_rewrite}` : '',
    defaultFiveChapterLaneTemplate?.conflict_rotation ? `冲突轮换：${defaultFiveChapterLaneTemplate.conflict_rotation}` : '',
    defaultFiveChapterLaneTemplate?.payoff_density ? `回报密度：${defaultFiveChapterLaneTemplate.payoff_density}` : '',
    defaultFiveChapterLaneTemplate?.ending_hook_template ? `章末追读模板：${defaultFiveChapterLaneTemplate.ending_hook_template}` : '',
    defaultFiveChapterLaneTemplateRedesignSource ? `模板重构来源：${defaultFiveChapterLaneTemplateRedesignSource}` : '',
    defaultFiveChapterLaneTemplateVersionId ? `模板版本：${defaultFiveChapterLaneTemplateVersionId}` : '',
    defaultFiveChapterLaneTemplateProductionRelapseCount ? `生产复发次数：${defaultFiveChapterLaneTemplateProductionRelapseCount}` : '',
    defaultFiveChapterLaneTemplateProductionRelapseChapterNos ? `生产复发章节：${defaultFiveChapterLaneTemplateProductionRelapseChapterNos}` : '',
    defaultFiveChapterLaneTemplateProductionRelapseValidationNos ? `生产复发前验证：${defaultFiveChapterLaneTemplateProductionRelapseValidationNos}` : '',
    defaultFiveChapterLaneTemplateProductionRelapseRestoreNos ? `生产恢复依据：${defaultFiveChapterLaneTemplateProductionRelapseRestoreNos}` : '',
    defaultFiveChapterLaneTemplateProductionFailureReasons.length ? `真实生产失败维度：${defaultFiveChapterLaneTemplateProductionFailureReasons.join('、')}` : '',
    defaultFiveChapterLaneTemplateProductionFailedRequirements.length ? `生产复发模板缺项：${defaultFiveChapterLaneTemplateProductionFailedRequirements.join('；')}` : '',
    defaultFiveChapterLaneTemplateProductionRelapseReview ? `模板版本后验验证：本轮3章验证批必须逐章对照 template_version_id ${defaultFiveChapterLaneTemplateVersionId || defaultFiveChapterLaneTemplateProductionRelapseReview.template_version_id || '当前版本'}${defaultFiveChapterLaneTemplateProductionRelapseChapterNos ? ` 和真实生产复发章节 ${defaultFiveChapterLaneTemplateProductionRelapseChapterNos}` : ''}，证明新版模板能修掉生产后验问题。` : '',
    defaultFiveChapterLaneTemplateTopFailed ? `高频缺项：${compactBriefText(defaultFiveChapterLaneTemplateTopFailed.label || defaultFiveChapterLaneTemplateTopFailed.key || '模板缺项')}失败 ${Number(defaultFiveChapterLaneTemplateTopFailed.failed_count ?? defaultFiveChapterLaneTemplateTopFailed.failedCount ?? 0)} 次` : '',
    ...defaultFiveChapterLaneTemplateRedesignLines.map(item => `重构模板：${item}`),
    defaultFiveChapterLaneTemplateValidationStandard.length ? `下一轮验证标准：${defaultFiveChapterLaneTemplateValidationStandard.join('；')}` : '',
    defaultFiveChapterLaneTemplateRequiredReceipts.length ? `逐章回填字段：${defaultFiveChapterLaneTemplateRequiredReceipts.join('、')}` : '',
    defaultFiveChapterLaneTemplateRepairSummaries.length ? `模板缺项修复：${defaultFiveChapterLaneTemplateRepairSummaries.join('；')}` : '',
    defaultFiveChapterLaneTemplateRepairActions.length ? `缺项修复动作：${defaultFiveChapterLaneTemplateRepairActions.join('；')}` : '',
    defaultFiveChapterLaneTemplate ? '默认档位模板验证要求：下一轮验证批逐章继承段位职责、冲突轮换、回报密度和章末追读模板，并逐章证明四项模板没有复发。' : '',
    defaultFiveChapterRegression ? `默认5章档位回退：${defaultFiveChapterRegression.summary || defaultFiveChapterRegression.label || '默认档位复发，需要回到3章验证批。'}` : '',
    defaultFiveChapterRegression?.default_batch_chapter_nos?.length ? `失效批次：${chapterNosBrief(defaultFiveChapterRegression.default_batch_chapter_nos)}` : '',
    defaultFiveChapterRegression?.restore_chapter_nos?.length ? `恢复依据：${chapterNosBrief(defaultFiveChapterRegression.restore_chapter_nos)}` : '',
    defaultFiveChapterRegression?.validation_chapter_nos?.length ? `前置3章验证：${chapterNosBrief(defaultFiveChapterRegression.validation_chapter_nos)}` : '',
    defaultFiveChapterRegression?.failure_reasons?.length ? `失败维度：${defaultFiveChapterRegression.failure_reasons.join('、')}` : '',
    defaultFiveChapterRegression ? '默认档位验证要求：本批每章都必须逐章证明核心守恒、显性回报和章末追读已经重新稳定；不能只修复单章句子，也不能把中段继续写成铺垫、转场或弱钩子。' : '',
    expansionStructureVerification ? JSON.stringify(expansionStructureVerification, null, 2).slice(0, 3000) : '',
    '',
    longformMemoryAnchor ? '【长篇正史锚点】' : '',
    longformMemoryAnchor ? '硬性要求：这是本批连续生产的压缩正史。角色状态、开放悬念、回报债务和核心承诺不得被改写、遗忘或绕开；新增情节必须从这些锚点自然推进。' : '',
    longformMemoryAnchor ? JSON.stringify(longformMemoryAnchor, null, 2).slice(0, 3000) : '',
    '',
    longformMemoryCapsule ? '【长篇记忆胶囊】' : '',
    longformMemoryCapsule ? '硬性要求：执行 chapter_target.longform_memory_capsule；这是本章必须召回的压缩正史。核心承诺、主线进度、角色状态、开放悬念、回报债务、正史事实和红线不得被遗忘、矛盾改写或跳过。' : '',
    '硬性要求：执行 chapter_target.established_events_contract；已锁正史事件（死亡方式、规则触发、能力代价等）在闪回或复述时不得改写 cause/mechanism/constraints，只能同义转述。',
    longformMemoryCapsule ? JSON.stringify(longformMemoryCapsule, null, 2).slice(0, 4000) : '',
    '',
    layeredMemoryContext ? '【长篇分层记忆】' : '',
    layeredMemoryContext ? '硬性要求：执行 chapter_target.layered_memory_context；近5章详记保留细节承接，十章概要只守阶段正史，卷级总览只守卷级方向。不得把近期状态、十章压缩事实和卷级红线互相覆盖。' : '',
    layeredMemoryContext?.recent_chapter_details?.length ? `近5章详记：${layeredMemoryContext.recent_chapter_details.join('；')}` : '',
    layeredMemoryContext?.ten_chapter_summaries?.length ? `十章概要：${layeredMemoryContext.ten_chapter_summaries.join('；')}` : '',
    layeredMemoryContext?.volume_overview?.length ? `卷级总览：${layeredMemoryContext.volume_overview.join('；')}` : '',
    layeredMemoryContext?.archive_refs?.length ? `归档索引：${layeredMemoryContext.archive_refs.join('；')}` : '',
    layeredMemoryContext?.red_lines?.length ? `分层记忆红线：${layeredMemoryContext.red_lines.join('；')}` : '',
    layeredMemoryContext ? JSON.stringify(layeredMemoryContext, null, 2).slice(0, 4000) : '',
    '',
    progressSummary ? '【日更进度断点】' : '',
    progressSummary ? '硬性要求：执行 story_state.progress_summary；这是 oh-story Step 4 从追踪/上下文.md 沉淀的续写断点。开篇必须承接最后完成章节后的状态，优先保留注意事项，不要把详细伏笔表、时间线表或角色状态表复制进正文。' : '',
    progressSummary?.last_completed_chapter ? `最后完成章节：第${progressSummary.last_completed_chapter}章` : '',
    progressSummary?.completed_chapter_count ? `本期完成：${progressSummary.completed_chapter_count}章` : '',
    progressSummary?.completed_word_count ? `本期字数：${progressSummary.completed_word_count}字` : '',
    progressSummary?.active_foreshadowing_count ? `活跃伏笔：${progressSummary.active_foreshadowing_count}条` : '',
    progressSummary?.recent_changed_characters?.length ? `最近变更角色：${progressSummary.recent_changed_characters.join('、')}` : '',
    progressSummary?.next_outline_status ? `下一章细纲状态：${progressSummary.next_outline_status}` : '',
    progressSummary?.notes?.length ? `注意事项：${progressSummary.notes.join('；')}` : '',
    progressSummary ? JSON.stringify(progressSummary, null, 2).slice(0, 2000) : '',
    '',
    dailyContextSnapshot ? '【日更上下文快照】' : '',
    dailyContextSnapshot ? '硬性要求：执行 story_state.daily_context_snapshot；这是 oh-story 完成后自动更新的追踪/上下文.md 快照。开篇必须接住当前位置、场景和情绪目标；写作变更要成为本章事实约束，待处理线索要么推进要么保持清晰债务。' : '',
    dailyContextSnapshot?.current_chapter ? `当前位置/章：第${dailyContextSnapshot.current_chapter}章` : '',
    dailyContextSnapshot?.current_scene ? `当前位置/场景：${dailyContextSnapshot.current_scene}` : '',
    dailyContextSnapshot?.current_emotion_target ? `当前位置/情绪目标：${dailyContextSnapshot.current_emotion_target}` : '',
    dailyContextSnapshot?.writing_changes?.length ? `本次写作变更：${dailyContextSnapshot.writing_changes.join('；')}` : '',
    dailyContextSnapshot?.pending_clues?.length ? `待处理线索：${dailyContextSnapshot.pending_clues.join('；')}` : '',
    dailyContextSnapshot ? JSON.stringify(dailyContextSnapshot, null, 2).slice(0, 2000) : '',
    '',
    foreshadowingConsistencyRadar ? '【伏笔一致性雷达】' : '',
    foreshadowingConsistencyRadar ? '硬性要求：执行 oh-story consistency-checker 的伏笔状态扫描；这是事实一致性债务，不是文学评价。活跃伏笔必须保持存在感，超期伏笔要推进、暂缓说明或进入回收路径；回收时不得改写角色知识边界、时间线、物品归属或后续新增设定。' : '',
    foreshadowingConsistencyRadar?.active_count ? `活跃伏笔：${foreshadowingConsistencyRadar.active_count}条` : '',
    foreshadowingConsistencyRadar?.overdue_count ? `超期伏笔：${foreshadowingConsistencyRadar.overdue_count}条` : '',
    foreshadowingConsistencyRadar?.active?.length ? `活跃伏笔清单：${foreshadowingConsistencyRadar.active.join('；')}` : '',
    foreshadowingConsistencyRadar?.overdue?.length ? `超期伏笔清单：${foreshadowingConsistencyRadar.overdue.join('；')}` : '',
    foreshadowingConsistencyRadar?.density_warnings?.length ? `伏笔密度提醒：${foreshadowingConsistencyRadar.density_warnings.join('；')}` : '',
    foreshadowingConsistencyRadar?.scope_rules?.length ? `伏笔盘点范围：${foreshadowingConsistencyRadar.scope_rules.join('；')}` : '',
    foreshadowingConsistencyRadar?.status_rules?.length ? `伏笔状态语义：${foreshadowingConsistencyRadar.status_rules.join('；')}` : '',
    foreshadowingConsistencyRadar?.guardrails?.length ? `一致性红线：${foreshadowingConsistencyRadar.guardrails.join('；')}` : '',
    foreshadowingConsistencyRadar ? JSON.stringify(foreshadowingConsistencyRadar, null, 2).slice(0, 2400) : '',
    '',
    styleFingerprintHandoff ? '【文风指纹断点】' : '',
    styleFingerprintHandoff ? '硬性要求：执行 story_state.style_fingerprint；这是 oh-story 追踪/上下文.md 的文风指纹锚。续写只承接剧情、状态和情绪债，不继承可能已漂移的上一章句式节奏。写完后按目标句长带检查碎句、逗号结巴和中长句呼吸。' : '',
    styleFingerprintHandoff?.target_sentence_band ? `目标句长带：${styleFingerprintHandoff.target_sentence_band}` : '',
    styleFingerprintHandoff?.style_fingerprint ? `文风指纹：${styleFingerprintHandoff.style_fingerprint}` : '',
    styleFingerprintHandoff?.policy ? `防漂移策略：${styleFingerprintHandoff.policy}` : '',
    styleFingerprintHandoff?.source_excerpt ? `来源摘录：${styleFingerprintHandoff.source_excerpt}` : '',
    styleFingerprintHandoff ? JSON.stringify(styleFingerprintHandoff, null, 2).slice(0, 1600) : '',
    '',
    storyUnitContext ? '【剧情单元任务】' : '',
    storyUnitContext ? '硬性要求：执行 chapter_target.story_unit_context；本章只完成 current_chapter_role，并服务 unit_goal。可以铺垫 pressure_escalation 和 setup_and_storyline，但不得提前消费 mini_climax_payoff、exit_hook 或 forbidden_advance 中的后段爆点。' : '',
    storyUnitContext ? JSON.stringify(storyUnitContext, null, 2).slice(0, 4000) : '',
    '',
    storyPressureBrief ? '【故事压力阶梯】' : '',
    storyPressureBrief ? '硬性要求：执行 chapter_target.story_pressure_brief；本章必须把压力源、冲突升级、赌注升级和反转逼迫写成可见事件。不得只平铺过场、复述设定或让主角无代价通关。' : '',
    storyPressureBrief?.pressure_sources?.length ? `压力源：${storyPressureBrief.pressure_sources.join('；')}` : '',
    storyPressureBrief?.conflict_escalation_guardrail ? `冲突升级：${storyPressureBrief.conflict_escalation_guardrail}` : '',
    storyPressureBrief?.stakes_growth_guardrail ? `赌注升级：${storyPressureBrief.stakes_growth_guardrail}` : '',
    storyPressureBrief?.reversal_pressure_guardrail ? `反转逼迫：${storyPressureBrief.reversal_pressure_guardrail}` : '',
    storyPressureBrief?.required_actions?.length ? `执行动作：${storyPressureBrief.required_actions.join('；')}` : '',
    storyPressureBrief ? JSON.stringify(storyPressureBrief, null, 2).slice(0, 4000) : '',
    '',
    storyDriveBrief ? '【主角能动性】' : '',
    storyDriveBrief ? '硬性要求：执行 chapter_target.story_drive_brief；本章必须让主角在压力下做出主动选择，并写清阻碍、选择代价、状态变化和下一步因果。不得让主角只听解释、等别人推动或无代价通关。' : '',
    storyDriveBrief?.obstacle ? `明确阻碍：${storyDriveBrief.obstacle}` : '',
    storyDriveBrief?.protagonist_choice ? `主角选择：${storyDriveBrief.protagonist_choice}` : '',
    storyDriveBrief?.choice_cost ? `选择代价：${storyDriveBrief.choice_cost}` : '',
    storyDriveBrief?.state_change ? `状态变化：${storyDriveBrief.state_change}` : '',
    storyDriveBrief?.causal_next_step ? `下一步因果：${storyDriveBrief.causal_next_step}` : '',
    storyDriveBrief?.required_actions?.length ? `执行动作：${storyDriveBrief.required_actions.join('；')}` : '',
    storyDriveBrief ? JSON.stringify(storyDriveBrief, null, 2).slice(0, 4000) : '',
    '',
    serialRhythmBrief ? '【连载节奏与回报密度】' : '',
    serialRhythmBrief ? '硬性要求：执行 chapter_target.serial_rhythm_brief；开篇钩子、中段回报密度、场景回报预算和章末追读必须写成正文中的可见行动、信息变化、反转、爽点或未解问题。不得用长解释、纯环境、心理总结或无效对话拖字数。' : '',
    serialRhythmBrief?.opening_hook_deadline ? `开篇钩子：${serialRhythmBrief.opening_hook_deadline}` : '',
    serialRhythmBrief?.payoff_interval ? `回报密度：${serialRhythmBrief.payoff_interval}` : '',
    serialRhythmBrief?.middle_guardrail ? `中段节奏：${serialRhythmBrief.middle_guardrail}` : '',
    serialRhythmBrief?.ending_hook_guardrail ? `章末追读：${serialRhythmBrief.ending_hook_guardrail}` : '',
    serialRhythmBrief?.scene_payoff_budget?.length ? `场景回报预算：${serialRhythmBrief.scene_payoff_budget.map((item: any) => `${item.scene_no || ''}.${item.title || '场景'}：${item.required_payoff || item.turn || item.ending_hook_seed || '必须有可见回报'}`).join('；')}` : '',
    serialRhythmBrief?.anti_drag_rules?.length ? `防水规则：${serialRhythmBrief.anti_drag_rules.join('；')}` : '',
    serialRhythmBrief ? JSON.stringify(serialRhythmBrief, null, 2).slice(0, 4000) : '',
    '',
    pageTurnHookBrief ? '【章末翻页钩子】' : '',
    pageTurnHookBrief ? '硬性要求：执行 chapter_target.page_turn_hook_brief；最后 300 字必须形成清晰翻页冲动。可见触发要落成角色现场看见、听见、拿到、失去、被迫选择或被反转击中；读者问题必须留到下一章推动；禁提前解答项不得在本章解释完。' : '',
    pageTurnHookBrief?.hook_type ? `钩子类型：${pageTurnHookBrief.hook_type}` : '',
    pageTurnHookBrief?.core_question ? `读者问题：${pageTurnHookBrief.core_question}` : '',
    pageTurnHookBrief?.visible_trigger ? `可见触发：${pageTurnHookBrief.visible_trigger}` : '',
    pageTurnHookBrief?.final_image ? `最后画面：${pageTurnHookBrief.final_image}` : '',
    pageTurnHookBrief?.next_chapter_pull ? `下一章拉力：${pageTurnHookBrief.next_chapter_pull}` : '',
    pageTurnHookBrief?.forbidden_resolution?.length ? `禁提前解答：${pageTurnHookBrief.forbidden_resolution.join('；')}` : '',
    pageTurnHookBrief?.required_actions?.length ? `执行动作：${pageTurnHookBrief.required_actions.join('；')}` : '',
    pageTurnHookBrief ? JSON.stringify(pageTurnHookBrief, null, 2).slice(0, 4000) : '',
    '',
    volumeClimaxBrief ? '【卷级高潮预算】' : '',
    volumeClimaxBrief ? '硬性要求：执行 chapter_target.volume_climax_brief；本章只兑现 current_chapter_role、required_beats 和 climax_promise，不得提前消费 forbidden_payoff 标注的卷末爆点、身份答案、终局反转或后续大回报。' : '',
    volumeClimaxBrief?.current_volume_title ? `当前卷：${volumeClimaxBrief.current_volume_title}` : '',
    volumeClimaxBrief?.chapter_range ? `卷区间：${volumeClimaxBrief.chapter_range}` : '',
    volumeClimaxBrief?.current_chapter_role ? `本章职责：${volumeClimaxBrief.current_chapter_role}` : '',
    volumeClimaxBrief?.volume_goal ? `卷目标：${volumeClimaxBrief.volume_goal}` : '',
    volumeClimaxBrief?.climax_promise ? `高潮承诺：${volumeClimaxBrief.climax_promise}` : '',
    volumeClimaxBrief?.required_beats?.length ? `必须兑现：${volumeClimaxBrief.required_beats.join('；')}` : '',
    volumeClimaxBrief?.forbidden_payoff?.length ? `禁提前消费：${volumeClimaxBrief.forbidden_payoff.join('；')}` : '',
    volumeClimaxBrief?.nearby_beats?.length ? `邻近爆点：${volumeClimaxBrief.nearby_beats.map((item: any) => `${item.chapter_no ? `第${item.chapter_no}章` : ''}${item.type ? `${item.type}` : ''}${item.label ? `《${item.label}》` : ''}${item.detail ? `：${item.detail}` : ''}`).join('；')}` : '',
    volumeClimaxBrief?.next_actions?.length ? `执行动作：${volumeClimaxBrief.next_actions.join('；')}` : '',
    volumeClimaxBrief ? JSON.stringify(volumeClimaxBrief, null, 2).slice(0, 4000) : '',
    '',
    recentFatigueBrief ? '【近章连载动能与疲劳规避】' : '',
    recentFatigueBrief ? '硬性要求：执行 chapter_target.recent_fatigue_brief，并逐条执行 next_actions；本章必须主动修复最近章节暴露的连载动能、冲突来源、回报形态、章末问题或可视化场面风险。不得为了稳妥继续复刻同一种压迫、同一种打脸、同一种悬念，也不得跳过两章/五章窗口里的写前预警。' : '',
    recentFatigueBrief?.chapter_range_label ? `观察区间：${recentFatigueBrief.chapter_range_label}` : '',
    Number.isFinite(Number(recentFatigueBrief?.score)) ? `疲劳分：${recentFatigueBrief.score}` : '',
    recentFatigueBrief?.summary ? `疲劳概览：${recentFatigueBrief.summary}` : '',
    recentFatigueBrief?.fatigue_risks?.length ? `疲劳风险：${recentFatigueBrief.fatigue_risks.join('；')}` : '',
    recentFatigueBrief?.conflict_variation ? `冲突换源：${recentFatigueBrief.conflict_variation}` : '',
    recentFatigueBrief?.payoff_variation ? `回报换形：${recentFatigueBrief.payoff_variation}` : '',
    recentFatigueBrief?.hook_variation ? `钩子换题：${recentFatigueBrief.hook_variation}` : '',
    recentFatigueBrief?.scene_freshness ? `场面新鲜度：${recentFatigueBrief.scene_freshness}` : '',
    recentFatigueBrief?.next_actions?.length ? `执行动作：${recentFatigueBrief.next_actions.join('；')}` : '',
    recentFatigueBrief ? JSON.stringify(recentFatigueBrief, null, 2).slice(0, 4000) : '',
    '',
    signatureSceneBrief ? '【本章标志性场面补位】' : '',
    signatureSceneBrief ? '硬性要求：必须把 signature_scene 写成正文核心场面；scene_repair_target 是本章要修复的强场面缺口；reader_payoff 和 storyline_service 必须落成可见爽点、冲突结果或主线推进。不能只在旁白里声明“场面很震撼”。' : '',
    signatureSceneBrief ? JSON.stringify(signatureSceneBrief, null, 2).slice(0, 3000) : '',
    '',
    characterArcBrief && Object.keys(characterArcBrief).length ? '【人物成长承接】' : '',
    characterArcBrief && Object.keys(characterArcBrief).length ? '硬性要求：执行 chapter_target.character_arc_brief；本章必须把角色欲望、缺陷受压、关系变化、成长节点和口吻锚点写成可见选择、行动后果、对话反馈或关系反应。不得只在旁白里说人物成长，不得提前揭露 forbidden_reveal。' : '',
    characterArcBrief && Object.keys(characterArcBrief).length ? JSON.stringify(characterArcBrief, null, 2).slice(0, 4000) : '',
    '',
    batchPreflight ? '【安全连写预执行门禁】' : '',
    batchPreflight ? '硬性要求：本章必须服从安全连写预执行门禁；若存在近10章疲劳、批次任务书缺口、被拦截章节或 caution/warn 风险，本章必须主动换冲突来源、回报形态、章末问题或可视化场面，不能沿用上一批同质化写法。' : '',
    batchPreflight ? JSON.stringify(batchPreflight, null, 2).slice(0, 4000) : '',
    '',
    batchChapterHandoffContract ? '【安全连写章节交接契约】' : '',
    batchChapterHandoffContract ? '硬性要求：执行 batch_preflight.chapter_handoff_contract；这是安全连写启动时从上一章交接单和读者期待账提炼出的连续性契约。开篇前 300 字必须承接 previous_handoff 和 opening_obligations；must_deliver 必须写成可见回报；keep_alive 必须保持存在感；overdue 必须优先推进，不能被新剧情覆盖。' : '',
    batchChapterHandoffContract?.from_chapter_no ? `交接来源：第${batchChapterHandoffContract.from_chapter_no}章` : '',
    batchChapterHandoffContract?.apply_to_chapter_no ? `优先落点：第${batchChapterHandoffContract.apply_to_chapter_no}章` : '',
    batchChapterHandoffContract?.previous_handoff ? `上一章最后一幕：${batchChapterHandoffContract.previous_handoff}` : '',
    batchChapterHandoffContract?.opening_obligations?.length ? `开篇义务：${batchChapterHandoffContract.opening_obligations.join('；')}` : '',
    batchChapterHandoffContract?.expectation_carry_over?.length ? `期待承接：${batchChapterHandoffContract.expectation_carry_over.join('；')}` : '',
    batchChapterHandoffContract?.must_deliver?.length ? `必须兑现：${batchChapterHandoffContract.must_deliver.join('；')}` : '',
    batchChapterHandoffContract?.keep_alive?.length ? `继续悬念：${batchChapterHandoffContract.keep_alive.join('；')}` : '',
    batchChapterHandoffContract?.overdue?.length ? `逾期优先：${batchChapterHandoffContract.overdue.join('；')}` : '',
    batchChapterHandoffContract ? JSON.stringify(batchChapterHandoffContract, null, 2).slice(0, 3000) : '',
    '',
    batchDeliveryRiskCarryOver ? '【安全连写交稿风险承接】' : '',
    batchDeliveryRiskCarryOver ? '硬性要求：执行 batch_preflight.delivery_risk_carry_over；这是安全连写启动时从上一章交稿状态带来的风险债务，本章必须把它们写成开篇承接、中段推进和章末追读动作，不能只在旁白中宣布已修复。' : '',
    batchDeliveryRiskCarryOver?.source_chapter_no ? `风险来源：第${batchDeliveryRiskCarryOver.source_chapter_no}章` : '',
    batchDeliveryRiskCarryOver?.apply_to_chapter_no ? `优先落点：第${batchDeliveryRiskCarryOver.apply_to_chapter_no}章` : '',
    batchDeliveryRiskCarryOver?.priority_label ? `优先级：${batchDeliveryRiskCarryOver.priority_label}` : '',
    batchDeliveryRiskCarryOver?.items?.length ? `风险项：${batchDeliveryRiskCarryOver.items.join('；')}` : '',
    batchDeliveryRiskCarryOver?.required_actions?.length ? `修复动作：${batchDeliveryRiskCarryOver.required_actions.join('；')}` : '',
    batchDeliveryRiskCarryOver?.opening_actions?.length ? `开篇动作：${batchDeliveryRiskCarryOver.opening_actions.join('；')}` : '',
    batchDeliveryRiskCarryOver?.middle_actions?.length ? `中段动作：${batchDeliveryRiskCarryOver.middle_actions.join('；')}` : '',
    batchDeliveryRiskCarryOver?.ending_actions?.length ? `章末动作：${batchDeliveryRiskCarryOver.ending_actions.join('；')}` : '',
    batchDeliveryRiskCarryOver ? JSON.stringify(batchDeliveryRiskCarryOver, null, 2).slice(0, 3000) : '',
    batchCreationContractCarryOver ? '【安全连写创作契约承接】' : '',
    batchCreationContractCarryOver ? '硬性要求：执行 batch_preflight.delivery_risk_carry_over.creation_contract_carry_over；这是安全连写第一章必须优先修复的长篇创作契约债务，不能只在旁白中声明契约已修复。' : '',
    batchCreationContractCarryOver?.priority_label ? `契约优先级：${batchCreationContractCarryOver.priority_label}` : '',
    batchCreationContractCarryOver?.checklist?.length ? `契约清单：${batchCreationContractCarryOver.checklist.join('、')}` : '',
    batchCreationContractCarryOver?.items?.length ? `契约缺口：${batchCreationContractCarryOver.items.join('；')}` : '',
    batchCreationContractCarryOver?.required_actions?.length ? `契约动作：${batchCreationContractCarryOver.required_actions.join('；')}` : '',
    batchCreationContractCarryOver?.policy ? `契约策略：${batchCreationContractCarryOver.policy}` : '',
    batchCreationContractCarryOver ? '执行口径：目标读者、题材定位、核心承诺、追读留存必须分别写成可定位正文证据；开篇先补读者压力，中段兑现题材长板和核心承诺，章末留下追读问题。' : '',
    '',
    millionWordRunway ? '【百万字航线守门】' : '',
    millionWordRunway ? '硬性要求：本章必须回答航线中的本章四问，遵守不可偏移红线，兑现追读燃料；如果 safeModeLabel 为仅单章或禁止连写，不得抢跑后续章节内容。' : '',
    millionWordRunway ? JSON.stringify(millionWordRunway, null, 2).slice(0, 5000) : '',
    '',
    goldenThreeBrief ? '【黄金三章启动守门】' : '',
    goldenThreeBrief ? '硬性要求：执行 chapter_target.golden_three_brief；前三章必须快速交付钩子、主角、事件、升级/追读理由、前三章至少两个爽点和每章结尾悬念，不得用大段世界观说明开局。' : '',
    goldenThreeBrief ? JSON.stringify(goldenThreeBrief, null, 2).slice(0, 3000) : '',
    '',
    first30RetentionBrief ? '【本章前30章留存修复】' : '',
    first30RetentionBrief ? '硬性要求：本章必须修复前30章诊断指出的目标、章末钩子、爽点/悬念和试读闭环风险；修复要落成可见行动、信息增量、回报或章末未解问题。' : '',
    first30RetentionBrief ? JSON.stringify(first30RetentionBrief, null, 2).slice(0, 4000) : '',
    '',
    readerDropRiskBrief ? '【读者弃读预警】' : '',
    readerDropRiskBrief ? '硬性要求：执行 chapter_target.reader_drop_risk_brief；drop_points 是试读读者可能离开的原因，必须分别在开篇 300 字、中段场景推进和章末翻页处补抓手。不得用设定说明、模板热血或空泛总结糊过去。' : '',
    readerDropRiskBrief?.opening_guardrail ? `开篇防弃读：${readerDropRiskBrief.opening_guardrail}` : '',
    readerDropRiskBrief?.middle_guardrail ? `中段防掉速：${readerDropRiskBrief.middle_guardrail}` : '',
    readerDropRiskBrief?.ending_guardrail ? `章末防流失：${readerDropRiskBrief.ending_guardrail}` : '',
    readerDropRiskBrief ? JSON.stringify(readerDropRiskBrief, null, 2).slice(0, 4000) : '',
    '',
    readerExpectationDebtContext.must_carry.length || readerExpectationDebtContext.keep_alive.length ? '【期待债务承接】' : '',
    readerExpectationDebtContext.must_carry.length || readerExpectationDebtContext.keep_alive.length ? '硬性要求：上一章或最近章节欠下的期待必须在本章可见推进；overdue/逾期待补项必须优先处理成动作、信息增量、冲突结果或章末升级。可延迟完全兑现，但不得遗忘、换线或矛盾改写。' : '',
    readerExpectationDebtContext.must_carry.length || readerExpectationDebtContext.keep_alive.length ? JSON.stringify(readerExpectationDebtContext, null, 2).slice(0, 3000) : '',
    '',
    innovationBrief ? '【本章创新执行】' : '',
    innovationBrief ? '硬性要求：执行 chapter_target.innovation_brief；chapter_angle 必须写成选择、规则、机制、反差或场面，execution_points 必须落成可见动作，differentiation_guardrails 不得越线，ip_adaptation_hooks 尽量转成可视化镜头。' : '',
    innovationBrief?.chapter_angle ? `创新角度：${innovationBrief.chapter_angle}` : '',
    innovationBrief?.execution_points?.length ? `执行点：${innovationBrief.execution_points.join('；')}` : '',
    innovationBrief?.differentiation_guardrails?.length ? `差异护栏：${innovationBrief.differentiation_guardrails.join('；')}` : '',
    innovationBrief?.ip_adaptation_hooks?.length ? `IP化场面：${innovationBrief.ip_adaptation_hooks.join('；')}` : '',
    innovationBrief ? JSON.stringify(innovationBrief, null, 2).slice(0, 3000) : '',
    '',
    styleSampleStrategy?.enabled ? '【本章风格样章策略】' : '',
    styleSampleStrategy?.enabled ? '硬性要求：只学习叙述节奏、句式密度、对白比例和情绪转折；原句不能照搬，不得复制样章桥段、专有设定、角色名和核心梗。' : '',
    styleSampleStrategy?.enabled ? JSON.stringify(styleSampleStrategy, null, 2).slice(0, 5000) : '',
    '',
    chapterBenchmarkStrategy?.enabled ? '【本章质量基准样例】' : '',
    chapterBenchmarkStrategy?.enabled ? '硬性要求：只学习章节结构、信息密度、冲突节拍、爽点兑现和章末钩子；不得复制样例桥段、角色名、专有设定和原句，不得把样例剧情替换成本章剧情。' : '',
    chapterBenchmarkStrategy?.enabled ? JSON.stringify(chapterBenchmarkStrategy, null, 2).slice(0, 5000) : '',
    '',
    '【结构化上下文包】',
    prosePromptJson(buildProsePromptContextSnapshot(contextPackage), 4500),
    '',
    '【参考迁移计划】',
    prosePromptJson(migrationPlan || {}, 2500),
    '',
    '【段落级写作要求】',
    '1. 严格按 scene_cards 顺序生成，每个场景至少 3-8 个自然段。',
    '2. 每个场景必须完成 purpose、conflict、required_beats、required_information、turning_point 和 exit_state；不能只写气氛、设定说明或心理总结。',
    '2+. 场景执行门禁：每个 scene_cards 必须按 goal -> obstacle -> action -> turn -> payoff -> state_delta 写成因果链；turn 必须优先来自 turning_point/reversal/information_gain，payoff 必须优先来自 reader_payoff/core_payoff/scene_payoff_budget，state_delta 必须写清本场景改变了角色、资产、关系、伏笔、规则或读者期待中的哪一项。',
    '2A. 每个场景必须把 opening_hook、reader_payoff、fear_point、rule_pressure、information_gap、reversal、ending_hook_seed、character_voice 中已有的商业意图落实到正文里；这些字段不是备注，必须转成动作、对话、危险、反转或章末疑问。',
    '2A+. 执行 scene_cards.dialogue_goals、scene_cards.style_directives、scene_cards.benchmark_recall_directives、scene_cards.concept_anchor_rules、scene_cards.prose_craft_directives、scene_cards.relationship_progression_plan、scene_cards.relationship_buffer_zone、scene_cards.supporting_character_action、scene_cards.attitude_shift_checkpoint 和 scene_cards.relationship_next_hook：对白目标必须变成角色差异化对话和潜台词，文风/对标召回只学习节奏与句式呼吸，新名词/新设定首次出现必须用动作反应、对话半句或物理后果建立当下作用锚点，不得写整段来历、原理或等级说明；关系推进必须写出关系类型/边界、配角攻略缓冲区、配角主动行动、从旁观/质疑/拒绝/试探到行动/协助/设限的态度变化，以及下一轮关系期待。',
    '2A+showdown. 执行 scene_cards.showoff_stage_chain、scene_cards.spectator_interest_shift、scene_cards.secondary_showoff_effect、scene_cards.combat_result_type、scene_cards.combat_dimension_plan 和 scene_cards.combat_reversal_plan：公开爽点必须按群众层 -> 中间层 -> 核心层落成不同反应；旁观者反应必须回答“这跟我有关系”的利益、目标、计划或站队变化；二级装逼效果必须让展示改变旁观者行动；战斗/智斗必须明确结果类型、心/体/技维度和预判反制/反预判链条。',
    '2A+. 如果存在 chapter_target.previous_handoff 或 continuity.previous_chapter，开篇前 300 字必须承接上一章最后一幕或章末钩子，先处理连续危机、角色反应和期待欠账，再展开新的场景信息。',
    '2A++. 如果存在 chapter_target.requiredHandoffAnchors 或 opening_obligations，开篇前 300 字必须命中这些交接锚点/义务；不得跳过上一章未完成动作直接进入新目标。',
    '2A++. 执行 chapter_target.delivery_risk_carry_over：上一章交稿后残留的吸引力、追读、创新、故事力、剧情线、强场面或可读性风险，必须在本章变成可见修复动作；尤其优先级指向开篇或章末时，必须在前 300 字或最后 300 字落地。',
    '2B. 执行 chapter_target.reader_retention_brief：开篇钩子必须在前 300 字落地；爽点承诺、信息缺口、情绪回报和短剧化场面必须转成可见行动；retention_double_engine 必须按留存=情绪+饥饿落地，情绪让读者快速代入，饥饿用信息差植入问号并按剥洋葱把关键信息卡到章末；retention_pillars 必须按留存四大支柱落地，升级、资源困境、目标、解密至少两项要转成正文证据；hook_addiction_model 必须按触发 -> 行动 -> 奖励 -> 投入落地，并用奖励随机性给出出乎意料的额外收获或沉没投入；章末追读问题必须压到最后一幕。',
    '2B+. 执行 chapter_target.reader_expectation_ledger：must_deliver 是本章必须还给读者的期待账，必须写成可见事件、冲突结果、情绪回报或章末钩子；keep_alive 可以保留但不能遗忘或矛盾改写。',
    '2B++. 执行 reader_expectation_debt_context：must_carry 来自上一章或最近章节的期待欠账，本章必须给可见推进；keep_alive 是继续悬念，必须保持存在感，不得被正文遗忘、反向改写或突然换线。',
    '2C. 执行 chapter_target.innovation_brief：本章必须有可见的创新执行点；把 chapter_angle 写成选择、规则、机制、反差或场面，不得写成普通套路章；ip_adaptation_hooks 要尽量落成可视化场面。',
    '2C+. 执行 chapter_target.signature_scene_brief：如果存在 signature_scene，必须把它写成本章最可被读者记住、可短剧/漫剧化的空间冲突、反转动作、规则压迫或视觉化爽点；scene_repair_target、reader_payoff、storyline_service 都必须在正文中可见。',
    '2C++. 执行 chapter_target.character_arc_brief：人物成长必须落成角色欲望驱动、缺陷受压、关系变化、成长节点或口吻锚点；如果有 forbidden_reveal，不得提前写穿，只能通过误解、遮挡、试探或代价保持边界。',
    '2C+++. 执行 chapter_target.golden_three_brief：前三章必须按启动守门交付前 500 字钩子、主角出场、真实事件、第二章升级、第三章追读理由、前三章至少两个爽点和章末悬念；禁止用大段世界观说明替代现场事件。',
    '2D. 执行 chapter_target.first30_retention_brief：如果当前章在前30章诊断中有风险，必须补强 flags 和 required_actions 指向的留存问题，尤其是章末钩子弱、爽点/悬念信号少、目标不清和缺正文。',
    '2D+. 执行 chapter_target.reader_drop_risk_brief：正文必须针对弃读点设计开篇抓手、中段反转/行动推进和章末翻页问题；任何 drop_points 中指出的风险都必须用可见事件、对话冲突、信息增量或读者回报修复。',
    '2D++. 执行 chapter_target.story_pressure_brief：本章必须补足压力源、冲突升级、赌注升级和反转逼迫；至少一个场景要让主角付出代价、被迫选择、暴露风险、遭遇反制或得到新的未解问题。',
    '2D+++. 执行 chapter_target.story_drive_brief：必须写出主角主动选择、选择代价、状态变化和下一步因果；主角不能只是旁观、听解释或被事件推着走。',
    '2D+++.1 执行 chapter_target.story_power_contract：必须让故事五维落成正文证据；每个关键场景都要有行动改变局势，开场压力要在章末形成状态变化，动作必须带来代价、信息、关系、规则或敌方反制反馈。',
    '2D+++.2 执行 chapter_target.chapter_blueprint.mainline_definition_contract：主线不等于升级，主线是一件事，不是一个元素，升级是主角达成目标的行动；每章必须让 mainline_event 发生状态变化，不能把境界升级、金手指展示、地图或设定罗列写成主线。',
    '2D++++. 执行 chapter_target.serial_rhythm_brief：前 300 字必须有开篇钩子；每 800-1200 字至少给一次信息增量、冲突转折、爽点兑现、能力展示、关系变化或小回收；每个场景必须兑现 scene_payoff_budget；章末必须压出追读问题。',
    '2D+++++. 执行 chapter_target.page_turn_hook_brief：最后 300 字必须有可见触发、读者问题和下一章拉力；禁提前解答项不得在本章说明完；结尾不能用“拉开序幕”等模板总结替代现场钩子。',
    '2D++++++. 执行 chapter_target.volume_climax_brief：本章只兑现 current_chapter_role、required_beats 和 climax_promise；不得提前消费 forbidden_payoff 中的卷末爆点、身份答案、终局反转或后续大回报。',
    '2D+++++++. 执行 chapter_target.recent_fatigue_brief：逐条执行 next_actions；如果近章连载动能或疲劳风险提示目标推进、阻碍升级、新信息、关系/世界调剂、大冲突冷却、冲突来源、回报形态、章末问题或可视化场面存在缺口，本章必须用可见事件修复；禁止继续复制最近章节的同类压迫、同类打脸、同类钩子或原地等待。',
    '2D++++++++. 执行 scene_cards.serial_risk_repairs 与 scene_cards.recent_fatigue_action：凡场景卡标注了风险修复动作，正文必须用目标推进、阻碍升级、新信息、关系/世界调剂或冲突冷却把它写成可见事件；不得只在旁白中宣布已修复。',
    '2D+++++++++. 执行 scene_cards.conflict_ladder_step、scene_cards.motivation_source、scene_cards.opposing_force、scene_cards.blocked_desire、scene_cards.protagonist_agency_action、scene_cards.no_exit_reason、scene_cards.event_value_change、scene_cards.next_conflict_seed、scene_cards.visible_line_role、scene_cards.hidden_line_seed、scene_cards.ab_weave_role：逐场写清有人阻止主角得到他想要的东西、有进无出、主角主动破局、明确价值变化、下一冲突种子、明线/暗线交汇伏笔和 A线/B线交织位置；不能只把这些字段留在场景卡里。',
    '2D++++++++. 执行 chapter_target.platform_rubric：按目标平台调整开篇强度、节奏密度、回报间隔、设定释放和章末拉力；平台检查项不能只写在说明里，必须落到正文证据。',
    '3. 如果 scene_type 是 action/combat/chase，必须逐条落实 action_beats：写出动作起手、空间位置、对手反应、受伤/损耗/暴露信息、反制动作和结果。战斗不能一笔带过。',
    '4. 段落预算：动作/冲突场景中可见行动与直接反应不少于 60%；环境描写最多 15%；心理描写最多 20%；解释性信息最多 15%。',
    '5. 禁止连续 2 段纯环境描写；每 3-5 段必须出现一次可见行动、选择、信息变化或关系变化。',
    '6. description_budget=low 的场景只允许 1-2 句环境描写；medium 最多 1 个短段；high 也必须服务危险、规则或动作空间。',
    '6A. 执行 scene_cards.purpose_tag 与 scene_cards.density_level：先按目的词分配详略；purpose_tag=爽点/打脸/高潮/卖点/关键揭露/反转的场景必须展开危机/期待铺垫、出手过程、对话交锋和配角差异化反应；purpose_tag=过渡/赶路/信息交代/时间跳转的场景只能 1-2 句带过。density_level=dense 的爽点/打脸/反转/情绪高潮必须用感知、动作、对话交锋铺满，慢镜头逐拍展开；density_level=sparse 的过场/赶路/信息交代/时间跳转只能 1-2 句带过，不展开三维度；density_level=medium 的铺垫/日常/关系升温只挑 1-2 个有代入感细节，其余略写。不允许每个 beat 一样长一样细。',
    '6B. 子事件连接不用叙述过渡；不要用“然后/接着/随后/于是”串联事件，改用约20字的身体动作、物件动作、触感、视线或呼吸承接下一个动作。',
    '6C. 执行 scene_cards.sensory_anchor：每个详写场景必须把感知锚点写成主角主动注意到的细节，并让它参与动作、规则判断、危险识别或对话反应，不能当装饰性氛围或独立风景句。',
    '6D. 主语与名字节奏：段首、场景切换、多人同场、视角重置时用角色名建立主语；同一动作链/同一段内部优先用“他/她”、动作承接或省略主语。关键转折、情绪爆点、身份反差时再点名强化；不要连续多句都以同一角色名开头，也不要为了省主语造成指代不清。',
    '6E. 自然节奏重排：断段按镜头/信息变化，不按发生/感知/反应三维度变化；同一镜头保持连续。新动作、新物件、新信息、新对话、视线转移、场景结束时可以断段；不要把完整推理链切成机械碎片，也不要把多个动作/信息/视线切换塞进一个拥挤长段。',
    '6F. 语气标点功能拍：被打断 / 拖长音用动作打断、换行、短句或未完成动作承接，不用 ——/—/-- 硬造停顿；信息揭示 / 判断落点可用冒号或短句制造落点，不写论文式长分号链。',
    '6G. 小节密度诊断：场景或小节偏短不得加环境描写、重复情绪、内心独白总结或无意义动作凑字数；先检查子事件三维度是否揉进，再补感官细节、身体反应、对话交锋、阻碍/反应/发现/递进，必要时只加 2-3 句简短回忆。',
    '6H. 具体字数表达校验：除非正文中那句话的字数确实经过核对且必须强调，否则不要写“这五个字 / 短短四字 / 三个字一落 / 八个字砸下去”这类精确字数表达；优先改成“这句话一落”“这一句落下”“那几个字”“这行字”“话音落下”，保持现场冲击但不制造可被读者数错的违和感。',
    '7. 场景之间必须有过渡，不能硬切。',
    '8. 保持 style_lock 中的人称、句长、对话比例、吐槽密度、爽点密度、描写浓度和禁用词约束。',
    '9. 只能学习参考作品的节奏、结构、爽点安排和信息密度；不得复制具体桥段、专有设定、原句、角色名和核心梗。',
    '10. 执行 setting_context：required 设定必须在正文中落地；forbidden 设定不得泄漏；ability_beats 必须写清代价/限制；item_beats 必须符合物品归属和位置；boss_move 必须符合 Boss 行动逻辑；rule_trigger 必须写出触发条件、代价和后果；角色只能知道 knowledge_scope 允许的信息。',
    '11. 执行 chapter_target.meme_strategy：网感只作为吐槽节奏、情绪共鸣、角色口吻或传播点；死亡、高压恐怖和关键情绪爆点处不得玩梗；不得直接复刻 meme_bank 的 unsafe_direct_phrases。',
    '12. 执行 chapter_target.style_sample_strategy：按 applicable_scenes / avoid_scenes 选择样章策略；只学习叙述节奏、句式密度、对白比例和情绪转折；do_not_copy 与 unsafe_direct_phrases 中的原句不能照搬。',
    '12A. 执行 chapter_target.chapter_benchmark_strategy：只学习开篇钩子、场景节拍、冲突升级、爽点兑现、对白推进、场面可视化和章末追读结构；不得复制样例桥段、角色名、专有设定和原句。',
    styleBoundaryContract ? '12B. 执行 chapter_target.style_boundary_contract：文风覆盖边界必须服从“硬约束永远赢”；不得为了模仿文风引入禁用词、Gate F 章末升华、万能比喻、章末预告、字数缩水、剧情/状态/关系/时间线漂移或样章复制。' : '',
    '13. 执行长篇作品罗盘：读者承诺、核心矛盾、创新卖点、长期爽点循环和结局方向不得漂移；新增人物、物品、支线或地图必须落在可调整区内。',
    '13A. 执行 chapter_target.chapter_launch_gate：读者承诺、本章目标、核心冲突、主线服务、读者回报、章末钩子必须在正文中可见落地；如果门禁信号为 warn/block，不得忽略，必须优先补成可见事件、选择、冲突结果或章末问题。',
    '13A+. 执行 chapter_target.core_contract_radar：必须服务 must_serve 中的全书核心承诺、核心矛盾、创新卖点和读者回报；不得漂移 no_drift 中的红线；repair_focus 不能只靠解释，要落成正文中的冲突结果、规则判定、角色选择或章末钩子。',
    '13A++. 执行 chapter_target.governance_recheck_memory：上一轮治理复查的修后证据和观察项必须进入本章任务执行；evidence 写成正文可见继承，failed_evidence 优先补救，watch_items 保持观察并避免再次失效。',
    '13B. 执行 chapter_target.longform_battle_context：核心守恒、读者拉力、剧情线调度、卷级爆点、创新/IP场面和生产燃料中的风险项必须在本章有可见承接；blocked/warn 风险优先于普通铺垫，不能写成空泛解释。',
    '14. 执行本批连载任务书：本章只完成 current_chapter_role 和本章读者回报；可以铺垫下一章，但不得提前解决 next_batch_brief.chapters 后续章节的冲突或钩子。',
    '14A. 执行 chapter_target.batch_preflight：如果安全连写预执行门禁提示近10章疲劳或批次风险，本章必须在冲突来源、回报形态、章末问题、可视化场面中至少改造一项；被 blocked_chapter_nos 拦截的后续章节内容不得提前写进本章。',
    expansionStructureDecision ? '14A0. 执行 next_batch_brief.expansion_structure_decision：按结构修复有效性决定本批写法；恢复5章时仍逐章落实段位职责，小批验证时逐章证明观察指标，单章重构时先重写批次设计原则后再推进正文。' : '',
    defaultFiveChapterLaneRedesign ? '14A0+. 默认5章档位结构重构：因连续恢复判定失效，本章必须输出可被后续5章复用的段位职责、冲突轮换、回报密度和章末追读模板；正文场景必须先证明这个模板能守住核心、回报和追读。' : '',
    expansionStructureVerification ? '14A+. 执行 next_batch_brief.expansion_structure_verification：本章必须承担验证批中的结构职责，换冲突来源、给显性回报、留不同章末追读问题；不得把已修复的扩批热区再次写成中段转场或空铺垫。' : '',
    defaultFiveChapterLaneTemplate ? '14A+0. 默认5章档位模板验证：本章必须继承已补齐的段位职责、冲突轮换、回报密度和章末追读模板；每个结构职责场景都要证明四项模板没有复发，不能只把模板写在说明里。' : '',
    '14A++. 执行 batch_preflight.longform_memory_anchor：批量续写时必须遵守压缩正史锚点，不能改变角色状态、遗忘开放悬念、跳过回报债务或偏离核心承诺。',
    '14A+++. 执行 batch_preflight.delivery_risk_carry_over：安全连写第一章必须优先承接上一章残留风险；opening_actions 在前 300 字落地，middle_actions 在中段转成事件推进，ending_actions 在最后 300 字形成追读钩子。',
    batchCreationContractCarryOver ? '14A+++.1 执行 batch_preflight.delivery_risk_carry_over.creation_contract_carry_over：安全连写第一章必须先修创作契约；目标读者、题材定位、核心承诺、追读留存分别要有正文证据，不能只靠旁白声明或任务书自述。' : '',
    '14A++++. 执行 batch_preflight.chapter_handoff_contract：安全连写第一章必须承接上一章最后一幕、开篇义务和读者期待债；must_deliver 写成可见回报，keep_alive 保持存在感，overdue 优先推进。',
    '14A+++++. 执行 chapter_target.longform_memory_capsule：单章开写也必须召回压缩正史，角色状态、开放悬念、回报债务、正史事实和 red_lines 不得遗忘、矛盾改写或跳过。',
    '14A++++++. 执行 chapter_target.established_events_contract：已锁正史事件不得在闪回或复述中改写；只能同义转述，并保留 cause/mechanism/constraints。',
    layeredMemoryContext ? '14A++++++. 执行 chapter_target.layered_memory_context：近5章详记决定本章承接细节，十章概要决定阶段正史，卷级总览决定卷级方向和关键转折；不得只看最近一章导致早期正史或卷级目标漂移。' : '',
    '14B. 执行 chapter_target.million_word_runway：正文必须可见回答本章四问，守住 redLines，不丢 readerFuel；如果航线为 single_chapter 或 blocked，只写当前章可兑现内容，不得预支后续章节主线回收。',
    '14C. 执行 chapter_target.story_unit_context：正文必须完成当前剧情单元的 current_chapter_role；只推进本章职责需要的 pressure_escalation、setup_and_storyline 和 reader payoff，不得提前写完 mini_climax_payoff、exit_hook 或 forbidden_advance 标注的后续兑现。',
    '15. 如果参考迁移计划包含 transferable_model，只能采用其中 allowed_learning 的抽象功能；rewrite_requirements 必须执行；copy_guard_terms 和 forbidden_transfer 禁止出现在正文里。',
    migrationPlan?.generation_prompt_addendum ? `16. ${prosePromptText(migrationPlan.generation_prompt_addendum, 700)}` : '',
    chapterDraft?.chapter_no ? `17. 本次只生成第${chapterDraft.chapter_no}章，不得输出其他章节或续章内容。` : '',
    '18. 正文元信息清洁：chapter_text 标题行以外不得出现“上一章/本章/前文/后文/伏笔/细纲/读者/第X章”等作者视角或工程词；必须改成角色当下能感知的事件锚点或相对时间，例如“门牌翻面那一刻”“刚才那句话”“那枚旧印”。',
    '19. 正文格式与小节结构：全文统一章节标记：###1. / ###第一章 / 1. 或项目指定格式，不混用；按网文阅读节奏断段，段间保留一个空行，不得出现两个以上连续空行；无缩进，正文段落中不使用 Markdown；断段按戏剧单元/镜头自然断开，不按字数机械切段；对话独立成行，引号风格按项目/平台约定，quote-mode keep 时保留合法「」；每个小节至少有一个主事件 + 3-5 个子事件、情绪变化、新信息和小节钩子。',
    '',
    expansionStructureDecision ? '输出附加要求：如果存在 next_batch_brief.expansion_structure_decision，scene_breakdown 的相关场景必须包含 expansion_structure_decision_execution，用 segment_role_delivered、observation_metrics_delivered、redesign_principles_delivered 和 evidence 说明是否真正执行。' : '',
    defaultFiveChapterLaneRedesign ? '输出附加要求：如果存在 default_five_chapter_lane_redesign，expansion_structure_decision_execution 还必须包含 default_lane_segment_duty_delivered、default_lane_conflict_rotation_delivered、default_lane_payoff_density_delivered、default_lane_ending_hook_template_delivered，并分别给出 evidence。' : '',
    defaultFiveChapterLaneTemplate ? '输出附加要求：如果存在 default_five_chapter_lane_template，expansion_structure_decision_execution 必须继续包含 default_lane_segment_duty_delivered、default_lane_conflict_rotation_delivered、default_lane_payoff_density_delivered、default_lane_ending_hook_template_delivered，并用 evidence 说明四项模板在验证批中没有复发。' : '',
    chapterBlueprint ? '输出附加要求：scene_breakdown 必须包含 blueprint_receipts，逐项回填 target_emotion、opening_hook、core_payoff、content_outline、plot_lines、character_order、beat_sequence、beat_density_contract、small_outline_contract、mainline_definition_contract、cost_and_reward、ending_contract 是否在正文兑现，并给出 evidence 摘要。' : '',
    '输出附加要求：scene_breakdown 每个场景必须包含 scene_start_anchor、scene_end_anchor 和 scene_card_receipts；scene_start_anchor/scene_end_anchor 必须摘自该场景正文的起止短句，用来定位该场景文本。scene_card_receipts 字段至少包含 scene_goal, obstacle, action, turn, payoff, state_delta, goal_obstacle_change_delivered(boolean)、purpose_tag_delivered(boolean)、density_level_delivered(boolean)、sensory_anchor_delivered(boolean)、serial_risk_repairs_delivered(boolean)、required_beats_delivered(boolean)、action_beats_delivered(boolean)、dialogue_goals_delivered(boolean)、style_directives_delivered(boolean)、benchmark_recall_directives_delivered(boolean)、concept_anchor_rules_delivered(boolean)、prose_craft_directives_delivered(boolean)、relationship_progression_delivered(boolean)、relationship_buffer_zone_delivered(boolean)、supporting_character_action_delivered(boolean)、attitude_shift_delivered(boolean)、relationship_next_hook_delivered(boolean)、showoff_stage_chain_delivered(boolean)、spectator_interest_shift_delivered(boolean)、secondary_showoff_effect_delivered(boolean)、combat_result_type_delivered(boolean)、combat_dimension_plan_delivered(boolean)、combat_reversal_plan_delivered(boolean)、evidence(array)。evidence 必须摘录对应场景正文中的动作、对话、信息变化、关系变化、对白声线、新概念锚点、配角主动行动、缓冲区、态度变化、公开舞台层级、旁观者利益变化或战斗反制证据，不能只写“已完成”，不能借用其他场景的证据。',
    '输出附加要求：必须在章节对象顶层输出 oh_story_delivery_receipts，用于后续诊断和修复闭环落库。oh_story_delivery_receipts 必须包含 chapter_blueprint、scene_card_receipts、delivery_risk_receipts、revision_receipts、pre_draft_execution_receipts；chapter_blueprint 记录本章蓝图兑现状态，scene_card_receipts 汇总每个场景的场景卡执行回执，delivery_risk_receipts 逐项记录上一章/批次交稿风险是否已兑现，revision_receipts 记录本轮生成中主动修正过的结构、连续性、资产或文风问题，pre_draft_execution_receipts 记录状态筛选、项目产物协议、写前准备、意图确认、文风召回和上一章质量续航计划是否真正落入正文。',
    ...buildStateTrackingReceiptPromptSection(stateTrackingContract),
    '输出附加要求：oh_story_delivery_receipts.pre_draft_execution_receipts.artifact_protocol_receipts 必须按 oh-story artifact-protocols 记录本章使用或依赖的项目产物；覆盖路径包括 设定/关系.md、设定/题材定位.md、大纲/卷纲_第X卷.md、大纲/细纲_第XXX章.md、追踪/伏笔.md、追踪/时间线.md、追踪/角色状态.md、追踪/上下文.md、对标/{对标书名}/拆文报告.md。每项包含 key,label,status(pass|warn|fail|ready),artifact_path,required_fields,used_fields,evidence,remaining_risk；required_fields 必须按对应模板列出核心字段，evidence 必须引用 chapter_text 中可定位的动作、对话、信息变化或关系变化。',
    writePreparationBrief ? '输出附加要求：oh_story_delivery_receipts.pre_draft_execution_receipts.write_preparation_checks 必须逐项覆盖【写前准备卡】中的 source_gaps、文风召回缺口和副对标边界、asset_risks、delivery_risk_actions、creation_contract_checklist、blueprint_focus、reader_payoff_focus 和 must_confirm；创作契约必须逐项说明目标读者、题材定位、核心承诺、追读留存是否被正文证据兑现；每项必须有 delivered(boolean)、evidence、remaining_risk，未完成时 delivered=false 并写明下一章需要承接的风险。' : '',
    deliveryRiskCarryOver ? '输出附加要求：oh_story_delivery_receipts.pre_draft_execution_receipts.next_chapter_quality_plan_receipts 必须逐项覆盖上一章质量续航计划和 chapter_target.delivery_risk_carry_over 中的 quality_focus、opening_actions、middle_actions、ending_actions、forbidden_repeats/avoid_repetition、evidence_basis；每项包含 key,label,delivered,evidence,remaining_risk，证明质量续航不是只写在任务书里，而是落成正文动作、信息变化、章末钩子或禁用重复。' : '',
    ...buildIntentConfirmationReceiptPromptSection(intentConfirmationContract),
    ...buildBenchmarkRecallReceiptPromptSection(benchmarkRecallBrief),
    '输出附加要求：oh_story_delivery_receipts 中所有 evidence / changed_evidence 必须引用 chapter_text 中可定位的动作、对话、信息变化或关系变化；changed_evidence 必须引用 chapter_text，不能只写“已完成”“已处理”“见正文”。如果没有完成，delivered 必须为 false 并写 remaining_risk。',
    '输出 JSON，包含 prose_chapters 数组。数组只能有一项，且必须包含 chapter_no, title, chapter_text, scene_breakdown, continuity_notes, oh_story_delivery_receipts。scene_breakdown 要回填每个场景的 scene_type、purpose_tag 目的词执行情况、required_beats/action_beats 完成情况、description_budget 执行情况、density_level 执行情况、scene_start_anchor、scene_end_anchor、scene_card_receipts 和 blueprint_receipts（如有章节蓝图合同）。chapter_text 是完整简体中文正文，不要 markdown 标题。',
  ])
}
