import { describe, expect, test } from 'bun:test'
import { readFileSync } from 'fs'
import { join } from 'path'

function source(file: string) {
  return readFileSync(join(import.meta.dir, file), 'utf8')
}

describe('commercial writing workspace UI shell', () => {
  test('uses command-oriented controls in the central writing toolbar', () => {
    const component = source('WorkspaceCenter.tsx')
    const css = source('WorkspaceCenter.css')

    expect(component).toContain('novel-editor-stagebar')
    expect(component).toContain('novel-editor-command-pill')
    expect(component).toContain('novel-editor-icon-command')
    expect(component).toContain('novel-word-preset')
    expect(component).toContain('NOVEL_WRITING_DESK_COLLAPSED_KEY')
    expect(component).toContain('setWritingDeskCollapsed')
    expect(component).toContain('novel-editor-toolbar-collapsed')
    expect(component).toContain('novel-editor-collapsed-summary')
    expect(component).toContain('novel-editor-toolbar-meta')
    expect(component).toContain('novel-editor-toolbar-actions')
    expect(component).toContain('novel-editor-toolbar-recommendation')
    expect(css).toContain('.novel-editor-command-pill')
    expect(css).toContain('.novel-editor-stage')
    expect(css).toContain('.novel-editor-toolbar-meta')
    expect(css).toContain('.novel-editor-toolbar-actions')
    expect(css).toContain('.novel-editor-toolbar-recommendation')
    expect(css).toContain('grid-template-columns')
    expect(css).toContain('.novel-editor-toolbar-collapsed')
    expect(css).toContain('.novel-editor-toolbar-collapsed .novel-editor-recommendation-hint')
    expect(css).toContain('display: none')
    expect(css).toContain('.novel-editor-collapsed-actions')
    expect(css).toContain('flex-shrink: 0')
  })

  test('uses a production guide command system instead of stacked block buttons', () => {
    const component = source('ProductionGuidePanel.tsx')
    const css = source('ProductionGuidePanel.css')

    expect(component).toContain("import './ProductionGuidePanel.css'")
    expect(component).toContain('production-guide-primary-command')
    expect(component).toContain('production-guide-secondary-command')
    expect(component).toContain('production-guide-step-status')
    expect(component).not.toContain('block\\n                      type={step.status')
    expect(css).toContain('.production-guide-secondary-command')
    expect(css).toContain('.production-guide-step-active')
  })

  test('separates the writing cockpit from delivery and collapsed workspace bars', () => {
    const component = source('WritingCockpitPanel.tsx')
    const css = source('WritingCockpitPanel.css')

    expect(component).toContain("import './WritingCockpitPanel.css'")
    expect(component).toContain('writing-cockpit-card-expanded')
    expect(component).toContain('writing-cockpit-card-collapsed')
    expect(component).toContain('writing-cockpit-subdesk')
    expect(component).toContain('writing-cockpit-command-grid')
    expect(css).toContain('.writing-cockpit-card-expanded')
    expect(css).toContain('.writing-cockpit-subdesk')
    expect(css).toContain('.writing-cockpit-card-collapsed')
  })

  test('uses a reference nav rail with compact revision chips', () => {
    const component = source('ReferencePanel.tsx')
    const css = source('ReferencePanel.css')

    expect(component).toContain("import './ReferencePanel.css'")
    expect(component).toContain('novel-reference-nav-rail')
    expect(component).toContain('novel-reference-nav-item')
    expect(component).toContain('novel-reference-revision-chip')
    expect(css).toContain('.novel-reference-nav-item')
    expect(css).toContain('.novel-reference-revision-chip')
  })

  test('shows storyline workshop types and draft brief storyline section', () => {
    const settingPanel = source('SettingWorkshopPanel.tsx')
    const workspaceCenter = source('WorkspaceCenter.tsx')
    const workspaceCss = source('WorkspaceCenter.css')

    expect(settingPanel).toContain("value: 'mainline'")
    expect(settingPanel).toContain("label: '主线'")
    expect(settingPanel).toContain("value: 'subplot'")
    expect(settingPanel).toContain("value: 'character_arc'")
    expect(settingPanel).toContain("value: 'relationship_arc'")
    expect(settingPanel).toContain("value: 'faction_arc'")
    expect(settingPanel).toContain("value: 'foreshadowing_arc'")
    expect(settingPanel).toContain("value: 'advance'")
    expect(settingPanel).toContain("value: 'payoff'")
    expect(settingPanel).toContain('/storylines/suggest')
    expect(settingPanel).toContain('匹配剧情线')
    expect(workspaceCenter).toContain('剧情线推进')
    expect(workspaceCenter).toContain('必推')
    expect(workspaceCenter).toContain('埋线')
    expect(workspaceCenter).toContain('回收')
    expect(workspaceCenter).toContain('禁用')
    expect(workspaceCss).toContain('.novel-draft-brief-storylines')
  })

  test('shows storyline sync status in the delivery strip', () => {
    const workspaceCenter = source('WorkspaceCenter.tsx')
    const workspaceCss = source('WorkspaceCenter.css')

    expect(workspaceCenter).toContain('storylineSync')
    expect(workspaceCenter).toContain('novel-delivery-storyline-tag')
    expect(workspaceCss).toContain('.novel-delivery-storyline-tag')
    expect(workspaceCss).toContain('.novel-delivery-storyline-tag-warn')
  })

  test('shows chapter core drift status in the delivery strip', () => {
    const workspaceCenter = source('WorkspaceCenter.tsx')
    const workspaceCss = source('WorkspaceCenter.css')
    const model = source('writingCockpitModel.ts')
    const service = readFileSync(join(import.meta.dir, '../../../../server/src/routes/novel-writing-service.ts'), 'utf8')

    expect(workspaceCenter).toContain('coreDrift')
    expect(workspaceCenter).toContain('novel-delivery-core-drift-tag')
    expect(workspaceCss).toContain('.novel-delivery-core-drift-tag')
    expect(workspaceCss).toContain('.novel-delivery-core-drift-tag-warn')
    expect(model).toContain('chapter_core_drift')
    expect(service).toContain("review_type: 'chapter_core_drift'")
  })

  test('shows reader payoff sync status in the delivery strip', () => {
    const workspaceCenter = source('WorkspaceCenter.tsx')
    const workspaceCss = source('WorkspaceCenter.css')
    const model = source('writingCockpitModel.ts')
    const service = readFileSync(join(import.meta.dir, '../../../../server/src/routes/novel-writing-service.ts'), 'utf8')

    expect(workspaceCenter).toContain('readerPayoffSync')
    expect(workspaceCenter).toContain('novel-delivery-payoff-tag')
    expect(workspaceCss).toContain('.novel-delivery-payoff-tag')
    expect(workspaceCss).toContain('.novel-delivery-payoff-tag-warn')
    expect(model).toContain('reader_payoff_sync')
    expect(service).toContain("review_type: 'reader_payoff_sync'")
  })

  test('shows discovered asset intake in delivery strip and setting workshop', () => {
    const workspaceCenter = source('WorkspaceCenter.tsx')
    const workspaceCss = source('WorkspaceCenter.css')
    const settingPanel = source('SettingWorkshopPanel.tsx')
    const projectWorkspace = readFileSync(join(import.meta.dir, '../NovelProjectWorkspace.tsx'), 'utf8')

    expect(workspaceCenter).toContain('assetIntake')
    expect(workspaceCenter).toContain('novel-delivery-asset-tag')
    expect(workspaceCenter).toContain('onOpenStoryAssets')
    expect(workspaceCss).toContain('.novel-delivery-asset-tag')
    expect(settingPanel).toContain('新资产候选')
    expect(settingPanel).toContain('focusDiscoveredAssetsToken')
    expect(settingPanel).toContain('setting-workshop-model-command')
    expect(settingPanel).toContain('actionLoadingKey')
    expect(settingPanel).toContain('isActionLoading')
    expect(settingPanel).toContain('/discovered-assets/apply')
    expect(settingPanel).toContain('selectedDiscoveredAssetKeys')
    expect(settingPanel).not.toContain('loading={saving}')
    expect(projectWorkspace).toContain('设定资产')
    expect(projectWorkspace).toContain('StoryAssetsWorkspace')
    expect(projectWorkspace).toContain('focusDiscoveredAssetsToken')
  })

  test('shows readability and restrained meme strategy in writing workflow', () => {
    const workspaceCenter = source('WorkspaceCenter.tsx')
    const workspaceCss = source('WorkspaceCenter.css')
    const projectWorkspace = readFileSync(join(import.meta.dir, '../NovelProjectWorkspace.tsx'), 'utf8')

    expect(workspaceCenter).toContain('readabilityReview')
    expect(workspaceCenter).toContain('novel-delivery-readability-tag')
    expect(workspaceCenter).toContain('本章网感策略')
    expect(workspaceCenter).toContain('novel-draft-brief-meme')
    expect(workspaceCenter).toContain('本批连载任务')
    expect(workspaceCenter).toContain('novel-draft-brief-batch')
    expect(workspaceCss).toContain('.novel-delivery-readability-tag')
    expect(workspaceCss).toContain('.novel-draft-brief-meme')
    expect(workspaceCss).toContain('.novel-draft-brief-batch')
    expect(projectWorkspace).toContain('网感素材池')
    expect(projectWorkspace).toContain('meme_bank')
  })

  test('shows first30 retention curve as a story planning workflow', () => {
    const planningWorkspace = source('StoryPlanningWorkspace.tsx')
    const planningModel = source('planningWorkspaceModel.ts')
    const projectWorkspace = readFileSync(join(import.meta.dir, '../NovelProjectWorkspace.tsx'), 'utf8')

    expect(planningWorkspace).toContain('前30章留存曲线')
    expect(planningWorkspace).toContain('novel-first30-retention-card')
    expect(planningWorkspace).toContain('运行前30章诊断')
    expect(planningWorkspace).toContain('生成修复任务')
    expect(planningWorkspace).toContain('开篇三章')
    expect(planningWorkspace).toContain('试读十章')
    expect(planningWorkspace).toContain('付费前蓄势')
    expect(planningModel).toContain('first30Retention')
    expect(planningModel).toContain('run_first30_retention')
    expect(planningModel).toContain('create_first30_repair')
    expect(projectWorkspace).toContain('run_first30_retention')
    expect(projectWorkspace).toContain('create_first30_repair')
  })

  test('shows storyline board as a story planning workflow', () => {
    const planningWorkspace = source('StoryPlanningWorkspace.tsx')
    const planningModel = source('planningWorkspaceModel.ts')
    const projectWorkspace = readFileSync(join(import.meta.dir, '../NovelProjectWorkspace.tsx'), 'utf8')

    expect(planningWorkspace).toContain('剧情线看板')
    expect(planningWorkspace).toContain('novel-storyline-board-card')
    expect(planningWorkspace).toContain('逾期未推')
    expect(planningWorkspace).toContain('回收债务')
    expect(planningWorkspace).toContain('影响留存')
    expect(planningModel).toContain('storylineBoard')
    expect(planningModel).toContain('settingEntities')
    expect(projectWorkspace).toContain('projectSettings')
  })

  test('shows volume climax budget as a story planning workflow', () => {
    const planningWorkspace = source('StoryPlanningWorkspace.tsx')
    const planningModel = source('planningWorkspaceModel.ts')
    const directorModel = source('autoCreationDirectorModel.ts')

    expect(planningWorkspace).toContain('卷级高潮预算')
    expect(planningWorkspace).toContain('novel-volume-beat-budget-card')
    expect(planningWorkspace).toContain('小高潮')
    expect(planningWorkspace).toContain('中高潮')
    expect(planningWorkspace).toContain('卷末爆点')
    expect(planningModel).toContain('volumeBeatBudget')
    expect(directorModel).toContain('volume_beat_budget')
    expect(directorModel).toContain('volumeBeatScore')
  })

  test('shows auto creation director as the longform control workspace', () => {
    const directorWorkspace = source('AutoCreationDirectorWorkspace.tsx')
    const directorCss = source('AutoCreationDirectorWorkspace.css')
    const directorModel = source('autoCreationDirectorModel.ts')
    const projectWorkspace = readFileSync(join(import.meta.dir, '../NovelProjectWorkspace.tsx'), 'utf8')
    const taskCenter = source('TaskCenterDrawer.tsx')

    expect(projectWorkspace).toContain("autoCreation")
    expect(projectWorkspace).toContain('自动创作')
    expect(projectWorkspace).toContain('AutoCreationDirectorWorkspace')
    expect(projectWorkspace).toContain('buildAutoCreationDirectorModel')
    expect(projectWorkspace).toContain('runRecords')
    expect(projectWorkspace).toContain('storyState')
    expect(projectWorkspace).toContain('chapters: sortedChapters')
    expect(projectWorkspace).toContain('handleAutoCreationDirectorAction')
    expect(projectWorkspace).toContain('start_safe_batch_generation')
    expect(projectWorkspace).toContain('createSafeBatchRiskRepairQueue')
    expect(projectWorkspace).toContain('create_safe_batch_risk_repair')
    expect(projectWorkspace).toContain('auto_creation_safe_batch_risk')
    expect(projectWorkspace).toContain('batch_plan_risk_count')
    expect(projectWorkspace).toContain('批次任务书兑现')
    expect(taskCenter).toContain('batch_brief_mismatch')
    expect(taskCenter).toContain('批次计划')
    expect(taskCenter).toContain('按批次修订')
    expect(taskCenter).toContain('batch_plan_review')
    expect(taskCenter).toContain('计划/实际')
    expect(projectWorkspace).toContain('stepGenerateProse({')
    expect(projectWorkspace).toContain('limit: autoCreationDirectorModel.batchGuardrail.safeChapterCount')
    expect(projectWorkspace).toContain('longformCompass: autoCreationDirectorModel.longformCompass')
    expect(projectWorkspace).toContain('nextBatchBrief: autoCreationDirectorModel.batchGuardrail.nextBatchBrief')
    expect(projectWorkspace).toContain('longform_compass: options?.longformCompass')
    expect(projectWorkspace).toContain('next_batch_brief: options?.nextBatchBrief')
    expect(projectWorkspace).toContain('runLongformCreationDiagnosis')
    expect(projectWorkspace).toContain('/longform-creation-diagnosis')
    expect(directorWorkspace).toContain("import './AutoCreationDirectorWorkspace.css'")
    expect(directorWorkspace).toContain('自动创作总控台')
    expect(directorWorkspace).toContain('唯一下一步')
    expect(directorWorkspace).toContain('创作诊断')
    expect(directorWorkspace).toContain('长篇作品罗盘')
    expect(directorWorkspace).toContain('longformCompass')
    expect(directorWorkspace).toContain('auto-director-compass-panel')
    expect(directorWorkspace).toContain('长篇创作契约')
    expect(directorWorkspace).toContain('核心不偏')
    expect(directorWorkspace).toContain('故事强度')
    expect(directorWorkspace).toContain('创新差异')
    expect(directorWorkspace).toContain('读者吸引')
    expect(directorWorkspace).toContain('长篇节奏总控')
    expect(directorWorkspace).toContain('百万字产能')
    expect(directorWorkspace).toContain('longformCapacity')
    expect(directorWorkspace).toContain('auto-director-capacity-panel')
    expect(directorWorkspace).toContain('生产燃料队列')
    expect(directorWorkspace).toContain('fuelQueue')
    expect(directorWorkspace).toContain('auto-director-fuel-queue')
    expect(directorWorkspace).toContain('连续生产护栏')
    expect(directorWorkspace).toContain('安全连写复盘')
    expect(directorWorkspace).toContain('auto-director-batch-panel')
    expect(directorWorkspace).toContain('下一批任务书')
    expect(directorWorkspace).toContain('nextBatchBrief')
    expect(directorWorkspace).toContain('auto-director-batch-brief')
    expect(directorWorkspace).toContain('批次任务书补齐')
    expect(directorWorkspace).toContain('briefRepair')
    expect(directorWorkspace).toContain('auto-director-batch-repair')
    expect(directorWorkspace).toContain('批次安全已恢复')
    expect(directorWorkspace).toContain('briefRecovery')
    expect(directorWorkspace).toContain('auto-director-batch-recovery')
    expect(directorWorkspace).toContain('auto-director-batch-review-panel')
    expect(directorWorkspace).toContain('batchReviewQueue')
    expect(directorWorkspace).toContain('delivered')
    expect(directorWorkspace).toContain('已交付')
    expect(directorWorkspace).toContain('批次风险雷达')
    expect(directorWorkspace).toContain('riskRadar')
    expect(directorWorkspace).toContain('修复任务')
    expect(directorWorkspace).toContain('safeChapterCount')
    expect(directorWorkspace).toContain('auto-director-stage')
    expect(directorWorkspace).toContain('auto-director-contract-item')
    expect(directorWorkspace).toContain('auto-director-rhythm-panel')
    expect(directorWorkspace).toContain('auto-director-batch-guardrail')
    expect(directorWorkspace).toContain('auto-director-model-action')
    expect(directorWorkspace).toContain('onSelectChapter')
    expect(directorCss).toContain('.auto-director-shell')
    expect(directorCss).toContain('.auto-director-stage')
    expect(directorCss).toContain('.auto-director-compass-panel')
    expect(directorCss).toContain('.auto-director-compass-axis')
    expect(directorCss).toContain('.auto-director-contract-item')
    expect(directorCss).toContain('.auto-director-rhythm-panel')
    expect(directorCss).toContain('.auto-director-rhythm-signal')
    expect(directorCss).toContain('.auto-director-capacity-panel')
    expect(directorCss).toContain('.auto-director-capacity-signal')
    expect(directorCss).toContain('.auto-director-fuel-queue')
    expect(directorCss).toContain('.auto-director-fuel-item')
    expect(directorCss).toContain('.auto-director-batch-panel')
    expect(directorCss).toContain('.auto-director-batch-brief')
    expect(directorCss).toContain('.auto-director-batch-repair')
    expect(directorCss).toContain('.auto-director-batch-recovery')
    expect(directorCss).toContain('.auto-director-batch-brief-chapter')
    expect(directorCss).toContain('.auto-director-batch-guardrail')
    expect(directorCss).toContain('.auto-director-batch-review-panel')
    expect(directorCss).toContain('.auto-director-batch-review-item')
    expect(directorCss).toContain('.auto-director-batch-risk-radar')
    expect(directorCss).toContain('.auto-director-batch-review-panel-risk')
    expect(directorCss).toContain('.auto-director-model-action')
    expect(directorModel).toContain('AutoCreationDirectorModel')
    expect(directorModel).toContain('longformCompass')
    expect(directorModel).toContain('buildLongformCompass')
    expect(directorModel).toContain('creationContract')
    expect(directorModel).toContain('longformRhythm')
    expect(directorModel).toContain('longformCapacity')
    expect(directorModel).toContain('fuelQueue')
    expect(directorModel).toContain('longform_capacity')
    expect(directorModel).toContain('longform_rhythm')
    expect(directorModel).toContain('batchGuardrail')
    expect(directorModel).toContain('nextBatchBrief')
    expect(directorModel).toContain('briefRepair')
    expect(directorModel).toContain('buildNextBatchBriefRepair')
    expect(directorModel).toContain('briefRecovery')
    expect(directorModel).toContain('buildNextBatchBriefRecovery')
    expect(directorModel).toContain('batch_guardrail')
    expect(directorModel).toContain('batchReviewQueue')
    expect(directorModel).toContain('BATCH_DELIVERY_QUALITY_THRESHOLD')
    expect(directorModel).toContain('batchChapterDelivered')
    expect(directorModel).toContain('buildBatchRiskRadar')
    expect(directorModel).toContain('repairTasks')
    expect(directorModel).toContain('create_safe_batch_risk_repair')
    expect(directorModel).toContain('安全连写批次存在质量风险')
    expect(directorModel).toContain('auto_creation_safe_batch')
    expect(directorModel).toContain('start_safe_batch_generation')
    expect(directorModel).toContain('MODEL_CALL_ACTIONS')
    expect(taskCenter).toContain('安全连写风险修复任务')
  })
})
