import { describe, expect, test } from 'bun:test'
import { readFileSync } from 'fs'
import { join } from 'path'
import {
  source,
  serverSource,
  sourceCached,
  localSourceCache,
  packageSourceCache,
  packageSource,
  writingServiceSource,
  editorRoutesSource,
  commercialOpsRoutesSource,
  directorModelSource,
  planningWorkspaceSource,
  workspaceCenterSource,
  projectWorkspaceSource,
  writingCockpitPanelSource,
  taskCenterSource,
  storyPlanningWorkspaceSource,
  autoCreationDirectorWorkspaceSource,
  writingCockpitModelSource,
  writingRecommendationModelSource,
} from './workspaceUiShellSource'

describe('commercial writing workspace UI shell b b', () => {

  test('shows longform memory capsule in planning and chapter launch workflow', () => {
    const planningWorkspace = storyPlanningWorkspaceSource()
    const workspaceCenter = workspaceCenterSource()
    const recommendationModel = writingRecommendationModelSource()
    const planningModel = planningWorkspaceSource()
    const writingService = writingServiceSource()

    expect(planningWorkspace).toContain('长篇记忆胶囊')
    expect(planningWorkspace).toContain('novel-longform-memory-capsule-card')
    expect(planningWorkspace).toContain('model.longformMemoryCapsule.characterStates')
    expect(planningWorkspace).toContain('开放悬念')
    expect(planningWorkspace).toContain('待兑现')
    expect(workspaceCenter).toContain('novel-draft-brief-memory-capsule')
    expect(workspaceCenter).toContain('长篇记忆胶囊')
    expect(recommendationModel).toContain('longformMemoryCorePromise')
    expect(planningModel).toContain('longformMemoryCapsule')
    expect(planningModel).toContain('buildLongformMemoryCapsuleModel')
    expect(writingService).toContain('longform_memory_capsule')
    expect(writingService).toContain('【长篇记忆胶囊】')
  })

  test('shows reader trust ledger as a story planning workflow', () => {
    const planningWorkspace = storyPlanningWorkspaceSource()
    const planningModel = planningWorkspaceSource()

    expect(planningWorkspace).toContain('追读信任账本')
    expect(planningWorkspace).toContain('novel-reader-trust-ledger-card')
    expect(planningWorkspace).toContain('model.readerTrustLedger.signals')
    expect(planningWorkspace).toContain('期待兑现')
    expect(planningWorkspace).toContain('爽点回报')
    expect(planningWorkspace).toContain('追读钩子')
    expect(planningWorkspace).toContain('继续悬念')
    expect(planningModel).toContain('readerTrustLedger')
    expect(planningModel).toContain('buildReaderTrustLedgerModel')
    expect(planningModel).toContain('reader_expectation_sync')
    expect(planningModel).toContain('reader_payoff_sync')
    expect(planningModel).toContain('reader_retention_sync')
  })

  test('shows innovation radar as a story planning workflow', () => {
    const planningWorkspace = storyPlanningWorkspaceSource()
    const planningModel = planningWorkspaceSource()

    expect(planningWorkspace).toContain('创新雷达')
    expect(planningWorkspace).toContain('novel-innovation-radar-card')
    expect(planningWorkspace).toContain('model.innovationRadar.signals')
    expect(planningWorkspace).toContain('创新角度')
    expect(planningWorkspace).toContain('执行点')
    expect(planningWorkspace).toContain('差异护栏')
    expect(planningWorkspace).toContain('IP化场面')
    expect(planningModel).toContain('innovationRadar')
    expect(planningModel).toContain('buildInnovationRadarModel')
    expect(planningModel).toContain('innovation_sync')
  })

  test('shows character growth board as a story planning workflow', () => {
    const planningWorkspace = storyPlanningWorkspaceSource()
    const planningModel = planningWorkspaceSource()
    const autoDirectorModel = directorModelSource()

    expect(planningWorkspace).toContain('人物成长看板')
    expect(planningWorkspace).toContain('novel-character-arc-board-card')
    expect(planningWorkspace).toContain('model.characterArcBoard.arcs')
    expect(planningWorkspace).toContain('成长断档')
    expect(planningWorkspace).toContain('关系待推进')
    expect(planningWorkspace).toContain('弧光缺口')
    expect(planningModel).toContain('characterArcBoard')
    expect(planningModel).toContain('buildCharacterArcBoardModel')
    expect(planningModel).toContain('character_arc_sync')
    expect(planningModel).toContain('relationship_arc')
    expect(autoDirectorModel).toContain('characterArcBoard')
    expect(autoDirectorModel).toContain('人物成长')
  })

  test('shows reader trial room as a story planning workflow', () => {
    const planningWorkspace = storyPlanningWorkspaceSource()
    const projectWorkspace = projectWorkspaceSource()
    const planningModel = planningWorkspaceSource()
    const taskCenter = taskCenterSource()
    const service = commercialOpsRoutesSource()

    expect(planningWorkspace).toContain('读者试读室')
    expect(planningWorkspace).toContain('爽点读者')
    expect(planningWorkspace).toContain('平台试读用户')
    expect(planningWorkspace).toContain('弃读点')
    expect(planningWorkspace).toContain('run_reader_trial_review')
    expect(planningWorkspace).toContain('create_reader_trial_repair')
    expect(projectWorkspace).toContain('reader-trial-review')
    expect(projectWorkspace).toContain('reader-trial-review/repair-queue')
    expect(taskCenter).toContain('读者试读修复任务')
    expect(taskCenter).toContain('补试读')
    expect(planningModel).toContain('readerTrialRoom')
    expect(planningModel).toContain('qidian_10k_reader_trial_baseline')
    expect(service).toContain("review_type: 'reader_trial_review'")
    expect(service).toContain("source: 'reader_trial_review'")
  })

  test('shows volume climax budget as a story planning workflow', () => {
    const planningWorkspace = storyPlanningWorkspaceSource()
    const planningModel = planningWorkspaceSource()
    const directorModel = directorModelSource()
    expect(planningWorkspace).toContain('卷级高潮预算')
    expect(planningWorkspace).toContain('novel-volume-beat-budget-card')
    expect(planningWorkspace).toContain('小高潮')
    expect(planningWorkspace).toContain('中高潮')
    expect(planningWorkspace).toContain('卷末爆点')
    expect(planningModel).toContain('volumeBeatBudget')
    expect(directorModel).toContain('volume_beat_budget')
    expect(directorModel).toContain('volumeBeatScore')
  })

  test('shows volume segment acceptance as a story planning workflow', () => {
    const planningWorkspace = storyPlanningWorkspaceSource()
    const planningModel = planningWorkspaceSource()

    expect(planningWorkspace).toContain('卷段验收')
    expect(planningWorkspace).toContain('novel-volume-segment-gate-card')
    expect(planningWorkspace).toContain('model.volumeSegmentGate.signals')
    expect(planningWorkspace).toContain('阶段目标')
    expect(planningWorkspace).toContain('高潮/回报')
    expect(planningWorkspace).toContain('读者信任')
    expect(planningWorkspace).toContain('创新/IP化')
    expect(planningWorkspace).toContain('风险闭环')
    expect(planningModel).toContain('volumeSegmentGate')
    expect(planningModel).toContain('buildVolumeSegmentGateModel')
  })

  test('shows recent fatigue radar as a story planning workflow', () => {
    const planningWorkspace = storyPlanningWorkspaceSource()
    const planningModel = planningWorkspaceSource()

    expect(planningWorkspace).toContain('近10章疲劳雷达')
    expect(planningWorkspace).toContain('novel-recent-fatigue-radar-card')
    expect(planningWorkspace).toContain('model.recentFatigueRadar.signals')
    expect(planningWorkspace).toContain('冲突变化')
    expect(planningWorkspace).toContain('回报变化')
    expect(planningWorkspace).toContain('钩子变化')
    expect(planningWorkspace).toContain('场面新鲜度')
    expect(planningModel).toContain('recentFatigueRadar')
    expect(planningModel).toContain('buildRecentFatigueRadarModel')
    expect(planningModel).toContain('ip_scene_intake')
    expect(planningModel).toContain('IP场面覆盖')
  })

  test('shows story pressure ladder as a story planning workflow', () => {
    const planningWorkspace = storyPlanningWorkspaceSource()
    const planningModel = planningWorkspaceSource()

    expect(planningWorkspace).toContain('故事压力阶梯')
    expect(planningWorkspace).toContain('novel-story-pressure-ladder-card')
    expect(planningWorkspace).toContain('model.storyPressureLadder.signals')
    expect(planningWorkspace).toContain('压力源')
    expect(planningWorkspace).toContain('冲突升级')
    expect(planningWorkspace).toContain('赌注升级')
    expect(planningWorkspace).toContain('反转逼迫')
    expect(planningModel).toContain('storyPressureLadder')
    expect(planningModel).toContain('buildStoryPressureLadderModel')
  })

  test('shows story unit workshop as a story planning workflow', () => {
    const planningWorkspace = storyPlanningWorkspaceSource()
    const planningModel = planningWorkspaceSource()

    expect(planningWorkspace).toContain('剧情单元工坊')
    expect(planningWorkspace).toContain('novel-story-unit-workshop-card')
    expect(planningWorkspace).toContain('model.storyUnitWorkshop.currentUnit.signals')
    expect(planningWorkspace).toContain('入口钩子')
    expect(planningWorkspace).toContain('压力升级')
    expect(planningWorkspace).toContain('小高潮/回报')
    expect(planningWorkspace).toContain('伏笔/剧情线')
    expect(planningWorkspace).toContain('出单元钩子')
    expect(planningModel).toContain('storyUnitWorkshop')
    expect(planningModel).toContain('buildStoryUnitWorkshopModel')
  })

  test('shows volume beat sync status in the delivery strip', () => {
    const workspaceCenter = workspaceCenterSource()
    const workspaceCss = source('WorkspaceCenter.css')
    const writingModel = writingCockpitModelSource()
    const recommendationModel = writingRecommendationModelSource()

    expect(writingModel).toContain('volumeBeatSync')
    expect(writingModel).toContain('buildVolumeBeatSyncSummary')
    expect(recommendationModel).toContain('volumeBeatSync')
    expect(workspaceCenter).toContain('deliverySummary.volumeBeatSync')
    expect(workspaceCenter).toContain('novel-delivery-volume-beat-tag')
    expect(workspaceCss).toContain('.novel-delivery-volume-beat-tag')
  })

  test('shows auto creation director as the longform control workspace', () => {
    const directorWorkspace = autoCreationDirectorWorkspaceSource()
    const directorCss = source('AutoCreationDirectorWorkspace.css')
    const directorModel = directorModelSource()
    const projectWorkspace = projectWorkspaceSource()
    const writingService = writingServiceSource()
    const taskCenter = taskCenterSource()

    expect(projectWorkspace).toContain("autoCreation")
    expect(projectWorkspace).toContain('自动创作')
    expect(projectWorkspace).toContain('AutoCreationDirectorWorkspace')
    expect(projectWorkspace).toContain("lazy(() => import('../AutoCreationDirectorWorkspace')")
    expect(projectWorkspace).toContain('buildAutoCreationDirectorModel')
    expect(projectWorkspace).toContain('runRecords')
    expect(projectWorkspace).toContain('activeRuns: [...activeTasks, ...runRecords]')
    expect(projectWorkspace).toContain('storyState')
    expect(projectWorkspace).toContain('chapters: sortedChapters')
    expect(projectWorkspace).toContain('handleAutoCreationDirectorAction')
    expect(projectWorkspace).toContain('start_safe_batch_generation')
    expect(projectWorkspace).toContain('runRollingPlan(options')
    expect(projectWorkspace).toContain('rolling_plan_intent: options?.intent')
    expect(projectWorkspace).toContain('action.payload?.source === \'batch_brief_repair\'')
    expect(projectWorkspace).toContain('action.payload?.source === \'recent_fatigue_repair\'')
    expect(projectWorkspace).toContain('handlePlanningAction(action.key as PlanningActionKey, { intent: action.payload })')
    expect(projectWorkspace).toContain('handlePlanningAction = (key: PlanningActionKey, options?: { intent?: any })')
    expect(projectWorkspace).toContain("const rollingPlanIntent = options?.intent || (key === 'update_rolling_plan' ? recentFatigueRollingPlanIntent : null)")
    expect(projectWorkspace).toContain('runRollingPlan({ intent: rollingPlanIntent || undefined })')
    expect(projectWorkspace).toContain('onAction={handlePlanningAction}')
    expect(projectWorkspace).toContain('source: \'recent_fatigue_repair\'')
    expect(projectWorkspace).toContain('createSafeBatchRiskRepairQueue')
    expect(projectWorkspace).toContain('create_safe_batch_risk_repair')
    expect(projectWorkspace).toContain('auto_creation_safe_batch_risk')
    expect(projectWorkspace).toContain('createStyleSampleBatchRepairQueue')
    expect(projectWorkspace).toContain('create_style_sample_batch_repair')
    expect(projectWorkspace).toContain('styleSampleEffectiveness')
    expect(projectWorkspace).toContain('/writing-bible/style-sample-effectiveness')
    expect(projectWorkspace).toContain('style_sample_batch_preflight')
    expect(projectWorkspace).toContain('createScriptRoomRepairQueue')
    expect(projectWorkspace).toContain('create_script_room_repair')
    expect(projectWorkspace).toContain('rolling_script_room')
    expect(projectWorkspace).toContain('script_room_layer_gap')
    expect(projectWorkspace).toContain('batch_plan_risk_count')
    expect(projectWorkspace).toContain('volume_segment_risk_count')
    expect(projectWorkspace).toContain('reader_pull_risk_count')
    expect(projectWorkspace).toContain('innovation_risk_count')
    expect(projectWorkspace).toContain('卷级阶段漏结算')
    expect(projectWorkspace).toContain('读者拉力不足')
    expect(projectWorkspace).toContain('创新/IP化缺口')
    expect(projectWorkspace).toContain('批次任务书兑现')
    expect(taskCenter).toContain('batch_brief_mismatch')
    expect(taskCenter).toContain('批次计划')
    expect(taskCenter).toContain('按批次修订')
    expect(taskCenter).toContain('recovery_evidence_mismatch')
    expect(taskCenter).toContain('恢复依据')
    expect(taskCenter).toContain('RecoveryEvidenceReviewPreview')
    expect(taskCenter).toContain('失效依据')
    expect(taskCenter).toContain('对应风险')
    expect(taskCenter).toContain('buildRecoveryEvidenceReviewRowAction(item)')
    expect(taskCenter).toContain('onRecoveryEvidenceReviewRowAction?.(item, rowAction)')
    expect(taskCenter).toContain('最近动作')
    expect(taskCenter).toContain('关闭条件')
    expect(taskCenter).toContain('治理记忆')
    expect(taskCenter).toContain('来源 #')
    expect(taskCenter).toContain('关联批次修复任务')
    expect(taskCenter).toContain('focusedTaskIndex')
    expect(taskCenter).toContain('定位任务')
    expect(taskCenter).toContain('打开章节')
    expect(taskCenter).toContain('style_sample_task_book_rebuild')
    expect(taskCenter).toContain('样章任务书')
    expect(taskCenter).toContain('重审样章')
    expect(projectWorkspace).toContain('executeStyleSampleTaskBookRebuild')
    expect(projectWorkspace).toContain('recheckStyleSampleTaskBookReviewTasks')
    expect(projectWorkspace).toContain('buildStyleSampleTaskBookRecheckPlan')
    expect(projectWorkspace).toContain('样章任务书复检通过')
    expect(projectWorkspace).toContain("issue_type || '') === 'style_sample_task_book_rebuild'")
    expect(projectWorkspace).toContain('已换样章并重审任务书')
    expect(taskCenter).toContain('onRecheckStyleSampleTaskBooks')
    expect(taskCenter).toContain('复检样章任务书')
    expect(taskCenter).toContain('volume_segment_missed')
    expect(taskCenter).toContain('卷级阶段')
    expect(taskCenter).toContain('补阶段结算')
    expect(taskCenter).toContain('reader_pull_missed')
    expect(taskCenter).toContain('读者拉力')
    expect(taskCenter).toContain('补追读')
    expect(taskCenter).toContain('innovation_execution_missed')
    expect(taskCenter).toContain('创新/IP')
    expect(taskCenter).toContain('补创新')
    expect(taskCenter).toContain('batch_plan_review')
    expect(taskCenter).toContain('计划/实际')
    expect(taskCenter).toContain('volume_beat')
    expect(taskCenter).toContain('爆点')
    expect(taskCenter).toContain('按剧本室修复')
    expect(taskCenter).toContain('剧本室')
    expect(projectWorkspace).toContain('stepGenerateProse({')
    expect(projectWorkspace).toContain('const currentChapterLaunchGate')
    expect(projectWorkspace).toContain('longform_compass: autoCreationDirectorModel.longformCompass')
    expect(projectWorkspace).toContain('chapter_launch_gate: currentChapterLaunchGate')
    expect(projectWorkspace).toContain('limit: autoCreationDirectorModel.batchGuardrail.safeChapterCount')
    expect(projectWorkspace).toContain('allowedChapterNos: autoCreationDirectorModel.batchGuardrail.nextBatchBrief.chapters.map(chapter => chapter.chapterNo)')
    expect(projectWorkspace).toContain('allowedChapterNos?: number[]')
    expect(projectWorkspace).toContain('allowedChapterNoSet')
    expect(projectWorkspace).toContain('allowed_chapter_nos')
    expect(projectWorkspace).toContain('longformCompass: autoCreationDirectorModel.longformCompass')
    expect(projectWorkspace).toContain('longformBattleContext: autoCreationDirectorModel.longformBattleDesk')
    expect(projectWorkspace).toContain('chapterLaunchGate: autoCreationDirectorModel.chapterLaunchGate')
    expect(projectWorkspace).toContain('nextBatchBrief: autoCreationDirectorModel.batchGuardrail.nextBatchBrief')
    expect(projectWorkspace).toContain('batchPreflight: autoCreationDirectorModel.batchGuardrail.preflight.inputSnapshot')
    expect(projectWorkspace).toContain('longform_compass: options?.longformCompass')
    expect(projectWorkspace).toContain('longform_battle_context: options?.longformBattleContext')
    expect(projectWorkspace).toContain('chapter_launch_gate: options?.chapterLaunchGate')
    expect(projectWorkspace).toContain('next_batch_brief: options?.nextBatchBrief')
    expect(projectWorkspace).toContain('batch_preflight: options?.batchPreflight')
    expect(projectWorkspace).toContain('longformBattleContext?: any')
    expect(projectWorkspace).toContain('chapterLaunchGate?: any')
    expect(projectWorkspace).toContain('batchPreflight?: any')
    expect(directorModel).toContain('governance_recheck_memory')
    expect(directorModel).toContain('governanceRecheckMemory: args.governanceRecheckMemory')
    expect(projectWorkspace).toContain('runLongformCreationDiagnosis')
    expect(projectWorkspace).toContain('/longform-creation-diagnosis')
    expect(directorWorkspace).toMatch(/import ['"].*AutoCreationDirectorWorkspace\.css['"]/)
    expect(directorWorkspace).toContain('自动创作总控台')
    expect(directorWorkspace).toContain('唯一下一步')
    expect(directorWorkspace).toContain('当前判断')
    expect(directorWorkspace).toContain('auto-director-repair-plan')
    expect(directorWorkspace).toContain('model.repairPlan.primaryAction')
    expect(directorWorkspace).toContain('model.governanceClosureBrief.status')
    expect(directorWorkspace).toContain('治理闭环')
    expect(directorModel).toContain('review_governance_closure')
    expect(directorModel).toContain('治理复查台')
    expect(projectWorkspace).toContain("action.key === 'review_governance_closure'")
    expect(projectWorkspace).toContain('generateLongformRepairAuditSummary(repairRun)')
    expect(projectWorkspace).toContain("action.key === 'auto_repair_blockers'")
    expect(projectWorkspace).toContain('runAutoCreationRepairPlan')
    expect(directorWorkspace).toContain('auto-director-judgement-card')
    expect(directorWorkspace).not.toContain('auto-director-next-card')
    expect(directorWorkspace).toContain('生产许可')
    expect(directorWorkspace).toContain('model.productionLicense')
    expect(directorWorkspace).toContain('auto-director-license-panel')
    expect(directorWorkspace).toContain('auto-director-license-detail')
    expect(directorWorkspace).not.toContain('action={model.productionLicense.nextAction}')
    expect(directorWorkspace).toContain('model.serialCockpit')
    expect(directorWorkspace).toContain('长篇连载驾驶舱')
    expect(directorWorkspace).toContain('今日唯一动作')
    expect(directorWorkspace).toContain('万订五项护栏')
    expect(directorWorkspace).toContain('当前章生产链')
    expect(directorWorkspace).toContain('连写许可')
    expect(directorWorkspace).toContain('待处理风险')
    expect(directorWorkspace).toContain('serialCockpit.command.action')
    expect(directorWorkspace).toContain('serialCockpit.guardrails.map')
    expect(directorWorkspace).toContain('serialCockpit.chapterChain.map')
    expect(directorWorkspace).toContain('serialCockpit.batchLicense')
    expect(directorWorkspace).toContain('serialCockpit.riskQueue')
    expect(directorWorkspace).toContain('auto-director-serial-cockpit')
    expect(directorWorkspace).toContain('auto-director-cockpit-guardrails')
    expect(directorWorkspace).toContain('auto-director-cockpit-chain')
    expect(directorWorkspace).toContain('auto-director-cockpit-risks')
    expect(directorWorkspace).toContain('长篇作战台')
    expect(directorWorkspace).toContain('model.longformBattleDesk')
    expect(directorWorkspace).toContain('auto-director-battle-desk')
    expect(directorWorkspace).toContain('auto-director-battle-lane')
    expect(directorWorkspace).toContain('核心守恒')
    expect(directorWorkspace).toContain('读者拉力')
    expect(directorWorkspace).toContain('剧情线调度')
    expect(directorWorkspace).toContain('卷级爆点')
    expect(directorWorkspace).toContain('创新/IP场面')
    expect(directorWorkspace).toContain('生产燃料')
    expect(directorWorkspace).toContain('auto-director-detail-drawer')
    expect(directorWorkspace).toContain('展开详细依据')
    expect(directorWorkspace).toContain('连载日更作战')
    expect(directorWorkspace).toContain('model.dailyBattlePlan.steps')
    expect(directorWorkspace).toContain('serialCockpit.command.governanceMemory.visible')
    expect(directorWorkspace).toContain('治理复查记忆')
    expect(directorWorkspace).toContain('auto-director-command-memory')
    expect(directorWorkspace).toContain('step.gateChecks')
    expect(directorWorkspace).toContain('auto-director-daily-gates')
    expect(directorWorkspace).toContain('完成口径')
    expect(directorWorkspace).toContain('auto-director-daily-panel')
    expect(directorWorkspace).toContain('auto-director-daily-step')
    expect(directorCss).toContain('.auto-director-daily-gates')
    expect(directorWorkspace).toContain('百章滚动剧本室')
    expect(directorWorkspace).toContain('model.rollingScriptRoom.layers')
    expect(directorWorkspace).toContain('auto-director-script-room-panel')
    expect(directorWorkspace).toContain('本章开写门禁')
    expect(directorWorkspace).toContain('model.chapterLaunchGate.signals')
    expect(directorWorkspace).toContain('auto-director-launch-gate-panel')
    expect(directorWorkspace).toContain('model.rollingScriptRoom.repairTasks.length')
    expect(directorWorkspace).toContain('生成剧本室修复任务')
    expect(directorWorkspace).toContain('当前章')
    expect(directorWorkspace).toContain('未来10章')
    expect(directorWorkspace).toContain('未来100章')
    expect(directorWorkspace).toContain('当前卷')
    expect(directorWorkspace).toContain('全书罗盘')
    expect(directorCss).toContain('auto-director-script-room-panel')
    expect(directorCss).toContain('.auto-director-launch-gate-panel')
    expect(directorCss).toContain('.auto-director-launch-gate-signal')
    expect(directorCss).toContain('.auto-director-license-panel')
    expect(directorCss).toContain('.auto-director-license-mode')
    expect(directorCss).toContain('.auto-director-serial-cockpit')
    expect(directorCss).toContain('.auto-director-cockpit-guardrails')
    expect(directorCss).toContain('.auto-director-cockpit-chain')
    expect(directorCss).toContain('.auto-director-cockpit-risks')
    expect(directorCss).toContain('.auto-director-battle-desk')
    expect(directorCss).toContain('.auto-director-battle-lanes')
    expect(directorCss).toContain('.auto-director-battle-lane')
    expect(directorCss).toContain('.auto-director-detail-drawer')
    expect(directorCss).toContain('.auto-director-detail-summary')
    expect(directorModel).toContain('rollingScriptRoom')
    expect(directorModel).toContain('AutoCreationProductionLicense')
    expect(directorModel).toContain('todayCommandDeck')
    expect(directorModel).toContain('longformBattleDesk')
    expect(directorModel).toContain('qualityGates')
    expect(directorModel).toContain('核心不偏')
    expect(directorModel).toContain('故事推进')
    expect(directorModel).toContain('读者拉力')
    expect(directorModel).toContain('创新差异')
    expect(directorModel).toContain('连载安全')
    expect(directorModel).toContain('buildTodayCommandDeck')
    expect(directorModel).toContain('buildProductionLicense')
    expect(directorModel).toContain('productionLicense')
    expect(directorModel).toContain('chapterLaunchGate')
    expect(directorModel).toContain('buildChapterLaunchGate')
    expect(directorModel).toContain('mainline_service')
    expect(directorModel).toContain('rolling_script_room')
    expect(directorModel).toContain('repairTasks')
    expect(directorModel).toContain('create_script_room_repair')
    expect(directorWorkspace).toContain('清交稿风险')
    expect(directorWorkspace).toContain('补长线材料')
    expect(directorWorkspace).toContain('写/修当前章')
    expect(directorWorkspace).toContain('放行下一批')
    expect(directorWorkspace).toContain('创作诊断')
    expect(directorWorkspace).toContain('长篇作品罗盘')
    expect(directorWorkspace).toContain('longformCompass')
    expect(directorWorkspace).toContain('auto-director-compass-panel')
    expect(directorWorkspace).toContain('长篇创作契约')
    expect(directorWorkspace).toContain('核心不偏')
    expect(directorWorkspace).toContain('故事强度')
    expect(directorWorkspace).toContain('创新差异')
    expect(directorWorkspace).toContain('读者吸引')
    expect(directorWorkspace).toContain('长篇节奏总控')
    expect(directorWorkspace).toContain('百万字产能')
    expect(directorWorkspace).toContain('longformCapacity')
    expect(directorWorkspace).toContain('auto-director-capacity-panel')
    expect(directorWorkspace).toContain('生产燃料队列')
    expect(directorWorkspace).toContain('fuelQueue')
    expect(directorWorkspace).toContain('auto-director-fuel-queue')
    expect(directorWorkspace).toContain('连续生产护栏')
    expect(directorWorkspace).toContain('本批放行范围')
    expect(directorWorkspace).toContain('安全连写预执行确认')
    expect(directorWorkspace).toContain('model.batchGuardrail.preflight')
    expect(directorWorkspace).toContain('model.batchGuardrail.recoveryEvidenceTrend')
    expect(directorWorkspace).toContain('longformMemoryAnchor')
    expect(directorWorkspace).toContain('governanceRecheckMemory')
    expect(directorWorkspace).toContain('正史锚点')
    expect(directorWorkspace).toContain('恢复依据画像趋势')
    expect(directorWorkspace).toContain('深层修复方向')
    expect(directorWorkspace).toContain('strengthenedAcceptanceTrend')
    expect(directorWorkspace).toContain('强化恢复验收趋势')
    expect(directorWorkspace).toContain('safeBatchExpansionFeedback')
    expect(directorWorkspace).toContain('扩批热区')
    expect(directorWorkspace).toContain('稳定连过')
    expect(directorWorkspace).toContain('safeBatchRecoveryRestoreStabilityEvidence')
    expect(directorWorkspace).toContain('safeBatchRecoveryRestoreStabilityLane')
    expect(directorWorkspace).toContain('长期扩批稳定证据')
    expect(directorWorkspace).toContain('批次复盘筛选')
    expect(directorWorkspace).toContain('5章观察批')
    expect(directorWorkspace).toContain('默认5章档位')
    expect(directorWorkspace).toContain('复发')
    expect(directorWorkspace).toContain('safeBatchExpansionStructureTrend')
    expect(directorWorkspace).toContain('验证通过率')
    expect(directorWorkspace).toContain('复发间隔')
    expect(directorWorkspace).toContain('safeBatchExpansionStructureEffectiveness')
    expect(directorWorkspace).toContain('结构修复有效性')
    expect(directorWorkspace).toContain('修复有效')
    expect(directorWorkspace).toContain('auto-director-batch-expansion-feedback')
    expect(directorWorkspace).toContain('auto-director-batch-preflight')
    expect(directorWorkspace).toContain('auto-director-batch-recovery-trend')
    expect(directorWorkspace).toContain('auto-director-batch-memory-anchor')
    expect(directorWorkspace).toContain('model.batchGuardrail.releaseWindow')
    expect(directorWorkspace).toContain('auto-director-batch-release-window')
    expect(directorWorkspace).toContain('auto-director-batch-release-chapter')
    expect(directorWorkspace).toContain('安全连写复盘')
    expect(directorWorkspace).toContain('auto-director-batch-panel')
    expect(directorWorkspace).toContain('近10章疲劳')
    expect(directorWorkspace).toContain('下一批任务书')
    expect(directorWorkspace).toContain('nextBatchBrief')
    expect(directorWorkspace).toContain('auto-director-batch-brief')
    expect(directorWorkspace).toContain('批次开工清单')
    expect(directorWorkspace).toContain('nextBatchBrief.startChecklist')
    expect(directorWorkspace).toContain('auto-director-batch-start-checklist')
    expect(directorWorkspace).toContain('批次任务书补齐')
    expect(directorWorkspace).toContain('briefRepair')
    expect(directorWorkspace).toContain('auto-director-batch-repair')
    expect(directorWorkspace).toContain('批次安全已恢复')
    expect(directorWorkspace).toContain('briefRecovery')
    expect(directorWorkspace).toContain('auto-director-batch-recovery')
    expect(directorWorkspace).toContain('auto-director-batch-review-panel')
    expect(directorWorkspace).toContain('batchReviewQueue')
    expect(directorWorkspace).toContain('delivered')
    expect(directorWorkspace).toContain('已交付')
    expect(directorWorkspace).toContain('批次完成度')
    expect(directorWorkspace).toContain('批次交接')
    expect(directorWorkspace).toContain('model.batchReviewQueue.handoff')
    expect(directorWorkspace).toContain('auto-director-batch-handoff')
    expect(directorWorkspace).toContain('model.batchReviewQueue.completionDashboard')
    expect(directorWorkspace).toContain('auto-director-batch-completion-dashboard')
    expect(directorWorkspace).toContain('批次风险雷达')
    expect(directorWorkspace).toContain('riskRadar')
    expect(directorWorkspace).toContain('修复任务')
    expect(directorWorkspace).toContain('safeChapterCount')
    expect(directorWorkspace).toContain('auto-director-stage')
    expect(directorWorkspace).toContain('auto-director-contract-item')
    expect(directorWorkspace).toContain('auto-director-rhythm-panel')
    expect(directorWorkspace).toContain('auto-director-batch-guardrail')
    expect(directorWorkspace).toContain('auto-director-model-action')
    expect(directorWorkspace).toContain('onSelectChapter')
    expect(directorCss).toContain('.auto-director-shell')
    expect(directorCss).toContain('.auto-director-judgement-card')
    expect(directorCss).toContain('.auto-director-repair-plan')
    expect(directorCss).not.toContain('.auto-director-next-card')
    expect(directorCss).toContain('.auto-director-daily-panel')
    expect(directorCss).toContain('.auto-director-daily-step')
    expect(directorCss).toContain('.auto-director-daily-step-active')
    expect(directorCss).toContain('.auto-director-daily-step-blocked')
    expect(directorCss).toContain('.auto-director-stage')
    expect(directorCss).toContain('.auto-director-compass-panel')
    expect(directorCss).toContain('.auto-director-compass-axis')
    expect(directorCss).toContain('.auto-director-contract-item')
    expect(directorCss).toContain('.auto-director-rhythm-panel')
    expect(directorCss).toContain('.auto-director-rhythm-signal')
    expect(directorCss).toContain('.auto-director-capacity-panel')
    expect(directorCss).toContain('.auto-director-capacity-signal')
    expect(directorCss).toContain('.auto-director-fuel-queue')
    expect(directorCss).toContain('.auto-director-fuel-item')
    expect(directorCss).toContain('.auto-director-batch-panel')
    expect(directorCss).toContain('.auto-director-batch-release-window')
    expect(directorCss).toContain('.auto-director-batch-preflight')
    expect(directorCss).toContain('.auto-director-batch-recovery-trend')
    expect(directorCss).toContain('.auto-director-batch-memory-anchor')
    expect(directorCss).toContain('.auto-director-batch-release-chapter')
    expect(directorCss).toContain('.auto-director-batch-release-chapter-blocked')
    expect(directorCss).toContain('.auto-director-batch-brief')
    expect(directorCss).toContain('.auto-director-batch-start-checklist')
    expect(directorCss).toContain('.auto-director-batch-repair')
    expect(directorCss).toContain('.auto-director-batch-recovery')
    expect(directorCss).toContain('.auto-director-batch-brief-chapter')
    expect(directorCss).toContain('.auto-director-batch-guardrail')
    expect(directorCss).toContain('.auto-director-batch-review-panel')
    expect(directorCss).toContain('.auto-director-batch-completion-dashboard')
    expect(directorCss).toContain('.auto-director-batch-handoff')
    expect(directorCss).toContain('.auto-director-batch-completion-metric')
    expect(directorCss).toContain('.auto-director-batch-review-item')
    expect(directorCss).toContain('.auto-director-batch-risk-radar')
    expect(directorCss).toContain('.auto-director-batch-review-panel-risk')
    expect(directorCss).toContain('.auto-director-model-action')
    expect(directorModel).toContain('AutoCreationDirectorModel')
    expect(directorModel).toContain('dailyBattlePlan')
    expect(directorModel).toContain('buildDailyBattlePlan')
    expect(directorModel).toContain('clear_risks')
    expect(directorModel).toContain('fuel_materials')
    expect(directorModel).toContain('chapter_work')
    expect(directorModel).toContain('batch_release')
    expect(directorModel).toContain('longformCompass')
    expect(directorModel).toContain('buildLongformCompass')
    expect(directorModel).toContain('creationContract')
    expect(directorModel).toContain('longformRhythm')
    expect(directorModel).toContain('longformCapacity')
    expect(directorModel).toContain('fuelQueue')
    expect(directorModel).toContain('longform_capacity')
    expect(directorModel).toContain('longform_rhythm')
    expect(directorModel).toContain('batchGuardrail')
    expect(directorModel).toContain('releaseWindow')
    expect(directorModel).toContain('preflight')
    expect(directorModel).toContain('buildBatchPreflight')
    expect(directorModel).toContain('buildLongformMemoryAnchor')
    expect(directorModel).toContain('longform_memory_anchor')
    expect(directorModel).toContain('auto_creation_safe_batch_preflight')
    expect(writingService).toContain('【长篇正史锚点】')
    expect(writingService).toContain('batch_preflight.longform_memory_anchor')
    expect(directorModel).toContain('allowedChapters')
    expect(directorModel).toContain('blockedChapters')
    expect(directorModel).toContain('recentFatigueRadar')
    expect(directorModel).toContain('近10章疲劳')
    expect(directorModel).toContain('storyPressureLadder')
    expect(directorModel).toContain('故事压力阶梯')
    expect(directorModel).toContain('story_pressure_repair')
    expect(directorModel).toContain('storyUnitWorkshop')
    expect(directorModel).toContain('剧情单元')
    expect(directorModel).toContain('story_unit_repair')
    expect(directorModel).toContain('story_unit_sync')
    expect(directorModel).toContain('story_unit_sync_risk')
    expect(directorModel).toContain('nextBatchBrief')
    expect(directorModel).toContain('briefRepair')
    expect(directorModel).toContain('buildNextBatchBriefRepair')
    expect(directorModel).toContain('batch_brief_repair')
    expect(directorModel).toContain('missing_items')
    expect(directorModel).toContain('briefRecovery')
    expect(directorModel).toContain('buildNextBatchBriefRecovery')
    expect(directorModel).toContain('batch_guardrail')
    expect(directorModel).toContain('batchReviewQueue')
    expect(directorModel).toContain('completionDashboard')
    expect(directorModel).toContain('handoff')
    expect(directorModel).toContain('buildBatchHandoff')
    expect(directorModel).toContain('deliver_chapters')
    expect(directorModel).toContain('continue_batch')
    expect(directorModel).toContain('prepare_next')
    expect(directorModel).toContain('reconcileBatchHandoffWithGuardrail')
    expect(directorModel).toContain('buildBatchCompletionDashboard')
    expect(directorModel).toContain('BATCH_DELIVERY_QUALITY_THRESHOLD')
    expect(directorModel).toContain('batchChapterDelivered')
    expect(directorModel).toContain('buildBatchRiskRadar')
    expect(directorModel).toContain('chapter_handoff')
    expect(directorModel).toContain('章节交接')
    expect(directorModel).toContain('chapterHandoffDetail')
    expect(directorModel).toContain('repairTasks')
    expect(directorModel).toContain('create_safe_batch_risk_repair')
    expect(directorModel).toContain('create_style_sample_batch_repair')
    expect(directorModel).toContain('风格样章预检')
    expect(directorModel).toContain('style_sample_batch_preflight')
    expect(directorModel).toContain('style_sample_task_book_rebuild')
    expect(directorModel).toContain('安全连写批次存在质量风险')
    expect(directorModel).toContain('auto_creation_safe_batch')
    expect(directorModel).toContain('start_safe_batch_generation')
    expect(directorModel).toContain('create_recovery_evidence_governance_queue')
    expect(directorModel).toContain('recoveryEvidenceGovernanceQueue')
    expect(directorModel).toContain('recoveryEvidenceReleaseSummary')
    expect(directorModel).toContain('recovery_evidence_release_summary')
    expect(directorModel).toContain('releaseSummaryEvidence')
    expect(directorModel).toContain('安全连写放行摘要')
    expect(directorModel).toContain('recovery_evidence_regovernance_queue')
    expect(directorModel).toContain('release_summary_regovernance')
    expect(directorModel).toContain('buildRecoveryEvidenceSourceRiskProfile')
    expect(directorModel).toContain('buildRecoveryEvidenceTrend')
    expect(directorModel).toContain('buildRecoveryEvidenceDeepRepairQueue')
    expect(directorModel).toContain('buildRecoveryEvidenceDeepRepairEffects')
    expect(directorModel).toContain('recovery_evidence_source_risk_profile')
    expect(directorModel).toContain('recovery_evidence_source_deep_repair')
    expect(directorModel).toContain('recoveryEvidenceTrend')
    expect(directorModel).toContain('deepRepairEffect')
    expect(directorModel).toContain('恢复依据画像')
    expect(directorModel).toContain('生成深层修复队列')
    expect(directorModel).toContain('深修后仍失效')
    expect(directorWorkspace).toContain('deepRepairEffect')
    expect(directorWorkspace).toContain('深修结果')
    expect(directorModel).toContain('deep_repair_single_brief')
    expect(directorModel).toContain('deep_repair_batch_brief')
    expect(directorModel).toContain('recheck_mode')
    expect(directorModel).toContain('closure_status')
    expect(directorModel).toContain('MODEL_CALL_ACTIONS')
    expect(projectWorkspace).toContain('createRecoveryEvidenceGovernanceQueue')
    expect(projectWorkspace).toContain('onCreateRecoveryEvidenceGovernanceQueue')
    expect(projectWorkspace).toContain('已生成放行摘要再治理队列')
    expect(projectWorkspace).toContain('executeRecoveryEvidenceGovernanceQueueTask')
    expect(projectWorkspace).toContain("actionKey === 'deep_repair_single_brief'")
    expect(projectWorkspace).toContain("actionKey === 'deep_repair_batch_brief'")
    expect(projectWorkspace).toContain("String(task?.issue_type || '') === 'recovery_evidence_governance_queue'")
    expect(projectWorkspace).toContain('skipRevisionConfirm: true')
    expect(projectWorkspace).toContain('governance_recheck_sync')
    expect(projectWorkspace).toContain('generateLongformRepairAuditSummary(run, { keepTaskCenterOpen: true })')
    expect(projectWorkspace).toContain('recovery_evidence_governance_queue')
    expect(taskCenter).toContain('安全连写风险修复任务')
    expect(taskCenter).toContain('恢复依据治理队列')
    expect(taskCenter).toContain('buildRecoveryEvidenceRegovernanceSummary')
    expect(taskCenter).toContain('buildRecoveryEvidenceSourceRiskProfileSnapshot')
    expect(taskCenter).toContain('恢复依据画像趋势')
    expect(taskCenter).toContain('深层修复方向')
    expect(taskCenter).toContain('deepRepairEffect')
    expect(taskCenter).toContain('深修结果')
    expect(taskCenter).toContain('深修后暂无再失效')
    expect(taskCenter).toContain('深修单章任务书')
    expect(taskCenter).toContain('深修批次任务书')
    expect(taskCenter).toContain('生成再治理队列')
    expect(taskCenter).toContain('放行摘要再治理')
    expect(taskCenter).toContain('已处理并复盘')
    expect(taskCenter).toContain('恢复放行依据')
    expect(taskCenter).toContain('recovery_evidence')
    expect(taskCenter).toContain('batch_preflight')
  })

  test('shows the creative assistant panel shell', () => {
    const projectWorkspace = projectWorkspaceSource()
    const panel = source('CreativeAssistantPanel.tsx')
    const model = source('creativeAssistantModel.ts')
    const css = source('CreativeAssistantPanel.css')

    expect(projectWorkspace).toContain('CreativeAssistantPanel')
    expect(projectWorkspace).toContain('创作参谋')
    expect(projectWorkspace).toContain('/creative-assist')
    expect(projectWorkspace).toContain('creativeAssistantOpen')
    expect(projectWorkspace).toContain('runCreativeAssistant')
    expect(projectWorkspace).toContain('setCreativeAssistantOpen(true)')
    expect(projectWorkspace).toContain('apiClient.post(`/novel/projects/${projectId}/creative-assist`')
    expect(projectWorkspace).toContain('runRecords={runRecords}')
    expect(projectWorkspace).toContain('onCopyCard')
    expect(panel).toContain('runRecords')
    expect(model).toContain('治理闭环待处理')
    expect(model).toContain('治理复查已记录')
    expect(model).toContain('沿用治理复查结果')
    expect(model).toContain('先处理长线治理闭环')
    expect(panel).toContain('正文评析')
    expect(panel).toContain('下一章')
    expect(panel).toContain('后续大纲')
    expect(panel).toContain('伏笔')
    expect(panel).toContain('人物剧情')
    expect(panel).toContain('能力物品')
    expect(panel).toContain('联网资料')
    expect(panel).toContain('creative-assistant-card')
    expect(css).toContain('.creative-assistant-panel')
    expect(css).toContain('.creative-assistant-card')
  })

  test('dual-mode shell replaces focus mode with immersive/workbench classes and always-on task center', () => {
    const projectWorkspace = projectWorkspaceSource()
    const projectWorkspaceCss = source('../NovelProjectWorkspace.css')
    const shellModel = source('workspaceShellModel.ts')

    expect(shellModel).toContain("export type WorkspaceShellMode = 'immersive' | 'workbench'")
    expect(shellModel).toContain('novel.workspace.shellMode')
    expect(shellModel).toContain('isImmersiveShell')

    expect(projectWorkspace).toContain('writingShellMode')
    expect(projectWorkspace).toContain('setShellMode')
    expect(projectWorkspace).toContain('rootShellClassName')
    expect(projectWorkspace).toContain('展开工作台')
    expect(projectWorkspace).toContain('沉浸写作')
    expect(projectWorkspace).toContain('novel-workspace-topbar-left')
    expect(projectWorkspace).toContain('novel-workspace-topbar-center')
    expect(projectWorkspace).toContain('novel-workspace-topbar-right')
    expect(projectWorkspace).toContain('novel-workspace-topbar-more')
    expect(projectWorkspace).toContain('novel-workspace-task-entry')

    expect(projectWorkspace).not.toContain('focusWritingMode')
    expect(projectWorkspace).not.toContain('isWritingFocusMode')
    expect(projectWorkspace).not.toContain('专注写作')
    expect(projectWorkspace).not.toContain('退出专注')
    expect(projectWorkspace).not.toContain('novel-workspace-focus-mode')

    expect(projectWorkspaceCss).toContain('.novel-workspace-shell-immersive')
    expect(projectWorkspaceCss).toContain('.novel-workspace-shell-workbench')
    expect(projectWorkspaceCss).toContain('.novel-workspace-topbar-left')
    expect(projectWorkspaceCss).not.toContain('.novel-workspace-focus-mode .novel-workspace-task-entry')
    expect(projectWorkspaceCss).not.toContain('.novel-workspace-focus-mode .novel-workspace-directory-shell')
  })

  test('immersive writing keeps global cockpit hidden and does not zero-hide directory by focus class', () => {
    const projectWorkspace = projectWorkspaceSource()
    const projectWorkspaceCss = source('../NovelProjectWorkspace.css')

    expect(projectWorkspace).toContain('showGlobalWritingGuidance')
    expect(projectWorkspace).toContain("workspaceArea !== 'chapterWriting'")
    expect(projectWorkspace).toContain('{showGlobalWritingGuidance && (')
    expect(projectWorkspace).toContain('{showGlobalWritingGuidance && renderSerialPipeline()}')
    expect(projectWorkspaceCss).toContain('.novel-workspace-directory-shell.is-collapsed')
    expect(projectWorkspaceCss).toContain('flex: 0 0 var(--novel-shell-directory-collapsed)')
  })

  test('immersive writing aux uses toolbar popover instead of in-flow aux rail', () => {
    const component = workspaceCenterSource()
    const projectWorkspace = projectWorkspaceSource()
    const focusModel = source('writingAuxFocusModel.ts')

    expect(focusModel).toContain('pickWritingAuxFocusTags')
    expect(component).toContain('isImmersiveShell')
    expect(component).toContain('novel-writing-immersive-aux')
    expect(component).toContain('novel-writing-immersive-aux-trigger')
    expect(component).toContain('immersiveAuxOpen')
    expect(component).toContain('pickWritingAuxFocusTags')
    expect(component).toContain('辅助')
    expect(component).toContain('!isImmersiveShell')
    expect(component).toContain('novel-writing-aux-rail')
    expect(projectWorkspace).toContain('isImmersiveShell={isImmersiveShell}')
  })

  test('writing cockpit collapsed strip exposes primary action and L2 details default closed', () => {
    const component = writingCockpitPanelSource()
    const css = source('WritingCockpitPanel.css')

    expect(component).toContain('writing-cockpit-summary-strip')
    expect(component).toContain('writing-cockpit-summary-primary')
    expect(component).toContain('展开详情')
    expect(component).toContain('writing-cockpit-details')
    expect(component).toContain('写作详情')
    expect(component).toContain('cockpitDetailsOpen')
    expect(component).toMatch(/const \[cockpitDetailsOpen,\s*setCockpitDetailsOpen\] = useState\(false\)/)
    expect(component).toContain('writing-cockpit-role-strip')
    expect(component).not.toContain('onClick={() => onAction(role.actionKey)}')
    expect(css).toContain('.writing-cockpit-summary-strip')
    expect(css).toContain('.writing-cockpit-details')
  })
})
