import { describe, expect, test } from 'bun:test'
import { readFileSync } from 'fs'
import { join } from 'path'
import {
  source,
  serverSource,
  sourceCached,
  localSourceCache,
  packageSourceCache,
  packageSource,
  writingServiceSource,
  editorRoutesSource,
  commercialOpsRoutesSource,
  directorModelSource,
  planningWorkspaceSource,
  workspaceCenterSource,
  projectWorkspaceSource,
  writingCockpitPanelSource,
  taskCenterSource,
  storyPlanningWorkspaceSource,
  autoCreationDirectorWorkspaceSource,
  writingCockpitModelSource,
  writingRecommendationModelSource,
} from './workspaceUiShellSource'

describe('commercial writing workspace UI shell a', () => {
  test('lets the inner chapter directory rail collapse without hiding task center', () => {
    const projectWorkspace = projectWorkspaceSource()
    const projectWorkspaceCss = source('../NovelProjectWorkspace.css')
    const directorySidebar = source('ChapterDirectorySidebar.tsx')

    expect(projectWorkspace).toContain('directoryCollapsed')
    expect(projectWorkspace).toContain('setDirectoryCollapsed')
    expect(projectWorkspace).toContain('handleDirectoryCollapsedChange')
    expect(projectWorkspace).toContain("novel-workspace-directory-shell is-collapsed")
    expect(projectWorkspace).toContain('collapsed={directoryCollapsed}')
    expect(projectWorkspace).toContain('onCollapsedChange={handleDirectoryCollapsedChange}')
    expect(projectWorkspace).toContain('novel-workspace-task-entry')
    expect(directorySidebar).toContain('collapsed = false')
    expect(directorySidebar).toContain('onCollapsedChange')
    expect(directorySidebar).toContain('收起目录')
    expect(directorySidebar).toContain('展开目录')
    expect(directorySidebar).toContain('chapter-directory-sidebar is-collapsed')
    expect(projectWorkspaceCss).toContain('.novel-workspace-directory-shell.is-collapsed')
    expect(projectWorkspaceCss).toContain('flex: 0 0 var(--novel-shell-directory-collapsed)')
    expect(projectWorkspaceCss).toContain('.chapter-directory-sidebar-collapsed-rail')
  })

  test('uses a single primary action entry in the central writing toolbar', () => {
    const component = workspaceCenterSource()
    const css = source('WorkspaceCenter.css')

    expect(component).toContain('runRecommendedToolbarAction')
    expect(component).toContain('recommendedToolbarLoading')
    expect(component).toContain('novel-editor-primary-entry')
    expect(component).toContain('novel-editor-primary-action-main')
    expect(component).toContain('novel-editor-secondary-actions')
    expect(component).toContain('novel-editor-command-pill')
    expect(component).toContain('novel-word-preset')
    expect(component).toContain('novel-editor-toolbar-meta')
    expect(component).not.toContain('novel-editor-action-group-draft')
    expect(component).not.toContain('生成正文</Text>')
    expect(component).not.toContain('onStartChapterPipeline}>流水线')
    expect(component).not.toContain('onRepairAndGenerateCurrentChapter}>\n            补齐并生成')
    expect(component).not.toContain('onGenerateCurrentChapterProse}>\n          生成')
    expect(component).not.toContain('NOVEL_WRITING_DESK_COLLAPSED_KEY')
    expect(component).not.toContain('setWritingDeskCollapsed')
    expect(component).not.toContain('novel-editor-desk-toggle')
    expect(component).not.toContain('novel-editor-primary-reason')
    expect(component).not.toContain('novel-editor-toolbar-collapsed')
    expect(component).not.toContain('novel-editor-stagebar')
    expect(component).not.toContain('novel-editor-action-flow')
    expect(component).not.toContain('novel-editor-collapsed-summary')
    expect(component).not.toContain('novel-writing-aux-action')
    expect(component).not.toContain('novel-ai-responsibility-strip')
    expect(css).toContain('.novel-editor-command-pill')
    expect(css).toContain('.novel-editor-primary-entry')
    expect(css).toContain('.novel-editor-primary-action-main')
    expect(css).toContain('.novel-editor-secondary-actions')
    expect(css).toContain('.novel-editor-toolbar-meta')
    expect(css).toContain('grid-template-columns')
    expect(css).not.toContain('.novel-editor-toolbar-collapsed')
    expect(css).not.toContain('.novel-editor-desk-toggle')
    expect(css).not.toContain('.novel-editor-primary-reason')
    expect(css).not.toContain('.novel-editor-stagebar')
    expect(css).not.toContain('.novel-editor-action-flow')
    expect(css).not.toContain('.novel-editor-collapsed-actions')
    expect(css).toContain('flex-shrink: 0')
  })

  test('keeps pipeline and model team as status displays instead of duplicate writing actions', () => {
    const cockpit = writingCockpitPanelSource()
    const projectWorkspace = projectWorkspaceSource()
    const projectWorkspaceCss = source('../NovelProjectWorkspace.css')

    expect(cockpit).toContain('writing-cockpit-role-strip')
    expect(cockpit).not.toContain('onClick={() => onAction(role.actionKey)}')
    expect(cockpit).not.toContain('type={role.active ? \'primary\' : \'default\'}')
    expect(projectWorkspace).toContain('下一步：{serialPipelineModel.primaryAction.label || \'查看下一步\'}')
    expect(projectWorkspace).not.toContain('handleSerialPipelineAction(serialPipelineModel.primaryAction.key)')
    expect(projectWorkspace).not.toContain('novel-serial-pipeline-guide-action')
    expect(projectWorkspace).not.toContain('onClick={() => handleSerialPipelineAction(stage.action.key)}')
    expect(projectWorkspaceCss).not.toContain('.novel-serial-pipeline-guide-action')
    expect(projectWorkspaceCss).not.toContain('.novel-serial-pipeline-agent:hover')
  })

  test('keeps chapter writing to one guidance layer by hiding global cockpit and pipeline there', () => {
    const projectWorkspace = projectWorkspaceSource()

    expect(projectWorkspace).toContain('showGlobalWritingGuidance')
    expect(projectWorkspace).toContain("workspaceArea !== 'chapterWriting'")
    expect(projectWorkspace).toContain('{showGlobalWritingGuidance && (')
    expect(projectWorkspace).toContain('{showGlobalWritingGuidance && renderSerialPipeline()}')
  })

  test('shows a compact writing queue in the chapter workspace', () => {
    const component = workspaceCenterSource()
    const css = source('WorkspaceCenter.css')
    const projectWorkspace = projectWorkspaceSource()
    const model = writingCockpitModelSource()

    expect(model).toContain('writingQueue')
    expect(model).toContain('sourceLabel: chapterPlanSourceLabel')
    expect(component).toContain('writingQueue')
    expect(component).toContain('写作队列')
    expect(component).toContain('novel-writing-queue-strip')
    expect(component).toContain('novel-writing-queue-item-')
    expect(component).toContain('onSelectWritingQueueChapter')
    expect(component).toContain('role="button"')
    expect(component).toContain('tabIndex={0}')
    expect(component).toContain("event.key === 'Enter'")
    expect(component).toContain('novel-writing-queue-action')
    expect(component).toContain('item.actionLabel')
    expect(component).toContain('item.actionHint')
    expect(component).toContain('novel-writing-queue-focus')
    expect(component).toContain('本章计划缺口')
    expect(component).toContain('补齐本章计划')
    expect(component).toContain('本章开写就绪')
    expect(component).toContain('处理本章开写')
    expect(component).toContain('runDraftBriefAction')
    expect(component).toContain('novel-draft-brief-action')
    expect(component).toContain('{draftBriefSummary.actionLabel}')
    expect(component).toContain('onClick={runDraftBriefAction}')
    expect(component).toContain('本章交稿中')
    expect(component).toContain('novel-delivery-progress-panel')
    expect(component).toContain('交稿进度')
    expect(component).toContain('deliveryNeedsStorySync')
    expect(component).toContain('storyStateSyncAction')
    expect(component).toContain('runQueueDeliveryAction')
    expect(component).toContain('!(queueFocus.tone === \'delivery\' && deliverySummary.visible)')
    expect(css).toContain('.novel-delivery-progress-steps')
    expect(component).toContain('onRepairWritingQueuePlan')
    expect(component).toContain('补齐队列计划')
    expect(component).toContain('onRepairWritingQueuePlanBatch')
    expect(component).toContain('滚动规划')
    expect(css).toContain('.novel-writing-queue-strip')
    expect(css).toContain('.novel-writing-queue-item.is-active')
    expect(css).toContain('.novel-writing-queue-action')
    expect(css).toContain('.novel-writing-queue-focus')
    expect(css).toContain('cursor: pointer')
    expect(css).toContain('.novel-writing-queue-item-ready_to_draft')
    expect(css).toContain('.novel-writing-queue-item-needs_plan')
    expect(projectWorkspace).toContain('writingQueue={writingCockpitModel.writingQueue}')
    expect(projectWorkspace).toContain('onSelectWritingQueueChapter={(chapterId) => { void selectChapterForWriting(chapterId) }}')
    expect(projectWorkspace).toContain('onRepairWritingQueuePlan={repairWritingQueuePlan}')
    expect(projectWorkspace).toContain('onRepairWritingQueuePlanBatch={repairWritingQueuePlanBatch}')
    expect(projectWorkspace).toContain("source: 'writing_queue_plan_repair'")
    expect(projectWorkspace).toContain("source: 'writing_queue_batch_plan_repair'")
  })

  test('keeps manual writing visible by collapsing auxiliary writing panels', () => {
    const component = workspaceCenterSource()
    const css = source('WorkspaceCenter.css')
    const projectWorkspaceCss = source('../NovelProjectWorkspace.css')

    expect(component).toContain('NOVEL_WRITING_AUX_COLLAPSED_KEY')
    expect(component).toContain('loadWritingAuxCollapsed')
    expect(component).toContain('saveWritingAuxCollapsed')
    expect(component).toContain('writingAuxCollapsed')
    expect(component).toContain('setWritingAuxCollapsed')
    expect(component).toContain('novel-writing-aux-rail')
    expect(component).toContain('novel-writing-support-stack')
    expect(component).toContain('展开辅助面板')
    expect(component).toContain('收起辅助面板')
    expect(component).toContain('辅助面板已收起，编辑器优先显示')
    expect(component).toContain('辅助面板已展开，可查看队列、交稿和任务书')
    expect(css).toContain('.novel-writing-aux-rail')
    expect(css).toContain('.novel-writing-support-stack')
    expect(css).toContain('max-height: min(34vh, 320px)')
    expect(css).toContain('overflow: auto')
    expect(css).toContain('.novel-writing-support-stack .novel-writing-queue-strip')
    expect(css).toContain('@media (max-width: 768px)')
    expect(projectWorkspaceCss).toContain('max-height: min(30vh, 300px)')
    expect(projectWorkspaceCss).toContain('max-height: min(34vh, 260px)')
    expect(projectWorkspaceCss).toContain('.novel-workspace-area-tabs')
    expect(projectWorkspaceCss).toContain('overflow-x: auto')
    expect(projectWorkspaceCss).toContain('.novel-workspace-area-tabs .ant-space-item')
    expect(projectWorkspaceCss).toContain('flex: 0 0 auto')
  })

  test('surfaces a direct unattended shortcut inside the writing cockpit', () => {
    const component = writingCockpitPanelSource()
    const projectWorkspace = projectWorkspaceSource()

    expect(component).toContain('onOpenProductionOps')
    expect(component).toContain('无人值守')
    expect(projectWorkspace).toContain('onOpenProductionOps={() => setWorkspaceArea(\'productionOps\')}')
  })

  test('surfaces the oh-story longform workflow in the writing cockpit', () => {
    const component = writingCockpitPanelSource()
    const css = source('WritingCockpitPanel.css')

    expect(component).toContain('LongformWorkflowStrip')
    expect(component).toContain('model.longformWorkflow')
    expect(component).toContain('writing-cockpit-workflow-strip')
    expect(component).toContain('writing-cockpit-workflow-stage-')
    expect(component).toContain('workflow.currentStage.label')
    expect(component).toContain('workflow.primaryAction.label')
    expect(component).toContain('stage.evidence.slice(0, 2)')
    expect(css).toContain('.writing-cockpit-workflow-strip')
    expect(css).toContain('.writing-cockpit-workflow-stage')
    expect(css).toContain('.writing-cockpit-workflow-stage.is-current')
    expect(css).toContain('.writing-cockpit-workflow-evidence')
  })

  test('surfaces the oh-story chapter blueprint contract in the writing brief card', () => {
    const component = workspaceCenterSource()
    const css = source('WorkspaceCenter.css')
    const model = writingRecommendationModelSource()
    const projectWorkspace = projectWorkspaceSource()

    expect(model).toContain('chapter_blueprint')
    expect(model).toContain('blueprintOutline')
    expect(model).toContain('blueprintPlotLines')
    expect(model).toContain('blueprintBeatSequence')
    expect(model).toContain('blueprintTargetEmotion')
    expect(model).toContain('blueprintOpeningHook')
    expect(model).toContain('blueprintCorePayoff')
    expect(model).toContain('writePreparationStatus')
    expect(model).toContain('writePreparationSourceGaps')
    expect(model).toContain('writePreparationMustConfirm')
    expect(model).toContain('nextChapterQualityFocus')
    expect(model).toContain('nextChapterQualityAvoid')
    expect(projectWorkspace).toContain('savePreDraftBriefForActiveChapter')
    expect(projectWorkspace).toContain('onSavePreDraftBrief')
    expect(projectWorkspace).toContain('apiClient.put(`/novel/chapters/${activeChapter.id}/pre-draft-brief`')
    expect(component).toContain('写前准备确认')
    expect(component).toContain('novel-draft-brief-write-preparation')
    expect(component).toContain('下一章质量续航')
    expect(component).toContain('novel-draft-brief-next-quality')
    expect(component).toContain('draftBriefSummary.briefFields.nextChapterQualityFocus')
    expect(component).toContain('draftBriefSummary.briefFields.nextChapterQualityAvoid')
    expect(component).toContain('draftBriefSummary.briefFields.writePreparationStatus')
    expect(component).toContain('来源缺口')
    expect(component).toContain('资产关系')
    expect(component).toContain('必须确认')
    expect(component).toContain('章节蓝图合同')
    expect(component).toContain('编辑蓝图')
    expect(component).toContain('保存蓝图')
    expect(component).toContain('openChapterBlueprintEditor')
    expect(component).toContain('saveChapterBlueprintEditor')
    expect(component).toContain('JSON.parse(blueprintEditorText)')
    expect(component).toContain('delete nextBrief.confirmed_at')
    expect(component).toContain('onSavePreDraftBrief?.(nextBrief)')
    expect(component).toContain('novel-draft-brief-blueprint')
    expect(component).toContain('novel-draft-brief-blueprint-edit')
    expect(component).toContain('五段式')
    expect(component).toContain('目标情绪')
    expect(component).toContain('开篇钩子')
    expect(component).toContain('核心回报')
    expect(component).toContain('多线推进')
    expect(component).toContain('人物顺序')
    expect(component).toContain('节拍功能')
    expect(component).toContain('代价收益')
    expect(component).toContain('章尾承接')
    expect(css).toContain('.novel-draft-brief-blueprint')
    expect(css).toContain('.novel-draft-brief-blueprint strong')
    expect(css).toContain('.novel-draft-brief-blueprint-edit')
  })

  test('reads camelCase raw pre-draft briefs in the writing workspace UI', () => {
    const component = workspaceCenterSource()
    const projectWorkspace = projectWorkspaceSource()

    expect(component).toContain('activeChapter?.raw_payload?.pre_draft_brief || activeChapter?.raw_payload?.preDraftBrief || null')
    expect(projectWorkspace).toContain('activeChapter.raw_payload?.pre_draft_brief || activeChapter.raw_payload?.preDraftBrief')
    expect(projectWorkspace).toContain('activeChapter?.raw_payload?.pre_draft_brief?.style_sample_strategy')
    expect(projectWorkspace).toContain('activeChapter?.raw_payload?.preDraftBrief?.style_sample_strategy')
  })

  test('surfaces chapter blueprint, revision, and delivery risk receipts in the delivery status strip', () => {
    const component = workspaceCenterSource()
    const css = source('WorkspaceCenter.css')
    const model = writingCockpitModelSource()
    const recommendationModel = writingRecommendationModelSource()

    expect(model).toContain('blueprintReceipt')
    expect(model).toContain('revisionReceipt')
    expect(model).toContain('deliveryRiskReceipt')
    expect(model).toContain('sceneCardReceipt')
    expect(model).toContain('qualityAudit')
    expect(model).toContain('approvalBlocker')
    expect(model).toContain('buildBlueprintReceiptSummary')
    expect(model).toContain('buildRevisionReceiptSummary')
    expect(model).toContain('buildDeliveryRiskReceiptSummary')
    expect(model).toContain('buildSceneCardReceiptSummary')
    expect(model).toContain('buildQualityAuditSummary')
    expect(model).toContain('buildApprovalBlockerSummary')
    expect(model).toContain('writePreparation')
    expect(model).toContain('write_preparation_checks')
    expect(model).toContain('blueprint_receipts')
    expect(model).toContain('revision_receipts')
    expect(model).toContain('delivery_risk_receipts')
    expect(model).toContain('scene_card_receipt')
    expect(model).toContain('质量诊断缺口')
    expect(model).toContain('复核修订')
    expect(model).toContain('复核承接')
    expect(model).toContain('复核场景回执')
    expect(model).toContain('修质量诊断')
    expect(model).toContain('补写前准备')
    expect(model).toContain('chapterHandoffSync')
    expect(model).toContain('chapter_handoff_sync')
    expect(model).toContain('补章首承接')
    expect(model).toContain('补章末交接')
    expect(recommendationModel).toContain('blueprintReceipt')
    expect(recommendationModel).toContain('revisionReceipt')
    expect(recommendationModel).toContain('deliveryRiskReceipt')
    expect(recommendationModel).toContain('sceneCardReceipt')
    expect(recommendationModel).toContain('qualityAudit')
    expect(recommendationModel).toContain('writePreparation')
    expect(recommendationModel).toContain('chapterHandoffSync')
    expect(recommendationModel).toContain('chapterHandoffDeltaSync')
    expect(component).toContain('deliverySummary.blueprintReceipt')
    expect(component).toContain('deliverySummary.revisionReceipt')
    expect(component).toContain('deliverySummary.deliveryRiskReceipt')
    expect(component).toContain('deliverySummary.sceneCardReceipt')
    expect(component).toContain('deliverySummary.qualityAudit')
    expect(component).toContain('deliverySummary.writePreparation')
    expect(component).toContain('deliverySummary.chapterHandoffSync')
    expect(component).toContain('deliverySummary.chapterHandoffDeltaSync')
    expect(component).toContain('deliverySummary.approvalBlocker')
    expect(component).toContain('novel-delivery-blueprint-tag')
    expect(component).toContain('novel-delivery-revision-tag')
    expect(component).toContain('novel-delivery-risk-receipt-tag')
    expect(component).toContain('novel-delivery-scene-card-receipt-tag')
    expect(component).toContain('novel-delivery-quality-audit-tag')
    expect(component).toContain('novel-delivery-write-preparation-tag')
    expect(component).toContain('novel-delivery-handoff-sync-tag')
    expect(component).toContain('novel-delivery-handoff-delta-tag')
    expect(component).toContain('novel-delivery-approval-blocker-tag')
    expect(component).toContain('scoreLabel')
    expect(component).toContain('missed.join')
    expect(component).toContain('risks.join')
    expect(component).toContain('fixes.join')
    expect(css).toContain('.novel-delivery-blueprint-tag')
    expect(css).toContain('.novel-delivery-blueprint-tag-warn')
    expect(model).toContain('platformRubric')
    expect(model).toContain('buildPlatformRubricSummary')
    expect(model).toContain('platform_checks')
    expect(model).toContain('平台适配')
    expect(recommendationModel).toContain('platformRubric')
    expect(component).toContain('deliverySummary.platformRubric')
    expect(component).toContain('novel-delivery-platform-tag')
    expect(css).toContain('.novel-delivery-platform-tag')
    expect(css).toContain('.novel-delivery-revision-tag')
    expect(css).toContain('.novel-delivery-revision-tag-warn')
    expect(css).toContain('.novel-delivery-risk-receipt-tag')
    expect(css).toContain('.novel-delivery-risk-receipt-tag-warn')
    expect(css).toContain('.novel-delivery-scene-card-receipt-tag')
    expect(css).toContain('.novel-delivery-scene-card-receipt-tag-warn')
    expect(css).toContain('.novel-delivery-quality-audit-tag')
    expect(css).toContain('.novel-delivery-quality-audit-tag-warn')
    expect(css).toContain('.novel-delivery-write-preparation-tag')
    expect(css).toContain('.novel-delivery-write-preparation-tag-warn')
    expect(css).toContain('.novel-delivery-handoff-sync-tag')
    expect(css).toContain('.novel-delivery-handoff-sync-tag-warn')
    expect(css).toContain('.novel-delivery-handoff-delta-tag')
    expect(css).toContain('.novel-delivery-handoff-delta-tag-warn')
    expect(css).toContain('.novel-delivery-approval-blocker-tag')
    expect(css).toContain('.novel-delivery-approval-blocker-tag-warn')
  })

  test('explains approval-blocker resume failures instead of showing a generic run error', () => {
    const projectWorkspace = projectWorkspaceSource()

    expect(projectWorkspace).toContain('formatRunResumeErrorMessage')
    expect(projectWorkspace).toContain('APPROVAL_BLOCKER_REQUIRES_REPAIR')
    expect(projectWorkspace).toContain('入库阻断')
    expect(projectWorkspace).toContain('message.error(formatRunResumeErrorMessage(error))')
  })

  test('surfaces writing queue focus inside the auto creation director', () => {
    const component = autoCreationDirectorWorkspaceSource()
    const css = source('AutoCreationDirectorWorkspace.css')
    const model = directorModelSource()

    expect(model).toContain('writingQueueFocus')
    expect(model).toContain('buildWritingQueueFocus')
    expect(component).toContain('写作队列')
    expect(component).toContain('auto-director-writing-queue-focus')
    expect(component).toContain('model.writingQueueFocus.visible')
    expect(component).toContain('model.writingQueueFocus.badges')
    expect(component).toContain('model.writingQueueFocus.action')
    expect(css).toContain('.auto-director-writing-queue-focus')
    expect(css).toContain('.auto-director-writing-queue-focus-needs_plan')
    expect(css).toContain('.auto-director-writing-queue-focus-ready_to_draft')
    expect(css).toContain('.auto-director-writing-queue-focus-draft_generated')
  })

  test('shows a five-stage serial production rail in the auto creation director', () => {
    const component = autoCreationDirectorWorkspaceSource()
    const css = source('AutoCreationDirectorWorkspace.css')
    const model = directorModelSource()
    const projectWorkspace = projectWorkspaceSource()

    expect(model).toContain('serialWorkflow')
    expect(model).toContain('book_core')
    expect(model).toContain('longform_plan')
    expect(model).toContain('chapter_launch')
    expect(model).toContain('delivery_acceptance')
    expect(model).toContain('serial_governance')
    expect(component).toContain('连载生产轨道')
    expect(component).toContain('model.serialWorkflow.currentLabel')
    expect(component).toContain('auto-director-serial-rail')
    expect(component).toContain('model.serialWorkflow.stages.map')
    expect(component).toContain('onStageAction(stage.action)')
    expect(component).toContain('auto-director-serial-stage-button')
    expect(component).toContain('stage.action.label')
    expect(component).toContain('onStageAction?: (action: AutoCreationDirectorAction) => void')
    expect(projectWorkspace).toContain('onStageAction={handleAutoCreationDirectorAction}')
    expect(projectWorkspace).toContain("enter_story_planning: () => setWorkspaceArea('storyPlanning')")
    expect(model).toContain("planningAction('enter_story_planning'")
    expect(css).toContain('.auto-director-serial-rail')
    expect(css).toContain('.auto-director-serial-stage-button')
    expect(css).toContain('.auto-director-serial-stage-active')
    expect(css).toContain('.auto-director-serial-stage-blocked')
    expect(css).toContain('.auto-director-serial-stage-done')
  })

  test('exposes unattended writing goal controls in the production toolbox', () => {
    const projectWorkspace = projectWorkspaceSource()
    const startIdx = projectWorkspace.indexOf('const startUnattendedWritingGoal = async () =>')
    // After extract, openRunQueue stays in NWS while startUnattended lives in production handlers;
    // slice to the factory return binding that follows the function body.
    const endIdx = projectWorkspace.indexOf('startUnattendedWritingGoal,', startIdx + 1)
    const startBlock = projectWorkspace.slice(startIdx, endIdx > startIdx ? endIdx : startIdx + 2500)

    expect(startIdx).toBeGreaterThanOrEqual(0)
    expect(projectWorkspace).toContain('unattendedTargetChapter')
    expect(projectWorkspace).toContain('startUnattendedWritingGoal')
    expect(projectWorkspace).toContain("chapter-groups/start-unattended")
    expect(projectWorkspace).toContain('target_chapter: unattendedTargetChapter')
    expect(projectWorkspace).toContain('无人值守到目标章')
    expect(projectWorkspace).toContain('启动无人值守')
    expect(projectWorkspace).toContain('run-queue/start-worker')
    expect(startBlock).toContain('allow_incomplete: false')
    expect(startBlock).toContain('idle_wait_ms')
    expect(startBlock).toContain('idle_poll_ms')
    expect(startBlock).not.toContain('allow_incomplete: true')
    expect(startBlock).not.toContain('quality_threshold: 78')
  })

  test('surfaces unattended writing directly in the production operations workspace', () => {
    const projectWorkspace = projectWorkspaceSource()
    const productionOpsBlock = projectWorkspace.slice(
      projectWorkspace.indexOf("productionOps: {"),
      projectWorkspace.indexOf('const group = groups[workspaceArea]'),
    )

    expect(productionOpsBlock).toContain('无人值守到目标章')
    expect(productionOpsBlock).toContain('unattendedTargetChapter')
    expect(productionOpsBlock).toContain('startUnattendedWritingGoal')
    expect(productionOpsBlock).toContain('写前蓝图')
  })

  test('keeps a top bar shortcut for unattended writing visible from any workspace area', () => {
    const projectWorkspace = projectWorkspaceSource()
    const projectWorkspaceCss = source('../NovelProjectWorkspace.css')
    const topbarBlock = projectWorkspace.slice(
      projectWorkspace.indexOf('className="novel-workspace-topbar"'),
      projectWorkspace.indexOf("{workspaceArea === 'chapterWriting' && ("),
    )

    expect(topbarBlock).toContain('novel-unattended-topbar-entry')
    expect(topbarBlock).toContain("setWorkspaceArea('productionOps')")
    expect(topbarBlock).toContain('无人值守')
    expect(projectWorkspaceCss).toContain('.novel-unattended-topbar-entry')
    expect(projectWorkspaceCss).toContain('flex: 0 0 auto')
  })

  test('shows the shared six-stage AI creation pipeline inside the auto creation director', () => {
    const component = autoCreationDirectorWorkspaceSource()
    const css = source('AutoCreationDirectorWorkspace.css')
    const model = directorModelSource()

    expect(model).toContain('creationPipeline')
    expect(model).toContain('buildCreationPipeline')
    expect(component).toContain('AI长篇创作流水线')
    expect(component).toContain('model.creationPipeline.summary')
    expect(component).toContain('model.creationPipeline.primaryAction')
    expect(component).toContain('model.creationPipeline.stages.map')
    expect(component).toContain('auto-director-creation-pipeline')
    expect(component).toContain('auto-director-creation-stage')
    expect(component).toContain('全书核心')
    expect(component).toContain('长线规划')
    expect(component).toContain('设定资产')
    expect(component).toContain('章节开写')
    expect(component).toContain('交稿验收')
    expect(component).toContain('连载发布')
    expect(css).toContain('.auto-director-creation-pipeline')
    expect(css).toContain('.auto-director-creation-stage')
    expect(css).toContain('.auto-director-creation-stage.is-active')
  })

  test('shows the current agent chain inside the shared novel pipeline', () => {
    const projectWorkspace = projectWorkspaceSource()
    const css = source('../NovelProjectWorkspace.css')

    expect(projectWorkspace).toContain('serialPipelineModel.currentAgentSteps')
    expect(projectWorkspace).toContain('novel-serial-pipeline-agent-strip')
    expect(projectWorkspace).toContain('novel-serial-pipeline-agent')
    expect(projectWorkspace).toContain('agent.description')
    expect(projectWorkspace).toContain('agent.agent')
    expect(projectWorkspace).toContain("case 'create_editor_report'")
    expect(projectWorkspace).toContain("case 'apply_editor_revision'")
    expect(css).toContain('.novel-serial-pipeline-agent-strip')
    expect(css).toContain('.novel-serial-pipeline-agent')
    expect(css).toContain('.novel-serial-pipeline-agent-name')
  })

  test('keeps the shared novel pipeline stage rail compact enough to scan at once', () => {
    const projectWorkspace = projectWorkspaceSource()
    const css = source('../NovelProjectWorkspace.css')

    expect(projectWorkspace).toContain('`阻${stage.blockerCount}`')
    expect(projectWorkspace).toContain('`提${stage.warningCount}`')
    expect(css).toContain('grid-template-columns: repeat(6, minmax(0, 1fr))')
    expect(css).toContain('.novel-serial-pipeline-stage .ant-tag')
  })

  test('surfaces the shared novel pipeline as a blocker repair guide', () => {
    const projectWorkspace = projectWorkspaceSource()
    const css = source('../NovelProjectWorkspace.css')

    expect(projectWorkspace).toContain('novel-serial-pipeline-guide')
    expect(projectWorkspace).toContain('当前卡点')
    expect(projectWorkspace).toContain('去哪里修')
    expect(projectWorkspace).toContain('修完验证')
    expect(projectWorkspace).toContain('serialPipelineModel.repairGuide')
    expect(css).toContain('.novel-serial-pipeline-guide')
    expect(css).toContain('.novel-serial-pipeline-guide-steps')
  })

  test('offers a direct de-ai gate repair action from the chapter writing desk', () => {
    const workspaceCenter = workspaceCenterSource()
    const projectWorkspace = projectWorkspaceSource()

    expect(workspaceCenter).toContain('onRepairDeslopGate')
    expect(workspaceCenter).toContain('修复去AI味并复检')
    expect(workspaceCenter).toContain('novel-deslop-gate-action')
    expect(projectWorkspace).toContain('repairActiveDeslopGate')
    expect(projectWorkspace).toContain("revisionMode: 'tighten_pacing'")
    expect(projectWorkspace).toContain("source: 'deslop_gate_repair'")
  })

  test('exposes creation contract fields in the writing bible editor', () => {
    const projectWorkspace = projectWorkspaceSource()

    expect(projectWorkspace).toContain('创建契约')
    expect(projectWorkspace).toContain('name="reader_promise"')
    expect(projectWorkspace).toContain('name="protagonist_drive"')
    expect(projectWorkspace).toContain('name="core_conflict"')
    expect(projectWorkspace).toContain('name="current_volume_goal"')
    expect(projectWorkspace).toContain('name="innovation_hook"')
    expect(projectWorkspace).toContain('name="first30_plan"')
    expect(projectWorkspace).toContain('name="longform_capacity"')
    expect(projectWorkspace).toContain('reader_promise: v.reader_promise')
    expect(projectWorkspace).toContain('protagonist_drive: v.protagonist_drive')
  })

  test('keeps longform governance rails inside the auto creation detail drawer', () => {
    const component = autoCreationDirectorWorkspaceSource()

    const drawerIndex = component.indexOf('auto-director-detail-drawer')
    expect(drawerIndex).toBeGreaterThan(0)
    expect(component.indexOf('auto-director-creation-pipeline')).toBeGreaterThan(drawerIndex)
    expect(component.indexOf('auto-director-battle-desk')).toBeGreaterThan(drawerIndex)
    expect(component.indexOf('auto-director-serial-rail')).toBeGreaterThan(drawerIndex)
  })

  test('guards longform canon and memory runway before safe batching', () => {
    const model = directorModelSource()

    expect(model).toContain('buildCanonRunway')
    expect(model).toContain('story_state_stale')
    expect(model).toContain('memory_unavailable')
    expect(model).toContain('长线记忆')
    expect(model).toContain('长线记忆待同步')
    expect(model).toContain("writingAction('update_canon'")
    expect(model).toContain("writingAction('fix_continuity'")
  })

  test('passes memory palace summary into the writing cockpit runway checks', () => {
    const projectWorkspace = projectWorkspaceSource()

    expect(projectWorkspace).toContain('memoryPalaceProjects')
    expect(projectWorkspace).toContain('/memory-palace/projects')
    expect(projectWorkspace).toContain('activeMemorySummary')
    expect(projectWorkspace).toContain('memorySummary: activeMemorySummary')
    expect(projectWorkspace).toContain('memory_count: 0')
    expect(projectWorkspace).toContain('missing: true')
  })

  test('runs story state sync automatically from writing cockpit actions', () => {
    const projectWorkspace = projectWorkspaceSource()

    expect(projectWorkspace).toContain('syncStoryStateForChapter')
    expect(projectWorkspace).toContain('/story-state-sync')
    expect(projectWorkspace).toContain("source: 'writing_cockpit_state_sync'")
    expect(projectWorkspace).toContain("case 'sync_story_state'")
    expect(projectWorkspace).toContain('void syncStoryStateForChapter')
  })

  test('keeps the left production guide as a compact status summary', () => {
    const component = source('ProductionGuidePanel.tsx')
    const css = source('ProductionGuidePanel.css')

    expect(component).toContain("import './ProductionGuidePanel.css'")
    expect(component).toContain('production-guide-summary-panel')
    expect(component).toContain('production-guide-summary-grid')
    expect(component).toContain('production-guide-summary-action')
    expect(component).toContain('项目进度')
    expect(component).not.toContain('GuideStep')
    expect(component).not.toContain('production-guide-primary-command')
    expect(component).not.toContain('production-guide-secondary-command')
    expect(component).not.toContain('primaryLabel')
    expect(css).toContain('.production-guide-summary-panel')
    expect(css).toContain('.production-guide-summary-grid')
    expect(css).not.toContain('.production-guide-step-active')
    expect(css).not.toContain('.production-guide-secondary-command')
  })

  test('separates the writing cockpit from delivery and collapsed workspace bars', () => {
    const component = writingCockpitPanelSource()
    const css = source('WritingCockpitPanel.css')

    expect(component).toContain("import './WritingCockpitPanel.css'")
    expect(component).toContain('writing-cockpit-card-expanded')
    expect(component).toContain('writing-cockpit-card-collapsed')
    expect(component).toContain('writing-cockpit-summary-strip')
    expect(component).toContain('writing-cockpit-summary-primary')
    expect(component).toContain('writing-cockpit-summary-right')
    expect(component).not.toContain('writing-cockpit-collapsed-actions')
    expect(component).toContain('writing-cockpit-subdesk')
    expect(component).toContain('writing-cockpit-command-grid')
    expect(component).toContain('核心契约')
    expect(component).toContain('mustServe')
    expect(component).toContain('不得漂移')
    expect(component).toContain('弃读预警')
    expect(component).toContain('readerDropRisk')
    expect(component).toContain('开篇防弃读')
    expect(component).toContain('中段防掉速')
    expect(component).toContain('故事压力')
    expect(component).toContain('storyPressure')
    expect(component).toContain('冲突升级')
    expect(component).toContain('赌注升级')
    expect(component).toContain('反转逼迫')
    expect(component).toContain('主角能动性')
    expect(component).toContain('storyDrive')
    expect(component).toContain('主角选择')
    expect(component).toContain('选择代价')
    expect(component).toContain('状态变化')
    expect(component).toContain('连载节奏')
    expect(component).toContain('serialRhythm')
    expect(component).toContain('回报密度')
    expect(component).toContain('开篇钩子')
    expect(component).toContain('章末追读')
    expect(component).toContain('章末翻页')
    expect(component).toContain('pageTurnHook')
    expect(component).toContain('读者问题')
    expect(component).toContain('禁提前解答')
    expect(component).toContain('卷级爆点')
    expect(component).toContain('volumeClimax')
    expect(component).toContain('本章爆点职责')
    expect(component).toContain('禁提前消费')
    expect(component).toContain('交稿风险转写作动作')
    expect(component).toContain('deliveryRiskCarryOver')
    expect(component).toContain('风险：')
    expect(component).toContain('证据：')
    expect(component).toContain('deliveryRiskCarryOver.evidence')
    expect(component).toContain('动作：')
    expect(component).toContain('开篇修复')
    expect(component).toContain('中段推进')
    expect(component).toContain('章末追读')
    expect(css).toContain('.writing-cockpit-card-expanded')
    expect(css).toContain('.writing-cockpit-subdesk')
    expect(css).toContain('.writing-cockpit-card-collapsed')
    expect(css).toContain('.writing-cockpit-summary-strip')
    expect(css).toContain('.writing-cockpit-summary-primary')
    expect(css).not.toContain('.writing-cockpit-collapsed-actions')
    expect(css).toContain('.writing-cockpit-reader-drop-risk')
    expect(css).toContain('.writing-cockpit-story-pressure')
    expect(css).toContain('.writing-cockpit-story-drive')
    expect(css).toContain('.writing-cockpit-serial-rhythm')
    expect(css).toContain('.writing-cockpit-page-turn-hook')
    expect(css).toContain('.writing-cockpit-volume-climax')
    expect(css).toContain('.writing-cockpit-delivery-risk')
  })

  test('uses a reference nav rail with compact revision chips', () => {
    const component = source('ReferencePanel.tsx')
    const css = source('ReferencePanel.css')

    expect(component).toContain("import './ReferencePanel.css'")
    expect(component).toContain('novel-reference-nav-rail')
    expect(component).toContain('novel-reference-nav-item')
    expect(component).toContain('novel-reference-revision-chip')
    expect(css).toContain('.novel-reference-nav-item')
    expect(css).toContain('.novel-reference-revision-chip')
  })

  test('shows storyline workshop types and draft brief storyline section', () => {
    const settingPanel = source('SettingWorkshopPanel.tsx')
    const usageModel = source('settingUsageWorkbenchModel.ts')
    const workspaceCenter = workspaceCenterSource()
    const workspaceCss = source('WorkspaceCenter.css')

    expect(settingPanel).toContain("value: 'mainline'")
    expect(settingPanel).toContain("label: '主线'")
    expect(settingPanel).toContain("value: 'subplot'")
    expect(settingPanel).toContain("value: 'character_arc'")
    expect(settingPanel).toContain("value: 'relationship_arc'")
    expect(settingPanel).toContain("value: 'faction_arc'")
    expect(settingPanel).toContain("value: 'foreshadowing_arc'")
    expect(settingPanel).toContain('usageSegmentOptions')
    expect(usageModel).toContain("value: 'advance'")
    expect(usageModel).toContain("value: 'payoff'")
    expect(settingPanel).toContain('/storylines/suggest')
    expect(settingPanel).toContain('匹配剧情线')
    expect(workspaceCenter).toContain('剧情线推进')
    expect(workspaceCenter).toContain('必推')
    expect(workspaceCenter).toContain('埋线')
    expect(workspaceCenter).toContain('回收')
    expect(workspaceCenter).toContain('禁用')
    expect(workspaceCss).toContain('.novel-draft-brief-storylines')
  })

  test('shows character growth obligations in the chapter pre-draft brief', () => {
    const workspaceCenter = workspaceCenterSource()
    const workspaceCss = source('WorkspaceCenter.css')
    const model = writingRecommendationModelSource()
    const service = writingServiceSource()

    expect(workspaceCenter).toContain('人物成长承接')
    expect(workspaceCenter).toContain('角色欲望')
    expect(workspaceCenter).toContain('缺陷受压')
    expect(workspaceCenter).toContain('成长节点')
    expect(workspaceCenter).toContain('关系变化')
    expect(workspaceCenter).toContain('禁揭')
    expect(workspaceCss).toContain('.novel-draft-brief-character-arc')
    expect(model).toContain('character_arc_brief')
    expect(model).toContain('characterArcGrowthBeat')
    expect(service).toContain('character_arc_brief')
    expect(service).toContain('【人物成长承接】')
  })

  test('shows storyline board evidence details for plan versus actual sync', () => {
    const workspaceCenter = storyPlanningWorkspaceSource()
    const model = planningWorkspaceSource()

    expect(workspaceCenter).toContain('剧情线证据')
    expect(workspaceCenter).toContain('计划推进')
    expect(workspaceCenter).toContain('实际推进')
    expect(workspaceCenter).toContain('差异复盘')
    expect(workspaceCenter).toContain('差异决策')
    expect(workspaceCenter).toContain('回修正文')
    expect(workspaceCenter).toContain('接受为新计划')
    expect(workspaceCenter).toContain('标记误判')
    expect(workspaceCenter).toContain('novel-storyline-evidence')
    expect(model).toContain('planEvidence')
    expect(model).toContain('actualEvidence')
    expect(model).toContain('diffEvidence')
    expect(model).toContain('syncRisks')
    expect(model).toContain('latestSyncChapter')
  })

  test('shows reader retention radar in the chapter pre-draft brief', () => {
    const workspaceCenter = workspaceCenterSource()
    const workspaceCss = source('WorkspaceCenter.css')
    const model = writingRecommendationModelSource()
    const service = writingServiceSource()

    expect(workspaceCenter).toContain('追读雷达')
    expect(workspaceCenter).toContain('开篇钩子')
    expect(workspaceCenter).toContain('爽点承诺')
    expect(workspaceCenter).toContain('短剧场面')
    expect(workspaceCenter).toContain('章末追读')
    expect(workspaceCss).toContain('.novel-draft-brief-retention')
    expect(model).toContain('reader_retention_brief')
    expect(model).toContain('retentionOpeningHook')
    expect(service).toContain('reader_retention_brief')
    expect(service).toContain('short_drama_scene')
  })

  test('shows story unit task in the chapter pre-draft brief', () => {
    const workspaceCenter = workspaceCenterSource()
    const workspaceCss = source('WorkspaceCenter.css')
    const model = writingRecommendationModelSource()
    const service = writingServiceSource()

    expect(workspaceCenter).toContain('剧情单元任务')
    expect(workspaceCenter).toContain('当前职责')
    expect(workspaceCenter).toContain('单元目标')
    expect(workspaceCenter).toContain('禁抢跑')
    expect(workspaceCss).toContain('.novel-draft-brief-story-unit')
    expect(model).toContain('story_unit_context')
    expect(model).toContain('storyUnitRole')
    expect(service).toContain('story_unit_context')
    expect(service).toContain('【剧情单元任务】')
  })

  test('shows volume climax budget in the chapter pre-draft brief', () => {
    const workspaceCenter = workspaceCenterSource()
    const workspaceCss = source('WorkspaceCenter.css')
    const model = writingRecommendationModelSource()
    const service = writingServiceSource()

    expect(workspaceCenter).toContain('卷级爆点预算')
    expect(workspaceCenter).toContain('本章爆点职责')
    expect(workspaceCenter).toContain('禁提前消费')
    expect(workspaceCss).toContain('.novel-draft-brief-volume-climax')
    expect(model).toContain('volume_climax_brief')
    expect(model).toContain('volumeClimaxRole')
    expect(service).toContain('volume_climax_brief')
    expect(service).toContain('【卷级高潮预算】')
  })

  test('shows recent fatigue avoidance in the chapter pre-draft brief', () => {
    const workspaceCenter = workspaceCenterSource()
    const workspaceCss = source('WorkspaceCenter.css')
    const model = writingRecommendationModelSource()
    const service = writingServiceSource()

    expect(workspaceCenter).toContain('近10章疲劳规避')
    expect(workspaceCenter).toContain('冲突换源')
    expect(workspaceCenter).toContain('回报换形')
    expect(workspaceCenter).toContain('钩子换题')
    expect(workspaceCss).toContain('.novel-draft-brief-recent-fatigue')
    expect(model).toContain('recent_fatigue_brief')
    expect(model).toContain('recentFatigueConflict')
    expect(service).toContain('recent_fatigue_brief')
    expect(service).toContain('【近章连载动能与疲劳规避】')
  })

  test('shows strong story and reader pull execution in the chapter pre-draft brief', () => {
    const workspaceCenter = workspaceCenterSource()
    const workspaceCss = source('WorkspaceCenter.css')
    const model = writingRecommendationModelSource()
    const service = writingServiceSource()

    expect(workspaceCenter).toContain('弃读预警')
    expect(workspaceCenter).toContain('强故事节奏')
    expect(workspaceCenter).toContain('主角选择')
    expect(workspaceCenter).toContain('回报密度')
    expect(workspaceCenter).toContain('章末翻页')
    expect(workspaceCss).toContain('.novel-draft-brief-reader-drop')
    expect(workspaceCss).toContain('.novel-draft-brief-story-pull')
    expect(model).toContain('reader_drop_risk_brief')
    expect(model).toContain('readerDropRisks')
    expect(model).toContain('story_drive_brief')
    expect(model).toContain('storyDriveChoice')
    expect(model).toContain('serial_rhythm_brief')
    expect(model).toContain('serialRhythmPayoffInterval')
    expect(model).toContain('page_turn_hook_brief')
    expect(model).toContain('pageTurnQuestion')
    expect(service).toContain('reader_drop_risk_brief')
    expect(service).toContain('story_drive_brief')
    expect(service).toContain('serial_rhythm_brief')
    expect(service).toContain('page_turn_hook_brief')
  })

  test('shows chapter innovation execution in the pre-draft brief', () => {
    const workspaceCenter = workspaceCenterSource()
    const workspaceCss = source('WorkspaceCenter.css')
    const model = writingRecommendationModelSource()
    const service = writingServiceSource()

    expect(workspaceCenter).toContain('创新执行')
    expect(workspaceCenter).toContain('创新角度')
    expect(workspaceCenter).toContain('差异护栏')
    expect(workspaceCenter).toContain('IP化场面')
    expect(workspaceCss).toContain('.novel-draft-brief-innovation')
    expect(model).toContain('innovation_brief')
    expect(model).toContain('innovationAngle')
    expect(service).toContain('innovation_brief')
    expect(service).toContain('differentiation_guardrails')
  })

  test('shows signature scene repair in the pre-draft brief', () => {
    const workspaceCenter = workspaceCenterSource()
    const workspaceCss = source('WorkspaceCenter.css')
    const model = writingRecommendationModelSource()
    const service = writingServiceSource()

    expect(workspaceCenter).toContain('强场面补位')
    expect(workspaceCenter).toContain('标志性场面')
    expect(workspaceCenter).toContain('补位目标')
    expect(workspaceCenter).toContain('服务主线')
    expect(workspaceCss).toContain('.novel-draft-brief-signature-scene')
    expect(model).toContain('signature_scene_brief')
    expect(model).toContain('signatureSceneTarget')
    expect(service).toContain('【本章标志性场面补位】')
    expect(service).toContain('signature_scene')
  })

  test('shows longform battle obligations in the pre-draft brief', () => {
    const workspaceCenter = workspaceCenterSource()
    const workspaceCss = source('WorkspaceCenter.css')
    const model = writingRecommendationModelSource()
    const service = writingServiceSource()
    const promptSections = serverSource('novel-writing/prose-generation-prompt-sections.ts')

    expect(workspaceCenter).toContain('长篇作战承接')
    expect(workspaceCenter).toContain('今日优先')
    expect(workspaceCenter).toContain('风险线')
    expect(workspaceCss).toContain('.novel-draft-brief-battle')
    expect(model).toContain('longform_battle_context')
    expect(model).toContain('longformBattleLaneRequirements')
    expect(service).toContain('longform_battle_context')
    expect(service).toContain('buildLongformBattleContextPromptSection')
    expect(promptSections).toContain('【长篇作战承接】')
  })

  test('shows governance recheck memory in the pre-draft brief', () => {
    const workspaceCenter = workspaceCenterSource()
    const workspaceCss = source('WorkspaceCenter.css')
    const model = writingRecommendationModelSource()
    const service = writingServiceSource()
    const promptSections = serverSource('novel-writing/prose-generation-prompt-sections.ts')

    expect(workspaceCenter).toContain('治理复查承接')
    expect(workspaceCenter).toContain('修后证据')
    expect(workspaceCenter).toContain('观察项')
    expect(workspaceCss).toContain('.novel-draft-brief-governance-memory')
    expect(model).toContain('governance_recheck_memory')
    expect(model).toContain('governanceMemoryEvidence')
    expect(service).toContain('governance_recheck_memory')
    expect(service).toContain('buildGovernanceRecheckPromptSection')
    expect(promptSections).toContain('【治理复查承接】')
  })

  test('shows storyline sync status in the delivery strip', () => {
    const workspaceCenter = workspaceCenterSource()
    const workspaceCss = source('WorkspaceCenter.css')

    expect(workspaceCenter).toContain('storylineSync')
    expect(workspaceCenter).toContain('novel-delivery-storyline-tag')
    expect(workspaceCss).toContain('.novel-delivery-storyline-tag')
    expect(workspaceCss).toContain('.novel-delivery-storyline-tag-warn')
  })

  test('shows story unit sync status in the delivery strip', () => {
    const workspaceCenter = workspaceCenterSource()
    const workspaceCss = source('WorkspaceCenter.css')
    const writingModel = writingCockpitModelSource()
    const recommendationModel = writingRecommendationModelSource()
    const service = writingServiceSource()
    const reviewRecords = serverSource('novel-writing/post-delivery-sync-review-record.ts')

    expect(workspaceCenter).toContain('storyUnitSync')
    expect(workspaceCenter).toContain('novel-delivery-story-unit-tag')
    expect(workspaceCss).toContain('.novel-delivery-story-unit-tag')
    expect(workspaceCss).toContain('.novel-delivery-story-unit-tag-warn')
    expect(writingModel).toContain('story_unit_sync')
    expect(recommendationModel).toContain('storyUnitSync')
    expect(service).toContain("reviewType: 'story_unit_sync'")
    expect(reviewRecords).toContain('review_type: input.reviewType')
  })

  test('shows chapter core drift status in the delivery strip', () => {
    const workspaceCenter = workspaceCenterSource()
    const workspaceCss = source('WorkspaceCenter.css')
    const model = writingCockpitModelSource()
    const service = writingServiceSource()
    const draftReviewRecords = serverSource('novel-writing/draft-sync-review-record.ts')

    expect(workspaceCenter).toContain('coreDrift')
    expect(workspaceCenter).toContain('novel-delivery-core-drift-tag')
    expect(workspaceCss).toContain('.novel-delivery-core-drift-tag')
    expect(workspaceCss).toContain('.novel-delivery-core-drift-tag-warn')
    expect(model).toContain('chapter_core_drift')
    expect(service).toContain('buildChapterCoreDriftDraftReviewRecord')
    expect(draftReviewRecords).toContain("reviewType: 'chapter_core_drift'")
  })

  test('shows reader payoff sync status in the delivery strip', () => {
    const workspaceCenter = workspaceCenterSource()
    const workspaceCss = source('WorkspaceCenter.css')
    const model = writingCockpitModelSource()
    const service = writingServiceSource()
    const draftReviewRecords = serverSource('novel-writing/draft-sync-review-record.ts')

    expect(workspaceCenter).toContain('readerPayoffSync')
    expect(workspaceCenter).toContain('novel-delivery-payoff-tag')
    expect(workspaceCss).toContain('.novel-delivery-payoff-tag')
    expect(workspaceCss).toContain('.novel-delivery-payoff-tag-warn')
    expect(model).toContain('reader_payoff_sync')
    expect(service).toContain('buildReaderPayoffDraftReviewRecord')
    expect(draftReviewRecords).toContain("reviewType: 'reader_payoff_sync'")
  })

})
