import { describe, expect, test } from 'bun:test'
import { readFileSync } from 'fs'
import { join } from 'path'

function source(file: string) {
  return readFileSync(join(import.meta.dir, file), 'utf8')
}

describe('commercial writing workspace UI shell', () => {
  test('uses command-oriented controls in the central writing toolbar', () => {
    const component = source('WorkspaceCenter.tsx')
    const css = source('WorkspaceCenter.css')

    expect(component).toContain('novel-editor-stagebar')
    expect(component).toContain('novel-editor-command-pill')
    expect(component).toContain('novel-editor-icon-command')
    expect(component).toContain('novel-word-preset')
    expect(component).toContain('NOVEL_WRITING_DESK_COLLAPSED_KEY')
    expect(component).toContain('setWritingDeskCollapsed')
    expect(component).toContain('novel-editor-toolbar-collapsed')
    expect(component).toContain('novel-editor-collapsed-summary')
    expect(component).toContain('novel-editor-toolbar-meta')
    expect(component).toContain('novel-editor-toolbar-actions')
    expect(component).toContain('novel-editor-toolbar-recommendation')
    expect(css).toContain('.novel-editor-command-pill')
    expect(css).toContain('.novel-editor-stage')
    expect(css).toContain('.novel-editor-toolbar-meta')
    expect(css).toContain('.novel-editor-toolbar-actions')
    expect(css).toContain('.novel-editor-toolbar-recommendation')
    expect(css).toContain('grid-template-columns')
    expect(css).toContain('.novel-editor-toolbar-collapsed')
    expect(css).toContain('.novel-editor-toolbar-collapsed .novel-editor-recommendation-hint')
    expect(css).toContain('display: none')
    expect(css).toContain('.novel-editor-collapsed-actions')
    expect(css).toContain('flex-shrink: 0')
  })

  test('shows a compact writing queue in the chapter workspace', () => {
    const component = source('WorkspaceCenter.tsx')
    const css = source('WorkspaceCenter.css')
    const projectWorkspace = source('../NovelProjectWorkspace.tsx')
    const model = source('writingCockpitModel.ts')

    expect(model).toContain('writingQueue')
    expect(model).toContain('sourceLabel: chapterPlanSourceLabel')
    expect(component).toContain('writingQueue')
    expect(component).toContain('写作队列')
    expect(component).toContain('novel-writing-queue-strip')
    expect(component).toContain('novel-writing-queue-item-')
    expect(component).toContain('onSelectWritingQueueChapter')
    expect(component).toContain('role="button"')
    expect(component).toContain('tabIndex={0}')
    expect(component).toContain("event.key === 'Enter'")
    expect(component).toContain('novel-writing-queue-action')
    expect(component).toContain('item.actionLabel')
    expect(component).toContain('item.actionHint')
    expect(component).toContain('novel-writing-queue-focus')
    expect(component).toContain('本章计划缺口')
    expect(component).toContain('补齐本章计划')
    expect(component).toContain('本章开写就绪')
    expect(component).toContain('处理本章开写')
    expect(component).toContain('runDraftBriefAction')
    expect(component).toContain('本章待质检')
    expect(component).toContain('处理交稿质检')
    expect(component).toContain('runQueueDeliveryAction')
    expect(component).toContain('onRepairWritingQueuePlan')
    expect(component).toContain('补齐队列计划')
    expect(component).toContain('onRepairWritingQueuePlanBatch')
    expect(component).toContain('滚动规划')
    expect(css).toContain('.novel-writing-queue-strip')
    expect(css).toContain('.novel-writing-queue-item.is-active')
    expect(css).toContain('.novel-writing-queue-action')
    expect(css).toContain('.novel-writing-queue-focus')
    expect(css).toContain('cursor: pointer')
    expect(css).toContain('.novel-writing-queue-item-ready_to_draft')
    expect(css).toContain('.novel-writing-queue-item-needs_plan')
    expect(projectWorkspace).toContain('writingQueue={writingCockpitModel.writingQueue}')
    expect(projectWorkspace).toContain('onSelectWritingQueueChapter={(chapterId) => { void selectChapterForWriting(chapterId) }}')
    expect(projectWorkspace).toContain('onRepairWritingQueuePlan={repairWritingQueuePlan}')
    expect(projectWorkspace).toContain('onRepairWritingQueuePlanBatch={repairWritingQueuePlanBatch}')
    expect(projectWorkspace).toContain("source: 'writing_queue_plan_repair'")
    expect(projectWorkspace).toContain("source: 'writing_queue_batch_plan_repair'")
  })

  test('keeps manual writing visible by collapsing auxiliary writing panels', () => {
    const component = source('WorkspaceCenter.tsx')
    const css = source('WorkspaceCenter.css')
    const projectWorkspaceCss = source('../NovelProjectWorkspace.css')

    expect(component).toContain('NOVEL_WRITING_AUX_COLLAPSED_KEY')
    expect(component).toContain('loadWritingAuxCollapsed')
    expect(component).toContain('saveWritingAuxCollapsed')
    expect(component).toContain('writingAuxCollapsed')
    expect(component).toContain('setWritingAuxCollapsed')
    expect(component).toContain('novel-writing-aux-rail')
    expect(component).toContain('novel-writing-support-stack')
    expect(component).toContain('展开辅助面板')
    expect(component).toContain('收起辅助面板')
    expect(component).toContain('辅助面板已收起，编辑器优先显示')
    expect(component).toContain('辅助面板已展开，可查看队列、交稿和任务书')
    expect(css).toContain('.novel-writing-aux-rail')
    expect(css).toContain('.novel-writing-support-stack')
    expect(css).toContain('max-height: min(34vh, 320px)')
    expect(css).toContain('overflow: auto')
    expect(css).toContain('.novel-writing-support-stack .novel-writing-queue-strip')
    expect(css).toContain('@media (max-width: 768px)')
    expect(projectWorkspaceCss).toContain('max-height: min(30vh, 300px)')
    expect(projectWorkspaceCss).toContain('max-height: min(34vh, 260px)')
    expect(projectWorkspaceCss).toContain('.novel-workspace-area-tabs')
    expect(projectWorkspaceCss).toContain('overflow-x: auto')
    expect(projectWorkspaceCss).toContain('.novel-workspace-area-tabs .ant-space-item')
    expect(projectWorkspaceCss).toContain('flex: 0 0 auto')
  })

  test('surfaces writing queue focus inside the auto creation director', () => {
    const component = source('AutoCreationDirectorWorkspace.tsx')
    const css = source('AutoCreationDirectorWorkspace.css')
    const model = source('autoCreationDirectorModel.ts')

    expect(model).toContain('writingQueueFocus')
    expect(model).toContain('buildWritingQueueFocus')
    expect(component).toContain('写作队列')
    expect(component).toContain('auto-director-writing-queue-focus')
    expect(component).toContain('model.writingQueueFocus.visible')
    expect(component).toContain('model.writingQueueFocus.badges')
    expect(component).toContain('model.writingQueueFocus.action')
    expect(css).toContain('.auto-director-writing-queue-focus')
    expect(css).toContain('.auto-director-writing-queue-focus-needs_plan')
    expect(css).toContain('.auto-director-writing-queue-focus-ready_to_draft')
    expect(css).toContain('.auto-director-writing-queue-focus-draft_generated')
  })

  test('shows a five-stage serial production rail in the auto creation director', () => {
    const component = source('AutoCreationDirectorWorkspace.tsx')
    const css = source('AutoCreationDirectorWorkspace.css')
    const model = source('autoCreationDirectorModel.ts')
    const projectWorkspace = source('../NovelProjectWorkspace.tsx')

    expect(model).toContain('serialWorkflow')
    expect(model).toContain('book_core')
    expect(model).toContain('longform_plan')
    expect(model).toContain('chapter_launch')
    expect(model).toContain('delivery_acceptance')
    expect(model).toContain('serial_governance')
    expect(component).toContain('连载生产轨道')
    expect(component).toContain('model.serialWorkflow.currentLabel')
    expect(component).toContain('auto-director-serial-rail')
    expect(component).toContain('model.serialWorkflow.stages.map')
    expect(component).toContain('onStageAction(stage.action)')
    expect(component).toContain('auto-director-serial-stage-button')
    expect(component).toContain('stage.action.label')
    expect(component).toContain('onStageAction?: (action: AutoCreationDirectorAction) => void')
    expect(projectWorkspace).toContain('onStageAction={handleAutoCreationDirectorAction}')
    expect(projectWorkspace).toContain("enter_story_planning: () => setWorkspaceArea('storyPlanning')")
    expect(model).toContain("planningAction('enter_story_planning'")
    expect(css).toContain('.auto-director-serial-rail')
    expect(css).toContain('.auto-director-serial-stage-button')
    expect(css).toContain('.auto-director-serial-stage-active')
    expect(css).toContain('.auto-director-serial-stage-blocked')
    expect(css).toContain('.auto-director-serial-stage-done')
  })

  test('shows the shared six-stage AI creation pipeline inside the auto creation director', () => {
    const component = source('AutoCreationDirectorWorkspace.tsx')
    const css = source('AutoCreationDirectorWorkspace.css')
    const model = source('autoCreationDirectorModel.ts')

    expect(model).toContain('creationPipeline')
    expect(model).toContain('buildCreationPipeline')
    expect(component).toContain('AI长篇创作流水线')
    expect(component).toContain('model.creationPipeline.summary')
    expect(component).toContain('model.creationPipeline.primaryAction')
    expect(component).toContain('model.creationPipeline.stages.map')
    expect(component).toContain('auto-director-creation-pipeline')
    expect(component).toContain('auto-director-creation-stage')
    expect(component).toContain('全书核心')
    expect(component).toContain('长线规划')
    expect(component).toContain('设定资产')
    expect(component).toContain('章节开写')
    expect(component).toContain('交稿验收')
    expect(component).toContain('连载发布')
    expect(css).toContain('.auto-director-creation-pipeline')
    expect(css).toContain('.auto-director-creation-stage')
    expect(css).toContain('.auto-director-creation-stage.is-active')
  })

  test('keeps longform governance rails inside the auto creation detail drawer', () => {
    const component = source('AutoCreationDirectorWorkspace.tsx')

    const drawerIndex = component.indexOf('auto-director-detail-drawer')
    expect(drawerIndex).toBeGreaterThan(0)
    expect(component.indexOf('auto-director-creation-pipeline')).toBeGreaterThan(drawerIndex)
    expect(component.indexOf('auto-director-battle-desk')).toBeGreaterThan(drawerIndex)
    expect(component.indexOf('auto-director-serial-rail')).toBeGreaterThan(drawerIndex)
  })

  test('guards longform canon and memory runway before safe batching', () => {
    const model = source('autoCreationDirectorModel.ts')

    expect(model).toContain('buildCanonRunway')
    expect(model).toContain('story_state_stale')
    expect(model).toContain('memory_unavailable')
    expect(model).toContain('长线记忆')
    expect(model).toContain('长线记忆待同步')
    expect(model).toContain("writingAction('update_canon'")
    expect(model).toContain("writingAction('fix_continuity'")
  })

  test('passes memory palace summary into the writing cockpit runway checks', () => {
    const projectWorkspace = source('../NovelProjectWorkspace.tsx')

    expect(projectWorkspace).toContain('memoryPalaceProjects')
    expect(projectWorkspace).toContain('/memory-palace/projects')
    expect(projectWorkspace).toContain('activeMemorySummary')
    expect(projectWorkspace).toContain('memorySummary: activeMemorySummary')
    expect(projectWorkspace).toContain('memory_count: 0')
    expect(projectWorkspace).toContain('missing: true')
  })

  test('runs story state sync automatically from writing cockpit actions', () => {
    const projectWorkspace = source('../NovelProjectWorkspace.tsx')

    expect(projectWorkspace).toContain('syncStoryStateForChapter')
    expect(projectWorkspace).toContain('/story-state-sync')
    expect(projectWorkspace).toContain("source: 'writing_cockpit_state_sync'")
    expect(projectWorkspace).toContain("case 'sync_story_state'")
    expect(projectWorkspace).toContain('void syncStoryStateForChapter')
  })

  test('uses a production guide command system instead of stacked block buttons', () => {
    const component = source('ProductionGuidePanel.tsx')
    const css = source('ProductionGuidePanel.css')

    expect(component).toContain("import './ProductionGuidePanel.css'")
    expect(component).toContain('production-guide-primary-command')
    expect(component).toContain('production-guide-secondary-command')
    expect(component).toContain('production-guide-step-status')
    expect(component).not.toContain('block\\n                      type={step.status')
    expect(css).toContain('.production-guide-secondary-command')
    expect(css).toContain('.production-guide-step-active')
  })

  test('separates the writing cockpit from delivery and collapsed workspace bars', () => {
    const component = source('WritingCockpitPanel.tsx')
    const css = source('WritingCockpitPanel.css')

    expect(component).toContain("import './WritingCockpitPanel.css'")
    expect(component).toContain('writing-cockpit-card-expanded')
    expect(component).toContain('writing-cockpit-card-collapsed')
    expect(component).toContain('writing-cockpit-subdesk')
    expect(component).toContain('writing-cockpit-command-grid')
    expect(component).toContain('核心契约')
    expect(component).toContain('mustServe')
    expect(component).toContain('不得漂移')
    expect(component).toContain('弃读预警')
    expect(component).toContain('readerDropRisk')
    expect(component).toContain('开篇防弃读')
    expect(component).toContain('中段防掉速')
    expect(component).toContain('故事压力')
    expect(component).toContain('storyPressure')
    expect(component).toContain('冲突升级')
    expect(component).toContain('赌注升级')
    expect(component).toContain('反转逼迫')
    expect(component).toContain('主角能动性')
    expect(component).toContain('storyDrive')
    expect(component).toContain('主角选择')
    expect(component).toContain('选择代价')
    expect(component).toContain('状态变化')
    expect(component).toContain('连载节奏')
    expect(component).toContain('serialRhythm')
    expect(component).toContain('回报密度')
    expect(component).toContain('开篇钩子')
    expect(component).toContain('章末追读')
    expect(component).toContain('章末翻页')
    expect(component).toContain('pageTurnHook')
    expect(component).toContain('读者问题')
    expect(component).toContain('禁提前解答')
    expect(component).toContain('卷级爆点')
    expect(component).toContain('volumeClimax')
    expect(component).toContain('本章爆点职责')
    expect(component).toContain('禁提前消费')
    expect(component).toContain('交稿风险转写作动作')
    expect(component).toContain('deliveryRiskCarryOver')
    expect(component).toContain('风险：')
    expect(component).toContain('动作：')
    expect(component).toContain('开篇修复')
    expect(component).toContain('中段推进')
    expect(component).toContain('章末追读')
    expect(css).toContain('.writing-cockpit-card-expanded')
    expect(css).toContain('.writing-cockpit-subdesk')
    expect(css).toContain('.writing-cockpit-card-collapsed')
    expect(css).toContain('.writing-cockpit-reader-drop-risk')
    expect(css).toContain('.writing-cockpit-story-pressure')
    expect(css).toContain('.writing-cockpit-story-drive')
    expect(css).toContain('.writing-cockpit-serial-rhythm')
    expect(css).toContain('.writing-cockpit-page-turn-hook')
    expect(css).toContain('.writing-cockpit-volume-climax')
    expect(css).toContain('.writing-cockpit-delivery-risk')
  })

  test('uses a reference nav rail with compact revision chips', () => {
    const component = source('ReferencePanel.tsx')
    const css = source('ReferencePanel.css')

    expect(component).toContain("import './ReferencePanel.css'")
    expect(component).toContain('novel-reference-nav-rail')
    expect(component).toContain('novel-reference-nav-item')
    expect(component).toContain('novel-reference-revision-chip')
    expect(css).toContain('.novel-reference-nav-item')
    expect(css).toContain('.novel-reference-revision-chip')
  })

  test('shows storyline workshop types and draft brief storyline section', () => {
    const settingPanel = source('SettingWorkshopPanel.tsx')
    const workspaceCenter = source('WorkspaceCenter.tsx')
    const workspaceCss = source('WorkspaceCenter.css')

    expect(settingPanel).toContain("value: 'mainline'")
    expect(settingPanel).toContain("label: '主线'")
    expect(settingPanel).toContain("value: 'subplot'")
    expect(settingPanel).toContain("value: 'character_arc'")
    expect(settingPanel).toContain("value: 'relationship_arc'")
    expect(settingPanel).toContain("value: 'faction_arc'")
    expect(settingPanel).toContain("value: 'foreshadowing_arc'")
    expect(settingPanel).toContain("value: 'advance'")
    expect(settingPanel).toContain("value: 'payoff'")
    expect(settingPanel).toContain('/storylines/suggest')
    expect(settingPanel).toContain('匹配剧情线')
    expect(workspaceCenter).toContain('剧情线推进')
    expect(workspaceCenter).toContain('必推')
    expect(workspaceCenter).toContain('埋线')
    expect(workspaceCenter).toContain('回收')
    expect(workspaceCenter).toContain('禁用')
    expect(workspaceCss).toContain('.novel-draft-brief-storylines')
  })

  test('shows character growth obligations in the chapter pre-draft brief', () => {
    const workspaceCenter = source('WorkspaceCenter.tsx')
    const workspaceCss = source('WorkspaceCenter.css')
    const model = source('writingRecommendationModel.ts')
    const service = readFileSync(join(import.meta.dir, '../../../../server/src/routes/novel-writing-service.ts'), 'utf8')

    expect(workspaceCenter).toContain('人物成长承接')
    expect(workspaceCenter).toContain('角色欲望')
    expect(workspaceCenter).toContain('缺陷受压')
    expect(workspaceCenter).toContain('成长节点')
    expect(workspaceCenter).toContain('关系变化')
    expect(workspaceCenter).toContain('禁揭')
    expect(workspaceCss).toContain('.novel-draft-brief-character-arc')
    expect(model).toContain('character_arc_brief')
    expect(model).toContain('characterArcGrowthBeat')
    expect(service).toContain('character_arc_brief')
    expect(service).toContain('【人物成长承接】')
  })

  test('shows storyline board evidence details for plan versus actual sync', () => {
    const workspaceCenter = source('StoryPlanningWorkspace.tsx')
    const model = source('planningWorkspaceModel.ts')

    expect(workspaceCenter).toContain('剧情线证据')
    expect(workspaceCenter).toContain('计划推进')
    expect(workspaceCenter).toContain('实际推进')
    expect(workspaceCenter).toContain('差异复盘')
    expect(workspaceCenter).toContain('差异决策')
    expect(workspaceCenter).toContain('回修正文')
    expect(workspaceCenter).toContain('接受为新计划')
    expect(workspaceCenter).toContain('标记误判')
    expect(workspaceCenter).toContain('novel-storyline-evidence')
    expect(model).toContain('planEvidence')
    expect(model).toContain('actualEvidence')
    expect(model).toContain('diffEvidence')
    expect(model).toContain('syncRisks')
    expect(model).toContain('latestSyncChapter')
  })

  test('shows reader retention radar in the chapter pre-draft brief', () => {
    const workspaceCenter = source('WorkspaceCenter.tsx')
    const workspaceCss = source('WorkspaceCenter.css')
    const model = source('writingRecommendationModel.ts')
    const service = readFileSync(join(import.meta.dir, '../../../../server/src/routes/novel-writing-service.ts'), 'utf8')

    expect(workspaceCenter).toContain('追读雷达')
    expect(workspaceCenter).toContain('开篇钩子')
    expect(workspaceCenter).toContain('爽点承诺')
    expect(workspaceCenter).toContain('短剧场面')
    expect(workspaceCenter).toContain('章末追读')
    expect(workspaceCss).toContain('.novel-draft-brief-retention')
    expect(model).toContain('reader_retention_brief')
    expect(model).toContain('retentionOpeningHook')
    expect(service).toContain('reader_retention_brief')
    expect(service).toContain('short_drama_scene')
  })

  test('shows story unit task in the chapter pre-draft brief', () => {
    const workspaceCenter = source('WorkspaceCenter.tsx')
    const workspaceCss = source('WorkspaceCenter.css')
    const model = source('writingRecommendationModel.ts')
    const service = readFileSync(join(import.meta.dir, '../../../../server/src/routes/novel-writing-service.ts'), 'utf8')

    expect(workspaceCenter).toContain('剧情单元任务')
    expect(workspaceCenter).toContain('当前职责')
    expect(workspaceCenter).toContain('单元目标')
    expect(workspaceCenter).toContain('禁抢跑')
    expect(workspaceCss).toContain('.novel-draft-brief-story-unit')
    expect(model).toContain('story_unit_context')
    expect(model).toContain('storyUnitRole')
    expect(service).toContain('story_unit_context')
    expect(service).toContain('【剧情单元任务】')
  })

  test('shows volume climax budget in the chapter pre-draft brief', () => {
    const workspaceCenter = source('WorkspaceCenter.tsx')
    const workspaceCss = source('WorkspaceCenter.css')
    const model = source('writingRecommendationModel.ts')
    const service = readFileSync(join(import.meta.dir, '../../../../server/src/routes/novel-writing-service.ts'), 'utf8')

    expect(workspaceCenter).toContain('卷级爆点预算')
    expect(workspaceCenter).toContain('本章爆点职责')
    expect(workspaceCenter).toContain('禁提前消费')
    expect(workspaceCss).toContain('.novel-draft-brief-volume-climax')
    expect(model).toContain('volume_climax_brief')
    expect(model).toContain('volumeClimaxRole')
    expect(service).toContain('volume_climax_brief')
    expect(service).toContain('【卷级高潮预算】')
  })

  test('shows recent fatigue avoidance in the chapter pre-draft brief', () => {
    const workspaceCenter = source('WorkspaceCenter.tsx')
    const workspaceCss = source('WorkspaceCenter.css')
    const model = source('writingRecommendationModel.ts')
    const service = readFileSync(join(import.meta.dir, '../../../../server/src/routes/novel-writing-service.ts'), 'utf8')

    expect(workspaceCenter).toContain('近10章疲劳规避')
    expect(workspaceCenter).toContain('冲突换源')
    expect(workspaceCenter).toContain('回报换形')
    expect(workspaceCenter).toContain('钩子换题')
    expect(workspaceCss).toContain('.novel-draft-brief-recent-fatigue')
    expect(model).toContain('recent_fatigue_brief')
    expect(model).toContain('recentFatigueConflict')
    expect(service).toContain('recent_fatigue_brief')
    expect(service).toContain('【近10章疲劳规避】')
  })

  test('shows strong story and reader pull execution in the chapter pre-draft brief', () => {
    const workspaceCenter = source('WorkspaceCenter.tsx')
    const workspaceCss = source('WorkspaceCenter.css')
    const model = source('writingRecommendationModel.ts')
    const service = readFileSync(join(import.meta.dir, '../../../../server/src/routes/novel-writing-service.ts'), 'utf8')

    expect(workspaceCenter).toContain('弃读预警')
    expect(workspaceCenter).toContain('强故事节奏')
    expect(workspaceCenter).toContain('主角选择')
    expect(workspaceCenter).toContain('回报密度')
    expect(workspaceCenter).toContain('章末翻页')
    expect(workspaceCss).toContain('.novel-draft-brief-reader-drop')
    expect(workspaceCss).toContain('.novel-draft-brief-story-pull')
    expect(model).toContain('reader_drop_risk_brief')
    expect(model).toContain('readerDropRisks')
    expect(model).toContain('story_drive_brief')
    expect(model).toContain('storyDriveChoice')
    expect(model).toContain('serial_rhythm_brief')
    expect(model).toContain('serialRhythmPayoffInterval')
    expect(model).toContain('page_turn_hook_brief')
    expect(model).toContain('pageTurnQuestion')
    expect(service).toContain('reader_drop_risk_brief')
    expect(service).toContain('story_drive_brief')
    expect(service).toContain('serial_rhythm_brief')
    expect(service).toContain('page_turn_hook_brief')
  })

  test('shows chapter innovation execution in the pre-draft brief', () => {
    const workspaceCenter = source('WorkspaceCenter.tsx')
    const workspaceCss = source('WorkspaceCenter.css')
    const model = source('writingRecommendationModel.ts')
    const service = readFileSync(join(import.meta.dir, '../../../../server/src/routes/novel-writing-service.ts'), 'utf8')

    expect(workspaceCenter).toContain('创新执行')
    expect(workspaceCenter).toContain('创新角度')
    expect(workspaceCenter).toContain('差异护栏')
    expect(workspaceCenter).toContain('IP化场面')
    expect(workspaceCss).toContain('.novel-draft-brief-innovation')
    expect(model).toContain('innovation_brief')
    expect(model).toContain('innovationAngle')
    expect(service).toContain('innovation_brief')
    expect(service).toContain('differentiation_guardrails')
  })

  test('shows signature scene repair in the pre-draft brief', () => {
    const workspaceCenter = source('WorkspaceCenter.tsx')
    const workspaceCss = source('WorkspaceCenter.css')
    const model = source('writingRecommendationModel.ts')
    const service = readFileSync(join(import.meta.dir, '../../../../server/src/routes/novel-writing-service.ts'), 'utf8')

    expect(workspaceCenter).toContain('强场面补位')
    expect(workspaceCenter).toContain('标志性场面')
    expect(workspaceCenter).toContain('补位目标')
    expect(workspaceCenter).toContain('服务主线')
    expect(workspaceCss).toContain('.novel-draft-brief-signature-scene')
    expect(model).toContain('signature_scene_brief')
    expect(model).toContain('signatureSceneTarget')
    expect(service).toContain('【本章标志性场面补位】')
    expect(service).toContain('signature_scene')
  })

  test('shows longform battle obligations in the pre-draft brief', () => {
    const workspaceCenter = source('WorkspaceCenter.tsx')
    const workspaceCss = source('WorkspaceCenter.css')
    const model = source('writingRecommendationModel.ts')
    const service = readFileSync(join(import.meta.dir, '../../../../server/src/routes/novel-writing-service.ts'), 'utf8')

    expect(workspaceCenter).toContain('长篇作战承接')
    expect(workspaceCenter).toContain('今日优先')
    expect(workspaceCenter).toContain('风险线')
    expect(workspaceCss).toContain('.novel-draft-brief-battle')
    expect(model).toContain('longform_battle_context')
    expect(model).toContain('longformBattleLaneRequirements')
    expect(service).toContain('longform_battle_context')
    expect(service).toContain('【长篇作战承接】')
  })

  test('shows storyline sync status in the delivery strip', () => {
    const workspaceCenter = source('WorkspaceCenter.tsx')
    const workspaceCss = source('WorkspaceCenter.css')

    expect(workspaceCenter).toContain('storylineSync')
    expect(workspaceCenter).toContain('novel-delivery-storyline-tag')
    expect(workspaceCss).toContain('.novel-delivery-storyline-tag')
    expect(workspaceCss).toContain('.novel-delivery-storyline-tag-warn')
  })

  test('shows story unit sync status in the delivery strip', () => {
    const workspaceCenter = source('WorkspaceCenter.tsx')
    const workspaceCss = source('WorkspaceCenter.css')
    const writingModel = source('writingCockpitModel.ts')
    const recommendationModel = source('writingRecommendationModel.ts')
    const service = readFileSync(join(import.meta.dir, '../../../../server/src/routes/novel-writing-service.ts'), 'utf8')

    expect(workspaceCenter).toContain('storyUnitSync')
    expect(workspaceCenter).toContain('novel-delivery-story-unit-tag')
    expect(workspaceCss).toContain('.novel-delivery-story-unit-tag')
    expect(workspaceCss).toContain('.novel-delivery-story-unit-tag-warn')
    expect(writingModel).toContain('story_unit_sync')
    expect(recommendationModel).toContain('storyUnitSync')
    expect(service).toContain("review_type: 'story_unit_sync'")
  })

  test('shows chapter core drift status in the delivery strip', () => {
    const workspaceCenter = source('WorkspaceCenter.tsx')
    const workspaceCss = source('WorkspaceCenter.css')
    const model = source('writingCockpitModel.ts')
    const service = readFileSync(join(import.meta.dir, '../../../../server/src/routes/novel-writing-service.ts'), 'utf8')

    expect(workspaceCenter).toContain('coreDrift')
    expect(workspaceCenter).toContain('novel-delivery-core-drift-tag')
    expect(workspaceCss).toContain('.novel-delivery-core-drift-tag')
    expect(workspaceCss).toContain('.novel-delivery-core-drift-tag-warn')
    expect(model).toContain('chapter_core_drift')
    expect(service).toContain("review_type: 'chapter_core_drift'")
  })

  test('shows reader payoff sync status in the delivery strip', () => {
    const workspaceCenter = source('WorkspaceCenter.tsx')
    const workspaceCss = source('WorkspaceCenter.css')
    const model = source('writingCockpitModel.ts')
    const service = readFileSync(join(import.meta.dir, '../../../../server/src/routes/novel-writing-service.ts'), 'utf8')

    expect(workspaceCenter).toContain('readerPayoffSync')
    expect(workspaceCenter).toContain('novel-delivery-payoff-tag')
    expect(workspaceCss).toContain('.novel-delivery-payoff-tag')
    expect(workspaceCss).toContain('.novel-delivery-payoff-tag-warn')
    expect(model).toContain('reader_payoff_sync')
    expect(service).toContain("review_type: 'reader_payoff_sync'")
  })

  test('shows reader retention sync status in the delivery strip', () => {
    const workspaceCenter = source('WorkspaceCenter.tsx')
    const workspaceCss = source('WorkspaceCenter.css')
    const model = source('writingCockpitModel.ts')
    const recommendationModel = source('writingRecommendationModel.ts')
    const service = readFileSync(join(import.meta.dir, '../../../../server/src/routes/novel-writing-service.ts'), 'utf8')

    expect(workspaceCenter).toContain('readerRetentionSync')
    expect(workspaceCenter).toContain('novel-delivery-retention-tag')
    expect(workspaceCenter).toContain('chapterAttraction')
    expect(workspaceCenter).toContain('novel-delivery-attraction-tag')
    expect(workspaceCenter).toContain('first30RetentionRecheck')
    expect(workspaceCenter).toContain('novel-delivery-first30-tag')
    expect(workspaceCss).toContain('.novel-delivery-retention-tag')
    expect(workspaceCss).toContain('.novel-delivery-retention-tag-warn')
    expect(workspaceCss).toContain('.novel-delivery-attraction-tag')
    expect(workspaceCss).toContain('.novel-delivery-first30-tag')
    expect(model).toContain('reader_retention_sync')
    expect(model).toContain('buildReaderRetentionSyncSummary')
    expect(model).toContain('chapter_attraction_review')
    expect(model).toContain('buildChapterAttractionSummary')
    expect(model).toContain('buildFirst30RetentionRecheckSummary')
    expect(recommendationModel).toContain('readerRetentionSync')
    expect(recommendationModel).toContain('chapterAttraction')
    expect(recommendationModel).toContain('first30RetentionRecheck')
    expect(service).toContain("review_type: 'reader_retention_sync'")
    expect(service).toContain("review_type: 'chapter_attraction_review'")
    expect(service).toContain('buildChapterAttractionReviewReport(project, chapter, contextPackage, chapterText)')
  })

  test('shows reader expectation ledger in draft brief and delivery strip', () => {
    const workspaceCenter = source('WorkspaceCenter.tsx')
    const workspaceCss = source('WorkspaceCenter.css')
    const model = source('writingCockpitModel.ts')
    const recommendationModel = source('writingRecommendationModel.ts')
    const service = readFileSync(join(import.meta.dir, '../../../../server/src/routes/novel-writing-service.ts'), 'utf8')

    expect(workspaceCenter).toContain('读者期待账本')
    expect(workspaceCenter).toContain('readerExpectationSync')
    expect(workspaceCenter).toContain('novel-delivery-expectation-tag')
    expect(workspaceCenter).toContain('novel-draft-brief-expectations')
    expect(workspaceCss).toContain('.novel-delivery-expectation-tag')
    expect(workspaceCss).toContain('.novel-delivery-expectation-tag-warn')
    expect(workspaceCss).toContain('.novel-draft-brief-expectations')
    expect(model).toContain('reader_expectation_sync')
    expect(model).toContain('buildReaderExpectationSyncSummary')
    expect(recommendationModel).toContain('reader_expectation_ledger')
    expect(recommendationModel).toContain('expectationMustDeliver')
    expect(service).toContain("review_type: 'reader_expectation_sync'")
    expect(service).toContain('reader_expectation_ledger')
  })

  test('shows reader expectation debt carry-over in the draft brief', () => {
    const workspaceCenter = source('WorkspaceCenter.tsx')
    const workspaceCss = source('WorkspaceCenter.css')
    const recommendationModel = source('writingRecommendationModel.ts')
    const repairPrompt = source('repairTaskRevisionPrompt.ts')
    const service = readFileSync(join(import.meta.dir, '../../../../server/src/routes/novel-writing-service.ts'), 'utf8')

    expect(workspaceCenter).toContain('期待债务承接')
    expect(workspaceCenter).toContain('上一章承接')
    expect(workspaceCenter).toContain('交稿风险承接')
    expect(workspaceCenter).toContain('novel-draft-brief-expectation-debt')
    expect(workspaceCenter).toContain('novel-draft-brief-handoff')
    expect(workspaceCenter).toContain('novel-draft-brief-delivery-risk')
    expect(workspaceCenter).toContain('handoffPreviousEnding')
    expect(workspaceCenter).toContain('handoffOpeningObligation')
    expect(workspaceCenter).toContain('deliveryRiskItems')
    expect(workspaceCenter).toContain('expectationDebtMustCarry')
    expect(workspaceCenter).toContain('expectationDebtKeepAlive')
    expect(workspaceCenter).toContain('expectationDebtOverdue')
    expect(workspaceCenter).toContain('逾期优先')
    expect(workspaceCss).toContain('.novel-draft-brief-expectation-debt')
    expect(workspaceCss).toContain('.novel-draft-brief-handoff')
    expect(workspaceCss).toContain('.novel-draft-brief-delivery-risk')
    expect(recommendationModel).toContain('reader_expectation_debt')
    expect(recommendationModel).toContain('delivery_risk_carry_over')
    expect(recommendationModel).toContain('deliveryRiskItems')
    expect(recommendationModel).toContain('expectationCarryOver')
    expect(recommendationModel).toContain('expectationDebtOverdue')
    expect(recommendationModel).toContain('expectationDebtSummary')
    expect(recommendationModel).toContain('handoffPreviousEnding')
    expect(recommendationModel).toContain('handoffOpeningObligation')
    expect(service).toContain('buildReaderExpectationDebtContext')
    expect(service).toContain('buildDeliveryRiskCarryOverContext')
    expect(service).toContain('delivery_risk_carry_over')
    expect(service).toContain('reader_expectation_debt_context')
    expect(repairPrompt).toContain('【开篇承接修复】')
    expect(repairPrompt).toContain('重写或补写本章前 300-500 字')
  })

  test('shows chapter handoff between delivery and next draft brief', () => {
    const workspaceCenter = source('WorkspaceCenter.tsx')
    const workspaceCss = source('WorkspaceCenter.css')
    const cockpitModel = source('writingCockpitModel.ts')

    expect(cockpitModel).toContain('chapterHandoffDesk')
    expect(cockpitModel).toContain('buildChapterHandoffDesk')
    expect(workspaceCenter).toContain('chapterHandoffDesk')
    expect(workspaceCenter).toContain('章节交接单')
    expect(workspaceCenter).toContain('novel-chapter-handoff-strip')
    expect(workspaceCenter).toContain('上一章钩子')
    expect(workspaceCenter).toContain('期待承接')
    expect(workspaceCenter).toContain('下一章开场')
    expect(workspaceCenter).toContain('交稿风险')
    expect(workspaceCenter).toContain('deliveryRiskCarryOver')
    expect(workspaceCss).toContain('.novel-chapter-handoff-strip')
    expect(workspaceCss).toContain('.novel-chapter-handoff-strip-ready')
    expect(workspaceCss).toContain('.novel-chapter-handoff-strip-needs_delivery')
    expect(cockpitModel).toContain('deliveryRiskCarryOver')
  })

  test('shows million word runway gate in the auto creation director', () => {
    const workspace = source('AutoCreationDirectorWorkspace.tsx')
    const workspaceCss = source('AutoCreationDirectorWorkspace.css')
    const model = source('autoCreationDirectorModel.ts')
    const projectWorkspace = readFileSync(join(import.meta.dir, '../NovelProjectWorkspace.tsx'), 'utf8')
    const workspaceCenter = source('WorkspaceCenter.tsx')
    const workspaceCenterCss = source('WorkspaceCenter.css')
    const cockpitModel = source('writingCockpitModel.ts')
    const recommendationModel = source('writingRecommendationModel.ts')
    const service = readFileSync(join(import.meta.dir, '../../../../server/src/routes/novel-writing-service.ts'), 'utf8')

    expect(workspace).toContain('百万字航线守门')
    expect(workspace).toContain('millionWordRunway')
    expect(workspace).toContain('auto-director-runway-panel')
    expect(workspaceCss).toContain('.auto-director-runway-panel')
    expect(workspaceCss).toContain('.auto-director-runway-gates')
    expect(model).toContain('AutoCreationMillionWordRunway')
    expect(model).toContain('buildMillionWordRunway')
    expect(model).toContain('fourQuestions')
    expect(projectWorkspace).toContain('millionWordRunway?: any')
    expect(projectWorkspace).toContain('million_word_runway: options?.millionWordRunway')
    expect(projectWorkspace).toContain('million_word_runway: autoCreationDirectorModel.millionWordRunway')
    expect(projectWorkspace).toContain('millionWordRunway: autoCreationDirectorModel.millionWordRunway')
    expect(workspaceCenter).toContain('runwaySync')
    expect(workspaceCenter).toContain('novel-delivery-runway-tag')
    expect(workspaceCenterCss).toContain('.novel-delivery-runway-tag')
    expect(cockpitModel).toContain('runway_sync')
    expect(cockpitModel).toContain('buildRunwaySyncSummary')
    expect(cockpitModel).toContain('补航线')
    expect(recommendationModel).toContain('runwaySync')
    expect(service).toContain("review_type: 'runway_sync'")
  })

  test('shows innovation sync status in the delivery strip and risk queue', () => {
    const workspaceCenter = source('WorkspaceCenter.tsx')
    const workspaceCss = source('WorkspaceCenter.css')
    const model = source('writingCockpitModel.ts')
    const recommendationModel = source('writingRecommendationModel.ts')
    const service = readFileSync(join(import.meta.dir, '../../../../server/src/routes/novel-writing-service.ts'), 'utf8')

    expect(workspaceCenter).toContain('innovationSync')
    expect(workspaceCenter).toContain('novel-delivery-innovation-tag')
    expect(workspaceCss).toContain('.novel-delivery-innovation-tag')
    expect(workspaceCss).toContain('.novel-delivery-innovation-tag-warn')
    expect(model).toContain('innovation_sync')
    expect(model).toContain('补创新')
    expect(recommendationModel).toContain('innovationSync')
    expect(service).toContain("review_type: 'innovation_sync'")
  })

  test('shows aggregated delivery risk queue in the delivery strip', () => {
    const workspaceCenter = source('WorkspaceCenter.tsx')
    const workspaceCss = source('WorkspaceCenter.css')
    const model = source('writingCockpitModel.ts')
    const recommendationModel = source('writingRecommendationModel.ts')
    const reviewAnnotations = source('ReviewAnnotationsDrawer.tsx')
    const workspace = readFileSync(join(import.meta.dir, '../NovelProjectWorkspace.tsx'), 'utf8')

    expect(workspaceCenter).toContain('deliveryRiskQueue')
    expect(workspaceCenter).toContain('novel-delivery-risk-tag')
    expect(workspaceCss).toContain('.novel-delivery-risk-tag')
    expect(workspaceCss).toContain('.novel-delivery-risk-tag-warn')
    expect(model).toContain('buildDeliveryRiskQueue')
    expect(recommendationModel).toContain('deliveryRiskQueue')
    expect(reviewAnnotations).toContain('交稿风险')
    expect(reviewAnnotations).toContain('DELIVERY_RISK_ANNOTATION_SOURCES')
    expect(reviewAnnotations).toContain('按风险修订')
    expect(reviewAnnotations).toContain('review_type: item.source')
    expect(reviewAnnotations).toContain('targetChapterId: Number(item.chapter_id)')
    expect(reviewAnnotations).toContain('onSelectChapter(Number(item.chapter_id))')
    expect(reviewAnnotations).toContain('categoryFilter')
    expect(reviewAnnotations).toContain('全部类别')
    expect(reviewAnnotations).toContain("value: 'delivery_core'")
    expect(reviewAnnotations).toContain("value: 'reader_expectation'")
    expect(reviewAnnotations).toContain("value: 'reader_retention'")
    expect(reviewAnnotations).toContain("value: 'chapter_attraction'")
    expect(reviewAnnotations).toContain("value: 'story_drive'")
    expect(reviewAnnotations).toContain("value: 'character_arc'")
    expect(reviewAnnotations).toContain("value: 'style_sample'")
    expect(reviewAnnotations).toContain("value: 'innovation'")
    expect(reviewAnnotations).toContain("value: 'storyline'")
    expect(workspace).toContain('按交稿风险生成修订稿')
    expect(workspace).toContain('reader_expectation_sync')
    expect(workspace).toContain('chapter_attraction_review')
    expect(workspace).toContain('story_drive_sync')
    expect(workspace).toContain('character_arc_sync')
    expect(workspace).toContain('style_sample_sync')
  })

  test('shows unresolved delivery risk fuse in the auto creation director', () => {
    const director = source('AutoCreationDirectorWorkspace.tsx')
    const directorCss = source('AutoCreationDirectorWorkspace.css')
    const directorModel = source('autoCreationDirectorModel.ts')
    const projectWorkspace = readFileSync(join(import.meta.dir, '../NovelProjectWorkspace.tsx'), 'utf8')

    expect(directorModel).toContain('deliveryRiskGate')
    expect(directorModel).toContain('未清交稿风险')
    expect(directorModel).toContain('review_annotation_status')
    expect(directorModel).toContain('signature_scene_sync')
    expect(directorModel).toContain('强场面')
    expect(directorModel).toContain('recentlyResolved')
    expect(director).toContain('auto-director-risk-fuse')
    expect(director).toContain('auto-director-risk-cleared')
    expect(director).toContain('交稿风险熔断')
    expect(director).toContain('交稿风险已清')
    expect(director).toContain('create_delivery_risk_repair')
    expect(director).toContain('model.deliveryRiskGate.categories')
    expect(director).toContain('model.deliveryRiskGate.recentlyResolved')
    expect(directorCss).toContain('.auto-director-risk-fuse')
    expect(directorCss).toContain('.auto-director-risk-fuse-block')
    expect(directorCss).toContain('.auto-director-risk-cleared')
    expect(projectWorkspace).toContain('createDeliveryRiskRepairQueue')
    expect(projectWorkspace).toContain('/review-annotations/repair-queue')
    expect(projectWorkspace).toContain('buildDeliveryRiskRevisionClosurePlan')
    expect(projectWorkspace).toContain('closeRepairTaskAfterRevision')
    expect(projectWorkspace).toContain('recheckRepairTaskConvergence')
    expect(projectWorkspace).toContain('/story-state-sync')
    expect(projectWorkspace).toContain('/review-annotations/status')
    expect(projectWorkspace).toContain('sourceTaskIndex')
    const taskCenter = source('TaskCenterDrawer.tsx')
    expect(taskCenter).toContain('交稿风险修复任务')
    expect(taskCenter).toContain('按风险修订')
    expect(taskCenter).toContain('onStartRepairTaskRevision?.(task, run, taskIndex)')
    expect(taskCenter).toContain('复检收敛')
    expect(taskCenter).toContain('onRecheckRepairTask(item.task, item.run, item.taskIndex)')
    expect(taskCenter).toContain('核心偏移')
    expect(taskCenter).toContain('追读')
    expect(taskCenter).toContain('回报欠账')
    expect(taskCenter).toContain('剧情线')
    expect(taskCenter).toContain('强场面')
    expect(taskCenter).toContain('可读性')
  })

  test('shows delivery risk convergence in the delivery strip', () => {
    const workspaceCenter = source('WorkspaceCenter.tsx')
    const workspaceCss = source('WorkspaceCenter.css')
    const model = source('writingCockpitModel.ts')
    const recommendationModel = source('writingRecommendationModel.ts')
    const editorRoutes = readFileSync(join(import.meta.dir, '../../../../server/src/routes/novel-editor-routes.ts'), 'utf8')

    expect(workspaceCenter).toContain('deliveryRiskConvergence')
    expect(workspaceCenter).toContain('novel-delivery-convergence-tag')
    expect(workspaceCss).toContain('.novel-delivery-convergence-tag')
    expect(model).toContain('delivery_risk_convergence')
    expect(model).toContain('buildDeliveryRiskConvergenceSummary')
    expect(recommendationModel).toContain('deliveryRiskConvergence')
    expect(editorRoutes).toContain("review_type: 'delivery_risk_convergence'")
  })

  test('shows discovered asset intake in delivery strip and setting workshop', () => {
    const workspaceCenter = source('WorkspaceCenter.tsx')
    const workspaceCss = source('WorkspaceCenter.css')
    const settingPanel = source('SettingWorkshopPanel.tsx')
    const projectWorkspace = readFileSync(join(import.meta.dir, '../NovelProjectWorkspace.tsx'), 'utf8')

    expect(workspaceCenter).toContain('assetIntake')
    expect(workspaceCenter).toContain('novel-delivery-asset-tag')
    expect(workspaceCenter).toContain('onOpenStoryAssets')
    expect(workspaceCss).toContain('.novel-delivery-asset-tag')
    expect(settingPanel).toContain('新资产候选')
    expect(settingPanel).toContain('focusDiscoveredAssetsToken')
    expect(settingPanel).toContain('setting-workshop-model-command')
    expect(settingPanel).toContain('actionLoadingKey')
    expect(settingPanel).toContain('isActionLoading')
    expect(settingPanel).toContain('/discovered-assets/apply')
    expect(settingPanel).toContain('selectedDiscoveredAssetKeys')
    expect(settingPanel).toContain('assetDispositionDrafts')
    expect(settingPanel).toContain("value: 'rename'")
    expect(settingPanel).toContain("value: 'merge'")
    expect(settingPanel).toContain("value: 'cameo'")
    expect(settingPanel).toContain('改名入库')
    expect(settingPanel).toContain('合并已有')
    expect(settingPanel).toContain('一次性过场')
    expect(settingPanel).toContain('merge_target_id')
    expect(settingPanel).toContain('target_name')
    expect(settingPanel).not.toContain('loading={saving}')
    expect(projectWorkspace).toContain('设定资产')
    expect(projectWorkspace).toContain('StoryAssetsWorkspace')
    expect(projectWorkspace).toContain('focusDiscoveredAssetsToken')
  })

  test('shows IP scene intake in delivery strip after story state sync', () => {
    const workspaceCenter = source('WorkspaceCenter.tsx')
    const workspaceCss = source('WorkspaceCenter.css')
    const writingModel = source('writingCockpitModel.ts')
    const recommendationModel = source('writingRecommendationModel.ts')
    const service = readFileSync(join(import.meta.dir, '../../../../server/src/routes/novel-writing-service.ts'), 'utf8')

    expect(workspaceCenter).toContain('ipSceneIntake')
    expect(workspaceCenter).toContain('novel-delivery-ip-scene-tag')
    expect(workspaceCenter).toContain('ipSceneIntakeTooltip')
    expect(workspaceCenter).toContain('visualHook')
    expect(workspaceCenter).toContain('adaptationValue')
    expect(workspaceCss).toContain('.novel-delivery-ip-scene-tag')
    expect(writingModel).toContain('ip_scene_intake')
    expect(writingModel).toContain('buildIpSceneIntakeSummary')
    expect(recommendationModel).toContain('ipSceneIntake')
    expect(service).toContain("review_type: 'ip_scene_intake'")
  })

  test('shows signature scene sync in delivery strip and risk queue', () => {
    const workspaceCenter = source('WorkspaceCenter.tsx')
    const workspaceCss = source('WorkspaceCenter.css')
    const writingModel = source('writingCockpitModel.ts')
    const recommendationModel = source('writingRecommendationModel.ts')
    const service = readFileSync(join(import.meta.dir, '../../../../server/src/routes/novel-writing-service.ts'), 'utf8')

    expect(workspaceCenter).toContain('signatureSceneSync')
    expect(workspaceCenter).toContain('novel-delivery-signature-scene-tag')
    expect(workspaceCss).toContain('.novel-delivery-signature-scene-tag')
    expect(workspaceCss).toContain('.novel-delivery-signature-scene-tag-warn')
    expect(writingModel).toContain('signature_scene_sync')
    expect(writingModel).toContain('补强场面')
    expect(recommendationModel).toContain('signatureSceneSync')
    expect(service).toContain("review_type: 'signature_scene_sync'")
  })

  test('shows readability and restrained meme strategy in writing workflow', () => {
    const workspaceCenter = source('WorkspaceCenter.tsx')
    const workspaceCss = source('WorkspaceCenter.css')
    const projectWorkspace = readFileSync(join(import.meta.dir, '../NovelProjectWorkspace.tsx'), 'utf8')

    expect(workspaceCenter).toContain('readabilityReview')
    expect(workspaceCenter).toContain('novel-delivery-readability-tag')
    expect(workspaceCenter).toContain('本章网感策略')
    expect(workspaceCenter).toContain('novel-draft-brief-meme')
    expect(workspaceCenter).toContain('本章风格样章')
    expect(workspaceCenter).toContain('命中：')
    expect(workspaceCenter).toContain('styleSampleReasons')
    expect(workspaceCenter).toContain('styleSampleControlState')
    expect(workspaceCenter).toContain('锁定样章')
    expect(workspaceCenter).toContain('换一组')
    expect(workspaceCenter).toContain('不用样章')
    expect(workspaceCenter).toContain('onLockStyleSamples')
    expect(workspaceCenter).toContain('onReplaceStyleSamples')
    expect(workspaceCenter).toContain('onDisableStyleSamples')
    expect(projectWorkspace).toContain('/pre-draft-brief/style-samples')
    expect(workspaceCenter).toContain('novel-draft-brief-style-samples')
    expect(workspaceCss).toContain('.novel-draft-brief-style-actions')
    expect(workspaceCenter).toContain('本章质量基准')
    expect(workspaceCenter).toContain('novel-draft-brief-benchmark-samples')
    expect(workspaceCenter).toContain('chapterBenchmarkKeys')
    expect(workspaceCenter).toContain('chapterBenchmarkSync')
    expect(workspaceCenter).toContain('novel-delivery-benchmark-tag')
    expect(workspaceCenter).toContain('storyDriveSync')
    expect(workspaceCenter).toContain('novel-delivery-story-drive-tag')
    expect(workspaceCenter).toContain('characterArcSync')
    expect(workspaceCenter).toContain('novel-delivery-character-arc-tag')
    expect(workspaceCenter).toContain('styleSampleSync')
    expect(workspaceCenter).toContain('novel-delivery-style-sample-tag')
    expect(workspaceCenter).toContain('前30章留存修复')
    expect(workspaceCenter).toContain('novel-draft-brief-first30')
    expect(workspaceCenter).toContain('本批连载任务')
    expect(workspaceCenter).toContain('novel-draft-brief-batch')
    expect(workspaceCss).toContain('.novel-delivery-readability-tag')
    expect(workspaceCss).toContain('.novel-draft-brief-meme')
    expect(workspaceCss).toContain('.novel-draft-brief-style-samples')
    expect(workspaceCss).toContain('.novel-draft-brief-benchmark-samples')
    expect(workspaceCss).toContain('.novel-delivery-benchmark-tag')
    expect(workspaceCss).toContain('.novel-delivery-story-drive-tag')
    expect(workspaceCss).toContain('.novel-delivery-character-arc-tag')
    expect(workspaceCss).toContain('.novel-delivery-style-sample-tag')
    expect(workspaceCss).toContain('.novel-draft-brief-first30')
    expect(workspaceCss).toContain('.novel-draft-brief-batch')
    expect(projectWorkspace).toContain('网感素材池')
    expect(projectWorkspace).toContain('meme_bank')
    expect(projectWorkspace).toContain('风格样章库 JSON')
    expect(projectWorkspace).toContain('style_sample_bank')
    expect(projectWorkspace).toContain('填入默认风格样本库')
    expect(projectWorkspace).toContain('从高分章节提炼样本候选')
    expect(projectWorkspace).toContain('/writing-bible/style-sample-candidates')
    expect(projectWorkspace).toContain('/writing-bible/style-sample-effectiveness')
    expect(projectWorkspace).toContain('styleSampleEffectiveness')
    expect(projectWorkspace).toContain('样章效果回收')
    expect(projectWorkspace).toContain('命中率')
    expect(projectWorkspace).toContain('表现稳定')
    expect(projectWorkspace).toContain('需复盘')
    expect(projectWorkspace).toContain('调整建议')
    expect(projectWorkspace).toContain('adjustment_suggestion')
    expect(projectWorkspace).toContain('补禁抄短语')
    expect(projectWorkspace).toContain('previewStyleSampleAdjustmentPatch')
    expect(projectWorkspace).toContain('/writing-bible/style-sample-adjustment')
    expect(projectWorkspace).toContain('dry_run')
    expect(projectWorkspace).toContain('样章补丁预览')
    expect(projectWorkspace).toContain('应用补丁')
    expect(projectWorkspace).toContain('patch_json')
    expect(projectWorkspace).toContain('previewStyleSampleAdjustmentBatch')
    expect(projectWorkspace).toContain('/writing-bible/style-sample-adjustments')
    expect(projectWorkspace).toContain('样章批量补丁预览')
    expect(projectWorkspace).toContain('应用全部补丁')
    expect(projectWorkspace).toContain('style_sample_patch_batch')
    expect(projectWorkspace).toContain('undoStyleSampleAdjustmentPatch')
    expect(projectWorkspace).toContain('/writing-bible/style-sample-adjustments/undo')
    expect(projectWorkspace).toContain('撤销上次补丁')
    expect(projectWorkspace).toContain('样章补丁已撤销')
    expect(projectWorkspace).toContain('reviewStyleSampleAdjustmentPatch')
    expect(projectWorkspace).toContain('/writing-bible/style-sample-adjustments/post-apply-review')
    expect(projectWorkspace).toContain('应用后复检')
    expect(projectWorkspace).toContain('样章补丁复检')
    expect(projectWorkspace).toContain('style_sample_patch_review')
    expect(projectWorkspace).toContain('repairStyleSamplePatchReviewSelection')
    expect(projectWorkspace).toContain('换样章并重审任务书')
    expect(projectWorkspace).toContain('recommended_repair_action')
    expect(projectWorkspace).toContain('只学习抽象策略，不复制样章原句')
    expect(projectWorkspace).toContain('applicable_scenes')
    expect(projectWorkspace).toContain('avoid_scenes')
    expect(projectWorkspace).toContain('mergeCommercialWebNovelStyleSampleDefaults')
    expect(projectWorkspace).toContain('章节质量基准样例库 JSON')
    expect(projectWorkspace).toContain('chapter_benchmark_sample_bank')

    const cockpitModel = source('writingCockpitModel.ts')
    const recommendationModel = source('writingRecommendationModel.ts')
    const service = readFileSync(join(import.meta.dir, '../../../../server/src/routes/novel-writing-service.ts'), 'utf8')
    expect(cockpitModel).toContain('buildChapterBenchmarkSyncSummary')
    expect(cockpitModel).toContain('chapter_benchmark_sync')
    expect(cockpitModel).toContain('buildStoryDriveSyncSummary')
    expect(cockpitModel).toContain('story_drive_sync')
    expect(cockpitModel).toContain('buildCharacterArcSyncSummary')
    expect(cockpitModel).toContain('character_arc_sync')
    expect(cockpitModel).toContain('buildStyleSampleSyncSummary')
    expect(cockpitModel).toContain('style_sample_sync')
    expect(recommendationModel).toContain('chapterBenchmarkSync')
    expect(recommendationModel).toContain('storyDriveSync')
    expect(recommendationModel).toContain('characterArcSync')
    expect(recommendationModel).toContain('styleSampleSync')
    expect(service).toContain("review_type: 'chapter_benchmark_sync'")
    expect(service).toContain("review_type: 'story_drive_sync'")
    expect(service).toContain("review_type: 'character_arc_sync'")
    expect(service).toContain("review_type: 'style_sample_sync'")
  })

  test('shows first30 retention curve as a story planning workflow', () => {
    const planningWorkspace = source('StoryPlanningWorkspace.tsx')
    const planningModel = source('planningWorkspaceModel.ts')
    const projectWorkspace = readFileSync(join(import.meta.dir, '../NovelProjectWorkspace.tsx'), 'utf8')
    const taskCenter = source('TaskCenterDrawer.tsx')

    expect(planningWorkspace).toContain('前30章留存曲线')
    expect(planningWorkspace).toContain('novel-first30-retention-card')
    expect(planningWorkspace).toContain('运行前30章诊断')
    expect(planningWorkspace).toContain('生成修复任务')
    expect(planningWorkspace).toContain('开篇三章')
    expect(planningWorkspace).toContain('试读十章')
    expect(planningWorkspace).toContain('付费前蓄势')
    expect(planningModel).toContain('first30Retention')
    expect(planningModel).toContain('run_first30_retention')
    expect(planningModel).toContain('create_first30_repair')
    expect(projectWorkspace).toContain('run_first30_retention')
    expect(projectWorkspace).toContain('create_first30_repair')
  })

  test('shows storyline board as a story planning workflow', () => {
    const planningWorkspace = source('StoryPlanningWorkspace.tsx')
    const planningModel = source('planningWorkspaceModel.ts')
    const projectWorkspace = readFileSync(join(import.meta.dir, '../NovelProjectWorkspace.tsx'), 'utf8')
    const taskCenter = source('TaskCenterDrawer.tsx')

    expect(planningWorkspace).toContain('剧情线看板')
    expect(planningWorkspace).toContain('novel-storyline-board-card')
    expect(planningWorkspace).toContain('逾期未推')
    expect(planningWorkspace).toContain('回收债务')
    expect(planningWorkspace).toContain('影响留存')
    expect(planningWorkspace).toContain('record_storyline_diff_decision')
    expect(planningWorkspace).toContain('recommendedDecision')
    expect(planningWorkspace).toContain('decisionKey')
    expect(planningModel).toContain('storylineBoard')
    expect(planningModel).toContain('settingEntities')
    expect(planningModel).toContain('accept_as_plan')
    expect(planningModel).toContain('false_positive')
    expect(projectWorkspace).toContain('projectSettings')
    expect(projectWorkspace).toContain('record_storyline_diff_decision')
    expect(projectWorkspace).toContain('/storyline-diff-decisions')
    expect(projectWorkspace).toContain('create_storyline_decision_tasks')
    expect(projectWorkspace).toContain('/storyline-diff-decisions/repair-queue')
    expect(projectWorkspace).toContain("source: 'storyline_decision_recheck'")
    expect(projectWorkspace).toContain('storyline_decision_closure')
    expect(planningWorkspace).toContain('生成决策任务')
    expect(taskCenter).toContain('storyline_diff_decision')
    expect(taskCenter).toContain('剧情线决策')
    expect(taskCenter).toContain('同步计划')
    expect(taskCenter).toContain('复检收敛')
  })

  test('shows serial governance hub in the story planning workflow', () => {
    const planningWorkspace = source('StoryPlanningWorkspace.tsx')
    const planningModel = source('planningWorkspaceModel.ts')
    const projectWorkspace = readFileSync(join(import.meta.dir, '../NovelProjectWorkspace.tsx'), 'utf8')

    expect(planningWorkspace).toContain('连载治理中枢')
    expect(planningWorkspace).toContain('novel-governance-hub-card')
    expect(planningWorkspace).toContain('model.governanceHub.primaryAction')
    expect(planningWorkspace).toContain('model.governanceHub.checkpoints')
    expect(planningWorkspace).toContain('生成风险修复任务')
    expect(planningWorkspace).toContain('打开任务中心')
    expect(planningWorkspace).toContain('交稿风险')
    expect(planningWorkspace).toContain('新资产')
    expect(planningModel).toContain('governanceHub')
    expect(planningModel).toContain('create_delivery_risk_repair')
    expect(planningModel).toContain('open_task_center')
    expect(projectWorkspace).toContain('create_delivery_risk_repair')
    expect(projectWorkspace).toContain('createDeliveryRiskRepairQueue')
    expect(projectWorkspace).toContain('open_task_center')
    expect(projectWorkspace).toContain('setTaskCenterOpen(true)')
    expect(projectWorkspace.indexOf('useWorkspaceTasks({')).toBeLessThan(projectWorkspace.indexOf('buildPlanningWorkspaceModel({'))
    expect(projectWorkspace).toContain("workspaceArea === 'storyPlanning'")
    expect(projectWorkspace).toContain('void loadProductionTasks()')
  })

  test('shows longform battle desk as the first daily planning decision surface', () => {
    const planningWorkspace = source('StoryPlanningWorkspace.tsx')
    const planningModel = source('planningWorkspaceModel.ts')

    expect(planningWorkspace).toContain('长篇作战台')
    expect(planningWorkspace).toContain('novel-longform-battle-desk-card')
    expect(planningWorkspace).toContain('model.longformBattleDesk.primaryAction')
    expect(planningWorkspace).toContain('model.longformBattleDesk.lanes')
    expect(planningWorkspace).toContain('核心守恒')
    expect(planningWorkspace).toContain('读者拉力')
    expect(planningWorkspace).toContain('剧情线调度')
    expect(planningWorkspace).toContain('卷级爆点')
    expect(planningWorkspace).toContain('创新/IP场面')
    expect(planningWorkspace).toContain('生产燃料')
    expect(planningModel).toContain('longformBattleDesk')
    expect(planningModel).toContain('buildLongformBattleDeskModel')
  })

  test('shows an AI longform creation pipeline as the top story planning navigator', () => {
    const planningWorkspace = source('StoryPlanningWorkspace.tsx')
    const planningModel = source('planningWorkspaceModel.ts')

    expect(planningWorkspace).toContain('AI长篇创作流水线')
    expect(planningWorkspace).toContain('novel-creation-pipeline-card')
    expect(planningWorkspace).toContain('model.creationPipeline.stages')
    expect(planningWorkspace).toContain('model.creationPipeline.primaryAction')
    expect(planningWorkspace).toContain('全书核心')
    expect(planningWorkspace).toContain('长线规划')
    expect(planningWorkspace).toContain('设定资产')
    expect(planningWorkspace).toContain('章节开写')
    expect(planningWorkspace).toContain('交稿验收')
    expect(planningWorkspace).toContain('连载发布')
    expect(planningWorkspace).toContain('当前建议')
    expect(planningModel).toContain('creationPipeline')
    expect(planningModel).toContain('buildCreationPipelineModel')
    expect(planningModel).toContain('book_core')
    expect(planningModel).toContain('serial_release')
  })

  test('shows serial release desk in the story planning workflow', () => {
    const planningWorkspace = source('StoryPlanningWorkspace.tsx')
    const planningModel = source('planningWorkspaceModel.ts')

    expect(planningWorkspace).toContain('连载发布节奏台')
    expect(planningWorkspace).toContain('novel-serial-release-desk-card')
    expect(planningWorkspace).toContain('model.serialReleaseDesk.primaryAction')
    expect(planningWorkspace).toContain('model.serialReleaseDesk.releaseWindow')
    expect(planningWorkspace).toContain('发布窗口')
    expect(planningWorkspace).toContain('存稿安全线')
    expect(planningWorkspace).toContain('可发布存稿')
    expect(planningWorkspace).toContain('待修订')
    expect(planningWorkspace).toContain('待生成正文')
    expect(planningWorkspace).toContain('待补计划')
    expect(planningModel).toContain('serialReleaseDesk')
    expect(planningModel).toContain('serialization_policy')
    expect(planningModel).toContain('buildSerialReleaseDeskModel')
  })

  test('shows a longform spine guard in the story planning workflow', () => {
    const planningWorkspace = source('StoryPlanningWorkspace.tsx')
    const planningModel = source('planningWorkspaceModel.ts')

    expect(planningWorkspace).toContain('核心契约雷达')
    expect(planningWorkspace).toContain('novel-core-contract-radar-card')
    expect(planningWorkspace).toContain('model.coreContractRadar.checks')
    expect(planningWorkspace).toContain('必须服务')
    expect(planningWorkspace).toContain('不可偏移')
    expect(planningModel).toContain('coreContractRadar')
    expect(planningModel).toContain('buildCoreContractRadarModel')
    expect(planningWorkspace).toContain('全书主轴护栏')
    expect(planningWorkspace).toContain('novel-longform-spine-guard-card')
    expect(planningWorkspace).toContain('model.longformSpineGuard.axes')
    expect(planningWorkspace).toContain('核心卖点')
    expect(planningWorkspace).toContain('不可漂移边界')
    expect(planningWorkspace).toContain('可调整区')
    expect(planningModel).toContain('longformSpineGuard')
    expect(planningModel).toContain('buildLongformSpineGuardModel')
    expect(planningModel).toContain('longform_creation_diagnosis')
  })

  test('shows a million-word milestone map in the story planning workflow', () => {
    const planningWorkspace = source('StoryPlanningWorkspace.tsx')
    const planningModel = source('planningWorkspaceModel.ts')

    expect(planningWorkspace).toContain('百万字里程碑地图')
    expect(planningWorkspace).toContain('novel-million-word-milestone-card')
    expect(planningWorkspace).toContain('model.millionWordMilestones.milestones')
    expect(planningWorkspace).toContain('主角状态')
    expect(planningWorkspace).toContain('世界扩展')
    expect(planningWorkspace).toContain('冲突升级')
    expect(planningWorkspace).toContain('读者回报')
    expect(planningModel).toContain('millionWordMilestones')
    expect(planningModel).toContain('buildMillionWordMilestonesModel')
  })

  test('shows longform memory capsule in planning and chapter launch workflow', () => {
    const planningWorkspace = source('StoryPlanningWorkspace.tsx')
    const workspaceCenter = source('WorkspaceCenter.tsx')
    const recommendationModel = source('writingRecommendationModel.ts')
    const planningModel = source('planningWorkspaceModel.ts')
    const writingService = readFileSync(join(import.meta.dir, '../../../../server/src/routes/novel-writing-service.ts'), 'utf8')

    expect(planningWorkspace).toContain('长篇记忆胶囊')
    expect(planningWorkspace).toContain('novel-longform-memory-capsule-card')
    expect(planningWorkspace).toContain('model.longformMemoryCapsule.characterStates')
    expect(planningWorkspace).toContain('开放悬念')
    expect(planningWorkspace).toContain('待兑现')
    expect(workspaceCenter).toContain('novel-draft-brief-memory-capsule')
    expect(workspaceCenter).toContain('长篇记忆胶囊')
    expect(recommendationModel).toContain('longformMemoryCorePromise')
    expect(planningModel).toContain('longformMemoryCapsule')
    expect(planningModel).toContain('buildLongformMemoryCapsuleModel')
    expect(writingService).toContain('longform_memory_capsule')
    expect(writingService).toContain('【长篇记忆胶囊】')
  })

  test('shows reader trust ledger as a story planning workflow', () => {
    const planningWorkspace = source('StoryPlanningWorkspace.tsx')
    const planningModel = source('planningWorkspaceModel.ts')

    expect(planningWorkspace).toContain('追读信任账本')
    expect(planningWorkspace).toContain('novel-reader-trust-ledger-card')
    expect(planningWorkspace).toContain('model.readerTrustLedger.signals')
    expect(planningWorkspace).toContain('期待兑现')
    expect(planningWorkspace).toContain('爽点回报')
    expect(planningWorkspace).toContain('追读钩子')
    expect(planningWorkspace).toContain('继续悬念')
    expect(planningModel).toContain('readerTrustLedger')
    expect(planningModel).toContain('buildReaderTrustLedgerModel')
    expect(planningModel).toContain('reader_expectation_sync')
    expect(planningModel).toContain('reader_payoff_sync')
    expect(planningModel).toContain('reader_retention_sync')
  })

  test('shows innovation radar as a story planning workflow', () => {
    const planningWorkspace = source('StoryPlanningWorkspace.tsx')
    const planningModel = source('planningWorkspaceModel.ts')

    expect(planningWorkspace).toContain('创新雷达')
    expect(planningWorkspace).toContain('novel-innovation-radar-card')
    expect(planningWorkspace).toContain('model.innovationRadar.signals')
    expect(planningWorkspace).toContain('创新角度')
    expect(planningWorkspace).toContain('执行点')
    expect(planningWorkspace).toContain('差异护栏')
    expect(planningWorkspace).toContain('IP化场面')
    expect(planningModel).toContain('innovationRadar')
    expect(planningModel).toContain('buildInnovationRadarModel')
    expect(planningModel).toContain('innovation_sync')
  })

  test('shows character growth board as a story planning workflow', () => {
    const planningWorkspace = source('StoryPlanningWorkspace.tsx')
    const planningModel = source('planningWorkspaceModel.ts')
    const autoDirectorModel = source('autoCreationDirectorModel.ts')

    expect(planningWorkspace).toContain('人物成长看板')
    expect(planningWorkspace).toContain('novel-character-arc-board-card')
    expect(planningWorkspace).toContain('model.characterArcBoard.arcs')
    expect(planningWorkspace).toContain('成长断档')
    expect(planningWorkspace).toContain('关系待推进')
    expect(planningWorkspace).toContain('弧光缺口')
    expect(planningModel).toContain('characterArcBoard')
    expect(planningModel).toContain('buildCharacterArcBoardModel')
    expect(planningModel).toContain('character_arc_sync')
    expect(planningModel).toContain('relationship_arc')
    expect(autoDirectorModel).toContain('characterArcBoard')
    expect(autoDirectorModel).toContain('人物成长')
  })

  test('shows reader trial room as a story planning workflow', () => {
    const planningWorkspace = source('StoryPlanningWorkspace.tsx')
    const projectWorkspace = source('../NovelProjectWorkspace.tsx')
    const planningModel = source('planningWorkspaceModel.ts')
    const taskCenter = source('TaskCenterDrawer.tsx')
    const service = readFileSync(join(import.meta.dir, '../../../../server/src/routes/novel-commercial-ops-routes.ts'), 'utf8')

    expect(planningWorkspace).toContain('读者试读室')
    expect(planningWorkspace).toContain('爽点读者')
    expect(planningWorkspace).toContain('平台试读用户')
    expect(planningWorkspace).toContain('弃读点')
    expect(planningWorkspace).toContain('run_reader_trial_review')
    expect(planningWorkspace).toContain('create_reader_trial_repair')
    expect(projectWorkspace).toContain('reader-trial-review')
    expect(projectWorkspace).toContain('reader-trial-review/repair-queue')
    expect(taskCenter).toContain('读者试读修复任务')
    expect(taskCenter).toContain('补试读')
    expect(planningModel).toContain('readerTrialRoom')
    expect(planningModel).toContain('qidian_10k_reader_trial_baseline')
    expect(service).toContain("review_type: 'reader_trial_review'")
    expect(service).toContain("source: 'reader_trial_review'")
  })

  test('shows volume climax budget as a story planning workflow', () => {
    const planningWorkspace = source('StoryPlanningWorkspace.tsx')
    const planningModel = source('planningWorkspaceModel.ts')
    const directorModel = source('autoCreationDirectorModel.ts')

    expect(planningWorkspace).toContain('卷级高潮预算')
    expect(planningWorkspace).toContain('novel-volume-beat-budget-card')
    expect(planningWorkspace).toContain('小高潮')
    expect(planningWorkspace).toContain('中高潮')
    expect(planningWorkspace).toContain('卷末爆点')
    expect(planningModel).toContain('volumeBeatBudget')
    expect(directorModel).toContain('volume_beat_budget')
    expect(directorModel).toContain('volumeBeatScore')
  })

  test('shows volume segment acceptance as a story planning workflow', () => {
    const planningWorkspace = source('StoryPlanningWorkspace.tsx')
    const planningModel = source('planningWorkspaceModel.ts')

    expect(planningWorkspace).toContain('卷段验收')
    expect(planningWorkspace).toContain('novel-volume-segment-gate-card')
    expect(planningWorkspace).toContain('model.volumeSegmentGate.signals')
    expect(planningWorkspace).toContain('阶段目标')
    expect(planningWorkspace).toContain('高潮/回报')
    expect(planningWorkspace).toContain('读者信任')
    expect(planningWorkspace).toContain('创新/IP化')
    expect(planningWorkspace).toContain('风险闭环')
    expect(planningModel).toContain('volumeSegmentGate')
    expect(planningModel).toContain('buildVolumeSegmentGateModel')
  })

  test('shows recent fatigue radar as a story planning workflow', () => {
    const planningWorkspace = source('StoryPlanningWorkspace.tsx')
    const planningModel = source('planningWorkspaceModel.ts')

    expect(planningWorkspace).toContain('近10章疲劳雷达')
    expect(planningWorkspace).toContain('novel-recent-fatigue-radar-card')
    expect(planningWorkspace).toContain('model.recentFatigueRadar.signals')
    expect(planningWorkspace).toContain('冲突变化')
    expect(planningWorkspace).toContain('回报变化')
    expect(planningWorkspace).toContain('钩子变化')
    expect(planningWorkspace).toContain('场面新鲜度')
    expect(planningModel).toContain('recentFatigueRadar')
    expect(planningModel).toContain('buildRecentFatigueRadarModel')
    expect(planningModel).toContain('ip_scene_intake')
    expect(planningModel).toContain('IP场面覆盖')
  })

  test('shows story pressure ladder as a story planning workflow', () => {
    const planningWorkspace = source('StoryPlanningWorkspace.tsx')
    const planningModel = source('planningWorkspaceModel.ts')

    expect(planningWorkspace).toContain('故事压力阶梯')
    expect(planningWorkspace).toContain('novel-story-pressure-ladder-card')
    expect(planningWorkspace).toContain('model.storyPressureLadder.signals')
    expect(planningWorkspace).toContain('压力源')
    expect(planningWorkspace).toContain('冲突升级')
    expect(planningWorkspace).toContain('赌注升级')
    expect(planningWorkspace).toContain('反转逼迫')
    expect(planningModel).toContain('storyPressureLadder')
    expect(planningModel).toContain('buildStoryPressureLadderModel')
  })

  test('shows story unit workshop as a story planning workflow', () => {
    const planningWorkspace = source('StoryPlanningWorkspace.tsx')
    const planningModel = source('planningWorkspaceModel.ts')

    expect(planningWorkspace).toContain('剧情单元工坊')
    expect(planningWorkspace).toContain('novel-story-unit-workshop-card')
    expect(planningWorkspace).toContain('model.storyUnitWorkshop.currentUnit.signals')
    expect(planningWorkspace).toContain('入口钩子')
    expect(planningWorkspace).toContain('压力升级')
    expect(planningWorkspace).toContain('小高潮/回报')
    expect(planningWorkspace).toContain('伏笔/剧情线')
    expect(planningWorkspace).toContain('出单元钩子')
    expect(planningModel).toContain('storyUnitWorkshop')
    expect(planningModel).toContain('buildStoryUnitWorkshopModel')
  })

  test('shows volume beat sync status in the delivery strip', () => {
    const workspaceCenter = source('WorkspaceCenter.tsx')
    const workspaceCss = source('WorkspaceCenter.css')
    const writingModel = source('writingCockpitModel.ts')
    const recommendationModel = source('writingRecommendationModel.ts')

    expect(writingModel).toContain('volumeBeatSync')
    expect(writingModel).toContain('buildVolumeBeatSyncSummary')
    expect(recommendationModel).toContain('volumeBeatSync')
    expect(workspaceCenter).toContain('deliverySummary.volumeBeatSync')
    expect(workspaceCenter).toContain('novel-delivery-volume-beat-tag')
    expect(workspaceCss).toContain('.novel-delivery-volume-beat-tag')
  })

  test('shows auto creation director as the longform control workspace', () => {
    const directorWorkspace = source('AutoCreationDirectorWorkspace.tsx')
    const directorCss = source('AutoCreationDirectorWorkspace.css')
    const directorModel = source('autoCreationDirectorModel.ts')
    const projectWorkspace = readFileSync(join(import.meta.dir, '../NovelProjectWorkspace.tsx'), 'utf8')
    const writingService = readFileSync(join(import.meta.dir, '../../../../server/src/routes/novel-writing-service.ts'), 'utf8')
    const taskCenter = source('TaskCenterDrawer.tsx')

    expect(projectWorkspace).toContain("autoCreation")
    expect(projectWorkspace).toContain('自动创作')
    expect(projectWorkspace).toContain('AutoCreationDirectorWorkspace')
    expect(projectWorkspace).toContain("lazy(() => import('./novel-workspace/AutoCreationDirectorWorkspace')")
    expect(projectWorkspace).toContain('buildAutoCreationDirectorModel')
    expect(projectWorkspace).toContain('runRecords')
    expect(projectWorkspace).toContain('storyState')
    expect(projectWorkspace).toContain('chapters: sortedChapters')
    expect(projectWorkspace).toContain('handleAutoCreationDirectorAction')
    expect(projectWorkspace).toContain('start_safe_batch_generation')
    expect(projectWorkspace).toContain('runRollingPlan(options')
    expect(projectWorkspace).toContain('rolling_plan_intent: options?.intent')
    expect(projectWorkspace).toContain('action.payload?.source === \'batch_brief_repair\'')
    expect(projectWorkspace).toContain('action.payload?.source === \'recent_fatigue_repair\'')
    expect(projectWorkspace).toContain('handlePlanningAction(action.key as PlanningActionKey, { intent: action.payload })')
    expect(projectWorkspace).toContain('handlePlanningAction = (key: PlanningActionKey, options?: { intent?: any })')
    expect(projectWorkspace).toContain("const rollingPlanIntent = options?.intent || (key === 'update_rolling_plan' ? recentFatigueRollingPlanIntent : null)")
    expect(projectWorkspace).toContain('runRollingPlan({ intent: rollingPlanIntent || undefined })')
    expect(projectWorkspace).toContain('onAction={handlePlanningAction}')
    expect(projectWorkspace).toContain('source: \'recent_fatigue_repair\'')
    expect(projectWorkspace).toContain('createSafeBatchRiskRepairQueue')
    expect(projectWorkspace).toContain('create_safe_batch_risk_repair')
    expect(projectWorkspace).toContain('auto_creation_safe_batch_risk')
    expect(projectWorkspace).toContain('createStyleSampleBatchRepairQueue')
    expect(projectWorkspace).toContain('create_style_sample_batch_repair')
    expect(projectWorkspace).toContain('styleSampleEffectiveness')
    expect(projectWorkspace).toContain('/writing-bible/style-sample-effectiveness')
    expect(projectWorkspace).toContain('style_sample_batch_preflight')
    expect(projectWorkspace).toContain('createScriptRoomRepairQueue')
    expect(projectWorkspace).toContain('create_script_room_repair')
    expect(projectWorkspace).toContain('rolling_script_room')
    expect(projectWorkspace).toContain('script_room_layer_gap')
    expect(projectWorkspace).toContain('batch_plan_risk_count')
    expect(projectWorkspace).toContain('volume_segment_risk_count')
    expect(projectWorkspace).toContain('reader_pull_risk_count')
    expect(projectWorkspace).toContain('innovation_risk_count')
    expect(projectWorkspace).toContain('卷级阶段漏结算')
    expect(projectWorkspace).toContain('读者拉力不足')
    expect(projectWorkspace).toContain('创新/IP化缺口')
    expect(projectWorkspace).toContain('批次任务书兑现')
    expect(taskCenter).toContain('batch_brief_mismatch')
    expect(taskCenter).toContain('批次计划')
    expect(taskCenter).toContain('按批次修订')
    expect(taskCenter).toContain('recovery_evidence_mismatch')
    expect(taskCenter).toContain('恢复依据')
    expect(taskCenter).toContain('RecoveryEvidenceReviewPreview')
    expect(taskCenter).toContain('失效依据')
    expect(taskCenter).toContain('对应风险')
    expect(taskCenter).toContain('style_sample_task_book_rebuild')
    expect(taskCenter).toContain('样章任务书')
    expect(taskCenter).toContain('重审样章')
    expect(projectWorkspace).toContain('executeStyleSampleTaskBookRebuild')
    expect(projectWorkspace).toContain('recheckStyleSampleTaskBookReviewTasks')
    expect(projectWorkspace).toContain('buildStyleSampleTaskBookRecheckPlan')
    expect(projectWorkspace).toContain('样章任务书复检通过')
    expect(projectWorkspace).toContain("issue_type || '') === 'style_sample_task_book_rebuild'")
    expect(projectWorkspace).toContain('已换样章并重审任务书')
    expect(taskCenter).toContain('onRecheckStyleSampleTaskBooks')
    expect(taskCenter).toContain('复检样章任务书')
    expect(taskCenter).toContain('volume_segment_missed')
    expect(taskCenter).toContain('卷级阶段')
    expect(taskCenter).toContain('补阶段结算')
    expect(taskCenter).toContain('reader_pull_missed')
    expect(taskCenter).toContain('读者拉力')
    expect(taskCenter).toContain('补追读')
    expect(taskCenter).toContain('innovation_execution_missed')
    expect(taskCenter).toContain('创新/IP')
    expect(taskCenter).toContain('补创新')
    expect(taskCenter).toContain('batch_plan_review')
    expect(taskCenter).toContain('计划/实际')
    expect(taskCenter).toContain('volume_beat')
    expect(taskCenter).toContain('爆点')
    expect(taskCenter).toContain('按剧本室修复')
    expect(taskCenter).toContain('剧本室')
    expect(projectWorkspace).toContain('stepGenerateProse({')
    expect(projectWorkspace).toContain('const currentChapterLaunchGate')
    expect(projectWorkspace).toContain('longform_compass: autoCreationDirectorModel.longformCompass')
    expect(projectWorkspace).toContain('chapter_launch_gate: currentChapterLaunchGate')
    expect(projectWorkspace).toContain('limit: autoCreationDirectorModel.batchGuardrail.safeChapterCount')
    expect(projectWorkspace).toContain('allowedChapterNos: autoCreationDirectorModel.batchGuardrail.nextBatchBrief.chapters.map(chapter => chapter.chapterNo)')
    expect(projectWorkspace).toContain('allowedChapterNos?: number[]')
    expect(projectWorkspace).toContain('allowedChapterNoSet')
    expect(projectWorkspace).toContain('allowed_chapter_nos')
    expect(projectWorkspace).toContain('longformCompass: autoCreationDirectorModel.longformCompass')
    expect(projectWorkspace).toContain('longformBattleContext: autoCreationDirectorModel.longformBattleDesk')
    expect(projectWorkspace).toContain('chapterLaunchGate: autoCreationDirectorModel.chapterLaunchGate')
    expect(projectWorkspace).toContain('nextBatchBrief: autoCreationDirectorModel.batchGuardrail.nextBatchBrief')
    expect(projectWorkspace).toContain('batchPreflight: autoCreationDirectorModel.batchGuardrail.preflight.inputSnapshot')
    expect(projectWorkspace).toContain('longform_compass: options?.longformCompass')
    expect(projectWorkspace).toContain('longform_battle_context: options?.longformBattleContext')
    expect(projectWorkspace).toContain('chapter_launch_gate: options?.chapterLaunchGate')
    expect(projectWorkspace).toContain('next_batch_brief: options?.nextBatchBrief')
    expect(projectWorkspace).toContain('batch_preflight: options?.batchPreflight')
    expect(projectWorkspace).toContain('longformBattleContext?: any')
    expect(projectWorkspace).toContain('chapterLaunchGate?: any')
    expect(projectWorkspace).toContain('batchPreflight?: any')
    expect(projectWorkspace).toContain('runLongformCreationDiagnosis')
    expect(projectWorkspace).toContain('/longform-creation-diagnosis')
    expect(directorWorkspace).toContain("import './AutoCreationDirectorWorkspace.css'")
    expect(directorWorkspace).toContain('自动创作总控台')
    expect(directorWorkspace).toContain('唯一下一步')
    expect(directorWorkspace).toContain('当前判断')
    expect(directorWorkspace).toContain('model.governanceClosureBrief.status')
    expect(directorWorkspace).toContain('治理闭环')
    expect(directorWorkspace).toContain('auto-director-judgement-card')
    expect(directorWorkspace).not.toContain('auto-director-next-card')
    expect(directorWorkspace).toContain('生产许可')
    expect(directorWorkspace).toContain('model.productionLicense')
    expect(directorWorkspace).toContain('auto-director-license-panel')
    expect(directorWorkspace).toContain('auto-director-license-detail')
    expect(directorWorkspace).not.toContain('action={model.productionLicense.nextAction}')
    expect(directorWorkspace).toContain('model.serialCockpit')
    expect(directorWorkspace).toContain('长篇连载驾驶舱')
    expect(directorWorkspace).toContain('今日唯一动作')
    expect(directorWorkspace).toContain('万订五项护栏')
    expect(directorWorkspace).toContain('当前章生产链')
    expect(directorWorkspace).toContain('连写许可')
    expect(directorWorkspace).toContain('待处理风险')
    expect(directorWorkspace).toContain('serialCockpit.command.action')
    expect(directorWorkspace).toContain('serialCockpit.guardrails.map')
    expect(directorWorkspace).toContain('serialCockpit.chapterChain.map')
    expect(directorWorkspace).toContain('serialCockpit.batchLicense')
    expect(directorWorkspace).toContain('serialCockpit.riskQueue')
    expect(directorWorkspace).toContain('auto-director-serial-cockpit')
    expect(directorWorkspace).toContain('auto-director-cockpit-guardrails')
    expect(directorWorkspace).toContain('auto-director-cockpit-chain')
    expect(directorWorkspace).toContain('auto-director-cockpit-risks')
    expect(directorWorkspace).toContain('长篇作战台')
    expect(directorWorkspace).toContain('model.longformBattleDesk')
    expect(directorWorkspace).toContain('auto-director-battle-desk')
    expect(directorWorkspace).toContain('auto-director-battle-lane')
    expect(directorWorkspace).toContain('核心守恒')
    expect(directorWorkspace).toContain('读者拉力')
    expect(directorWorkspace).toContain('剧情线调度')
    expect(directorWorkspace).toContain('卷级爆点')
    expect(directorWorkspace).toContain('创新/IP场面')
    expect(directorWorkspace).toContain('生产燃料')
    expect(directorWorkspace).toContain('auto-director-detail-drawer')
    expect(directorWorkspace).toContain('展开详细依据')
    expect(directorWorkspace).toContain('连载日更作战')
    expect(directorWorkspace).toContain('model.dailyBattlePlan.steps')
    expect(directorWorkspace).toContain('step.gateChecks')
    expect(directorWorkspace).toContain('auto-director-daily-gates')
    expect(directorWorkspace).toContain('完成口径')
    expect(directorWorkspace).toContain('auto-director-daily-panel')
    expect(directorWorkspace).toContain('auto-director-daily-step')
    expect(directorCss).toContain('.auto-director-daily-gates')
    expect(directorWorkspace).toContain('百章滚动剧本室')
    expect(directorWorkspace).toContain('model.rollingScriptRoom.layers')
    expect(directorWorkspace).toContain('auto-director-script-room-panel')
    expect(directorWorkspace).toContain('本章开写门禁')
    expect(directorWorkspace).toContain('model.chapterLaunchGate.signals')
    expect(directorWorkspace).toContain('auto-director-launch-gate-panel')
    expect(directorWorkspace).toContain('model.rollingScriptRoom.repairTasks.length')
    expect(directorWorkspace).toContain('生成剧本室修复任务')
    expect(directorWorkspace).toContain('当前章')
    expect(directorWorkspace).toContain('未来10章')
    expect(directorWorkspace).toContain('未来100章')
    expect(directorWorkspace).toContain('当前卷')
    expect(directorWorkspace).toContain('全书罗盘')
    expect(directorCss).toContain('auto-director-script-room-panel')
    expect(directorCss).toContain('.auto-director-launch-gate-panel')
    expect(directorCss).toContain('.auto-director-launch-gate-signal')
    expect(directorCss).toContain('.auto-director-license-panel')
    expect(directorCss).toContain('.auto-director-license-mode')
    expect(directorCss).toContain('.auto-director-serial-cockpit')
    expect(directorCss).toContain('.auto-director-cockpit-guardrails')
    expect(directorCss).toContain('.auto-director-cockpit-chain')
    expect(directorCss).toContain('.auto-director-cockpit-risks')
    expect(directorCss).toContain('.auto-director-battle-desk')
    expect(directorCss).toContain('.auto-director-battle-lanes')
    expect(directorCss).toContain('.auto-director-battle-lane')
    expect(directorCss).toContain('.auto-director-detail-drawer')
    expect(directorCss).toContain('.auto-director-detail-summary')
    expect(directorModel).toContain('rollingScriptRoom')
    expect(directorModel).toContain('AutoCreationProductionLicense')
    expect(directorModel).toContain('todayCommandDeck')
    expect(directorModel).toContain('longformBattleDesk')
    expect(directorModel).toContain('qualityGates')
    expect(directorModel).toContain('核心不偏')
    expect(directorModel).toContain('故事推进')
    expect(directorModel).toContain('读者拉力')
    expect(directorModel).toContain('创新差异')
    expect(directorModel).toContain('连载安全')
    expect(directorModel).toContain('buildTodayCommandDeck')
    expect(directorModel).toContain('buildProductionLicense')
    expect(directorModel).toContain('productionLicense')
    expect(directorModel).toContain('chapterLaunchGate')
    expect(directorModel).toContain('buildChapterLaunchGate')
    expect(directorModel).toContain('mainline_service')
    expect(directorModel).toContain('rolling_script_room')
    expect(directorModel).toContain('repairTasks')
    expect(directorModel).toContain('create_script_room_repair')
    expect(directorWorkspace).toContain('清交稿风险')
    expect(directorWorkspace).toContain('补长线材料')
    expect(directorWorkspace).toContain('写/修当前章')
    expect(directorWorkspace).toContain('放行下一批')
    expect(directorWorkspace).toContain('创作诊断')
    expect(directorWorkspace).toContain('长篇作品罗盘')
    expect(directorWorkspace).toContain('longformCompass')
    expect(directorWorkspace).toContain('auto-director-compass-panel')
    expect(directorWorkspace).toContain('长篇创作契约')
    expect(directorWorkspace).toContain('核心不偏')
    expect(directorWorkspace).toContain('故事强度')
    expect(directorWorkspace).toContain('创新差异')
    expect(directorWorkspace).toContain('读者吸引')
    expect(directorWorkspace).toContain('长篇节奏总控')
    expect(directorWorkspace).toContain('百万字产能')
    expect(directorWorkspace).toContain('longformCapacity')
    expect(directorWorkspace).toContain('auto-director-capacity-panel')
    expect(directorWorkspace).toContain('生产燃料队列')
    expect(directorWorkspace).toContain('fuelQueue')
    expect(directorWorkspace).toContain('auto-director-fuel-queue')
    expect(directorWorkspace).toContain('连续生产护栏')
    expect(directorWorkspace).toContain('本批放行范围')
    expect(directorWorkspace).toContain('安全连写预执行确认')
    expect(directorWorkspace).toContain('model.batchGuardrail.preflight')
    expect(directorWorkspace).toContain('longformMemoryAnchor')
    expect(directorWorkspace).toContain('正史锚点')
    expect(directorWorkspace).toContain('auto-director-batch-preflight')
    expect(directorWorkspace).toContain('auto-director-batch-memory-anchor')
    expect(directorWorkspace).toContain('model.batchGuardrail.releaseWindow')
    expect(directorWorkspace).toContain('auto-director-batch-release-window')
    expect(directorWorkspace).toContain('auto-director-batch-release-chapter')
    expect(directorWorkspace).toContain('安全连写复盘')
    expect(directorWorkspace).toContain('auto-director-batch-panel')
    expect(directorWorkspace).toContain('近10章疲劳')
    expect(directorWorkspace).toContain('下一批任务书')
    expect(directorWorkspace).toContain('nextBatchBrief')
    expect(directorWorkspace).toContain('auto-director-batch-brief')
    expect(directorWorkspace).toContain('批次开工清单')
    expect(directorWorkspace).toContain('nextBatchBrief.startChecklist')
    expect(directorWorkspace).toContain('auto-director-batch-start-checklist')
    expect(directorWorkspace).toContain('批次任务书补齐')
    expect(directorWorkspace).toContain('briefRepair')
    expect(directorWorkspace).toContain('auto-director-batch-repair')
    expect(directorWorkspace).toContain('批次安全已恢复')
    expect(directorWorkspace).toContain('briefRecovery')
    expect(directorWorkspace).toContain('auto-director-batch-recovery')
    expect(directorWorkspace).toContain('auto-director-batch-review-panel')
    expect(directorWorkspace).toContain('batchReviewQueue')
    expect(directorWorkspace).toContain('delivered')
    expect(directorWorkspace).toContain('已交付')
    expect(directorWorkspace).toContain('批次完成度')
    expect(directorWorkspace).toContain('批次交接')
    expect(directorWorkspace).toContain('model.batchReviewQueue.handoff')
    expect(directorWorkspace).toContain('auto-director-batch-handoff')
    expect(directorWorkspace).toContain('model.batchReviewQueue.completionDashboard')
    expect(directorWorkspace).toContain('auto-director-batch-completion-dashboard')
    expect(directorWorkspace).toContain('批次风险雷达')
    expect(directorWorkspace).toContain('riskRadar')
    expect(directorWorkspace).toContain('修复任务')
    expect(directorWorkspace).toContain('safeChapterCount')
    expect(directorWorkspace).toContain('auto-director-stage')
    expect(directorWorkspace).toContain('auto-director-contract-item')
    expect(directorWorkspace).toContain('auto-director-rhythm-panel')
    expect(directorWorkspace).toContain('auto-director-batch-guardrail')
    expect(directorWorkspace).toContain('auto-director-model-action')
    expect(directorWorkspace).toContain('onSelectChapter')
    expect(directorCss).toContain('.auto-director-shell')
    expect(directorCss).toContain('.auto-director-judgement-card')
    expect(directorCss).not.toContain('.auto-director-next-card')
    expect(directorCss).toContain('.auto-director-daily-panel')
    expect(directorCss).toContain('.auto-director-daily-step')
    expect(directorCss).toContain('.auto-director-daily-step-active')
    expect(directorCss).toContain('.auto-director-daily-step-blocked')
    expect(directorCss).toContain('.auto-director-stage')
    expect(directorCss).toContain('.auto-director-compass-panel')
    expect(directorCss).toContain('.auto-director-compass-axis')
    expect(directorCss).toContain('.auto-director-contract-item')
    expect(directorCss).toContain('.auto-director-rhythm-panel')
    expect(directorCss).toContain('.auto-director-rhythm-signal')
    expect(directorCss).toContain('.auto-director-capacity-panel')
    expect(directorCss).toContain('.auto-director-capacity-signal')
    expect(directorCss).toContain('.auto-director-fuel-queue')
    expect(directorCss).toContain('.auto-director-fuel-item')
    expect(directorCss).toContain('.auto-director-batch-panel')
    expect(directorCss).toContain('.auto-director-batch-release-window')
    expect(directorCss).toContain('.auto-director-batch-preflight')
    expect(directorCss).toContain('.auto-director-batch-memory-anchor')
    expect(directorCss).toContain('.auto-director-batch-release-chapter')
    expect(directorCss).toContain('.auto-director-batch-release-chapter-blocked')
    expect(directorCss).toContain('.auto-director-batch-brief')
    expect(directorCss).toContain('.auto-director-batch-start-checklist')
    expect(directorCss).toContain('.auto-director-batch-repair')
    expect(directorCss).toContain('.auto-director-batch-recovery')
    expect(directorCss).toContain('.auto-director-batch-brief-chapter')
    expect(directorCss).toContain('.auto-director-batch-guardrail')
    expect(directorCss).toContain('.auto-director-batch-review-panel')
    expect(directorCss).toContain('.auto-director-batch-completion-dashboard')
    expect(directorCss).toContain('.auto-director-batch-handoff')
    expect(directorCss).toContain('.auto-director-batch-completion-metric')
    expect(directorCss).toContain('.auto-director-batch-review-item')
    expect(directorCss).toContain('.auto-director-batch-risk-radar')
    expect(directorCss).toContain('.auto-director-batch-review-panel-risk')
    expect(directorCss).toContain('.auto-director-model-action')
    expect(directorModel).toContain('AutoCreationDirectorModel')
    expect(directorModel).toContain('dailyBattlePlan')
    expect(directorModel).toContain('buildDailyBattlePlan')
    expect(directorModel).toContain('clear_risks')
    expect(directorModel).toContain('fuel_materials')
    expect(directorModel).toContain('chapter_work')
    expect(directorModel).toContain('batch_release')
    expect(directorModel).toContain('longformCompass')
    expect(directorModel).toContain('buildLongformCompass')
    expect(directorModel).toContain('creationContract')
    expect(directorModel).toContain('longformRhythm')
    expect(directorModel).toContain('longformCapacity')
    expect(directorModel).toContain('fuelQueue')
    expect(directorModel).toContain('longform_capacity')
    expect(directorModel).toContain('longform_rhythm')
    expect(directorModel).toContain('batchGuardrail')
    expect(directorModel).toContain('releaseWindow')
    expect(directorModel).toContain('preflight')
    expect(directorModel).toContain('buildBatchPreflight')
    expect(directorModel).toContain('buildLongformMemoryAnchor')
    expect(directorModel).toContain('longform_memory_anchor')
    expect(directorModel).toContain('auto_creation_safe_batch_preflight')
    expect(writingService).toContain('【长篇正史锚点】')
    expect(writingService).toContain('batch_preflight.longform_memory_anchor')
    expect(directorModel).toContain('allowedChapters')
    expect(directorModel).toContain('blockedChapters')
    expect(directorModel).toContain('recentFatigueRadar')
    expect(directorModel).toContain('近10章疲劳')
    expect(directorModel).toContain('storyPressureLadder')
    expect(directorModel).toContain('故事压力阶梯')
    expect(directorModel).toContain('story_pressure_repair')
    expect(directorModel).toContain('storyUnitWorkshop')
    expect(directorModel).toContain('剧情单元')
    expect(directorModel).toContain('story_unit_repair')
    expect(directorModel).toContain('story_unit_sync')
    expect(directorModel).toContain('story_unit_sync_risk')
    expect(directorModel).toContain('nextBatchBrief')
    expect(directorModel).toContain('briefRepair')
    expect(directorModel).toContain('buildNextBatchBriefRepair')
    expect(directorModel).toContain('batch_brief_repair')
    expect(directorModel).toContain('missing_items')
    expect(directorModel).toContain('briefRecovery')
    expect(directorModel).toContain('buildNextBatchBriefRecovery')
    expect(directorModel).toContain('batch_guardrail')
    expect(directorModel).toContain('batchReviewQueue')
    expect(directorModel).toContain('completionDashboard')
    expect(directorModel).toContain('handoff')
    expect(directorModel).toContain('buildBatchHandoff')
    expect(directorModel).toContain('deliver_chapters')
    expect(directorModel).toContain('continue_batch')
    expect(directorModel).toContain('prepare_next')
    expect(directorModel).toContain('reconcileBatchHandoffWithGuardrail')
    expect(directorModel).toContain('buildBatchCompletionDashboard')
    expect(directorModel).toContain('BATCH_DELIVERY_QUALITY_THRESHOLD')
    expect(directorModel).toContain('batchChapterDelivered')
    expect(directorModel).toContain('buildBatchRiskRadar')
    expect(directorModel).toContain('chapter_handoff')
    expect(directorModel).toContain('章节交接')
    expect(directorModel).toContain('chapterHandoffDetail')
    expect(directorModel).toContain('repairTasks')
    expect(directorModel).toContain('create_safe_batch_risk_repair')
    expect(directorModel).toContain('create_style_sample_batch_repair')
    expect(directorModel).toContain('风格样章预检')
    expect(directorModel).toContain('style_sample_batch_preflight')
    expect(directorModel).toContain('style_sample_task_book_rebuild')
    expect(directorModel).toContain('安全连写批次存在质量风险')
    expect(directorModel).toContain('auto_creation_safe_batch')
    expect(directorModel).toContain('start_safe_batch_generation')
    expect(directorModel).toContain('MODEL_CALL_ACTIONS')
    expect(taskCenter).toContain('安全连写风险修复任务')
    expect(taskCenter).toContain('恢复放行依据')
    expect(taskCenter).toContain('recovery_evidence')
    expect(taskCenter).toContain('batch_preflight')
  })

  test('shows the creative assistant panel shell', () => {
    const projectWorkspace = source('../NovelProjectWorkspace.tsx')
    const panel = source('CreativeAssistantPanel.tsx')
    const model = source('creativeAssistantModel.ts')
    const css = source('CreativeAssistantPanel.css')

    expect(projectWorkspace).toContain('CreativeAssistantPanel')
    expect(projectWorkspace).toContain('创作参谋')
    expect(projectWorkspace).toContain('/creative-assist')
    expect(projectWorkspace).toContain('creativeAssistantOpen')
    expect(projectWorkspace).toContain('runCreativeAssistant')
    expect(projectWorkspace).toContain('setCreativeAssistantOpen(true)')
    expect(projectWorkspace).toContain('apiClient.post(`/novel/projects/${projectId}/creative-assist`')
    expect(projectWorkspace).toContain('runRecords={runRecords}')
    expect(projectWorkspace).toContain('onCopyCard')
    expect(panel).toContain('runRecords')
    expect(model).toContain('治理闭环待处理')
    expect(model).toContain('先处理长线治理闭环')
    expect(panel).toContain('正文评析')
    expect(panel).toContain('下一章')
    expect(panel).toContain('后续大纲')
    expect(panel).toContain('伏笔')
    expect(panel).toContain('人物剧情')
    expect(panel).toContain('能力物品')
    expect(panel).toContain('联网资料')
    expect(panel).toContain('creative-assistant-card')
    expect(css).toContain('.creative-assistant-panel')
    expect(css).toContain('.creative-assistant-card')
  })
})
