import { describe, expect, test } from 'bun:test'
import { readFileSync } from 'fs'
import { join } from 'path'
import {
  source,
  serverSource,
  sourceCached,
  localSourceCache,
  packageSourceCache,
  packageSource,
  writingServiceSource,
  editorRoutesSource,
  commercialOpsRoutesSource,
  directorModelSource,
  planningWorkspaceSource,
  workspaceCenterSource,
  projectWorkspaceSource,
  writingCockpitPanelSource,
  taskCenterSource,
  storyPlanningWorkspaceSource,
  autoCreationDirectorWorkspaceSource,
  writingCockpitModelSource,
  writingRecommendationModelSource,
} from './workspaceUiShellSource'

describe('commercial writing workspace UI shell b a', () => {

  test('shows reader retention sync status in the delivery strip', () => {
    const workspaceCenter = workspaceCenterSource()
    const workspaceCss = source('WorkspaceCenter.css')
    const model = writingCockpitModelSource()
    const recommendationModel = writingRecommendationModelSource()
    const service = writingServiceSource()
    const reviewRecords = serverSource('novel-writing/post-delivery-sync-review-record.ts')

    expect(workspaceCenter).toContain('readerRetentionSync')
    expect(workspaceCenter).toContain('novel-delivery-retention-tag')
    expect(workspaceCenter).toContain('chapterAttraction')
    expect(workspaceCenter).toContain('novel-delivery-attraction-tag')
    expect(workspaceCenter).toContain('first30RetentionRecheck')
    expect(workspaceCenter).toContain('novel-delivery-first30-tag')
    expect(workspaceCss).toContain('.novel-delivery-retention-tag')
    expect(workspaceCss).toContain('.novel-delivery-retention-tag-warn')
    expect(workspaceCss).toContain('.novel-delivery-attraction-tag')
    expect(workspaceCss).toContain('.novel-delivery-first30-tag')
    expect(model).toContain('reader_retention_sync')
    expect(model).toContain('buildReaderRetentionSyncSummary')
    expect(model).toContain('chapter_attraction_review')
    expect(model).toContain('buildChapterAttractionSummary')
    expect(model).toContain('buildFirst30RetentionRecheckSummary')
    expect(recommendationModel).toContain('readerRetentionSync')
    expect(recommendationModel).toContain('chapterAttraction')
    expect(recommendationModel).toContain('first30RetentionRecheck')
    expect(service).toContain("reviewType: 'reader_retention_sync'")
    expect(service).toContain("reviewType: 'chapter_attraction_review'")
    expect(service).toContain('buildChapterAttractionReviewReport(project, chapter, contextPackage, chapterText)')
    expect(reviewRecords).toContain('review_type: input.reviewType')
  })

  test('shows reader expectation ledger in draft brief and delivery strip', () => {
    const workspaceCenter = workspaceCenterSource()
    const workspaceCss = source('WorkspaceCenter.css')
    const model = writingCockpitModelSource()
    const recommendationModel = writingRecommendationModelSource()
    const service = writingServiceSource()
    const reviewRecords = serverSource('novel-writing/post-delivery-sync-review-record.ts')

    expect(workspaceCenter).toContain('读者期待账本')
    expect(workspaceCenter).toContain('readerExpectationSync')
    expect(workspaceCenter).toContain('novel-delivery-expectation-tag')
    expect(workspaceCenter).toContain('novel-draft-brief-expectations')
    expect(workspaceCss).toContain('.novel-delivery-expectation-tag')
    expect(workspaceCss).toContain('.novel-delivery-expectation-tag-warn')
    expect(workspaceCss).toContain('.novel-draft-brief-expectations')
    expect(model).toContain('reader_expectation_sync')
    expect(model).toContain('buildReaderExpectationSyncSummary')
    expect(recommendationModel).toContain('reader_expectation_ledger')
    expect(recommendationModel).toContain('expectationMustDeliver')
    expect(service).toContain("reviewType: 'reader_expectation_sync'")
    expect(service).toContain('reader_expectation_ledger')
    expect(reviewRecords).toContain('review_type: input.reviewType')
  })

  test('shows quality audit carry-over sync in the delivery strip', () => {
    const workspaceCenter = workspaceCenterSource()
    const workspaceCss = source('WorkspaceCenter.css')
    const model = writingCockpitModelSource()
    const recommendationModel = writingRecommendationModelSource()
    const service = writingServiceSource()
    const reviewRecords = serverSource('novel-writing/post-delivery-sync-review-record.ts')

    expect(workspaceCenter).toContain('qualityAuditSync')
    expect(workspaceCenter).toContain('novel-delivery-quality-sync-tag')
    expect(workspaceCss).toContain('.novel-delivery-quality-sync-tag')
    expect(workspaceCss).toContain('.novel-delivery-quality-sync-tag-warn')
    expect(model).toContain('quality_audit_sync')
    expect(model).toContain('buildQualityAuditSyncSummary')
    expect(model).toContain('补诊断承接')
    expect(recommendationModel).toContain('qualityAuditSync')
    expect(service).toContain("reviewType: 'quality_audit_sync'")
    expect(reviewRecords).toContain('review_type: input.reviewType')
  })

  test('shows quality audit repair receipt sync in the delivery strip', () => {
    const workspaceCenter = workspaceCenterSource()
    const workspaceCss = source('WorkspaceCenter.css')
    const model = writingCockpitModelSource()
    const recommendationModel = writingRecommendationModelSource()
    const service = writingServiceSource()
    const reviewRecords = serverSource('novel-writing/post-delivery-sync-review-record.ts')

    expect(workspaceCenter).toContain('qualityAuditRepairReceiptSync')
    expect(workspaceCenter).toContain('novel-delivery-quality-repair-receipt-tag')
    expect(workspaceCss).toContain('.novel-delivery-quality-repair-receipt-tag')
    expect(workspaceCss).toContain('.novel-delivery-quality-repair-receipt-tag-warn')
    expect(model).toContain('quality_audit_repair_receipt_sync')
    expect(model).toContain('buildQualityAuditRepairReceiptSyncSummary')
    expect(model).toContain('复核质量修复回执')
    expect(recommendationModel).toContain('qualityAuditRepairReceiptSync')
    expect(service).toContain("reviewType: 'quality_audit_repair_receipt_sync'")
    expect(reviewRecords).toContain('review_type: input.reviewType')
  })

  test('shows reader expectation debt carry-over in the draft brief', () => {
    const workspaceCenter = workspaceCenterSource()
    const workspaceCss = source('WorkspaceCenter.css')
    const recommendationModel = writingRecommendationModelSource()
    const repairPrompt = [source('repair-task/prompt.ts'), source('repair-task/prompt-lines.ts'), source('repair-task/prompt-lines-quality.ts'), source('repair-task/prompt-lines-quality-core.ts'), source('repair-task/prompt-lines-quality-craft.ts'), source('repair-task/prompt-lines-quality-craft-a.ts'), source('repair-task/prompt-lines-quality-craft-b.ts'), source('repair-task/prompt-lines-quality-receipts.ts'), source('repair-task/prompt-lines-quality-repairs.ts')].join('\n')
    const service = writingServiceSource()

    expect(workspaceCenter).toContain('期待债务承接')
    expect(workspaceCenter).toContain('上一章承接')
    expect(workspaceCenter).toContain('交稿风险承接')
    expect(workspaceCenter).toContain('novel-draft-brief-expectation-debt')
    expect(workspaceCenter).toContain('novel-draft-brief-handoff')
    expect(workspaceCenter).toContain('novel-draft-brief-delivery-risk')
    expect(workspaceCenter).toContain('handoffPreviousEnding')
    expect(workspaceCenter).toContain('handoffOpeningObligation')
    expect(workspaceCenter).toContain('deliveryRiskItems')
    expect(workspaceCenter).toContain('deliveryRiskOpeningActions')
    expect(workspaceCenter).toContain('deliveryRiskMiddleActions')
    expect(workspaceCenter).toContain('deliveryRiskEndingActions')
    expect(workspaceCenter).toContain('开篇：')
    expect(workspaceCenter).toContain('中段：')
    expect(workspaceCenter).toContain('章末：')
    expect(workspaceCenter).toContain('deliveryRiskEvidence')
    expect(workspaceCenter).toContain('expectationDebtMustCarry')
    expect(workspaceCenter).toContain('expectationDebtKeepAlive')
    expect(workspaceCenter).toContain('expectationDebtOverdue')
    expect(workspaceCenter).toContain('逾期优先')
    expect(workspaceCss).toContain('.novel-draft-brief-expectation-debt')
    expect(workspaceCss).toContain('.novel-draft-brief-handoff')
    expect(workspaceCss).toContain('.novel-draft-brief-delivery-risk')
    expect(recommendationModel).toContain('reader_expectation_debt')
    expect(recommendationModel).toContain('delivery_risk_carry_over')
    expect(recommendationModel).toContain('deliveryRiskItems')
    expect(recommendationModel).toContain('opening_actions')
    expect(recommendationModel).toContain('middle_actions')
    expect(recommendationModel).toContain('ending_actions')
    expect(recommendationModel).toContain('deliveryRiskOpeningActions')
    expect(recommendationModel).toContain('deliveryRiskMiddleActions')
    expect(recommendationModel).toContain('deliveryRiskEndingActions')
    expect(recommendationModel).toContain('deliveryRiskEvidence')
    expect(recommendationModel).toContain('expectationCarryOver')
    expect(recommendationModel).toContain('expectationDebtOverdue')
    expect(recommendationModel).toContain('expectationDebtSummary')
    expect(recommendationModel).toContain('handoffPreviousEnding')
    expect(recommendationModel).toContain('handoffOpeningObligation')
    expect(service).toContain('buildReaderExpectationDebtContext')
    expect(service).toContain('buildDeliveryRiskCarryOverContext')
    expect(service).toContain('delivery_risk_carry_over')
    expect(service).toContain('reader_expectation_debt_context')
    expect(repairPrompt).toContain('【开篇承接修复】')
    expect(repairPrompt).toContain('重写或补写本章前 300-500 字')
  })

  test('shows chapter handoff between delivery and next draft brief', () => {
    const workspaceCenter = workspaceCenterSource()
    const workspaceCss = source('WorkspaceCenter.css')
    const cockpitModel = writingCockpitModelSource()

    expect(cockpitModel).toContain('chapterHandoffDesk')
    expect(cockpitModel).toContain('buildChapterHandoffDesk')
    expect(workspaceCenter).toContain('chapterHandoffDesk')
    expect(workspaceCenter).toContain('章节交接单')
    expect(workspaceCenter).toContain('novel-chapter-handoff-strip')
    expect(workspaceCenter).toContain('上一章钩子')
    expect(workspaceCenter).toContain('期待承接')
    expect(workspaceCenter).toContain('下一章开场')
    expect(workspaceCenter).toContain('交稿风险')
    expect(workspaceCenter).toContain('deliveryRiskCarryOver')
    expect(workspaceCss).toContain('.novel-chapter-handoff-strip')
    expect(workspaceCss).toContain('.novel-chapter-handoff-strip-ready')
    expect(workspaceCss).toContain('.novel-chapter-handoff-strip-needs_delivery')
    expect(cockpitModel).toContain('deliveryRiskCarryOver')
  })

  test('shows million word runway gate in the auto creation director', () => {
    const workspace = autoCreationDirectorWorkspaceSource()
    const workspaceCss = source('AutoCreationDirectorWorkspace.css')
    const model = directorModelSource()
    const projectWorkspace = projectWorkspaceSource()
    const workspaceCenter = workspaceCenterSource()
    const workspaceCenterCss = source('WorkspaceCenter.css')
    const cockpitModel = writingCockpitModelSource()
    const recommendationModel = writingRecommendationModelSource()
    const service = writingServiceSource()
    const reviewRecords = serverSource('novel-writing/post-delivery-sync-review-record.ts')

    expect(workspace).toContain('百万字航线守门')
    expect(workspace).toContain('millionWordRunway')
    expect(workspace).toContain('auto-director-runway-panel')
    expect(workspaceCss).toContain('.auto-director-runway-panel')
    expect(workspaceCss).toContain('.auto-director-runway-gates')
    expect(model).toContain('AutoCreationMillionWordRunway')
    expect(model).toContain('buildMillionWordRunway')
    expect(model).toContain('fourQuestions')
    expect(projectWorkspace).toContain('millionWordRunway?: any')
    expect(projectWorkspace).toContain('million_word_runway: options?.millionWordRunway')
    expect(projectWorkspace).toContain('million_word_runway: autoCreationDirectorModel.millionWordRunway')
    expect(projectWorkspace).toContain('millionWordRunway: autoCreationDirectorModel.millionWordRunway')
    expect(workspaceCenter).toContain('runwaySync')
    expect(workspaceCenter).toContain('novel-delivery-runway-tag')
    expect(workspaceCenterCss).toContain('.novel-delivery-runway-tag')
    expect(cockpitModel).toContain('runway_sync')
    expect(cockpitModel).toContain('buildRunwaySyncSummary')
    expect(cockpitModel).toContain('补航线')
    expect(recommendationModel).toContain('runwaySync')
    expect(service).toContain("reviewType: 'runway_sync'")
    expect(reviewRecords).toContain('review_type: input.reviewType')
  })

  test('shows innovation sync status in the delivery strip and risk queue', () => {
    const workspaceCenter = workspaceCenterSource()
    const workspaceCss = source('WorkspaceCenter.css')
    const model = writingCockpitModelSource()
    const recommendationModel = writingRecommendationModelSource()
    const service = writingServiceSource()
    const reviewRecords = serverSource('novel-writing/post-delivery-sync-review-record.ts')

    expect(workspaceCenter).toContain('innovationSync')
    expect(workspaceCenter).toContain('novel-delivery-innovation-tag')
    expect(workspaceCss).toContain('.novel-delivery-innovation-tag')
    expect(workspaceCss).toContain('.novel-delivery-innovation-tag-warn')
    expect(model).toContain('innovation_sync')
    expect(model).toContain('补创新')
    expect(recommendationModel).toContain('innovationSync')
    expect(service).toContain("reviewType: 'innovation_sync'")
    expect(reviewRecords).toContain('review_type: input.reviewType')
  })

  test('shows aggregated delivery risk queue in the delivery strip', () => {
    const workspaceCenter = workspaceCenterSource()
    const workspaceCss = source('WorkspaceCenter.css')
    const model = writingCockpitModelSource()
    const recommendationModel = writingRecommendationModelSource()
    const reviewAnnotations = source('ReviewAnnotationsDrawer.tsx')
    const workspace = projectWorkspaceSource()

    expect(workspaceCenter).toContain('deliveryRiskQueue')
    expect(workspaceCenter).toContain('novel-delivery-risk-tag')
    expect(workspaceCss).toContain('.novel-delivery-risk-tag')
    expect(workspaceCss).toContain('.novel-delivery-risk-tag-warn')
    expect(model).toContain('buildDeliveryRiskQueue')
    expect(recommendationModel).toContain('deliveryRiskQueue')
    expect(reviewAnnotations).toContain('交稿风险')
    expect(reviewAnnotations).toContain('DELIVERY_RISK_ANNOTATION_SOURCES')
    expect(reviewAnnotations).toContain('按风险修订')
    expect(reviewAnnotations).toContain('review_type: item.source')
    expect(reviewAnnotations).toContain('targetChapterId: Number(item.chapter_id)')
    expect(reviewAnnotations).toContain('onSelectChapter(Number(item.chapter_id))')
    expect(reviewAnnotations).toContain('categoryFilter')
    expect(reviewAnnotations).toContain('全部类别')
    expect(reviewAnnotations).toContain("value: 'delivery_core'")
    expect(reviewAnnotations).toContain("value: 'reader_expectation'")
    expect(reviewAnnotations).toContain("value: 'reader_retention'")
    expect(reviewAnnotations).toContain("value: 'chapter_attraction'")
    expect(reviewAnnotations).toContain("value: 'story_drive'")
    expect(reviewAnnotations).toContain("value: 'character_arc'")
    expect(reviewAnnotations).toContain("value: 'style_sample'")
    expect(reviewAnnotations).toContain("value: 'innovation'")
    expect(reviewAnnotations).toContain("value: 'storyline'")
    expect(workspace).toContain('按交稿风险生成修订稿')
    expect(workspace).toContain('reader_expectation_sync')
    expect(workspace).toContain('chapter_attraction_review')
    expect(workspace).toContain('story_drive_sync')
    expect(workspace).toContain('character_arc_sync')
    expect(workspace).toContain('style_sample_sync')
  })

  test('shows unresolved delivery risk fuse in the auto creation director', () => {
    const director = autoCreationDirectorWorkspaceSource()
    const directorCss = source('AutoCreationDirectorWorkspace.css')
    const directorModel = directorModelSource()
    const projectWorkspace = projectWorkspaceSource()

    expect(directorModel).toContain('deliveryRiskGate')
    expect(directorModel).toContain('未清交稿风险')
    expect(directorModel).toContain('review_annotation_status')
    expect(directorModel).toContain('signature_scene_sync')
    expect(directorModel).toContain('强场面')
    expect(directorModel).toContain('recentlyResolved')
    expect(director).toContain('auto-director-risk-fuse')
    expect(director).toContain('auto-director-risk-cleared')
    expect(director).toContain('交稿风险熔断')
    expect(director).toContain('交稿风险已清')
    expect(director).toContain('create_delivery_risk_repair')
    expect(director).toContain('deliveryRiskGate: model.deliveryRiskGate')
    expect(director).toContain('model.deliveryRiskGate.categories')
    expect(director).toContain('model.deliveryRiskGate.recentlyResolved')
    expect(directorCss).toContain('.auto-director-risk-fuse')
    expect(directorCss).toContain('.auto-director-risk-fuse-block')
    expect(directorCss).toContain('.auto-director-risk-cleared')
    expect(projectWorkspace).toContain('createDeliveryRiskRepairQueue')
    expect(projectWorkspace).toContain('createDeliveryRiskRepairQueue = async (payload?: AnyRecord)')
    expect(projectWorkspace).toContain('apiClient.post(`/novel/projects/${projectId}/review-annotations/repair-queue`, payload || {})')
    expect(projectWorkspace).toContain('/review-annotations/repair-queue')
    expect(projectWorkspace).toContain('buildDeliveryRiskRevisionClosurePlan')
    expect(projectWorkspace).toContain('closeRepairTaskAfterRevision')
    expect(projectWorkspace).toContain('recheckRepairTaskConvergence')
    expect(projectWorkspace).toContain('/story-state-sync')
    expect(projectWorkspace).toContain('/review-annotations/status')
    expect(projectWorkspace).toContain('sourceTaskIndex')
    const taskCenter = taskCenterSource()
    expect(taskCenter).toContain('交稿风险修复任务')
    expect(taskCenter).toContain('按风险修订')
    expect(taskCenter).toContain('onStartRepairTaskRevision?.(task, run, taskIndex, options)')
    expect(taskCenter).toContain('复检收敛')
    expect(taskCenter).toContain('onRecheckRepairTask(item.task, item.run, item.taskIndex)')
    expect(taskCenter).toContain('核心偏移')
    expect(taskCenter).toContain('追读')
    expect(taskCenter).toContain('回报欠账')
    expect(taskCenter).toContain('剧情线')
    expect(taskCenter).toContain('强场面')
    expect(taskCenter).toContain('可读性')
  })

  test('unifies auto creation action hints and execution type labels', () => {
    const director = autoCreationDirectorWorkspaceSource()
    const directorCss = source('AutoCreationDirectorWorkspace.css')
    const projectWorkspace = projectWorkspaceSource()

    expect(director).toContain('actionExecutionMeta')
    expect(director).toContain('ActionSurfaceButton')
    expect(director).toContain('buildActionTooltip')
    expect(director).toContain('调用大模型')
    expect(director).toContain('本地计算')
    expect(director).toContain('打开面板')
    expect(director).toContain('创建任务')
    expect(director).toContain('后台执行')
    expect(director).toContain('auto-director-action-kind')
    expect(directorCss).toContain('.auto-director-action-kind')
    expect(projectWorkspace).toContain('Promise.resolve(handlePlanningAction')
    expect(projectWorkspace).toContain('Promise.resolve(handleWritingCockpitAction')
    expect(projectWorkspace).toContain('finally(() => setAutoDirectorActionLoadingKey')
  })

  test('offers automatic fixes for preflight character and setting gaps', () => {
    const projectWorkspace = projectWorkspaceSource()
    const repairModel = readFileSync(join(import.meta.dir, './generationPreflightRepairModel.ts'), 'utf8')

    expect(projectWorkspace).toContain('buildGenerationPreflightRepairActions')
    expect(projectWorkspace).toContain('runGenerationPreflightRepairSpec')
    expect(projectWorkspace).toContain('repairGenerationPreflightGaps')
    expect(projectWorkspace).toContain('auto-repair-context')
    expect(projectWorkspace).toContain('settings/incubate-from-project')
    expect(projectWorkspace).toContain('settings-usage/suggest')
    expect(projectWorkspace).toContain("item.type === 'character_created'")
    expect(projectWorkspace).toContain('角色卡已补')
    expect(projectWorkspace).toContain('设定工坊不足')
    expect(projectWorkspace).toContain('本章设定调用不足')
    expect(projectWorkspace).toContain('formatStoryStateSyncFailure')
    expect(projectWorkspace).toContain('正在同步第')
    expect(projectWorkspace).toContain('正在${spec.label || \'补齐材料\'}...')
    expect(repairModel).toContain('补角色卡')
    expect(repairModel).toContain('提炼设定工坊')
    expect(repairModel).toContain('匹配本章设定调用')
    expect(repairModel).toContain('自动补齐角色/设定并继续')
    expect(repairModel).toContain('调用大模型')
    expect(repairModel).toContain('不调用大模型')
  })

  test('routes recovery evidence source actions to single-chapter and batch rechecks', () => {
    const projectWorkspace = projectWorkspaceSource()
    const taskCenter = taskCenterSource()

    expect(taskCenter).toContain('recoveryEvidenceSourceRecheckAction')
    expect(taskCenter).toContain('复检单章')
    expect(taskCenter).toContain('复盘批次')
    expect(taskCenter).toContain('onRecheckRepairTask?.(sourceTask, run')
    expect(taskCenter).toContain('onGenerateRepairAuditSummary?.(run)')
    expect(projectWorkspace).toContain('isSingleChapterRecoveryEvidenceRepairTask')
    expect(projectWorkspace).toContain("source: 'governance_recheck_sync'")
  })

  test('routes recovery evidence residuals into the next repair action', () => {
    const taskCenter = taskCenterSource()

    expect(taskCenter).toContain('residualActionLabel')
    expect(taskCenter).toContain('回修依据')
    expect(taskCenter).toContain('定位批次任务')
    expect(taskCenter).toContain('onStartRepairTaskRevision?.(sourceTask, run')
    expect(taskCenter).toContain('setFocusedTaskIndex(sourceTaskIndex)')
  })

  test('renders task center runs as clear lifecycle cards instead of ambiguous status chips', () => {
    const taskCenter = taskCenterSource()

    expect(taskCenter).toContain('buildTaskRunCardModel')
    expect(taskCenter).toContain('TaskRunCard')
    expect(taskCenter).toContain('task-run-card')
    expect(taskCenter).toContain('运行状态')
    expect(taskCenter).toContain('执行方式')
    expect(taskCenter).toContain('闭环状态')
    expect(taskCenter).toContain('model.timeline.map')
    expect(taskCenter).toContain('model.primaryAction.label')
    expect(taskCenter).toContain('处理下一项')
    expect(taskCenter).toContain('复查任务')
    expect(taskCenter).toContain('查看失败')
  })

  test('shows recovery evidence production block hints after source recheck', () => {
    const taskCenter = taskCenterSource()

    expect(taskCenter).toContain('productionBlockLabel')
    expect(taskCenter).toContain('生产阻断已解除')
    expect(taskCenter).toContain('暂缓安全连写')
    expect(taskCenter).toContain('等待复检结论')
  })

  test('shows delivery risk convergence in the delivery strip', () => {
    const workspaceCenter = workspaceCenterSource()
    const workspaceCss = source('WorkspaceCenter.css')
    const model = writingCockpitModelSource()
    const recommendationModel = writingRecommendationModelSource()
    const editorRoutes = editorRoutesSource()

    expect(workspaceCenter).toContain('deliveryRiskConvergence')
    expect(workspaceCenter).toContain('novel-delivery-convergence-tag')
    expect(workspaceCss).toContain('.novel-delivery-convergence-tag')
    expect(model).toContain('delivery_risk_convergence')
    expect(model).toContain('buildDeliveryRiskConvergenceSummary')
    expect(recommendationModel).toContain('deliveryRiskConvergence')
    expect(editorRoutes).toContain("review_type: 'delivery_risk_convergence'")
  })

  test('shows discovered asset intake in delivery strip and setting workshop', () => {
    const workspaceCenter = workspaceCenterSource()
    const workspaceCss = source('WorkspaceCenter.css')
    const settingPanel = source('SettingWorkshopPanel.tsx')
    const projectWorkspace = projectWorkspaceSource()

    expect(workspaceCenter).toContain('assetIntake')
    expect(workspaceCenter).toContain('novel-delivery-asset-tag')
    expect(workspaceCenter).toContain('onOpenStoryAssets')
    expect(workspaceCss).toContain('.novel-delivery-asset-tag')
    expect(settingPanel).toContain('新资产候选')
    expect(settingPanel).toContain('focusDiscoveredAssetsToken')
    expect(settingPanel).toContain('setting-workshop-model-command')
    expect(settingPanel).toContain('actionLoadingKey')
    expect(settingPanel).toContain('isActionLoading')
    expect(settingPanel).toContain('/discovered-assets/apply')
    expect(settingPanel).toContain('selectedDiscoveredAssetKeys')
    expect(settingPanel).toContain('assetDispositionDrafts')
    expect(settingPanel).toContain("value: 'rename'")
    expect(settingPanel).toContain("value: 'merge'")
    expect(settingPanel).toContain("value: 'cameo'")
    expect(settingPanel).toContain('改名入库')
    expect(settingPanel).toContain('合并已有')
    expect(settingPanel).toContain('一次性过场')
    expect(settingPanel).toContain('merge_target_id')
    expect(settingPanel).toContain('target_name')
    expect(settingPanel).not.toContain('loading={saving}')
    expect(projectWorkspace).toContain('设定资产')
    expect(projectWorkspace).toContain('StoryAssetsWorkspace')
    expect(projectWorkspace).toContain('focusDiscoveredAssetsToken')
  })

  test('shows IP scene intake in delivery strip after story state sync', () => {
    const workspaceCenter = workspaceCenterSource()
    const workspaceCss = source('WorkspaceCenter.css')
    const writingModel = writingCockpitModelSource()
    const recommendationModel = writingRecommendationModelSource()
    const service = writingServiceSource()
    const reviewRecords = serverSource('novel-writing/post-delivery-sync-review-record.ts')

    expect(workspaceCenter).toContain('ipSceneIntake')
    expect(workspaceCenter).toContain('novel-delivery-ip-scene-tag')
    expect(workspaceCenter).toContain('ipSceneIntakeTooltip')
    expect(workspaceCenter).toContain('visualHook')
    expect(workspaceCenter).toContain('adaptationValue')
    expect(workspaceCss).toContain('.novel-delivery-ip-scene-tag')
    expect(writingModel).toContain('ip_scene_intake')
    expect(writingModel).toContain('buildIpSceneIntakeSummary')
    expect(recommendationModel).toContain('ipSceneIntake')
    expect(service).toContain('buildIpSceneIntakeReviewRecord')
    expect(reviewRecords).toContain("review_type: 'ip_scene_intake'")
  })

  test('shows signature scene sync in delivery strip and risk queue', () => {
    const workspaceCenter = workspaceCenterSource()
    const workspaceCss = source('WorkspaceCenter.css')
    const writingModel = writingCockpitModelSource()
    const recommendationModel = writingRecommendationModelSource()
    const service = writingServiceSource()
    const reviewRecords = serverSource('novel-writing/post-delivery-sync-review-record.ts')

    expect(workspaceCenter).toContain('signatureSceneSync')
    expect(workspaceCenter).toContain('novel-delivery-signature-scene-tag')
    expect(workspaceCss).toContain('.novel-delivery-signature-scene-tag')
    expect(workspaceCss).toContain('.novel-delivery-signature-scene-tag-warn')
    expect(writingModel).toContain('signature_scene_sync')
    expect(writingModel).toContain('补强场面')
    expect(recommendationModel).toContain('signatureSceneSync')
    expect(service).toContain("reviewType: 'signature_scene_sync'")
    expect(reviewRecords).toContain('review_type: input.reviewType')
  })

  test('shows readability and restrained meme strategy in writing workflow', () => {
    const workspaceCenter = workspaceCenterSource()
    const workspaceCss = source('WorkspaceCenter.css')
    const projectWorkspace = projectWorkspaceSource()

    expect(workspaceCenter).toContain('readabilityReview')
    expect(workspaceCenter).toContain('novel-delivery-readability-tag')
    expect(workspaceCenter).toContain('aiSmellTactics')
    expect(workspaceCenter).toContain('去AI味建议')
    expect(workspaceCenter).toContain('去AI味门禁')
    expect(workspaceCenter).toContain('deslopGateDiagnostics')
    expect(workspaceCenter).toContain('novel-deslop-gate-panel')
    expect(workspaceCenter).toContain('novel-deslop-gate-card')
    expect(workspaceCenter).toContain('evidence')
    expect(workspaceCenter).toContain('fix')
    expect(workspaceCenter).toContain('本章网感策略')
    expect(workspaceCenter).toContain('novel-draft-brief-meme')
    expect(workspaceCenter).toContain('本章风格样章')
    expect(workspaceCenter).toContain('命中：')
    expect(workspaceCenter).toContain('styleSampleReasons')
    expect(workspaceCenter).toContain('styleSampleControlState')
    expect(workspaceCenter).toContain('锁定样章')
    expect(workspaceCenter).toContain('换一组')
    expect(workspaceCenter).toContain('不用样章')
    expect(workspaceCenter).toContain('onLockStyleSamples')
    expect(workspaceCenter).toContain('onReplaceStyleSamples')
    expect(workspaceCenter).toContain('onDisableStyleSamples')
    expect(projectWorkspace).toContain('/pre-draft-brief/style-samples')
    expect(workspaceCenter).toContain('novel-draft-brief-style-samples')
    expect(workspaceCss).toContain('.novel-draft-brief-style-actions')
    expect(workspaceCenter).toContain('本章质量基准')
    expect(workspaceCenter).toContain('novel-draft-brief-benchmark-samples')
    expect(workspaceCenter).toContain('chapterBenchmarkKeys')
    expect(workspaceCenter).toContain('chapterBenchmarkSync')
    expect(workspaceCenter).toContain('novel-delivery-benchmark-tag')
    expect(workspaceCenter).toContain('storyDriveSync')
    expect(workspaceCenter).toContain('novel-delivery-story-drive-tag')
    expect(workspaceCenter).toContain('characterArcSync')
    expect(workspaceCenter).toContain('novel-delivery-character-arc-tag')
    expect(workspaceCenter).toContain('styleSampleSync')
    expect(workspaceCenter).toContain('novel-delivery-style-sample-tag')
    expect(workspaceCenter).toContain('前30章留存修复')
    expect(workspaceCenter).toContain('novel-draft-brief-first30')
    expect(workspaceCenter).toContain('本批连载任务')
    expect(workspaceCenter).toContain('novel-draft-brief-batch')
    expect(workspaceCss).toContain('.novel-delivery-readability-tag')
    expect(workspaceCss).toContain('.novel-deslop-gate-panel')
    expect(workspaceCss).toContain('.novel-deslop-gate-card')
    expect(workspaceCss).toContain('.novel-deslop-gate-card-warn')
    expect(workspaceCss).toContain('.novel-draft-brief-meme')
    expect(workspaceCss).toContain('.novel-draft-brief-style-samples')
    expect(workspaceCss).toContain('.novel-draft-brief-benchmark-samples')
    expect(workspaceCss).toContain('.novel-delivery-benchmark-tag')
    expect(workspaceCss).toContain('.novel-delivery-story-drive-tag')
    expect(workspaceCss).toContain('.novel-delivery-character-arc-tag')
    expect(workspaceCss).toContain('.novel-delivery-style-sample-tag')
    expect(workspaceCss).toContain('.novel-draft-brief-first30')
    expect(workspaceCss).toContain('.novel-draft-brief-batch')
    expect(projectWorkspace).toContain('网感素材池')
    expect(projectWorkspace).toContain('meme_bank')
    expect(projectWorkspace).toContain('风格样章库 JSON')
    expect(projectWorkspace).toContain('style_sample_bank')
    expect(projectWorkspace).toContain('填入默认风格样本库')
    expect(projectWorkspace).toContain('从高分章节提炼样本候选')
    expect(projectWorkspace).toContain('/writing-bible/style-sample-candidates')
    expect(projectWorkspace).toContain('/writing-bible/style-sample-effectiveness')
    expect(projectWorkspace).toContain('styleSampleEffectiveness')
    expect(projectWorkspace).toContain('样章效果回收')
    expect(projectWorkspace).toContain('命中率')
    expect(projectWorkspace).toContain('表现稳定')
    expect(projectWorkspace).toContain('需复盘')
    expect(projectWorkspace).toContain('调整建议')
    expect(projectWorkspace).toContain('adjustment_suggestion')
    expect(projectWorkspace).toContain('补禁抄短语')
    expect(projectWorkspace).toContain('previewStyleSampleAdjustmentPatch')
    expect(projectWorkspace).toContain('/writing-bible/style-sample-adjustment')
    expect(projectWorkspace).toContain('dry_run')
    expect(projectWorkspace).toContain('样章补丁预览')
    expect(projectWorkspace).toContain('应用补丁')
    expect(projectWorkspace).toContain('patch_json')
    expect(projectWorkspace).toContain('previewStyleSampleAdjustmentBatch')
    expect(projectWorkspace).toContain('/writing-bible/style-sample-adjustments')
    expect(projectWorkspace).toContain('样章批量补丁预览')
    expect(projectWorkspace).toContain('应用全部补丁')
    expect(projectWorkspace).toContain('style_sample_patch_batch')
    expect(projectWorkspace).toContain('undoStyleSampleAdjustmentPatch')
    expect(projectWorkspace).toContain('/writing-bible/style-sample-adjustments/undo')
    expect(projectWorkspace).toContain('撤销上次补丁')
    expect(projectWorkspace).toContain('样章补丁已撤销')
    expect(projectWorkspace).toContain('reviewStyleSampleAdjustmentPatch')
    expect(projectWorkspace).toContain('/writing-bible/style-sample-adjustments/post-apply-review')
    expect(projectWorkspace).toContain('应用后复检')
    expect(projectWorkspace).toContain('样章补丁复检')
    expect(projectWorkspace).toContain('style_sample_patch_review')
    expect(projectWorkspace).toContain('repairStyleSamplePatchReviewSelection')
    expect(projectWorkspace).toContain('换样章并重审任务书')
    expect(projectWorkspace).toContain('recommended_repair_action')
    expect(projectWorkspace).toContain('只学习抽象策略，不复制样章原句')
    expect(projectWorkspace).toContain('applicable_scenes')
    expect(projectWorkspace).toContain('avoid_scenes')
    expect(projectWorkspace).toContain('mergeCommercialWebNovelStyleSampleDefaults')
    expect(projectWorkspace).toContain('章节质量基准样例库 JSON')
    expect(projectWorkspace).toContain('chapter_benchmark_sample_bank')

    const cockpitModel = writingCockpitModelSource()
    const recommendationModel = writingRecommendationModelSource()
    const service = writingServiceSource()
    const reviewRecords = serverSource('novel-writing/post-delivery-sync-review-record.ts')
    expect(cockpitModel).toContain('buildChapterBenchmarkSyncSummary')
    expect(cockpitModel).toContain('chapter_benchmark_sync')
    expect(cockpitModel).toContain('buildStoryDriveSyncSummary')
    expect(cockpitModel).toContain('story_drive_sync')
    expect(cockpitModel).toContain('buildCharacterArcSyncSummary')
    expect(cockpitModel).toContain('character_arc_sync')
    expect(cockpitModel).toContain('buildStyleSampleSyncSummary')
    expect(cockpitModel).toContain('style_sample_sync')
    expect(recommendationModel).toContain('chapterBenchmarkSync')
    expect(recommendationModel).toContain('storyDriveSync')
    expect(recommendationModel).toContain('characterArcSync')
    expect(recommendationModel).toContain('styleSampleSync')
    expect(service).toContain("reviewType: 'chapter_benchmark_sync'")
    expect(service).toContain("reviewType: 'story_drive_sync'")
    expect(service).toContain("reviewType: 'character_arc_sync'")
    expect(service).toContain("reviewType: 'style_sample_sync'")
    expect(reviewRecords).toContain('review_type: input.reviewType')
  })

  test('shows first30 retention curve as a story planning workflow', () => {
    const planningWorkspace = storyPlanningWorkspaceSource()
    const planningModel = planningWorkspaceSource()
    const projectWorkspace = projectWorkspaceSource()
    const taskCenter = taskCenterSource()

    expect(planningWorkspace).toContain('前30章留存曲线')
    expect(planningWorkspace).toContain('novel-first30-retention-card')
    expect(planningWorkspace).toContain('运行前30章诊断')
    expect(planningWorkspace).toContain('生成修复任务')
    expect(planningWorkspace).toContain('开篇三章')
    expect(planningWorkspace).toContain('试读十章')
    expect(planningWorkspace).toContain('付费前蓄势')
    expect(planningModel).toContain('first30Retention')
    expect(planningModel).toContain('run_first30_retention')
    expect(planningModel).toContain('create_first30_repair')
    expect(projectWorkspace).toContain('run_first30_retention')
    expect(projectWorkspace).toContain('create_first30_repair')
  })

  test('shows storyline board as a story planning workflow', () => {
    const planningWorkspace = storyPlanningWorkspaceSource()
    const planningModel = planningWorkspaceSource()
    const projectWorkspace = projectWorkspaceSource()
    const taskCenter = taskCenterSource()

    expect(planningWorkspace).toContain('剧情线看板')
    expect(planningWorkspace).toContain('novel-storyline-board-card')
    expect(planningWorkspace).toContain('逾期未推')
    expect(planningWorkspace).toContain('回收债务')
    expect(planningWorkspace).toContain('影响留存')
    expect(planningWorkspace).toContain('record_storyline_diff_decision')
    expect(planningWorkspace).toContain('recommendedDecision')
    expect(planningWorkspace).toContain('decisionKey')
    expect(planningModel).toContain('storylineBoard')
    expect(planningModel).toContain('settingEntities')
    expect(planningModel).toContain('accept_as_plan')
    expect(planningModel).toContain('false_positive')
    expect(projectWorkspace).toContain('projectSettings')
    expect(projectWorkspace).toContain('record_storyline_diff_decision')
    expect(projectWorkspace).toContain('/storyline-diff-decisions')
    expect(projectWorkspace).toContain('create_storyline_decision_tasks')
    expect(projectWorkspace).toContain('/storyline-diff-decisions/repair-queue')
    expect(projectWorkspace).toContain("source: 'storyline_decision_recheck'")
    expect(projectWorkspace).toContain('storyline_decision_closure')
    expect(planningWorkspace).toContain('生成决策任务')
    expect(taskCenter).toContain('storyline_diff_decision')
    expect(taskCenter).toContain('剧情线决策')
    expect(taskCenter).toContain('同步计划')
    expect(taskCenter).toContain('复检收敛')
  })

  test('shows serial governance hub in the story planning workflow', () => {
    const planningWorkspace = storyPlanningWorkspaceSource()
    const planningModel = planningWorkspaceSource()
    const projectWorkspace = projectWorkspaceSource()

    expect(planningWorkspace).toContain('连载治理中枢')
    expect(planningWorkspace).toContain('novel-governance-hub-card')
    expect(planningWorkspace).toContain('model.governanceHub.primaryAction')
    expect(planningWorkspace).toContain('model.governanceHub.checkpoints')
    expect(planningWorkspace).toContain('生成风险修复任务')
    expect(planningWorkspace).toContain('打开任务中心')
    expect(planningWorkspace).toContain('交稿风险')
    expect(planningWorkspace).toContain('新资产')
    expect(planningModel).toContain('governanceHub')
    expect(planningModel).toContain('create_delivery_risk_repair')
    expect(planningModel).toContain('open_task_center')
    expect(projectWorkspace).toContain('create_delivery_risk_repair')
    expect(projectWorkspace).toContain('createDeliveryRiskRepairQueue')
    expect(projectWorkspace).toContain('open_task_center')
    expect(projectWorkspace).toContain('setTaskCenterOpen(true)')
    expect(projectWorkspace.indexOf('useWorkspaceTasks({')).toBeLessThan(projectWorkspace.indexOf('buildPlanningWorkspaceModel({'))
    expect(projectWorkspace).toContain("workspaceArea === 'storyPlanning'")
    expect(projectWorkspace).toContain('void loadProductionTasks()')
  })

  test('shows longform battle desk as the first daily planning decision surface', () => {
    const planningWorkspace = storyPlanningWorkspaceSource()
    const planningModel = planningWorkspaceSource()

    expect(planningWorkspace).toContain('长篇作战台')
    expect(planningWorkspace).toContain('novel-longform-battle-desk-card')
    expect(planningWorkspace).toContain('model.longformBattleDesk.primaryAction')
    expect(planningWorkspace).toContain('model.longformBattleDesk.lanes')
    expect(planningWorkspace).toContain('核心守恒')
    expect(planningWorkspace).toContain('读者拉力')
    expect(planningWorkspace).toContain('剧情线调度')
    expect(planningWorkspace).toContain('卷级爆点')
    expect(planningWorkspace).toContain('创新/IP场面')
    expect(planningWorkspace).toContain('生产燃料')
    expect(planningModel).toContain('longformBattleDesk')
    expect(planningModel).toContain('buildLongformBattleDeskModel')
  })

  test('shows an AI longform creation pipeline as the top story planning navigator', () => {
    const planningWorkspace = storyPlanningWorkspaceSource()
    const planningModel = planningWorkspaceSource()

    expect(planningWorkspace).toContain('AI长篇创作流水线')
    expect(planningWorkspace).toContain('novel-creation-pipeline-card')
    expect(planningWorkspace).toContain('model.creationPipeline.stages')
    expect(planningWorkspace).toContain('model.creationPipeline.primaryAction')
    expect(planningWorkspace).toContain('全书核心')
    expect(planningWorkspace).toContain('长线规划')
    expect(planningWorkspace).toContain('设定资产')
    expect(planningWorkspace).toContain('章节开写')
    expect(planningWorkspace).toContain('交稿验收')
    expect(planningWorkspace).toContain('连载发布')
    expect(planningWorkspace).toContain('当前建议')
    expect(planningModel).toContain('creationPipeline')
    expect(planningModel).toContain('buildCreationPipelineModel')
    expect(planningModel).toContain('book_core')
    expect(planningModel).toContain('serial_release')
  })

  test('shows serial release desk in the story planning workflow', () => {
    const planningWorkspace = storyPlanningWorkspaceSource()
    const planningModel = planningWorkspaceSource()

    expect(planningWorkspace).toContain('连载发布节奏台')
    expect(planningWorkspace).toContain('novel-serial-release-desk-card')
    expect(planningWorkspace).toContain('model.serialReleaseDesk.primaryAction')
    expect(planningWorkspace).toContain('model.serialReleaseDesk.releaseWindow')
    expect(planningWorkspace).toContain('发布窗口')
    expect(planningWorkspace).toContain('存稿安全线')
    expect(planningWorkspace).toContain('可发布存稿')
    expect(planningWorkspace).toContain('待修订')
    expect(planningWorkspace).toContain('待生成正文')
    expect(planningWorkspace).toContain('待补计划')
    expect(planningModel).toContain('serialReleaseDesk')
    expect(planningModel).toContain('serialization_policy')
    expect(planningModel).toContain('buildSerialReleaseDeskModel')
  })

  test('shows a longform spine guard in the story planning workflow', () => {
    const planningWorkspace = storyPlanningWorkspaceSource()
    const planningModel = planningWorkspaceSource()

    expect(planningWorkspace).toContain('核心契约雷达')
    expect(planningWorkspace).toContain('novel-core-contract-radar-card')
    expect(planningWorkspace).toContain('model.coreContractRadar.checks')
    expect(planningWorkspace).toContain('必须服务')
    expect(planningWorkspace).toContain('不可偏移')
    expect(planningModel).toContain('coreContractRadar')
    expect(planningModel).toContain('buildCoreContractRadarModel')
    expect(planningWorkspace).toContain('全书主轴护栏')
    expect(planningWorkspace).toContain('novel-longform-spine-guard-card')
    expect(planningWorkspace).toContain('model.longformSpineGuard.axes')
    expect(planningWorkspace).toContain('核心卖点')
    expect(planningWorkspace).toContain('不可漂移边界')
    expect(planningWorkspace).toContain('可调整区')
    expect(planningModel).toContain('longformSpineGuard')
    expect(planningModel).toContain('buildLongformSpineGuardModel')
    expect(planningModel).toContain('longform_creation_diagnosis')
  })

  test('shows a million-word milestone map in the story planning workflow', () => {
    const planningWorkspace = storyPlanningWorkspaceSource()
    const planningModel = planningWorkspaceSource()

    expect(planningWorkspace).toContain('百万字里程碑地图')
    expect(planningWorkspace).toContain('novel-million-word-milestone-card')
    expect(planningWorkspace).toContain('model.millionWordMilestones.milestones')
    expect(planningWorkspace).toContain('主角状态')
    expect(planningWorkspace).toContain('世界扩展')
    expect(planningWorkspace).toContain('冲突升级')
    expect(planningWorkspace).toContain('读者回报')
    expect(planningModel).toContain('millionWordMilestones')
    expect(planningModel).toContain('buildMillionWordMilestonesModel')
  })

})
