import type { NovelDraftBriefActionKey } from './writing-recommendation-types-pre-draft'

export type NovelDraftBriefSummary = {
  visible: boolean
  statusLabel: string
  focus: string
  checks: string[]
  actionKey: NovelDraftBriefActionKey | null
  actionLabel: string
  briefFields: {
    chapterGoal: string
    readerPromise: string
    coreConflict: string
    emotionalCurve: string
    blueprintVersion: string
    blueprintTargetEmotion: string
    blueprintOpeningHook: string
    blueprintCorePayoff: string
    blueprintOutline: string
    blueprintPlotLines: string
    blueprintCharacterOrder: string
    blueprintRelationshipChange: string
    blueprintInformationGap: string
    blueprintBeatSequence: string
    blueprintCostAndReward: string
    blueprintEndingContract: string
    blueprintWritingIntent: string
    keySettings: string
    forbiddenContent: string
    storylineAdvances: string
    storylinePlants: string
    storylinePayoffs: string
    storylineForbidden: string
    retentionOpeningHook: string
    retentionPayoffPromise: string
    retentionInformationGap: string
    retentionEmotionalReward: string
    retentionShortDramaScene: string
    retentionEndingQuestion: string
    retentionForbiddenCliches: string
    readerDropRiskStatus: string
    readerDropRisks: string
    readerDropOpening: string
    readerDropMiddle: string
    readerDropEnding: string
    storyPressureSources: string
    storyPressureConflict: string
    storyPressureStakes: string
    storyPressureReversal: string
    storyPressureActions: string
    storyDriveChoice: string
    storyDriveCost: string
    storyDriveChange: string
    storyDriveObstacle: string
    storyDriveNextStep: string
    serialRhythmOpening: string
    serialRhythmPayoffInterval: string
    serialRhythmMiddle: string
    serialRhythmEnding: string
    serialRhythmScenePayoffs: string
    serialRhythmAntiDrag: string
    pageTurnQuestion: string
    pageTurnTrigger: string
    pageTurnPull: string
    pageTurnForbidden: string
    writePreparationStatus: string
    writePreparationSourceGaps: string
    writePreparationAssetRisks: string
    writePreparationDeliveryActions: string
    writePreparationBlueprintFocus: string
    writePreparationReaderPayoff: string
    writePreparationMustConfirm: string
    writePreparationExecutionOrder: string
    expectationCarryOver: string
    expectationDebtMustCarry: string
    expectationDebtKeepAlive: string
    handoffPreviousEnding: string
    handoffOpeningObligation: string
    handoffMustCarry: string
    handoffKeepAlive: string
    deliveryRiskLabel: string
    deliveryRiskItems: string
    deliveryRiskPriority: string
    deliveryRiskActions: string
    deliveryRiskOpeningActions: string
    deliveryRiskMiddleActions: string
    deliveryRiskEndingActions: string
    deliveryRiskEvidence: string
    nextChapterQualityFocus: string
    nextChapterQualityOpening: string
    nextChapterQualityMiddle: string
    nextChapterQualityEnding: string
    nextChapterQualityAvoid: string
    nextChapterQualityEvidence: string
    governanceMemoryStatus: string
    governanceMemorySummary: string
    governanceMemoryEvidence: string
    governanceMemoryFailedEvidence: string
    governanceMemoryWatchItems: string
    expectationMustDeliver: string
    expectationKeepAlive: string
    expectationMustNotBreak: string
    innovationAngle: string
    innovationExecution: string
    innovationGuardrails: string
    innovationIpHooks: string
    signatureScene: string
    signatureSceneTarget: string
    signatureScenePayoff: string
    signatureSceneStoryline: string
    longformBattleStatus: string
    longformBattleSummary: string
    longformBattleRisks: string
    longformBattlePrimaryAction: string
    longformBattleLaneRequirements: string
    longformMemoryStatus: string
    longformMemoryCorePromise: string
    longformMemoryMainline: string
    longformMemoryCharacters: string
    longformMemoryQuestions: string
    longformMemoryPayoffDebts: string
    longformMemoryCanonFacts: string
    longformMemoryRedLines: string
    memeIntensity: string
    memeFunctions: string
    memeForbidden: string
    styleSampleKeys: string
    styleSampleUsage: string
    styleSampleReasons: string
    styleSampleControlState: string
    styleSampleForbidden: string
    chapterBenchmarkKeys: string
    chapterBenchmarkUsage: string
    chapterBenchmarkForbidden: string
    first30RetentionSegment: string
    first30RetentionFlags: string
    first30RetentionActions: string
    first30RetentionFocus: string
    recentFatigueRange: string
    recentFatigueRisks: string
    recentFatigueConflict: string
    recentFatiguePayoff: string
    recentFatigueHook: string
    recentFatigueScene: string
    recentFatigueActions: string
    storyUnitRange: string
    storyUnitRole: string
    storyUnitGoal: string
    storyUnitEntryHook: string
    storyUnitPressure: string
    storyUnitSetup: string
    storyUnitPayoff: string
    storyUnitExitHook: string
    storyUnitForbidden: string
    volumeClimaxRange: string
    volumeClimaxRole: string
    volumeClimaxGoal: string
    volumeClimaxPromise: string
    volumeClimaxRequiredBeats: string
    volumeClimaxForbidden: string
    volumeClimaxNearbyBeats: string
    volumeClimaxNextActions: string
    batchRange: string
    batchGoal: string
    batchReaderPayoff: string
    batchMainlineFocus: string
    batchForbidden: string
    batchCurrentRole: string
    sceneBudget: string
    wordBudget: string
    endingHook: string
  }
}

