export type {
  AnyRecord,
  WritingCockpitRole,
  WritingCockpitActionKey,
  WritingReadinessStatus,
  WritingReadinessCheck,
  WritingCockpitChapter,
  WritingQueueItemStatus,
  WritingQueueItem,
  WritingQueueModel,
  ChapterPlanningReadiness,
  ChapterContextPackageStatus,
  ChapterScenePlanStatus,
  ChapterPlanningDeskSceneCard,
  ChapterQualityContinuitySceneMapItem,
  ChapterWritePreparationBrief,
  ChapterPlanningDeskModel,
  ChapterAcceptanceStatus,
  DeslopGateDiagnosticsModel,
  ChapterAcceptanceDeskModel,
  ChapterHandoffStatus,
  ChapterHandoffDeskModel,
  LongformWorkflowStageKey,
  LongformWorkflowStageStatus,
  LongformWorkflowStageModel,
  LongformWorkflowModel,
  WritingCockpitModel,
  BuildWritingCockpitModelInput,
} from './writing-cockpit/model/types'
import type {
  AnyRecord,
  WritingCockpitRole,
  WritingCockpitActionKey,
  WritingReadinessStatus,
  WritingReadinessCheck,
  WritingCockpitChapter,
  WritingQueueItemStatus,
  WritingQueueItem,
  WritingQueueModel,
  ChapterPlanningReadiness,
  ChapterContextPackageStatus,
  ChapterScenePlanStatus,
  ChapterPlanningDeskSceneCard,
  ChapterQualityContinuitySceneMapItem,
  ChapterWritePreparationBrief,
  ChapterPlanningDeskModel,
  ChapterAcceptanceStatus,
  DeslopGateDiagnosticsModel,
  ChapterAcceptanceDeskModel,
  ChapterHandoffStatus,
  ChapterHandoffDeskModel,
  LongformWorkflowStageKey,
  LongformWorkflowStageStatus,
  LongformWorkflowStageModel,
  LongformWorkflowModel,
  WritingCockpitModel,
  BuildWritingCockpitModelInput,
} from './writing-cockpit/model/types'

import {
  ROLE_META,
  ACTION_LABELS,
  text,
  arrayValue,
  normalizeOhStoryDirector,
  directorPlannerAction,
  directorActionLabel,
  directorPlanningReasons,
  firstNonEmpty,
  deliveryReceiptsFrom,
  uniqueObjects,
  blueprintReceiptLabel,
  blueprintReceiptDelivered,
  blueprintReceiptEvidence,
  isBlueprintReceiptValue,
  blueprintReceiptEntries,
  buildBlueprintReceiptSummary,
  revisionReceiptRemainingRisk,
  revisionReceiptSyncPayload,
  revisionReceiptSyncRiskSummary,
  buildRevisionReceiptSummary,
  deliveryRiskReceiptRemainingRisk,
  buildDeliveryRiskReceiptSummary,
  sceneCardReceiptCheckText,
  sceneCardReceiptCheckFailed,
  buildSceneCardReceiptSummary,
  qualityAuditCheckText,
  qualityAuditCheckFailed,
  buildQualityAuditSummary,
  approvalBlockerLabel,
  buildApprovalBlockerSummary,
  platformRubricLabel,
  platformCheckPassed,
  buildPlatformRubricSummary,
  compactWordCount,
  compactText,
  hasProse,
  sortChapters,
  hasValidId,
  resolveWritingBible,
  resolveStoryState,
  writingBibleExists,
  outlineLevel,
  outlineRange,
  chapterInOutline,
  titleMatches,
  resolveVolume,
  chapterNoFromTitle,
  chapterFromOutline,
  firstArrayText,
  outlineRawPayload,
  outlinePlanPayload,
  chapterPlanFields,
  hasUsableChapterPlan,
  chapterHasOutline,
  materialReady,
  memoryReady,
  stringArray,
  labelStringArray,
  normalizeCoreContractPlan,
  normalizeReaderDropRiskPlan,
  normalizeStoryPressurePlan,
  normalizeStoryDrivePlan,
  normalizeSerialRhythmBudget,
  normalizeSerialRhythmPlan,
  normalizePageTurnHookPlan,
  normalizeVolumeClimaxBeat,
  sortNearbyVolumeClimaxBeats,
  normalizeVolumeClimaxPlan,
  normalizeDeliveryRiskCarryOverPlan,
  uniqueStrings,
  categorizeDeliveryRiskActions,
  previousEnding,
  whyItMatters,
  toCockpitChapter,
  chooseNextChapter,
  buildReadinessChecks,
  resolvePrimaryAction,
  pipelineState,
  chapterPlanSourceLabel,
  missingPlanItems,
  writingQueueAction,
  buildWritingQueue,
  contextPreflight,
  contextTarget,
  relationshipGraphRiskTexts,
  contextContractCandidates,
  sourceGapTextsFromStateTracking,
  normalizeWritePreparationBrief,
  writePreparationReasonTexts,
  blockerTexts,
  contextPackageStatus,
  diagnosticsBlockers,
  rawChapterSceneCards,
  chapterSceneCards,
  qualityContinuityStage,
  buildQualityContinuitySceneMap,
  deliveryRiskCarryOverNeedsSceneMapping,
  parseReviewPayload,
  resolveEditorRevisionChapterId,
  reviewPayload,
  reviewChapterId,
  reviewBelongsToChapter,
  reviewType,
  parsedTime,
  createdTime,
  compareReviewRefs,
  latestReviewRef,
  qualityPayload,
  buildDeslopGateDiagnosticsSummary,
  qualityReviewFinalText,
  proseQualityReviewMatchesCurrentChapter,
  reportPayload,
  revisionPayload,
  storylineSyncPayload,
  countArray,
  buildStorylineSyncSummary,
  storyUnitSyncPayload,
  buildStoryUnitSyncSummary,
  assetIntakePayload,
  buildAssetIntakeSummary,
  ipSceneIntakePayload,
  buildIpSceneIntakeSummary,
  signatureSceneSyncPayload,
  buildSignatureSceneSyncSummary,
  readabilityPayload,
  buildReadabilityReviewSummary,
  coreDriftPayload,
  buildCoreDriftSummary,
  runwaySyncPayload,
  buildRunwaySyncSummary,
  readerPayoffSyncPayload,
  buildReaderPayoffSyncSummary,
  readerExpectationSyncPayload,
  isOpeningHandoffMiss,
  buildReaderExpectationSyncSummary,
  qualityAuditSyncPayload,
  qualityAuditSyncEvidence,
  buildQualityAuditSyncSummary,
  chapterHandoffSyncPayload,
  buildChapterHandoffSyncSummary,
  qualityAuditRepairReceiptSyncPayload,
  buildQualityAuditRepairReceiptSyncSummary,
  contractSyncPayload,
  preDraftExecutionReceiptSections,
  preDraftExecutionCheckNeedsRepair,
  buildPreDraftExecutionSyncSummary,
  mergeContractSyncSummary,
  qualityCheckNeedsRepair,
  buildQualityCheckSummary,
  sceneCardDirectiveCheckText,
  sceneCardDirectiveCheckMatches,
  buildSceneCardDirectiveSummary,
  buildIntentConfirmationSyncSummary,
  buildBenchmarkRecallSyncSummary,
  readerRetentionSyncPayload,
  buildReaderRetentionSyncSummary,
  chapterAttractionPayload,
  buildChapterAttractionSummary,
  storyDriveSyncPayload,
  buildStoryDriveSyncSummary,
  characterArcSyncPayload,
  buildCharacterArcSyncSummary,
  chapterBenchmarkSyncPayload,
  buildChapterBenchmarkSyncSummary,
  styleSampleSyncPayload,
  buildStyleSampleSyncSummary,
  latestFirst30RetentionReview,
  buildFirst30RetentionRecheckSummary,
  innovationSyncPayload,
  buildInnovationSyncSummary,
  volumeBeatSyncPayload,
  buildVolumeBeatSyncSummary,
  buildDeliveryRiskQueue,
  deliveryRiskConvergencePayload,
  buildDeliveryRiskConvergenceSummary,
  governanceRecheckSyncPayload,
  reviewItemTextArray,
  buildGovernanceRecheckSyncSummary,
  extractQualityScore,
  recordValue,
  unwrapStorageEnvelope,
  normalizeAdmissionCandidate,
  recordBelongsToChapter,
  runAdmissionOrder,
  admissionRank,
  runAdmission,
  resolveProseAdmission,
  normalizedAdmissionWarnings,
  normalizedPostCommitWarnings,
  hasUsableProseQualityReview,
  issueText,
  hasHighSeverityIssue,
  extractMustFix,
  extractOptionalImprovements,
  reportBelongsToCurrentQualityCycle,
  storyStateFailureMessages,
  buildStoryStatePanel,
  buildHiddenAcceptanceDesk,
  buildChapterAcceptanceDesk,
  buildHiddenHandoffDesk,
  handoffItemText,
  handoffTextItems,
  buildChapterHandoffDesk,
  buildEpisodePlan,
  buildChapterPlanningDesk,
  workflowStatusFromChecks,
  workflowStatusFromPlanning,
  compactWorkflowEvidence,
  buildLongformWorkflow,
} from './writing-cockpit/model/helpers'

export {
  ROLE_META,
  ACTION_LABELS,
  selectTargetChapterForWriting,
  resolveEditorRevisionChapterId,
} from './writing-cockpit/model/helpers'


export function buildWritingCockpitModel(input: BuildWritingCockpitModelInput): WritingCockpitModel {
  const project = input.project || input.selectedProject || {}
  const outlines = arrayValue(input.outlines)
  const chapters = arrayValue(input.chapters)
  const activeRuns = arrayValue(input.activeRuns || input.runs)
  const nextChapter = chooseNextChapter(chapters, input.activeChapter)
  const sorted = sortChapters(chapters)
  const writtenChapters = sorted.filter(hasProse)
  const latestWrittenChapterNo = Math.max(0, ...writtenChapters.map(chapter => Number(chapter?.chapter_no || 0)))
  const chapterAfterNext = nextChapter
    ? sorted.find(chapter => Number(chapter?.chapter_no || 0) > Number(nextChapter?.chapter_no || 0)) || null
    : null
  const previousChapter = nextChapter
    ? [...writtenChapters].reverse().find(chapter => Number(chapter?.chapter_no || 0) < Number(nextChapter?.chapter_no || 0)) || null
    : writtenChapters[writtenChapters.length - 1] || null

  const writingBible = resolveWritingBible(project)
  const storyState = resolveStoryState(project)
  const volume = resolveVolume(outlines, writingBible, nextChapter)
  const nextChapterOutline = nextChapter ? chapterFromOutline(outlines, nextChapter) : null
  const previousChapterOutline = previousChapter ? chapterFromOutline(outlines, previousChapter) : null
  const writingBibleReady = writingBibleExists(writingBible)
  const volumeGoalReady = Boolean(text(volume.goal))
  const hasChapter = Boolean(nextChapter)
  const chapterOutlineReady = hasChapter ? chapterHasOutline(nextChapter, outlines) : false
  const materialsReady = materialReady(input.materialScore || input.commercialReadiness || input.diagnostics?.material_score || null)
  const storyStateReady = latestWrittenChapterNo === 0 || Number(storyState?.last_updated_chapter || 0) >= latestWrittenChapterNo
  const memorySummaryReady = memoryReady(input.memorySummary || null)
  const nextHasProse = hasProse(nextChapter)

  const readinessChecks = buildReadinessChecks({
    writingBibleReady,
    volumeGoalReady,
    hasChapter,
    chapterOutlineReady,
    materialsReady,
    storyStateReady,
    memoryReady: memorySummaryReady,
  })
  const readinessBlockers = readinessChecks.filter(check => check.status === 'blocker')
  const readinessWarnings = readinessChecks.filter(check => check.status === 'warning')
  const blockers = readinessBlockers.map(check => check.key)
  const cockpitNextChapter = nextChapter ? toCockpitChapter(nextChapter, { previousChapter, volumeGoal: volume.goal, outline: nextChapterOutline }) : null
  const cockpitPreviousChapter = previousChapter ? toCockpitChapter(previousChapter, { volumeGoal: volume.goal, outline: previousChapterOutline }) : null
  const chapterPlanningDesk = buildChapterPlanningDesk({
    nextChapter,
    cockpitChapter: cockpitNextChapter,
    contextPackage: input.contextPackage || null,
    diagnostics: input.diagnostics || null,
  })
  const reviews = arrayValue(input.reviews)
  const chapterAcceptanceDesk = buildChapterAcceptanceDesk({
    nextChapter,
    cockpitChapter: cockpitNextChapter,
    reviews,
    activeRuns,
    storyState,
  })
  const chapterHandoffDesk = buildChapterHandoffDesk({
    fromChapter: nextChapter,
    toChapter: chapterAfterNext,
    acceptanceDesk: chapterAcceptanceDesk,
    reviews,
  })
  const longformWorkflow = buildLongformWorkflow({
    readinessChecks,
    chapterPlanningDesk,
    chapterAcceptanceDesk,
  })
  const fallbackPrimary = resolvePrimaryAction({
    writingBibleReady,
    hasChapter,
    chapterOutlineReady,
    materialsReady,
    nextHasProse,
    storyStateReady,
  })
  const acceptanceAction = chapterAcceptanceDesk.visible
    ? chapterAcceptanceDesk.recommendedAcceptanceAction.key
    : null
  const primary = acceptanceAction
    ? { role: 'revision_editor' as WritingCockpitRole, action: acceptanceAction }
    : fallbackPrimary
  const { role, action } = primary

  return {
    topStatus: {
      projectTitle: text(project?.title, '未命名项目'),
      currentVolume: volume.title,
      writtenWords: writtenChapters.reduce((sum, chapter) => sum + compactWordCount(chapter?.chapter_text), 0),
      currentRoleLabel: ROLE_META[role].label,
      nextActionLabel: ACTION_LABELS[action],
      primaryActionKey: action,
    },
    nextChapter: cockpitNextChapter,
    previousChapter: cockpitPreviousChapter,
    chapterPlanningDesk,
    chapterAcceptanceDesk,
    chapterHandoffDesk,
    longformWorkflow,
    primaryActionKey: action,
    recommendedRole: role,
    readiness: {
      checks: readinessChecks,
      blockers: readinessBlockers,
      warnings: readinessWarnings,
    },
    blockers,
    readinessChecks,
    modelTeam: {
      recommendedRole: role,
      roles: (Object.keys(ROLE_META) as WritingCockpitRole[]).map(key => ({
        key,
        label: ROLE_META[key].label,
        description: key === 'operations_analyst' && activeRuns.length > 0
          ? `${ROLE_META[key].description}当前有 ${activeRuns.length} 个运行记录。`
          : ROLE_META[key].description,
        actionKey: ROLE_META[key].actionKey,
        active: key === role,
      })),
    },
    draftPipeline: pipelineState(nextChapter),
    writingQueue: buildWritingQueue(chapters, outlines, nextChapter),
    canonUpdatePreview: [
      '同步最近已写章节的关键事实',
      '检查人物立场与伏笔状态',
      '更新下一章可引用的王府人心变化',
    ],
  }
}
