/** Compatibility barrel. Prefer importing from the package root (`../novel-writing-service`). */
import './service/runtime-bindings'

export * from './quality/admission-error'
export * from './quality/structured-review-fields'
export * from './quality/review-status'
export * from './quality/text-utils'
export * from './quality/platform-carry-over'
export * from './quality/word-count-guard'
export * from './quality/review-merge'
export * from './quality/prose-quality-entry'
export * from './quality/revision-receipt-risk'
export * from './quality/pre-draft-receipt-sections'
export * from './quality/review-fill'
export * from './quality/missing-review-checks'
export * from './quality/prose-expansion'
export * from './context/context-contract'
export * from './revision/revision-artifacts'
export * from './revision/revision-strategy'
export * from './quality/review-lookup'
export * from './batch-serial/serial-momentum'
export * from './quality/serial-risk-repair'
export * from './batch-serial/ending-hook-type'
export * from './post-delivery/asset-banks'
export * from './quality/five-dimension-scores'
export * from './quality/receipt-evidence'
export * from './post-delivery/delivery-risk-core'
export * from './quality/prose-quality-risks'
export * from './quality/craft-tension-contracts'
export * from './quality/plot-opening-prose-contracts'
export * from './quality/audience-quality-contracts'
export * from './quality/character-asset-contracts'
export * from './quality/state-tracking-contracts'
export * from './quality/intent-benchmark-contracts'
export * from './quality/continuity-dialogue-contracts'
export * from './quality/outline-blueprint-contracts'
export * from './quality/chapter-blueprint-execution'
export * from './quality/preflight-auto-repair'
export * from './quality/platform-content-rubrics'
export * from './quality/write-preparation-contracts'
export * from './quality/style-sample-strategy'
export * from './quality/pre-draft-brief'
export * from './quality/character-arc-brief'
export * from './quality/blueprint-function-tag'
export * from './quality/prose-transport-admission'
export * from './quality/paragraph-prose-context'
export * from './quality/core-contract-radar'
export * from './quality/memory-longform-contracts'
export * from './post-delivery/artifact-protocol'
export * from './post-delivery/delivery-risk-carry-over'
export * from './post-delivery/chapter-handoff-contracts'
export * from './post-delivery/delta-sync-reports'
export * from './post-delivery/core-handoff-sync-reports'
export * from './post-delivery/quality-sync-reports'
export * from './post-delivery/scene-cards'
export * from './post-delivery/scene-card-delivery-risk'
export * from './service/runtime-helpers'
export * from './service/story-state-helpers'
export * from './service/writing-bible'
export * from './service/story-state-machine'
export * from './service/prose-polish-methods'
export * from './public-novel-writing-surface'

export { createStoryStateMachineMethods } from './service/story-state-machine'
export { createProsePolishMethods } from './service/prose-polish-methods'
export { createSceneCardsMethods } from './service/scene-cards-methods'
export { createStructuredReviewFillMethods } from './service/structured-review-fill-methods'
export { createProseWordTargetMethods } from './service/prose-word-target-methods'
export { buildChapterContextPackage as buildChapterContextPackageModule } from './service/chapter-context-package'
export { createAutoRepairChapterPreflightMethods } from './service/auto-repair-preflight-methods'
export { createProseSelfReviewMethods } from './service/prose-self-review-methods'
export { buildParagraphProseContext as buildParagraphProseContextModule } from './service/paragraph-prose-context'
export { createGenerateChapterForGroupMethods } from './service/generate-chapter-for-group-methods'
export { createNovelWritingService, type NovelWritingService, type NovelWritingRuntime } from './service/create-novel-writing-service'
export {
  buildHeuristicSettingUsage,
  selectProseForChapter,
  throwIfAborted,
  isAbortError,
} from './service/runtime-helpers'
export {
  normalizeStoryStateDeltaForStorage,
  mergeStoryState,
} from './service/story-state-helpers'
export {
  buildWritingBible,
  hasMeaningfulWritingBible,
  getStoredOrBuiltWritingBible as getStoredOrBuiltWritingBibleCore,
} from './service/writing-bible'
export type { ProseTransportTruncationCode } from './quality/prose-transport-admission'

