export const STRUCTURED_REVIEW_CHECK_FIELDS = [
  ['platform_checks', 'platformChecks'],
  ['content_rubric_checks', 'contentRubricChecks'],
  ['factual_checks', 'factualChecks'],
  ['innovation_checks', 'innovationChecks'],
  ['chapter_attraction_checks', 'chapterAttractionChecks'],
  ['story_drive_checks', 'storyDriveChecks'],
  ['character_arc_checks', 'characterArcChecks'],
  ['chapter_benchmark_checks', 'chapterBenchmarkChecks'],
  ['title_uniqueness_checks', 'titleUniquenessChecks'],
  ['banned_words_checks', 'bannedWordsChecks'],
  ['blueprint_consumption_checks', 'blueprintConsumptionChecks'],
  ['word_count_checks', 'wordCountChecks'],
  ['reader_retention_checks', 'readerRetentionChecks'],
  ['target_reader_checks', 'targetReaderChecks'],
  ['genre_positioning_checks', 'genrePositioningChecks'],
  ['plot_special_topics_checks', 'plotSpecialTopicsChecks'],
  ['core_contract_checks', 'coreContractChecks'],
  ['female_audience_checks', 'femaleAudienceChecks'],
  ['upgrade_rhythm_checks', 'upgradeRhythmChecks'],
  ['structure_checks', 'structureChecks'],
  ['progression_checks', 'progressionChecks'],
  ['information_checks', 'informationChecks'],
  ['conflict_structure_checks', 'conflictStructureChecks'],
  ['deslop_checks', 'deslopChecks'],
  ['prose_meta_checks', 'proseMetaChecks'],
  ['dialogue_checks', 'dialogueChecks'],
  ['plot_dynamics_checks', 'plotDynamicsChecks'],
  ['mainline_definition_checks', 'mainlineDefinitionChecks'],
  ['story_power_checks', 'storyPowerChecks'],
  ['continuity_heat_checks', 'continuityHeatChecks'],
  ['character_relation_checks', 'characterRelationChecks'],
  ['character_behavior_checks', 'characterBehaviorChecks'],
  ['asset_linkage_checks', 'assetLinkageChecks'],
  ['state_tracking_checks', 'stateTrackingChecks'],
  ['story_state_update_checks', 'storyStateUpdateChecks'],
  ['foreshadowing_delta_checks', 'foreshadowingDeltaChecks'],
  ['source_readiness_checks', 'sourceReadinessChecks'],
  ['artifact_protocol_receipts', 'artifactProtocolReceipts'],
  ['write_preparation_checks', 'writePreparationChecks'],
  ['next_chapter_quality_plan_receipts', 'nextChapterQualityPlanReceipts'],
  ['chapter_handoff_checks', 'chapterHandoffChecks'],
  ['intent_confirmation_checks', 'intentConfirmationChecks'],
  ['benchmark_recall_checks', 'benchmarkRecallChecks'],
  ['style_boundary_checks', 'styleBoundaryChecks'],
  ['style_sample_checks', 'styleSampleChecks'],
  ['information_flow_checks', 'informationFlowChecks'],
  ['expectation_threshold_checks', 'expectationThresholdChecks'],
  ['story_loop_checks', 'storyLoopChecks'],
  ['emotional_arc_checks', 'emotionalArcChecks'],
  ['chapter_hook_checks', 'chapterHookChecks'],
  ['chapter_hook_quality_checks', 'chapterHookQualityChecks'],
  ['paragraph_hook_checks', 'paragraphHookChecks'],
  ['suspense_checks', 'suspenseChecks'],
  ['reversal_checks', 'reversalChecks'],
  ['showdown_checks', 'showdownChecks'],
  ['bridge_unit_checks', 'bridgeUnitChecks'],
  ['opening_checks', 'openingChecks'],
  ['prose_craft_checks', 'proseCraftChecks'],
  ['serial_risk_repair_checks', 'serialRiskRepairChecks'],
  ['punctuation_tone_checks', 'punctuationToneChecks'],
  ['longform_checks', 'longformChecks'],
  ['revision_receipt_checks', 'revisionReceiptChecks'],
  ['deslop_repair_checks', 'deslopRepairChecks'],
  ['status_filter_receipts', 'statusFilterReceipts'],
  ['quality_audit_checks', 'qualityAuditChecks'],
]

export const STRUCTURED_REVIEW_REQUIRED_FIELDS: Record<string, string[]> = {
  content_rubric_checks: [
    'key',
    'label',
    'status',
    'core_selling_point',
    'conflict_progression',
    'chapter_change',
    'page_turn_reason',
    'evidence',
    'fix',
    'remaining_risk',
  ],
  quality_audit_checks: [
    'key',
    'label',
    'status',
    'strategy',
    'purpose_tag',
    'density_change',
    'conflict_bound_info',
    'changed_evidence',
    'fix',
    'remaining_risk',
  ],
  core_contract_checks: [
    'key',
    'label',
    'status',
    'core_promise',
    'mainline_service',
    'core_emotion',
    'rule_judgement',
    'ending_question',
    'evidence',
    'fix',
    'remaining_risk',
  ],
  innovation_checks: [
    'key',
    'label',
    'status',
    'innovation_type',
    'differentiating_mechanism',
    'visualized_scene',
    'reader_retellable_hook',
    'long_term_fit',
    'evidence',
    'fix',
    'remaining_risk',
  ],
  chapter_attraction_checks: [
    'key',
    'label',
    'status',
    'attraction_dimension',
    'opening_hook',
    'scene_goal_obstacle_turn_reward',
    'payoff_density',
    'ending_page_turn',
    'spreadable_scene',
    'evidence',
    'fix',
    'remaining_risk',
  ],
  story_drive_checks: [
    'key',
    'label',
    'status',
    'protagonist_choice',
    'obstacle',
    'cost',
    'state_change',
    'next_causality',
    'evidence',
    'fix',
    'remaining_risk',
  ],
  character_arc_checks: [
    'key',
    'label',
    'status',
    'character',
    'desire',
    'flaw_pressure',
    'relationship_change',
    'growth_beat',
    'voice_anchor',
    'evidence',
    'fix',
    'remaining_risk',
  ],
  chapter_benchmark_checks: [
    'key',
    'label',
    'status',
    'benchmark_dimension',
    'expected_method',
    'delivered_evidence',
    'originality_guard',
    'fix',
    'remaining_risk',
  ],
  title_uniqueness_checks: [
    'key',
    'label',
    'status',
    'old_title',
    'new_title',
    'outline_title_synced',
    'file_name_synced',
    'chapter_title_line_synced',
    'evidence',
    'remaining_risk',
  ],
  prose_meta_checks: [
    'key',
    'label',
    'status',
    'matched_term',
    'location',
    'replacement',
    'evidence',
    'remaining_risk',
  ],
  banned_words_checks: [
    'key',
    'label',
    'status',
    'matched_word',
    'level',
    'location',
    'replacement',
    'evidence',
    'remaining_risk',
  ],
  blueprint_consumption_checks: [
    'key',
    'label',
    'status',
    'blueprint_field',
    'expected',
    'delivered_evidence',
    'missing_gap',
    'fix',
    'remaining_risk',
  ],
  word_count_checks: [
    'key',
    'label',
    'status',
    'current_count',
    'target_count',
    'min_required_count',
    'evidence',
    'remaining_risk',
  ],
  chapter_handoff_checks: [
    'key',
    'label',
    'status',
    'previous_handoff',
    'opening_obligation',
    'opening_evidence',
    'location',
    'continuity_action',
    'remaining_risk',
  ],
  story_state_update_checks: [
    'key',
    'label',
    'status',
    'state_domain',
    'target_file',
    'update_path',
    'before_state',
    'after_state',
    'source_excerpt',
    'evidence',
    'fix',
    'remaining_risk',
  ],
  source_readiness_checks: [
    'key',
    'label',
    'status',
    'source_name',
    'source_path',
    'read_status',
    'used_as_fact',
    'chapter_evidence',
    'fix',
    'remaining_risk',
  ],
  artifact_protocol_receipts: [
    'key',
    'label',
    'status',
    'artifact_path',
    'required_fields',
    'used_fields',
    'evidence',
    'fix',
    'remaining_risk',
  ],
  factual_checks: [
    'key',
    'label',
    'status',
    'fact_type',
    'claim',
    'verification_status',
    'evidence',
    'fix',
    'remaining_risk',
  ],
  write_preparation_checks: [
    'key',
    'label',
    'status',
    'preparation_type',
    'expected',
    'delivered_evidence',
    'chapter_location',
    'fix',
    'remaining_risk',
  ],
  reader_retention_checks: [
    'key',
    'label',
    'status',
    'retention_engine',
    'emotional_payoff',
    'information_hunger',
    'page_turn_question',
    'evidence',
    'fix',
    'remaining_risk',
  ],
  target_reader_checks: [
    'key',
    'label',
    'status',
    'target_reader_profile',
    'reader_desire',
    'emotion_gap',
    'chapter_hit',
    'platform_taste',
    'evidence',
    'fix',
    'remaining_risk',
  ],
  genre_positioning_checks: [
    'key',
    'label',
    'status',
    'genre_tag',
    'core_hook',
    'type_formula',
    'genre_strength',
    'book_title_blurb_alignment',
    'evidence',
    'fix',
    'remaining_risk',
  ],
  intent_confirmation_checks: [
    'key',
    'label',
    'status',
    'intent_field',
    'expected_intent',
    'delivered_evidence',
    'blueprint_link',
    'fix',
    'remaining_risk',
  ],
  benchmark_recall_checks: [
    'key',
    'label',
    'status',
    'source_type',
    'source_path',
    'expected_application',
    'delivered_evidence',
    'gaps_preserved',
    'fix',
    'remaining_risk',
  ],
  style_sample_checks: [
    'key',
    'label',
    'status',
    'style_dimension',
    'source_technique',
    'adapted_evidence',
    'copied_phrase_rewritten',
    'fix',
    'remaining_risk',
  ],
  style_boundary_checks: [
    'key',
    'label',
    'status',
    'reference_risk',
    'rewritten_with_local_action',
    'voice_anchor',
    'copied_phrase_removed',
    'evidence',
    'fix',
    'remaining_risk',
  ],
  plot_special_topics_checks: [
    'key',
    'label',
    'status',
    'matched_topics',
    'goldfinger_execution',
    'genre_boundary_execution',
    'market_benchmark_execution',
    'urban_high_martial_execution',
    'launch_checkpoint_execution',
    'faction_hand_execution',
    'evidence',
    'fix',
    'remaining_risk',
  ],
  female_audience_checks: [
    'key',
    'label',
    'status',
    'security_anchor',
    'reader_identification',
    'heroine_agency',
    'relationship_axis',
    'post_abuse_payoff',
    'evidence',
    'fix',
    'remaining_risk',
  ],
  upgrade_rhythm_checks: [
    'key',
    'label',
    'status',
    'before_after_contrast',
    'instant_feedback',
    'delayed_feedback',
    'new_threshold',
    'cheat_rule',
    'evidence',
    'fix',
    'remaining_risk',
  ],
  structure_checks: [
    'key',
    'label',
    'status',
    'opening_hook',
    'middle_progression',
    'situation_change',
    'ending_page_turn',
    'evidence',
    'fix',
    'remaining_risk',
  ],
  progression_checks: [
    'key',
    'label',
    'status',
    'non_deletable_change',
    'mainline_shift',
    'relationship_or_state_change',
    'compressed_water',
    'evidence',
    'fix',
    'remaining_risk',
  ],
  information_checks: [
    'key',
    'label',
    'status',
    'new_concept_count',
    'action_bound_info',
    'conflict_release',
    'reader_first_scene',
    'evidence',
    'fix',
    'remaining_risk',
  ],
  information_flow_checks: [
    'key',
    'label',
    'status',
    'reveal_order',
    'withheld_question',
    'action_bound_release',
    'conflict_or_cost',
    'evidence',
    'fix',
    'remaining_risk',
  ],
  expectation_threshold_checks: [
    'key',
    'label',
    'status',
    'reader_question',
    'stakes',
    'choice_pressure',
    'payoff_promise',
    'next_chapter_pull',
    'evidence',
    'fix',
    'remaining_risk',
  ],
  story_loop_checks: [
    'key',
    'label',
    'status',
    'setup_question',
    'obstacle',
    'choice',
    'cost',
    'payoff_or_answer_fragment',
    'new_question',
    'evidence',
    'fix',
    'remaining_risk',
  ],
  emotional_arc_checks: [
    'key',
    'label',
    'status',
    'calm_or_pressure',
    'mobilization',
    'counteraction',
    'release',
    'reader_payoff',
    'evidence',
    'fix',
    'remaining_risk',
  ],
  chapter_hook_checks: [
    'key',
    'label',
    'status',
    'hook_position',
    'trigger',
    'reader_question',
    'next_chapter_pressure',
    'delivered_evidence',
    'fix',
    'remaining_risk',
  ],
  paragraph_hook_checks: [
    'key',
    'label',
    'status',
    'paragraph_range',
    'hook_type',
    'micro_change',
    'information_or_risk_delta',
    'emotion_or_relation_delta',
    'evidence',
    'fix',
    'remaining_risk',
  ],
  suspense_checks: [
    'key',
    'label',
    'status',
    'question',
    'misdirect',
    'partial_answer',
    'new_expectation',
    'evidence',
    'fix',
    'remaining_risk',
  ],
  conflict_structure_checks: [
    'key',
    'label',
    'status',
    'blocker',
    'no_exit_condition',
    'stakes_or_exit_cost',
    'action_block',
    'win_loss_result',
    'evidence',
    'fix',
    'remaining_risk',
  ],
  opening_checks: [
    'key',
    'label',
    'status',
    'protagonist_entry',
    'first_300_goal',
    'first_1000_expectation',
    'opening_principle',
    'evidence',
    'fix',
    'remaining_risk',
  ],
  bridge_unit_checks: [
    'key',
    'label',
    'status',
    'bridge_position',
    'old_expectation_payoff',
    'new_expectation_seed',
    'goal_progression',
    'climax_hook',
    'stage_handoff',
    'evidence',
    'fix',
    'remaining_risk',
  ],
  reversal_checks: [
    'key',
    'label',
    'status',
    'reversal_type',
    'fair_clues',
    'misdirect',
    'reveal_timing',
    'impact_after_reveal',
    'evidence',
    'fix',
    'remaining_risk',
  ],
  showdown_checks: [
    'key',
    'label',
    'status',
    'payoff_release',
    'trump_card_used',
    'pressure_layers',
    'audience_reactions',
    'consequence',
    'next_threshold',
    'evidence',
    'fix',
    'remaining_risk',
  ],
  prose_craft_checks: [
    'key',
    'label',
    'status',
    'pov_depth',
    'body_detail',
    'environment_interaction',
    'action_stillness_balance',
    'crowd_reaction_layering',
    'evidence',
    'fix',
    'remaining_risk',
  ],
  punctuation_tone_checks: [
    'key',
    'label',
    'status',
    'speaker',
    'punctuation_issue',
    'tone_intent',
    'replacement',
    'voice_difference',
    'evidence',
    'fix',
    'remaining_risk',
  ],
  chapter_hook_quality_checks: [
    'key',
    'label',
    'status',
    'hook_position',
    'trigger_type',
    'concrete_question',
    'danger_or_choice',
    'next_action_link',
    'evidence',
    'fix',
    'remaining_risk',
  ],
  asset_linkage_checks: [
    'key',
    'label',
    'status',
    'asset_name',
    'function',
    'ownership',
    'trigger_condition',
    'limitation',
    'consequence',
    'story_link',
    'evidence',
    'fix',
    'remaining_risk',
  ],
  dialogue_checks: [
    'key',
    'label',
    'status',
    'speaker',
    'agenda',
    'subtext',
    'power_shift',
    'information_delta',
    'character_voice',
    'evidence',
    'fix',
    'remaining_risk',
  ],
  plot_dynamics_checks: [
    'key',
    'label',
    'status',
    'goal',
    'obstacle',
    'action',
    'cost_or_feedback',
    'new_expectation',
    'evidence',
    'fix',
    'remaining_risk',
  ],
  story_power_checks: [
    'key',
    'label',
    'status',
    'story_power_dimension',
    'action_changed_situation',
    'beginning_to_end_change',
    'causal_feedback',
    'evidence',
    'fix',
    'remaining_risk',
  ],
  continuity_heat_checks: [
    'key',
    'label',
    'status',
    'heat_state',
    'hot_progress',
    'warm_keepalive',
    'cold_warmup',
    'archived_boundary',
    'evidence',
    'fix',
    'remaining_risk',
  ],
  character_relation_checks: [
    'key',
    'label',
    'status',
    'relation_type',
    'protagonist_goal',
    'agency_choice',
    'cost',
    'relation_shift',
    'buffer_zone',
    'evidence',
    'fix',
    'remaining_risk',
  ],
  character_behavior_checks: [
    'key',
    'label',
    'status',
    'character',
    'concrete_motive',
    'emotional_reason',
    'trigger_change',
    'visible_choice',
    'cost',
    'evidence',
    'fix',
    'remaining_risk',
  ],
  state_tracking_checks: [
    'key',
    'label',
    'status',
    'state_subject',
    'state_type',
    'previous_state',
    'allowed_state',
    'used_in_chapter',
    'evidence',
    'excluded_reason',
    'fix',
    'remaining_risk',
  ],
  serial_risk_repair_checks: [
    'key',
    'label',
    'status',
    'risk_type',
    'repair_receipt',
    'continuity_change',
    'state_change',
    'evidence',
    'fix',
    'remaining_risk',
  ],
  longform_checks: [
    'key',
    'label',
    'status',
    'recent_5_chapter_progress',
    'payoff_interval',
    'stage_goal_shift',
    'next_stage_pull',
    'context_layer',
    'evidence',
    'fix',
    'remaining_risk',
  ],
  revision_receipt_checks: [
    'key',
    'label',
    'status',
    'required_action',
    'repair_segment',
    'applied_fix',
    'changed_evidence',
    'evidence',
    'fix',
    'remaining_risk',
  ],
  deslop_repair_checks: [
    'key',
    'label',
    'status',
    'gate',
    'original_risk',
    'rewritten_evidence',
    'changed_evidence',
    'receipt_synced',
    'fix',
    'remaining_risk',
  ],
  status_filter_receipts: [
    'key',
    'label',
    'used_in_chapter',
    'evidence',
    'excluded_reason',
    'remaining_risk',
  ],
  next_chapter_quality_plan_receipts: [
    'key',
    'label',
    'delivered',
    'evidence',
    'remaining_risk',
  ],
  foreshadowing_delta_checks: [
    'key',
    'label',
    'status',
    'clue_name',
    'delta_type',
    'current_status',
    'chapter',
    'source_excerpt',
    'ledger_path',
    'fix',
    'remaining_risk',
  ],
}

