import { buildProsePromptContextSnapshot, prosePromptJson } from './prose-prompt-context'
import {
  buildWritingPrecisionPlan,
  formatSceneCardPrecisionPrompt,
} from './writing-precision-prompt'

export function buildSceneCardsPrompt(project: any, contextPackage: any) {
  const cleanContext = buildProsePromptContextSnapshot(contextPackage)
  const writingPrecisionPlan = buildWritingPrecisionPlan({
    contextPackage,
    modelRuntime: contextPackage?.runtime_model || contextPackage?.model_runtime || null,
    modelFamilyStrategy: contextPackage?.model_family_strategy || null,
  })
  return [
    '任务：为当前章节生成可人工确认的场景卡。场景卡是正文生成前的蓝图，不要写完整正文。',
    ...formatSceneCardPrecisionPrompt(writingPrecisionPlan),
    `作品标题：${project.title}`,
    `目标章节：第${contextPackage?.chapter_target?.chapter_no || '?'}章《${contextPackage?.chapter_target?.title || '无标题'}》`,
    '必须以 chapter_target.summary、chapter_target.conflict、chapter_target.ending_hook 为准重建本章场景卡。',
    '如果上下文里已有 scene_cards 与本章目标不一致，视为旧草稿，必须忽略。',
    '本次不是生成总纲、分卷或章节大纲。严禁输出 master_outline、volume_outlines、chapter_outlines、foreshadowing_plan。',
    '只允许围绕目标章节生成 2-6 个 scene_cards；不得输出其他章节内容。',
    '',
    '【结构化上下文包】',
    prosePromptJson(cleanContext, 9000),
    '',
    '输出 JSON，字段 scene_cards(array)。每个场景卡包含：scene_no, title, scene_type, location, characters_present(array), pov_lens(object: pov_character, knows_now(array), suspects_now(array), does_not_know(array), want_now, fear_or_cost_now, private_bias, allowed_senses(array), decision_in_scene, emotion_from_pov, emotion_tell), purpose_tag, purpose_tags(array), chapter_positioning, pressure_level, chapter_positioning_role, benchmark_structure_coordinate, purpose, conflict, conflict_ladder_step, motivation_source, opposing_force, blocked_desire, protagonist_agency_action, no_exit_reason, event_value_change, next_conflict_seed, visible_line_role, hidden_line_seed, ab_weave_role, required_beats(array), action_beats(array), beat, opening_hook, reader_payoff, fear_point, rule_pressure, information_gap, reversal, ending_hook_seed, character_voice, dialogue_goals(array), style_directives(array), benchmark_recall_directives(array), concept_anchor_rules(array), prose_craft_directives(array), relationship_progression_plan, relationship_buffer_zone, supporting_character_action, attitude_shift_checkpoint, relationship_next_hook, showoff_stage_chain, spectator_interest_shift, secondary_showoff_effect, combat_result_type, combat_dimension_plan, combat_reversal_plan, sensory_anchor, serial_risk_repairs(array), recent_fatigue_action, emotional_tone, key_dialogue, dialogue_goal, required_information(array), used_settings(array), revealed_settings(array), forbidden_settings(array), ability_beats(array), item_beats(array), boss_move, rule_trigger, state_changes_expected(array), turning_point, description_budget, density_level, transition_from_previous, exit_state。',
    '章节定位：每张场景卡必须填写 chapter_positioning，取值参考 高压/推进/修炼试错/关系回收/低压生活/信息整理；pressure_level 用 1-5 表示冲突压力；chapter_positioning_role 写明本场怎样服务本章定位，避免所有章节同一强度。',
    '对标结构坐标：如果 contextPackage.chapter_target.chapter_positioning_brief.benchmark_structure_coordinates 或场景已有 benchmark_structure_coordinate，必须把对标结构坐标迁移为本章本场的 normalized_position/source_event/local_event/event_type，学习结构功能位，不复制桥段。',
    'scene_type 只能取：action/combat/chase/investigation/dialogue/reveal/emotion/transition/hook。凡是本章有战斗、追逐、灾祸、清剿、冲突升级，必须至少有一个 action/combat/chase 场景。',
    '商业读者钩子：每个场景至少落实 opening_hook/reader_payoff/fear_point/rule_pressure/information_gap/reversal/ending_hook_seed 中的一项，不允许只写剧情摘要。',
    '近章连载风险：如果 contextPackage.chapter_target.recent_fatigue_brief 存在，必须在场景卡阶段读取 recent_fatigue_brief.risk_signals 与 recent_fatigue_brief.next_actions；正文生成前先把 two_chapter_momentum_stall、five_chapter_texture_gap、conflict_thrill_overrun 等风险转成可执行场景安排。',
    '执行 next_actions：two_chapter_momentum_stall 用目标推进、阻碍升级、新信息修复；five_chapter_texture_gap 补关系/世界调剂；conflict_thrill_overrun 安排冲突冷却或余波承接；不得等到正文阶段再临场补救。',
    '每个风险修复场景都必须写入 serial_risk_repairs，列出命中的风险 key；同时写入 recent_fatigue_action，用一句话说明本场怎样执行 next_actions。',
    '滚动节奏预检：如果 contextPackage.chapter_target.write_preparation_brief.rolling_rhythm_preflight 存在，场景卡阶段必须先执行 rolling_rhythm_preflight.principle：拉期待速度 > 断期待速度；读取 expectation_vacuum_risks、selling_point_drift_risks、repetition_boundary_risks 和 next_actions。',
    '期待真空期急救：rolling_rhythm_preflight 触发期待真空时，必须至少选择反派视角转接、突发意外、配角杠杆、超额收获之一拆成可见场景；不得让当前目标兑现后只剩等待或整理。',
    '卖点偏移与重复边界：rolling_rhythm_preflight 触发卖点偏移或同一核心梗连续3次以上无差异化时，必须更换冲突来源、回报形态、影响范围或章末问题，并把修复写入 serial_risk_repairs 与 recent_fatigue_action。',
    '交稿风险/质量续航：如果 contextPackage.chapter_target.delivery_risk_carry_over 或 contextPackage.batch_preflight.delivery_risk_carry_over 存在，必须在场景卡阶段读取 delivery_risk_carry_over.items、required_actions、opening_actions、middle_actions、ending_actions、forbidden_repeats；正文生成前先把质量续航计划拆成可执行场景安排。',
    '执行 delivery_risk_carry_over：opening_actions 必须进入第一场 opening_hook、purpose 或 required_beats；middle_actions 必须进入中段场景的 conflict、turning_point 或 state_changes_expected；ending_actions 必须进入最后一场 ending_hook_seed；forbidden_repeats 必须写入对应场景的 serial_risk_repairs，提醒正文不得复现该套路。',
    '每个承接上一章/批次风险的场景都必须在 serial_risk_repairs 写入 delivery_risk_carry_over 或 质量续航，并用 recent_fatigue_action 或 required_beats 说明本场如何把承接风险转成可见目标推进、阻碍升级、新信息、关系/状态变化或章末追读钩子。',
    '场景推进硬约束：每个场景必须同时声明：人物要什么、什么挡着、结束后哪里不同；缺任一项不得输出该场景卡。',
    '章首因果桥：第一张场景卡必须填写 transition_from_previous，直接承接 chapter_target.previous_handoff 中上一章最后一幕、人物所在位置、持有物和未完成动作；如需换时空，必须写出明确时间/空间转移及其因果桥，禁止为了强钩子无桥接另起危机。',
    'purpose 不得只写“观察/进入/等待/经过”，必须写出角色主动目标或当场必须完成的任务。',
    'conflict 必须是可见阻碍/规则压力/对手动作/代价，不能只写“气氛紧张”“内心挣扎”。',
    '冲突结构合同：如果 chapter_target.conflict_structure_contract 存在，必须读取 conflict_ladder、motivation_sources、antagonist_pressure_rules、protagonist_agency_rules、event_value_changes、next_conflict_seeds、conflict_network_layers、no_exit_rules，并拆进每个主要场景的 conflict_ladder_step、motivation_source、opposing_force、blocked_desire、protagonist_agency_action、no_exit_reason、event_value_change、next_conflict_seed。',
    '逐场冲突标准：blocked_desire 回答主角想得到什么；opposing_force 回答谁/什么规则在阻止主角得到他想要的东西，本质必须是有人阻止主角得到他想要的东西；conflict_ladder_step 标注言语/规则压迫 -> 行动阻拦 -> 激烈对抗 -> 决定胜负的当前位置；event_value_change 写出胜负、资格、关系、信息、资源或局势的明确改变；next_conflict_seed 必须承接第一幕陷阱或下一危机伏笔。',
    '有进无出：no_exit_reason 必须说明主角为什么非踏入不可，并写清死亡赌注/退出代价/黏结剂中的至少一项，不能让主角或对手随时能退出冲突。',
    '明暗线与 AB 交织：关键场景必须写 visible_line_role、hidden_line_seed、ab_weave_role；visible_line_role 标明明线主角行动或支线如何服务主线；hidden_line_seed 标明暗线/反派线/隐藏信息如何在后续与明线交汇；ab_weave_role 标明 A线升级/资源/能力 或 B线拉出矛盾/卷入矛盾/爆发/解决/收获的交织位置。',
    'turning_point/exit_state/state_changes_expected 必须写出局势、关系、信息或状态变化，说明这一场结束后故事哪里不可逆地不同。',
    '目的词：每个场景必须写 purpose_tag，并可用 purpose_tags 补充；取值优先从 铺垫/高潮/爽点/打脸/人物塑造/设定/过渡/信息交代/关键揭露/反转 中选。',
    'purpose_tag 驱动详略：爽点/打脸/高潮展开，必须有危机或期待铺垫、出手过程、对话交锋和配角差异化反应；过渡/赶路/信息交代带过，只保留必要位移、时间跳转或信息交接。',
    '前三章第一场必须有 opening_hook；最后一个场景必须有 ending_hook_seed；规则怪谈、恐怖、悬疑类章节必须把 rule_pressure 与 fear_point 写成具体可见风险。',
    'reader_payoff 要说明这一场给读者的爽点、惊点、信息回收或关系变化；character_voice 要标出主要角色的差异化说话方式。',
    '对白/文风/正文工艺：如果 chapter_target.dialogue_contract、benchmark_recall_brief、style_boundary_contract 或 prose_craft_contract 存在，必须把相关要求拆进对应场景的 dialogue_goals、style_directives、benchmark_recall_directives、concept_anchor_rules 或 prose_craft_directives；新名词/新设定首次出现的场景必须写 concept_anchor_rules，要求用动作反应、对话半句或物理后果建立当下作用锚点，禁止整段来历/等级解释。',
    '角色关系推进：如果 chapter_target.character_relation_contract、delivery_risk_carry_over 或上一章诊断提示角色关系缺口，必须把关系修复拆进 relationship_progression_plan、relationship_buffer_zone、supporting_character_action、attitude_shift_checkpoint、relationship_next_hook；配角攻略缓冲区必须保留信息差、地位差距、亲密度差距或信任程度，配角要主动行动，关键拐点要写清从旁观/质疑/拒绝/试探到行动/协助/设限的态度变化。',
    '高潮对抗/公开打脸：如果 chapter_target.showdown_contract 存在，必须把装逼打脸和战斗/智斗口径拆进 showoff_stage_chain、spectator_interest_shift、secondary_showoff_effect、combat_result_type、combat_dimension_plan、combat_reversal_plan；showoff_stage_chain 按群众层 -> 中间层 -> 核心层铺舞台，spectator_interest_shift 必须回答“这跟我有关系”的利益/目标变化，secondary_showoff_effect 写展示如何改变旁观者计划、利益或站队，combat_result_type 取 碾压 / 以弱胜强 / 逃走进入第二阶段 / 平局留钩，combat_dimension_plan 至少覆盖心/体/技一项，combat_reversal_plan 写预判反制或反预判。',
    'action_beats 必须写成可见动作链：起手/试探/受阻/受伤或代价/反制/结果。非动作场景也要写 required_beats，避免只写氛围。',
    'description_budget 写 low/medium/high。默认 low；只有新地点首次登场或诡异规则首次显形时才允许 medium/high。',
    '疏密分配：每个场景必须写 density_level，取 dense/medium/sparse，并与 purpose_tag 一致。',
    'density_level=dense 只给爽点/打脸/反转/情绪高潮/关键揭露/强冲突场景，要求感知、动作、对话交锋铺满，慢镜头逐拍展开。',
    'density_level=sparse 给过场/赶路/信息交代/时间跳转，要求 1-2 句带过，不展开三维度。',
    'density_level=medium 给铺垫/日常/关系升温，只挑 1-2 个有代入感细节，其余略写。',
    '一章详写必须集中在情绪节点；过场必须压缩，不允许每个 beat 一样长一样细。',
    '感知素材库：每个场景必须写 sensory_anchor，按 scene_type 选择一个可被主角主动注意到且能推动动作、规则、危险或对话判断的感知锚点。',
    'sensory_anchor 可参考：阅读/翻看=字迹深浅、纸张触感、墨水洇开、页角卷曲；对话场景=对方表情变化、语气停顿、空气里的沉默；回忆场景=气味/声音/触感里突然清晰的细节；室内场景=光线变化、物品的位置、温度；移动场景=脚步声、地面的触感、风的方向。',
    '三维度边界：感知是主角主动注意到的细节，反应是具体身体动作；感知不能是装饰性场景描写，反应不能是情绪词。',
    '设定工坊约束：必须优先使用 setting_context.chapter_usage.required；allowed 可按需使用；forbidden_settings 不得揭露或误用；能力、物品、Boss、规则、境界和角色认知必须服从 setting_context.entities 的 constraints_json/state_json。',
    '要求：2-6 个场景；每个场景必须服务本章目标并给出 pov_lens（角色视角透镜）；dense/medium 场景必须有 decision_in_scene；最后一个场景必须到达 ending_hook；不要复制参考作品专名、桥段或原句；只返回 JSON object，顶层只能包含 scene_cards。',
  ].join('\n')
}
