import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, test } from 'bun:test'

const readServiceLeaf = (name: string) => readFileSync(join(import.meta.dir, '../novel-writing-service/service', name), 'utf8')
const readQualityLeaf = (name: string) => readFileSync(join(import.meta.dir, '../novel-writing-service/quality', name), 'utf8')
const readNovelWritingLeaf = (name: string) => readFileSync(join(import.meta.dir, '../novel-writing', name), 'utf8')
const readProseQualityReviewRecordSource = () => readFileSync(join(import.meta.dir, '../novel-writing/prose-quality-review-record.ts'), 'utf8')

describe('novel writing service quality contract wiring', () => {
  test('prose quality review payloads store latest generated scene breakdown context', () => {
    const source = readServiceLeaf('generate-chapter-quality-prestore-finalize.ts')
    const reviewRecordSource = readProseQualityReviewRecordSource()
    const finalReviewContextStart = source.indexOf('const finalReviewContextPackage = buildProseReviewContextPackage')
    const qualityReviewStorageEnd = source.indexOf('\n  return {', finalReviewContextStart)
    if (finalReviewContextStart < 0 || qualityReviewStorageEnd <= finalReviewContextStart) {
      throw new Error('Unable to locate prose quality review storage source block')
    }
    const qualityReviewStorageBlock = source.slice(finalReviewContextStart, qualityReviewStorageEnd)

    expect(finalReviewContextStart).toBeGreaterThanOrEqual(0)
    expect(qualityReviewStorageEnd).toBeGreaterThan(finalReviewContextStart)
    expect(qualityReviewStorageBlock).toContain('const finalReviewContextPackage = buildProseReviewContextPackage(contextPackage, finalSceneBreakdown, wordTargetExpansionPatches)')
    expect(qualityReviewStorageBlock).toContain('contextPackage: finalReviewContextPackage')
    expect(reviewRecordSource).toContain('context_package: input.contextPackage')
    expect(qualityReviewStorageBlock).not.toContain('contextPackage: contextPackage')
  })

  test('quality gates include revision cascade evidence failures before storing prose', () => {
    const source = readServiceLeaf('generate-chapter-quality-prestore-finalize.ts')
    const cascadeCheckStart = source.indexOf('const revisionCascadeImpactChecks =')
    const gateReviewStart = source.indexOf('let qualityGateReview =', cascadeCheckStart)
    const preStoreStart = source.indexOf('const revisionDeliveryReceipts =', gateReviewStart)
    const gateBlock = source.slice(cascadeCheckStart, preStoreStart)

    expect(cascadeCheckStart).toBeGreaterThanOrEqual(0)
    expect(gateReviewStart).toBeGreaterThan(cascadeCheckStart)
    expect(preStoreStart).toBeGreaterThan(gateReviewStart)
    expect(gateBlock).toContain('revisionCascadeImpactSync.evidence_missing')
    expect(gateBlock).toContain('revisionCascadeImpactSync.evidence_unlocated')
    expect(gateBlock).toContain("key: 'revision_cascade_impact_evidence'")
    expect(gateBlock).toContain('修订级联影响证据未闭环')
    expect(gateBlock).toContain('...revisionCascadeImpactChecks')
  })

  test('quality gates include structural sync failures before storing prose', () => {
    const source = readServiceLeaf('generate-chapter-quality-prestore-finalize.ts')
    const syncStart = source.indexOf('const preStoreStructuralSyncChecks = buildPreStoreStructuralSyncChecks')
    const qualityGateStart = source.indexOf('let qualityGateReview = buildQualityGateReviewWithDeterministicCleanup', syncStart)
    const preStoreStart = source.indexOf('const revisionDeliveryReceipts =', qualityGateStart)
    const gateBlock = source.slice(syncStart, preStoreStart)

    expect(syncStart).toBeGreaterThanOrEqual(0)
    expect(syncStart).toBeLessThan(qualityGateStart)
    expect(gateBlock).toContain('chapterBlueprintSync')
    expect(gateBlock).toContain('benchmarkRecallSync')
    expect(gateBlock).toContain('storyDriveSync')
    expect(gateBlock).toContain('chapterAttractionReview')
    expect(gateBlock).toContain('runwaySync')
    expect(gateBlock).toContain('...preStoreStructuralSyncChecks')
  })

  test('blocks hard chapter launch gate before drafting prose', () => {
    const source = readServiceLeaf('generate-chapter-context-scene-cards.ts')
    const orchestratorSource = readServiceLeaf('generate-chapter-for-group-methods.ts')
    const contextSource = readQualityLeaf('core-contract-radar.ts')
    const blockerSource = readNovelWritingLeaf('prose-quality-contracts.ts')
    const decisionSource = readNovelWritingLeaf('prose-generation-contract.ts')
    const entrySource = readQualityLeaf('prose-quality-entry.ts')
    const firstGateStart = source.indexOf('await enforcePreparedGate(false)')
    const sceneCardsStart = source.indexOf("await onStage('scene_cards'", firstGateStart)
    const finalGateStart = source.indexOf('await enforcePreparedGate(true)', sceneCardsStart)
    const contextCallStart = orchestratorSource.indexOf('const contextSceneResult = await runGenerateChapterContextAndSceneCards')
    const draftCallStart = orchestratorSource.indexOf('const draftResultBundle = await runGenerateChapterDraftProse', contextCallStart)
    const contextStart = contextSource.indexOf('export function chapterLaunchGateFromContext')
    const contextEnd = contextSource.indexOf('\nexport function normalizeCoreContractRadar', contextStart)
    const contextBlock = contextSource.slice(contextStart, contextEnd)
    const blockerStart = blockerSource.indexOf('export function getChapterLaunchGateBlocker')
    const blockerEnd = blockerSource.indexOf('\nexport function selectUsableRevisionText', blockerStart)
    const blockerBlock = blockerSource.slice(blockerStart, blockerEnd)
    const decisionStart = decisionSource.indexOf('export function evaluateProsePreDraftGate')
    const decisionLaunchStart = decisionSource.indexOf('const launchBlocker = getChapterLaunchGateBlocker', decisionStart)
    const decisionLaunchEnd = decisionSource.indexOf('const directorReadiness =', decisionLaunchStart)
    const decisionBlock = decisionSource.slice(decisionLaunchStart, decisionLaunchEnd)
    const entryGateStart = entrySource.indexOf('const gateDecision = evaluateProsePreDraftGate')
    const entryGateEnd = entrySource.indexOf('const toxicDebtGate =', entryGateStart)
    const entryGateBlock = entrySource.slice(entryGateStart, entryGateEnd)

    expect(source).toContain('await preparedGeneration.runAfterGate(async () => undefined, requireSceneCards)')
    expect(firstGateStart).toBeGreaterThanOrEqual(0)
    expect(sceneCardsStart).toBeGreaterThan(firstGateStart)
    expect(finalGateStart).toBeGreaterThan(sceneCardsStart)
    expect(contextCallStart).toBeGreaterThanOrEqual(0)
    expect(draftCallStart).toBeGreaterThan(contextCallStart)
    expect(contextStart).toBeGreaterThanOrEqual(0)
    expect(contextEnd).toBeGreaterThan(contextStart)
    expect(contextBlock).toContain('target.chapter_launch_gate')
    expect(contextBlock).toContain('brief.chapter_launch_gate')
    expect(blockerStart).toBeGreaterThanOrEqual(0)
    expect(blockerEnd).toBeGreaterThan(blockerStart)
    expect(blockerBlock).toContain('if (blockedChecks.length === 0) return null')
    expect(blockerBlock).toContain("code: 'PROSE_LAUNCH_GATE_BLOCKED'")
    expect(decisionStart).toBeGreaterThanOrEqual(0)
    expect(decisionLaunchStart).toBeGreaterThan(decisionStart)
    expect(decisionLaunchEnd).toBeGreaterThan(decisionLaunchStart)
    expect(decisionBlock).toContain('const launchBlocker = getChapterLaunchGateBlocker(launchGate')
    expect(decisionBlock).toContain('if (launchBlocker)')
    expect(decisionBlock).toContain('passed: false')
    expect(decisionBlock).toContain("code: 'PROSE_LAUNCH_GATE_BLOCKED'")
    expect(decisionBlock).toContain('details: launchBlocker')
    expect(entryGateStart).toBeGreaterThanOrEqual(0)
    expect(entryGateEnd).toBeGreaterThan(entryGateStart)
    expect(entryGateBlock).toContain('if (!gateDecision.passed)')
    expect(entryGateBlock).toContain('throw Object.assign(')
    expect(entryGateBlock).toContain('code: gateDecision.code')
    expect(entryGateBlock).toContain('gateDecision,')
  })

  test('prose revision parser falls back to plain prose and records diagnostics', () => {
    const source = readServiceLeaf('prose-self-review-run-revision.ts')
    const revisionStart = source.indexOf('const revisionPayload = getNovelPayload(revisionResult)')
    const revisionEnd = source.length
    const revisionBlock = source.slice(revisionStart, revisionEnd)

    expect(revisionStart).toBeGreaterThanOrEqual(0)
    expect(revisionEnd).toBeGreaterThan(revisionStart)
    expect(revisionBlock).toContain('const revisionPlainProseFallback = extractPlainProseFallback(revisionResult')
    expect(revisionBlock).toContain('|| revisionPlainProseFallback')
    expect(revisionBlock).toContain('llm_diagnostics: buildLLMResultDiagnostics(revisionResult)')
  })

  test('prose revision uses expanded output budget for quality-gate repair', () => {
    const source = readServiceLeaf('prose-self-review-run.ts')
    const runStart = source.indexOf('const runProseSelfReviewAndRevision = async')
    const revisionStart = source.indexOf('const revisionMaxTokens', runStart)
    const revisionEnd = source.indexOf('} catch (revisionError)', revisionStart)
    const revisionBlock = source.slice(revisionStart, revisionEnd)

    expect(revisionStart).toBeGreaterThan(runStart)
    expect(revisionEnd).toBeGreaterThan(revisionStart)
    expect(revisionBlock).toContain('options.quality_gate_repair')
    expect(revisionBlock).toContain('maxTokens: revisionMaxTokens')
    expect(revisionBlock).not.toContain('maxTokens: 8000')
  })

  test('prose self-review uses expanded output budget for oh-story structured checks', () => {
    const source = readServiceLeaf('prose-self-review-run.ts')
    const reviewStart = source.indexOf('const runProseSelfReviewAndRevision = async')
    const reviewEnd = source.indexOf('const reviewPayload = getNovelPayload(reviewResult)', reviewStart)
    const reviewBlock = source.slice(reviewStart, reviewEnd)

    expect(reviewStart).toBeGreaterThanOrEqual(0)
    expect(reviewEnd).toBeGreaterThan(reviewStart)
    expect(reviewBlock).toContain('const reviewMaxTokens')
    expect(reviewBlock).toContain('maxTokens: reviewMaxTokens')
    expect(reviewBlock).not.toContain('maxTokens: 3000')
  })

  test('prose self-review runs a compact follow-up when oh-story structured checks are omitted', () => {
    const source = readServiceLeaf('prose-self-review-run.ts')
    const fillSource = readServiceLeaf('structured-review-fill-methods.ts')
    const fillPromptSource = readQualityLeaf('paragraph-prose-context.ts')
    const reviewStart = source.indexOf('const runProseSelfReviewAndRevision = async')
    const repairStart = source.indexOf('const structuredFillReview = await fillMissingStructuredReviewChecks', reviewStart)
    const concernStart = source.indexOf('const hasDeliveryRiskReceiptConcern =', reviewStart)
    const revisionPromptStart = source.indexOf('task: buildProseRevisionPrompt', reviewStart)
    const reviewBlock = source.slice(reviewStart, revisionPromptStart)

    expect(reviewStart).toBeGreaterThanOrEqual(0)
    expect(repairStart).toBeGreaterThan(reviewStart)
    expect(repairStart).toBeLessThan(concernStart)
    expect(repairStart).toBeLessThan(revisionPromptStart)
    expect(reviewBlock).toContain('fillMissingStructuredReviewChecks(activeWorkspace, project, contextPackage, chapterText, normalizedReview, modelId, options)')
    expect(fillSource).toContain('chunkStructuredReviewFields(missingFields')
    expect(reviewBlock).toContain('mergeStructuredReviewFillPayload')
    expect(fillPromptSource).toContain('只补缺失的 oh-story 结构化自检字段')
  })

  test('prose generation and revision prompts hard-lock simplified Chinese chapter text', () => {
    const draftPromptBlock = readServiceLeaf('paragraph-prose-context-sections-lead.ts')
    const revisionPromptBlock = readServiceLeaf('prose-self-review-prompts.ts')
    const draftPromptStart = draftPromptBlock.indexOf('硬性语言要求：chapter_text 必须使用简体中文')
    const revisionPromptStart = revisionPromptBlock.indexOf('export const buildProseRevisionPrompt =')

    expect(draftPromptStart).toBeGreaterThanOrEqual(0)
    expect(revisionPromptStart).toBeGreaterThanOrEqual(0)
    expect(draftPromptBlock).toContain('chapter_text 必须使用简体中文')
    expect(draftPromptBlock).toContain('不得输出葡萄牙语、英语或拼音正文')
    expect(revisionPromptBlock).toContain('chapter_text 必须使用简体中文')
    expect(revisionPromptBlock).toContain('不得输出葡萄牙语、英语或拼音正文')
  })

  test('structured review fill cannot overwrite overall quality score from compact batches', () => {
    const source = readQualityLeaf('review-fill.ts')
    const mergeStart = source.indexOf('function mergeStructuredReviewFillPayload')
    const mergeEnd = source.length
    const mergeBlock = source.slice(mergeStart, mergeEnd)

    expect(mergeStart).toBeGreaterThanOrEqual(0)
    expect(mergeEnd).toBeGreaterThan(mergeStart)
    expect(mergeBlock).toContain('for (const [snakeField, camelField] of STRUCTURED_REVIEW_CHECK_FIELDS)')
    expect(mergeBlock).not.toContain("if (typeof payload?.passed === 'boolean') merged.passed = payload.passed")
    expect(mergeBlock).not.toContain("if (Number.isFinite(Number(payload?.score))) merged.score = Number(payload.score)")
    expect(mergeBlock).not.toContain("if (typeof payload?.needs_revision === 'boolean') merged.needs_revision = payload.needs_revision")
    expect(mergeBlock).not.toContain("if (typeof payload?.needsRevision === 'boolean') merged.needs_revision = payload.needsRevision")
  })

  test('structured review fill considers every omitted oh-story check field instead of truncating at 24', () => {
    const source = readQualityLeaf('review-merge.ts')
    const missingStart = source.indexOf('function missingStructuredReviewCheckFields')
    const missingEnd = source.indexOf('function structuredReviewCheckStableKey', missingStart)
    const missingBlock = source.slice(missingStart, missingEnd)

    expect(missingStart).toBeGreaterThanOrEqual(0)
    expect(missingEnd).toBeGreaterThan(missingStart)
    expect(missingBlock).toContain('STRUCTURED_REVIEW_CHECK_FIELDS')
    expect(missingBlock).not.toContain('.slice(0, 24)')
  })
})
