import React from 'react'
import apiClient from '../../../api/client'
import {
  selectTargetChapterForWriting,
} from '../writingCockpitModel'
import {
  chapterHasProse,
} from '../utils'
import { editorRevisionForChapter } from '../editorRevisionTasks'
import {
  NovelWorkspaceAreaView,
} from './workspace-area-view'
import {
  SerialPipelineStrip,
} from './workspace-serial-pipeline'
import {
  buildNovelWorkspaceAreaViewProps,
} from './workspace-view-props'
import {
  buildWorkspaceWritingRecommendation,
  resolveActiveChapterSceneCards,
} from './workspace-derived-state'
import {
  WORKSPACE_AREA_TABS,
} from './workspace-area-tabs'
import {
  bindNovelWorkspaceActionHandlers,
} from './workspace-view-bind-action-handlers'
import {
  buildWorkspaceCockpitPrimaryActionOverride,
} from './workspace-cockpit-primary-override'
import type {
  PlanningLoadingKey,
} from '../StoryPlanningWorkspace'

export function editorRevisionForReadyRuntime({
  editorRevisionTasks,
  editorRevisionTasksProjectId,
  projectId,
  activeChapterId,
}: {
  editorRevisionTasks: unknown[]
  editorRevisionTasksProjectId?: number | null
  projectId?: number | null
  activeChapterId?: number | null
}) {
  if (Number(editorRevisionTasksProjectId) !== Number(projectId)) return null
  return editorRevisionForChapter(editorRevisionTasks, Number(activeChapterId || 0))
}

export function buildNovelWorkspaceReadyRuntime(base: Record<string, any>) {
  const {
    activeChapter,
    activeChapterDiagnosticsData,
    activeChapterId,
    activeContextPackageData,
    activeKnowledgeJobCount,
    activeTasks,
    agentAuditOpen,
    agentExecution,
    applyEditorRevision,
    autoCreationDirectorModel,
    autoDirectorActionLoadingKey,
    backupImportOpen,
    backupImportText,
    bookReviewLoading,
    bookReviews,
    cancelEditorRevision,
    cancelKnowledgeIngestJob,
    chapterDrawerOpen,
    chapterGenerationSourceAuthority,
    chapterInvocationPending,
    chapterSourcePendingState,
    chapterGroupExecutingId,
    chapterSearch,
    chapterSortMode,
    chapterStatusFilter,
    chapterTargetWordCount,
    writingSkillsEnabled,
    writingSkillsCatalog,
    fictionHumanizerMode,
    chapterTreeData,
    chapterSourceLocallyBusy,
    chapterVersionDetail,
    chapterVersions,
    chapterVersionsLoading,
    chapterWordTargetMode,
    chapters,
    characters,
    commercialReadiness,
    commercialToolLoading,
    commercialToolsOpen,
    consistencyGraphOpen,
    contextPackageLoading,
    continuityAudit,
    continuityAuditLoading,
    coreHandlers,
    createDeliveryRiskRepairQueue,
    createEditorReport,
    createEditorReportForChapter,
    createFirst30RetentionRepairQueue,
    createReaderTrialRepairQueue,
    createRecoveryEvidenceGovernanceQueue,
    createSafeBatchRiskRepairQueue,
    createScriptRoomRepairQueue,
    createStyleSampleBatchRepairQueue,
    creativeAssistantError,
    creativeAssistantLoading,
    creativeAssistantMode,
    creativeAssistantOpen,
    creativeAssistantResult,
    creativeAssistantSelectedText,
    creativeCardsOpen,
    creativeCommandOpen,
    creativeCommandPlan,
    creativeCommandText,
    dashboardLoading,
    diagnosticsLoading,
    directoryCollapsed,
    directoryShellClassName,
    editorForm,
    editorKind,
    editorReportLoading,
    editorReports,
    editorRevisionReports,
    editorRevisionTasks,
    editorRevisionTasksProjectId,
    exportDeliveryOpen,
    extractStyleSampleCandidates,
    fillDefaultStyleSampleBank,
    filteredChapters,
    flushPendingSave,
    future100ApplyLoading,
    future100Draft,
    future100SelectedNos,
    future100FocusOutlineIds,
    generateCurrentChapterProse,
    generateSceneCardsForActiveChapter,
    generateSceneCardsForChapter,
    generateWritingBibleEditor,
    generatingProse,
    rewriteSelection,
    onWriteContinue,
    onCancelContinue,
    expandOutlineJob,
    onExpandOutline,
    generatingSceneCards,
    generationPipeline,
    handleDirectoryCollapsedChange,
    id,
    incubatingOriginal,
    isEmptyProject,
    isImmersiveShell,
    knowledgeIngestJobs,
    knowledgeJobsLoading,
    loadEditorRevisionDiagnostics,
    loadKnowledgeIngestJobs,
    loadProductionTasks,
    loadProjectModules,
    loading,
    modelOptions,
    navigate,
    openChapterQualityCard,
    openContinuityAudit,
    openGenerationDiagnostics,
    openLongformProductionTrends,
    openStoryAssetsWorkspace,
    openStoryStateEditor,
    openWritingBibleEditor,
    outlinePanelOpen,
    outlineTreeOpen,
    outlines,
    pauseKnowledgeIngestJob,
    pipelineLoading,
    planning,
    planningWorkspaceModel,
    previewStyleSampleAdjustmentBatch,
    previewStyleSampleAdjustmentPatch,
    productionMode,
    productionModeOptions,
    productionTasks,
    productionTasksLoading,
    projectId,
    projectSettings,
    proseChapters,
    proseEditorRef,
    proseProgress,
    proseQualityLoading,
    proseQualityReports,
    ohStoryReviews,
    qualityBenchmarkOpen,
    recentFatigueRollingPlanIntent,
    referenceConfigOpen,
    referenceEngineeringOpen,
    referenceReports,
    referenceSummary,
    refreshActiveProseQuality,
    refreshProseQualityForChapter,
    openChapterQualityCardForChapter,
    openMaterialRepairPlan,
    loadActiveChapterContextPackage,
    latestCockpitEditorReport,
    releaseRepairExecutingId,
    repairContextAndGenerateCurrentChapter,
    restructurePanelOpen,
    resumeKnowledgeIngestJob,
    retryEditorRevision,
    reviewAnnotationsOpen,
    reviewStyleSampleAdjustmentPatch,
    reviews,
    rightPanelOpen,
    rightPanelTab,
    rollbackChapterVersion,
    rollingBackVersionId,
    runBookReview,
    runRecords,
    runRollingPlan,
    saveStatus,
    saveStoryStateEditor,
    saveWritingBibleEditor,
    scheduleSave,
    selectChapterForWriting,
    selectMode,
    selectedChapterIds,
    selectedChaptersList,
    selectedModelId,
    selectedProject,
    serialPipelineModel,
    setAgentAuditOpen,
    setAgentExecution,
    setAutoDirectorActionLoadingKey,
    setBackupImportOpen,
    setBackupImportText,
    setChapterDrawerOpen,
    setChapterSearch,
    setChapterSortMode,
    setChapterStatusFilter,
    setChapterTargetWordCount,
    setChapterVersionDetail,
    setChapterWordTargetMode,
    setWritingSkillsEnabled,
    setWritingSkillsCatalog,
    setFictionHumanizerMode,
    setChapters,
    setCommercialToolsOpen,
    setConsistencyGraphOpen,
    setCreativeAssistantMode,
    setCreativeAssistantOpen,
    setCreativeCardsOpen,
    setCreativeCommandOpen,
    setCreativeCommandText,
    setEditorItem,
    setEditorKind,
    setExportDeliveryOpen,
    setFuture100Draft,
    setFuture100FocusOutlineIds,
    setFuture100SelectedNos,
    setOutlinePanelOpen,
    setOutlineTreeOpen,
    setProductionMode,
    setQualityBenchmarkOpen,
    setReferenceConfigOpen,
    setReferenceEngineeringOpen,
    setRestructurePanelOpen,
    setReviewAnnotationsOpen,
    setRightPanelOpen,
    setRightPanelTab,
    setSelectMode,
    setSelectedChapterIds,
    setChapterGenerationSourceAuthority,
    setChapterSourceMutationPending,
    setSelectedModelId,
    setSelectedProject,
    setShellMode,
    setShowOnlyDiff,
    setStoryStateOpen,
    setTaskCenterOpen,
    setTaskCenterRecoveryFocus,
    setUnattendedTargetChapter,
    setWorkspaceArea,
    setWritingBibleOpen,
    showGlobalWritingGuidance,
    showOnlyDiff,
    sortedChapters,
    stepGenerateProse,
    stepProseLoading,
    beginChapterSourceOperation,
    assertChapterSourceOperationCurrent,
    claimChapterInvocation,
    chapterInvocationOwnerIsActive,
    releaseChapterInvocation,
    storyAssetsFocusDiscoveredToken,
    storyStateForm,
    storyStateOpen,
    streamingChapterId,
    streamingEndRef,
    streamingPercent,
    streamingProgress,
    streamingText,
    styleSampleCandidateLoading,
    styleSampleEffectiveness,
    styleSampleEffectivenessItems,
    styleSampleEffectivenessLoading,
    styleSamplePatchLoadingKey,
    syncStoryStateForChapter,
    taskCenterOpen,
    taskCenterRecoveryFocus,
    unattendedTargetChapter,
    undoStyleSampleAdjustmentPatch,
    workspaceArea,
    worldbuilding,
    writingBibleForm,
    writingBibleGenerating,
    writingBibleOpen,
    writingCockpitModel,
    acceptChapterVersion,} = base

  const planningLoadingKey = ((): PlanningLoadingKey | undefined => {
    const keys: PlanningLoadingKey[] = ['rollingPlan', 'future100Audit', 'future100Generate', 'longformPressure', 'longformCreationDiagnosis', 'topic', 'referenceDiagnosis', 'first30Retention', 'first30Repair', 'readerTrial', 'readerTrialRepair']
    return keys.includes(commercialToolLoading as PlanningLoadingKey) ? commercialToolLoading as PlanningLoadingKey : undefined
  })()
  const workspaceAreaTabs = WORKSPACE_AREA_TABS
  const currentEditorRevisionTask = editorRevisionForReadyRuntime({
    editorRevisionTasks,
    editorRevisionTasksProjectId,
    projectId,
    activeChapterId,
  })

  const actionHandlers = bindNovelWorkspaceActionHandlers({
    activeChapter,
    activeChapterId,
    apiClient,
    applyEditorRevision,
    autoCreationDirectorModel,
    chapterHasProse,
    chapters,
    createDeliveryRiskRepairQueue,
    createEditorReport,
    createEditorReportForChapter,
    createFirst30RetentionRepairQueue,
    createReaderTrialRepairQueue,
    createRecoveryEvidenceGovernanceQueue,
    createSafeBatchRiskRepairQueue,
    createScriptRoomRepairQueue,
    createStyleSampleBatchRepairQueue,
    generateCurrentChapterProse,
    generateSceneCardsForChapter,
    loadProductionTasks,
    loadProjectModules,
    openChapterQualityCard,
    openContinuityAudit,
    openGenerationDiagnostics,
    openLongformProductionTrends,
    openStoryAssetsWorkspace,
    openStoryStateEditor,
    openWritingBibleEditor,
    openChapterQualityCardForChapter: openChapterQualityCardForChapter || coreHandlers?.openChapterQualityCardForChapter,
    openMaterialRepairPlan: openMaterialRepairPlan || coreHandlers?.openMaterialRepairPlan,
    loadActiveChapterContextPackage,
    latestCockpitEditorReport,
    generateSceneCardsForActiveChapter,
    projectId,
    recentFatigueRollingPlanIntent,
    refreshActiveProseQuality,
    refreshProseQualityForChapter: refreshProseQualityForChapter || coreHandlers?.refreshProseQualityForChapter,
    runRecords,
    runRollingPlan,
    selectChapterForWriting,
    selectTargetChapterForWriting,
    serialPipelineModel,
    setAutoDirectorActionLoadingKey,
    setOutlinePanelOpen,
    setOutlineTreeOpen,
    setRightPanelOpen,
    setRightPanelTab,
    setTaskCenterOpen,
    setWorkspaceArea,
    sortedChapters,
    stepGenerateProse,
    syncStoryStateForChapter,
    writingCockpitModel,
  })
  const {
    acceptCockpitChapterAndContinue,
    createStorylineDecisionTasks,
    handleAutoCreationDirectorAction,
    handlePlanningAction,
    handleSerialPipelineAction,
    handleWritingCockpitAction,
    recordStorylineDiffDecision,
    runAutoCreationRepairAction,
    runAutoCreationRepairPlan,
  } = actionHandlers

  const renderSerialPipeline = () => (
    <SerialPipelineStrip model={serialPipelineModel} />
  )

  const activeChapterSceneCards = resolveActiveChapterSceneCards(activeChapter)

  const writingRecommendation = buildWorkspaceWritingRecommendation({
    activeChapterDiagnosticsData,
    activeChapterSceneCards,
    activeChapter,
    writingCockpitModel,
  })

  const cockpitPrimaryActionOverride = buildWorkspaceCockpitPrimaryActionOverride({
    activeChapter,
    workspaceArea,
    writingRecommendation,
    openGenerationDiagnostics,
    generateSceneCardsForActiveChapter,
    repairContextAndGenerateCurrentChapter,
    generateCurrentChapterProse,
    openChapterQualityCard,
  })

  const workspaceViewDeps = {
    ...coreHandlers,
    ...actionHandlers,
    activeChapter,
    activeChapterDiagnosticsData,
    activeChapterId,
    activeContextPackageData,
    activeKnowledgeJobCount,
    activeTasks,
    agentAuditOpen,
    agentExecution,
    autoCreationDirectorModel,
    autoDirectorActionLoadingKey,
    backupImportOpen,
    backupImportText,
    bookReviewLoading,
    bookReviews,
    cancelEditorRevision,
    cancelKnowledgeIngestJob,
    chapterDrawerOpen,
    chapterGenerationSourceAuthority,
    chapterInvocationPending,
    chapterGroupExecutingId,
    chapterId: activeChapterId,
    chapterSearch,
    chapterSortMode,
    chapterStatusFilter,
    chapterTargetWordCount,
    writingSkillsEnabled,
    writingSkillsCatalog,
    fictionHumanizerMode,
    chapterTreeData,
    chapterSourceLocallyBusy,
    chapterVersionDetail,
    chapterVersions,
    chapterVersionsLoading,
    chapterWordTargetMode,
    chapters,
    characters,
    cockpitPrimaryActionOverride,
    commercialReadiness,
    commercialToolLoading,
    commercialToolsOpen,
    consistencyGraphOpen,
    contextPackage: activeContextPackageData,
    contextPackageLoading,
    continuityAudit,
    continuityAuditLoading,
    creativeAssistantError,
    creativeAssistantLoading,
    creativeAssistantMode,
    creativeAssistantOpen,
    creativeAssistantResult,
    creativeAssistantSelectedText,
    creativeCardsOpen,
    creativeCommandOpen,
    creativeCommandPlan,
    creativeCommandText,
    dashboardLoading,
    diagnosticsLoading,
    directoryCollapsed,
    directoryShellClassName,
    editorForm,
    editorKind,
    editorReportLoading,
    editorReports,
    editorRevisionReports,
    editorRevisionTasks,
    exportDeliveryOpen,
    extractStyleSampleCandidates,
    fillDefaultStyleSampleBank,
    filteredChapters,
    flushPendingSave,
    future100ApplyLoading,
    future100Draft,
    future100SelectedNos,
    future100FocusOutlineIds,
    generateWritingBibleEditor,
    generatingProse,
    rewriteSelection,
    onWriteContinue,
    onCancelContinue,
    expandOutlineJob,
    onExpandOutline,
    generatingSceneCards,
    generationPipeline,
    handleDirectoryCollapsedChange,
    id,
    incubatingOriginal,
    isEmptyProject,
    isImmersiveShell,
    knowledgeIngestJobs,
    knowledgeJobsLoading,
    loadEditorRevisionDiagnostics,
    loadKnowledgeIngestJobs,
    loadProductionTasks,
    loadProjectModules,
    loading,
    modelOptions,
    navigate,
    openStoryAssetsWorkspace,
    openStoryStateEditor,
    openWritingBibleEditor,
    outlinePanelOpen,
    outlineTreeOpen,
    outlines,
    pauseKnowledgeIngestJob,
    pipelineLoading,
    planning,
    planningLoadingKey,
    planningWorkspaceModel,
    previewStyleSampleAdjustmentBatch,
    previewStyleSampleAdjustmentPatch,
    productionMode,
    productionModeOptions,
    productionTasks,
    productionTasksLoading,
    projectId,
    projectSettings,
    proseChapters,
    proseEditorRef,
    proseProgress,
    proseQualityLoading,
    proseQualityReports,
    ohStoryReviews,
    qualityBenchmarkOpen,
    referenceConfigOpen,
    referenceEngineeringOpen,
    referenceReports,
    referenceSummary,
    releaseRepairExecutingId,
    renderSerialPipeline,
    restructurePanelOpen,
    resumeKnowledgeIngestJob,
    retryEditorRevision,
    reviewAnnotationsOpen,
    reviewStyleSampleAdjustmentPatch,
    reviews,
    rightPanelOpen,
    rightPanelTab,
    rollbackChapterVersion,
    rollingBackVersionId,
    runBookReview,
    runRecords,
    saveStatus,
    saveStoryStateEditor,
    saveWritingBibleEditor,
    scheduleSave,
    selectChapterForWriting,
    selectMode,
    selectedChapterIds,
    selectedChaptersList,
    selectedModelId,
    selectedProject,
    setAgentAuditOpen,
    setAgentExecution,
    setBackupImportOpen,
    setBackupImportText,
    setChapterDrawerOpen,
    setChapterSearch,
    setChapterSortMode,
    setChapterStatusFilter,
    setChapterTargetWordCount,
    setChapterVersionDetail,
    setChapterWordTargetMode,
    setWritingSkillsEnabled,
    setWritingSkillsCatalog,
    setFictionHumanizerMode,
    setChapters,
    setCommercialToolsOpen,
    setConsistencyGraphOpen,
    setCreativeAssistantMode,
    setCreativeAssistantOpen,
    setCreativeCardsOpen,
    setCreativeCommandOpen,
    setCreativeCommandText,
    setEditorItem,
    setEditorKind,
    setExportDeliveryOpen,
    setFuture100Draft,
    setFuture100FocusOutlineIds,
    setFuture100SelectedNos,
    setOutlinePanelOpen,
    setOutlineTreeOpen,
    setProductionMode,
    setQualityBenchmarkOpen,
    setReferenceConfigOpen,
    setReferenceEngineeringOpen,
    setRestructurePanelOpen,
    setReviewAnnotationsOpen,
    setRightPanelOpen,
    setRightPanelTab,
    setSelectMode,
    setSelectedChapterIds,
    setChapterGenerationSourceAuthority,
    chapterSourcePendingState,
    setChapterSourceMutationPending,
    setSelectedModelId,
    setSelectedProject,
    setShellMode,
    setShowOnlyDiff,
    setStoryStateOpen,
    setTaskCenterOpen,
    setTaskCenterRecoveryFocus,
    setUnattendedTargetChapter,
    setWorkspaceArea,
    setWritingBibleOpen,
    showGlobalWritingGuidance,
    showOnlyDiff,
    sortedChapters,
    stepProseLoading,
    beginChapterSourceOperation,
    assertChapterSourceOperationCurrent,
    claimChapterInvocation,
    chapterInvocationOwnerIsActive,
    releaseChapterInvocation,
    storyAssetsFocusDiscoveredToken,
    storyStateForm,
    storyStateOpen,
    streamingChapterId,
    streamingEndRef,
    streamingPercent,
    streamingProgress,
    streamingText,
    styleSampleCandidateLoading,
    styleSampleEffectiveness,
    styleSampleEffectivenessItems,
    styleSampleEffectivenessLoading,
    styleSamplePatchLoadingKey,
    taskCenterOpen,
    taskCenterRecoveryFocus,
    unattendedTargetChapter,
    undoStyleSampleAdjustmentPatch,
    workspaceArea,
    workspaceAreaTabs,
    worldbuilding,
    writingBibleForm,
    writingBibleGenerating,
    writingBibleOpen,
    writingCockpitModel,
    writingRecommendation,
    acceptChapterVersion,
    applyEditorRevision,
    refreshActiveProseQuality,
    createFirst30RetentionRepairQueue,
    createRecoveryEvidenceGovernanceQueue,
    generateCurrentChapterProse,
    openChapterQualityCard,
    openContinuityAudit,
    openLongformProductionTrends,
    runRollingPlan,
  }

  const renderWorkspaceArea = () => (
    <NovelWorkspaceAreaView
      {...buildNovelWorkspaceAreaViewProps(workspaceViewDeps)}
      editorRevisionTask={currentEditorRevisionTask}
      cancelEditorRevision={cancelEditorRevision}
      retryEditorRevision={retryEditorRevision}
      loadEditorRevisionDiagnostics={loadEditorRevisionDiagnostics}
    />
  )
  workspaceViewDeps.renderWorkspaceArea = renderWorkspaceArea

  return {
    status: 'ready' as const,
    isImmersiveShell,
    workspaceViewDeps,
  }
}
