export function buildNovelWorkspaceBodyProps(deps: Record<string, any>) {
  const {
    activeChapter,
    activeChapterDiagnosticsData,
    activeChapterId,
    activeContextPackageData,
    activeKnowledgeJobCount,
    activeTasks,
    applyEditorRevision,
    bookReviews,
    chapterId,
    chapterVersions,
    chapterVersionsLoading,
    characters,
    cockpitPrimaryActionOverride,
    commercialReadiness,
    commercialToolLoading,
    contextPackage,
    contextPackageLoading,
    copyCreativeAssistantCard,
    creativeAssistantError,
    creativeAssistantLoading,
    creativeAssistantMode,
    creativeAssistantOpen,
    creativeAssistantResult,
    creativeAssistantSelectedText,
    diagnosticsLoading,
    directoryCollapsed,
    directoryShellClassName,
    editorReports,
    editorRevisionReports,
    generatingProse,
    generatingSceneCards,
    handleDirectoryCollapsedChange,
    handleWritingCockpitAction,
    isImmersiveShell,
    openEditor,
    openStoryStateEditor,
    outlines,
    projectId,
    proseChapters,
    proseProgress,
    proseQualityLoading,
    proseQualityReports,
    referenceReports,
    refreshActiveProseQuality,
    renderSerialPipeline,
    renderWorkspaceArea,
    reviews,
    rightPanelOpen,
    rightPanelTab,
    rollbackChapterVersion,
    rollingBackVersionId,
    runCreativeAssistant,
    runRecords,
    selectChapterForWriting,
    selectedModelId,
    selectedProject,
    setChapterDrawerOpen,
    setChapterVersionDetail,
    setCreativeAssistantMode,
    setCreativeAssistantOpen,
    setCreativeCardsOpen,
    setOutlineTreeOpen,
    setRightPanelOpen,
    setRightPanelTab,
    setTaskCenterOpen,
    setWorkspaceArea,
    showGlobalWritingGuidance,
    sortedChapters,
    stepProseLoading,
    workspaceArea,
    worldbuilding,
    writingCockpitModel,
  } = deps
  return {
    activeChapter: activeChapter,
    activeChapterDiagnosticsData: activeChapterDiagnosticsData,
    activeChapterId: activeChapterId,
    activeContextPackageData: activeContextPackageData,
    activeKnowledgeJobCount: activeKnowledgeJobCount,
    activeTasks: activeTasks,
    applyEditorRevision: applyEditorRevision,
    bookReviews: bookReviews,
    chapterId: chapterId,
    chapterVersions: chapterVersions,
    chapterVersionsLoading: chapterVersionsLoading,
    characters: characters,
    cockpitPrimaryActionOverride: cockpitPrimaryActionOverride,
    commercialReadiness: commercialReadiness,
    commercialToolLoading: commercialToolLoading,
    contextPackage: contextPackage,
    contextPackageLoading: contextPackageLoading,
    copyCreativeAssistantCard: copyCreativeAssistantCard,
    creativeAssistantError: creativeAssistantError,
    creativeAssistantLoading: creativeAssistantLoading,
    creativeAssistantMode: creativeAssistantMode,
    creativeAssistantOpen: creativeAssistantOpen,
    creativeAssistantResult: creativeAssistantResult,
    creativeAssistantSelectedText: creativeAssistantSelectedText,
    diagnosticsLoading: diagnosticsLoading,
    directoryCollapsed: directoryCollapsed,
    directoryShellClassName: directoryShellClassName,
    editorReports: editorReports,
    editorRevisionReports: editorRevisionReports,
    generatingProse: generatingProse,
    generatingSceneCards: generatingSceneCards,
    handleDirectoryCollapsedChange: handleDirectoryCollapsedChange,
    handleWritingCockpitAction: handleWritingCockpitAction,
    isImmersiveShell: isImmersiveShell,
    openEditor: openEditor,
    openStoryStateEditor: openStoryStateEditor,
    outlines: outlines,
    projectId: projectId,
    proseChapters: proseChapters,
    proseProgress: proseProgress,
    proseQualityLoading: proseQualityLoading,
    proseQualityReports: proseQualityReports,
    referenceReports: referenceReports,
    refreshActiveProseQuality: refreshActiveProseQuality,
    renderSerialPipeline: renderSerialPipeline,
    renderWorkspaceArea: renderWorkspaceArea,
    reviews: reviews,
    rightPanelOpen: rightPanelOpen,
    rightPanelTab: rightPanelTab,
    rollbackChapterVersion: rollbackChapterVersion,
    rollingBackVersionId: rollingBackVersionId,
    runCreativeAssistant: runCreativeAssistant,
    runRecords: runRecords,
    selectChapterForWriting: selectChapterForWriting,
    selectedModelId: selectedModelId,
    selectedProject: selectedProject,
    setChapterDrawerOpen: setChapterDrawerOpen,
    setChapterVersionDetail: setChapterVersionDetail,
    setCreativeAssistantMode: setCreativeAssistantMode,
    setCreativeAssistantOpen: setCreativeAssistantOpen,
    setCreativeCardsOpen: setCreativeCardsOpen,
    setOutlineTreeOpen: setOutlineTreeOpen,
    setRightPanelOpen: setRightPanelOpen,
    setRightPanelTab: setRightPanelTab,
    setTaskCenterOpen: setTaskCenterOpen,
    setWorkspaceArea: setWorkspaceArea,
    showGlobalWritingGuidance: showGlobalWritingGuidance,
    sortedChapters: sortedChapters,
    stepProseLoading: stepProseLoading,
    workspaceArea: workspaceArea,
    worldbuilding: worldbuilding,
    writingCockpitModel: writingCockpitModel,
  }
}

