export function buildNovelWorkspaceAreaViewProps(deps: Record<string, any>) {
  const {
    activeChapter,
    activeChapterDiagnosticsData,
    activeChapterId,
    applyStyleSampleActionForActiveChapter,
    autoCreationDirectorModel,
    autoDirectorActionLoadingKey,
    bookReviewLoading,
    buildPreDraftBriefForActiveChapter,
    chapterTargetWordCount,
    chapterWordTargetMode,
    writingSkillsEnabled,
    writingSkillsCatalog,
    fictionHumanizerMode,
    characters,
    commercialToolLoading,
    confirmPreDraftBriefForActiveChapter,
    continuityAudit,
    createEditorReport,
    dashboardLoading,
    diagnosticsLoading,
    editorReportLoading,
    generateCurrentChapterProse,
    generateSceneCardsForActiveChapter,
    generatingProse,
    generatingSceneCards,
    generationPipeline,
    handleAutoCreationDirectorAction,
    handlePlanningAction,
    handleWritingCockpitAction,
    id,
    incubatingOriginal,
    isEmptyProject,
    isImmersiveShell,
    loadProjectModules,
    openChapterQualityCard,
    openContinuityAudit,
    openEditor,
    openGenerationDiagnostics,
    openProductionDashboard,
    openProductionDesk,
    openProductionMetrics,
    openRunQueue,
    openStoryAssetsWorkspace,
    openStoryStateEditor,
    openWritingBibleEditor,
    outlines,
    pipelineLoading,
    planning,
    planningLoadingKey,
    planningWorkspaceModel,
    projectId,
    projectSettings,
    proseEditorRef,
    proseQualityLoading,
    proseQualityReports,
    editorRevisionReports,
    applyEditorRevision,
    refreshActiveProseQuality,
    repairActiveDeslopGate,
    repairChapterPreflightMaterials,
    repairContextAndGenerateCurrentChapter,
    repairWritingQueuePlan,
    repairWritingQueuePlanBatch,
    runBookReview,
    runOriginalIncubator,
    runPlan,
    runReferenceMigrationPlan,
    savePreDraftBriefForActiveChapter,
    saveStatus,
    scheduleSave,
    selectChapterForWriting,
    selectedModelId,
    selectedProject,
    setAgentAuditOpen,
    setChapterTargetWordCount,
    setChapterWordTargetMode,
    setWritingSkillsEnabled,
    setFictionHumanizerMode,
    setChapters,
    setCommercialToolsOpen,
    setConsistencyGraphOpen,
    setCreativeCardsOpen,
    setExportDeliveryOpen,
    setQualityBenchmarkOpen,
    setReferenceConfigOpen,
    setReferenceEngineeringOpen,
    setReviewAnnotationsOpen,
    setRightPanelOpen,
    setRightPanelTab,
    setTaskCenterOpen,
    setUnattendedTargetChapter,
    setWorkspaceArea,
    sortedChapters,
    startChapterGroupGeneration,
    startChapterPipeline,
    startReadyChapterGroupGeneration,
    startUnattendedWritingGoal,
    storyAssetsFocusDiscoveredToken,
    streamingChapterId,
    streamingEndRef,
    streamingPercent,
    streamingProgress,
    streamingText,
    unattendedTargetChapter,
    workspaceArea,
    worldbuilding,
    writingCockpitModel,
    writingRecommendation,
  } = deps
  return {
    activeChapter: activeChapter,
    activeChapterDiagnosticsData: activeChapterDiagnosticsData,
    activeChapterId: activeChapterId,
    applyStyleSampleActionForActiveChapter: applyStyleSampleActionForActiveChapter,
    autoCreationDirectorModel: autoCreationDirectorModel,
    autoDirectorActionLoadingKey: autoDirectorActionLoadingKey,
    bookReviewLoading: bookReviewLoading,
    buildPreDraftBriefForActiveChapter: buildPreDraftBriefForActiveChapter,
    chapterTargetWordCount: chapterTargetWordCount,
    chapterWordTargetMode: chapterWordTargetMode,
    writingSkillsEnabled: writingSkillsEnabled,
    writingSkillsCatalog: writingSkillsCatalog,
    fictionHumanizerMode: fictionHumanizerMode,
    characters: characters,
    commercialToolLoading: commercialToolLoading,
    confirmPreDraftBriefForActiveChapter: confirmPreDraftBriefForActiveChapter,
    continuityAudit: continuityAudit,
    createEditorReport: createEditorReport,
    dashboardLoading: dashboardLoading,
    diagnosticsLoading: diagnosticsLoading,
    editorReportLoading: editorReportLoading,
    generateCurrentChapterProse: generateCurrentChapterProse,
    generateSceneCardsForActiveChapter: generateSceneCardsForActiveChapter,
    generatingProse: generatingProse,
    generatingSceneCards: generatingSceneCards,
    generationPipeline: generationPipeline,
    handleAutoCreationDirectorAction: handleAutoCreationDirectorAction,
    handlePlanningAction: handlePlanningAction,
    handleWritingCockpitAction: handleWritingCockpitAction,
    id: id,
    incubatingOriginal: incubatingOriginal,
    isEmptyProject: isEmptyProject,
    isImmersiveShell: isImmersiveShell,
    loadProjectModules: loadProjectModules,
    openChapterQualityCard: openChapterQualityCard,
    openContinuityAudit: openContinuityAudit,
    openEditor: openEditor,
    openGenerationDiagnostics: openGenerationDiagnostics,
    openProductionDashboard: openProductionDashboard,
    openProductionDesk: openProductionDesk,
    openProductionMetrics: openProductionMetrics,
    openRunQueue: openRunQueue,
    openStoryAssetsWorkspace: openStoryAssetsWorkspace,
    openStoryStateEditor: openStoryStateEditor,
    openWritingBibleEditor: openWritingBibleEditor,
    outlines: outlines,
    pipelineLoading: pipelineLoading,
    planning: planning,
    planningLoadingKey: planningLoadingKey,
    planningWorkspaceModel: planningWorkspaceModel,
    projectId: projectId,
    projectSettings: projectSettings,
    proseEditorRef: proseEditorRef,
    proseQualityLoading: proseQualityLoading,
    proseQualityReports: proseQualityReports,
    editorRevisionReports: editorRevisionReports,
    applyEditorRevision: applyEditorRevision,
    refreshActiveProseQuality: refreshActiveProseQuality,
    repairActiveDeslopGate: repairActiveDeslopGate,
    repairChapterPreflightMaterials: repairChapterPreflightMaterials,
    repairContextAndGenerateCurrentChapter: repairContextAndGenerateCurrentChapter,
    repairWritingQueuePlan: repairWritingQueuePlan,
    repairWritingQueuePlanBatch: repairWritingQueuePlanBatch,
    runBookReview: runBookReview,
    runOriginalIncubator: runOriginalIncubator,
    runPlan: runPlan,
    runReferenceMigrationPlan: runReferenceMigrationPlan,
    savePreDraftBriefForActiveChapter: savePreDraftBriefForActiveChapter,
    saveStatus: saveStatus,
    scheduleSave: scheduleSave,
    selectChapterForWriting: selectChapterForWriting,
    selectedModelId: selectedModelId,
    selectedProject: selectedProject,
    setAgentAuditOpen: setAgentAuditOpen,
    setChapterTargetWordCount: setChapterTargetWordCount,
    setChapterWordTargetMode: setChapterWordTargetMode,
    setWritingSkillsEnabled: setWritingSkillsEnabled,
    setFictionHumanizerMode: setFictionHumanizerMode,
    setChapters: setChapters,
    setCommercialToolsOpen: setCommercialToolsOpen,
    setConsistencyGraphOpen: setConsistencyGraphOpen,
    setCreativeCardsOpen: setCreativeCardsOpen,
    setExportDeliveryOpen: setExportDeliveryOpen,
    setQualityBenchmarkOpen: setQualityBenchmarkOpen,
    setReferenceConfigOpen: setReferenceConfigOpen,
    setReferenceEngineeringOpen: setReferenceEngineeringOpen,
    setReviewAnnotationsOpen: setReviewAnnotationsOpen,
    setRightPanelOpen: setRightPanelOpen,
    setRightPanelTab: setRightPanelTab,
    setTaskCenterOpen: setTaskCenterOpen,
    setUnattendedTargetChapter: setUnattendedTargetChapter,
    setWorkspaceArea: setWorkspaceArea,
    sortedChapters: sortedChapters,
    startChapterGroupGeneration: startChapterGroupGeneration,
    startChapterPipeline: startChapterPipeline,
    startReadyChapterGroupGeneration: startReadyChapterGroupGeneration,
    startUnattendedWritingGoal: startUnattendedWritingGoal,
    storyAssetsFocusDiscoveredToken: storyAssetsFocusDiscoveredToken,
    streamingChapterId: streamingChapterId,
    streamingEndRef: streamingEndRef,
    streamingPercent: streamingPercent,
    streamingProgress: streamingProgress,
    streamingText: streamingText,
    unattendedTargetChapter: unattendedTargetChapter,
    workspaceArea: workspaceArea,
    worldbuilding: worldbuilding,
    writingCockpitModel: writingCockpitModel,
    writingRecommendation: writingRecommendation,
  }
}

