export function buildNovelWorkspaceDeferredSurfacesProps(deps: Record<string, any>) {
  const {
    acceptChapterVersion,
    activeChapter,
    activeChapterId,
    activeTasks,
    agentAuditOpen,
    agentExecution,
    applyEditorRevision,
    applyFuture100SkeletonDraft,
    approveChapterGroupStage,
    backupImportOpen,
    backupImportText,
    bulkUpdateRepairTaskStatus,
    cancelEditorRevision,
    cancelKnowledgeIngestJob,
    chapterDrawerOpen,
    chapterGroupExecutingId,
    chapterSearch,
    chapterSortMode,
    chapterStatusFilter,
    chapterTreeData,
    chapterVersionDetail,
    chapters,
    characters,
    commercialToolLoading,
    commercialToolsOpen,
    consistencyGraphOpen,
    continuityAudit,
    continuityAuditLoading,
    createBackupSnapshot,
    createFirst30RetentionRepairQueue,
    createLongformProductionRepairQueue,
    createMechanicalQaRepairQueue,
    createRecoveryEvidenceGovernanceQueue,
    creativeCardsOpen,
    creativeCommandOpen,
    creativeCommandPlan,
    creativeCommandText,
    deleteChapter,
    downloadBackupPackage,
    editorForm,
    editorKind,
    executeChapterGroupRun,
    executeReleaseRepairRun,
    executeTypedRepairTask,
    exportDeliveryOpen,
    extractStyleSampleCandidates,
    fillDefaultStyleSampleBank,
    filteredChapters,
    flushPendingSave,
    future100ApplyLoading,
    future100FocusOutlineIds,
    generateCurrentChapterProse,
    generateFuture100Skeleton,
    generateLongformRepairAuditSummary,
    generateWritingBibleEditor,
    generatingProse,
    handleOutlineGenerate,
    handleRestructure,
    importBackupPackage,
    knowledgeIngestJobs,
    knowledgeJobsLoading,
    loadEditorRevisionDiagnostics,
    loadKnowledgeIngestJobs,
    loadProductionTasks,
    loadProjectModules,
    loading,
    locateRepairTaskChapter,
    mergeChapterVersion,
    openAgentConfigEditor,
    openApprovalPolicyEditor,
    openChapterQualityCard,
    openContinuityAudit,
    openEditor,
    openGenreTemplates,
    openLongformProductionTrends,
    openMaterialRepairPlan,
    openModelDiagnostics,
    openProductionDesk,
    openProductionMetrics,
    openReferenceKnowledgeDiagnosis,
    openRepairTaskChapterEditor,
    openRunQueue,
    openStoryStateEditor,
    openWritingBibleEditor,
    outlinePanelOpen,
    outlineTreeOpen,
    outlines,
    pauseKnowledgeIngestJob,
    previewStyleSampleAdjustmentBatch,
    previewStyleSampleAdjustmentPatch,
    productionMode,
    productionModeOptions,
    productionTasks,
    productionTasksLoading,
    projectId,
    proseChapters,
    qualityBenchmarkOpen,
    recheckRepairTaskConvergence,
    recheckStyleSampleTaskBookReviewTasks,
    recoverRunQueue,
    referenceConfigOpen,
    referenceEngineeringOpen,
    referenceReports,
    refreshConsistencyAudit,
    refreshPropagationDebt,
    releaseRepairExecutingId,
    restructurePanelOpen,
    resumeKnowledgeIngestJob,
    retryEditorRevision,
    retryChapterGroupStage,
    reviewAnnotationsOpen,
    reviewStyleSampleAdjustmentPatch,
    reviews,
    rollingBackVersionId,
    runCreativeCommand,
    runFirst30RetentionDiagnosis,
    runFuture100SkeletonAudit,
    runLongformCreationDiagnosis,
    runLongformPressureTest,
    runMechanicalQa,
    runMechanicalQaLlmReview,
    runPropagationDebtLlmPlan,
    runQualityBenchmark,
    runRecords,
    runReferenceMigrationPlan,
    runRollingPlan,
    runSimilarityForActiveChapter,
    runTopicValidation,
    runVersionReviewForActiveChapter,
    saveStoryStateEditor,
    saveWritingBibleEditor,
    selectChapterForWriting,
    selectMode,
    selectedChapterIds,
    selectedChaptersList,
    selectedModelId,
    selectedProject,
    setAgentAuditOpen,
    setAgentExecution,
    setBackupImportOpen,
    setBackupImportText,
    setChapterDrawerOpen,
    setChapterSearch,
    setChapterSortMode,
    setChapterStatusFilter,
    setChapterVersionDetail,
    setCommercialToolsOpen,
    setConsistencyGraphOpen,
    setCreativeCardsOpen,
    setCreativeCommandOpen,
    setCreativeCommandText,
    setEditorItem,
    setEditorKind,
    setExportDeliveryOpen,
    setFuture100Draft,
    setFuture100FocusOutlineIds,
    setFuture100SelectedNos,
    setOutlinePanelOpen,
    setOutlineTreeOpen,
    setProductionMode,
    setQualityBenchmarkOpen,
    setReferenceConfigOpen,
    setReferenceEngineeringOpen,
    setRestructurePanelOpen,
    setReviewAnnotationsOpen,
    setRightPanelOpen,
    setRightPanelTab,
    setSelectMode,
    setSelectedChapterIds,
    setSelectedProject,
    setShowOnlyDiff,
    setStoryStateOpen,
    setTaskCenterOpen,
    setTaskCenterRecoveryFocus,
    setUnattendedTargetChapter,
    setWritingBibleOpen,
    showOnlyDiff,
    skipChapterGroupStage,
    sortedChapters,
    startFuture100ChapterGroupGeneration,
    startReadyChapterGroupGeneration,
    startRepairTaskRevision,
    startRunQueueWorker,
    startUnattendedWritingGoal,
    stopRunQueueWorker,
    storyStateForm,
    storyStateOpen,
    styleSampleCandidateLoading,
    styleSampleEffectiveness,
    styleSampleEffectivenessItems,
    styleSampleEffectivenessLoading,
    styleSamplePatchLoadingKey,
    submitEditor,
    taskCenterOpen,
    taskCenterRecoveryFocus,
    unattendedTargetChapter,
    undoStyleSampleAdjustmentPatch,
    updateRepairTaskStatus,
    worldbuilding,
    writingBibleForm,
    writingBibleGenerating,
    writingBibleOpen,
    chapterId,
    future100Draft,
    future100SelectedNos,
    id,
  } = deps

  return {
    acceptChapterVersion: acceptChapterVersion,
    activeChapter: activeChapter,
    activeChapterId: activeChapterId,
    activeTasks: activeTasks,
    agentAuditOpen: agentAuditOpen,
    agentExecution: agentExecution,
    applyEditorRevision: applyEditorRevision,
    applyFuture100SkeletonDraft: applyFuture100SkeletonDraft,
    approveChapterGroupStage: approveChapterGroupStage,
    backupImportOpen: backupImportOpen,
    backupImportText: backupImportText,
    bulkUpdateRepairTaskStatus: bulkUpdateRepairTaskStatus,
    cancelEditorRevision: cancelEditorRevision,
    cancelKnowledgeIngestJob: cancelKnowledgeIngestJob,
    chapterDrawerOpen: chapterDrawerOpen,
    chapterGroupExecutingId: chapterGroupExecutingId,
    chapterSearch: chapterSearch,
    chapterSortMode: chapterSortMode,
    chapterStatusFilter: chapterStatusFilter,
    chapterTreeData: chapterTreeData,
    chapterVersionDetail: chapterVersionDetail,
    chapters: chapters,
    characters: characters,
    commercialToolLoading: commercialToolLoading,
    commercialToolsOpen: commercialToolsOpen,
    consistencyGraphOpen: consistencyGraphOpen,
    continuityAudit: continuityAudit,
    continuityAuditLoading: continuityAuditLoading,
    createBackupSnapshot: createBackupSnapshot,
    createFirst30RetentionRepairQueue: createFirst30RetentionRepairQueue,
    createLongformProductionRepairQueue: createLongformProductionRepairQueue,
    createMechanicalQaRepairQueue: createMechanicalQaRepairQueue,
    createRecoveryEvidenceGovernanceQueue: createRecoveryEvidenceGovernanceQueue,
    creativeCardsOpen: creativeCardsOpen,
    creativeCommandOpen: creativeCommandOpen,
    creativeCommandPlan: creativeCommandPlan,
    creativeCommandText: creativeCommandText,
    deleteChapter: deleteChapter,
    downloadBackupPackage: downloadBackupPackage,
    editorForm: editorForm,
    editorKind: editorKind,
    executeChapterGroupRun: executeChapterGroupRun,
    executeReleaseRepairRun: executeReleaseRepairRun,
    executeTypedRepairTask: executeTypedRepairTask,
    exportDeliveryOpen: exportDeliveryOpen,
    extractStyleSampleCandidates: extractStyleSampleCandidates,
    fillDefaultStyleSampleBank: fillDefaultStyleSampleBank,
    filteredChapters: filteredChapters,
    flushPendingSave: flushPendingSave,
    future100ApplyLoading: future100ApplyLoading,
    future100FocusOutlineIds: future100FocusOutlineIds,
    generateCurrentChapterProse: generateCurrentChapterProse,
    generateFuture100Skeleton: generateFuture100Skeleton,
    generateLongformRepairAuditSummary: generateLongformRepairAuditSummary,
    generateWritingBibleEditor: generateWritingBibleEditor,
    generatingProse: generatingProse,
    handleOutlineGenerate: handleOutlineGenerate,
    handleRestructure: handleRestructure,
    importBackupPackage: importBackupPackage,
    knowledgeIngestJobs: knowledgeIngestJobs,
    knowledgeJobsLoading: knowledgeJobsLoading,
    loadEditorRevisionDiagnostics: loadEditorRevisionDiagnostics,
    loadKnowledgeIngestJobs: loadKnowledgeIngestJobs,
    loadProductionTasks: loadProductionTasks,
    loadProjectModules: loadProjectModules,
    loading: loading,
    locateRepairTaskChapter: locateRepairTaskChapter,
    mergeChapterVersion: mergeChapterVersion,
    openAgentConfigEditor: openAgentConfigEditor,
    openApprovalPolicyEditor: openApprovalPolicyEditor,
    openChapterQualityCard: openChapterQualityCard,
    openContinuityAudit: openContinuityAudit,
    openEditor: openEditor,
    openGenreTemplates: openGenreTemplates,
    openLongformProductionTrends: openLongformProductionTrends,
    openMaterialRepairPlan: openMaterialRepairPlan,
    openModelDiagnostics: openModelDiagnostics,
    openProductionDesk: openProductionDesk,
    openProductionMetrics: openProductionMetrics,
    openReferenceKnowledgeDiagnosis: openReferenceKnowledgeDiagnosis,
    openRepairTaskChapterEditor: openRepairTaskChapterEditor,
    openRunQueue: openRunQueue,
    openStoryStateEditor: openStoryStateEditor,
    openWritingBibleEditor: openWritingBibleEditor,
    outlinePanelOpen: outlinePanelOpen,
    outlineTreeOpen: outlineTreeOpen,
    outlines: outlines,
    pauseKnowledgeIngestJob: pauseKnowledgeIngestJob,
    previewStyleSampleAdjustmentBatch: previewStyleSampleAdjustmentBatch,
    previewStyleSampleAdjustmentPatch: previewStyleSampleAdjustmentPatch,
    productionMode: productionMode,
    productionModeOptions: productionModeOptions,
    productionTasks: productionTasks,
    productionTasksLoading: productionTasksLoading,
    projectId: projectId,
    proseChapters: proseChapters,
    qualityBenchmarkOpen: qualityBenchmarkOpen,
    recheckRepairTaskConvergence: recheckRepairTaskConvergence,
    recheckStyleSampleTaskBookReviewTasks: recheckStyleSampleTaskBookReviewTasks,
    recoverRunQueue: recoverRunQueue,
    referenceConfigOpen: referenceConfigOpen,
    referenceEngineeringOpen: referenceEngineeringOpen,
    referenceReports: referenceReports,
    refreshConsistencyAudit: refreshConsistencyAudit,
    refreshPropagationDebt: refreshPropagationDebt,
    releaseRepairExecutingId: releaseRepairExecutingId,
    restructurePanelOpen: restructurePanelOpen,
    resumeKnowledgeIngestJob: resumeKnowledgeIngestJob,
    retryEditorRevision: retryEditorRevision,
    retryChapterGroupStage: retryChapterGroupStage,
    reviewAnnotationsOpen: reviewAnnotationsOpen,
    reviewStyleSampleAdjustmentPatch: reviewStyleSampleAdjustmentPatch,
    reviews: reviews,
    rollingBackVersionId: rollingBackVersionId,
    runCreativeCommand: runCreativeCommand,
    runFirst30RetentionDiagnosis: runFirst30RetentionDiagnosis,
    runFuture100SkeletonAudit: runFuture100SkeletonAudit,
    runLongformCreationDiagnosis: runLongformCreationDiagnosis,
    runLongformPressureTest: runLongformPressureTest,
    runMechanicalQa: runMechanicalQa,
    runMechanicalQaLlmReview: runMechanicalQaLlmReview,
    runPropagationDebtLlmPlan: runPropagationDebtLlmPlan,
    runQualityBenchmark: runQualityBenchmark,
    runRecords: runRecords,
    runReferenceMigrationPlan: runReferenceMigrationPlan,
    runRollingPlan: runRollingPlan,
    runSimilarityForActiveChapter: runSimilarityForActiveChapter,
    runTopicValidation: runTopicValidation,
    runVersionReviewForActiveChapter: runVersionReviewForActiveChapter,
    saveStoryStateEditor: saveStoryStateEditor,
    saveWritingBibleEditor: saveWritingBibleEditor,
    selectChapterForWriting: selectChapterForWriting,
    selectMode: selectMode,
    selectedChapterIds: selectedChapterIds,
    selectedChaptersList: selectedChaptersList,
    selectedModelId: selectedModelId,
    selectedProject: selectedProject,
    setAgentAuditOpen: setAgentAuditOpen,
    setAgentExecution: setAgentExecution,
    setBackupImportOpen: setBackupImportOpen,
    setBackupImportText: setBackupImportText,
    setChapterDrawerOpen: setChapterDrawerOpen,
    setChapterSearch: setChapterSearch,
    setChapterSortMode: setChapterSortMode,
    setChapterStatusFilter: setChapterStatusFilter,
    setChapterVersionDetail: setChapterVersionDetail,
    setCommercialToolsOpen: setCommercialToolsOpen,
    setConsistencyGraphOpen: setConsistencyGraphOpen,
    setCreativeCardsOpen: setCreativeCardsOpen,
    setCreativeCommandOpen: setCreativeCommandOpen,
    setCreativeCommandText: setCreativeCommandText,
    setEditorItem: setEditorItem,
    setEditorKind: setEditorKind,
    setExportDeliveryOpen: setExportDeliveryOpen,
    setFuture100Draft: setFuture100Draft,
    setFuture100FocusOutlineIds: setFuture100FocusOutlineIds,
    setFuture100SelectedNos: setFuture100SelectedNos,
    setOutlinePanelOpen: setOutlinePanelOpen,
    setOutlineTreeOpen: setOutlineTreeOpen,
    setProductionMode: setProductionMode,
    setQualityBenchmarkOpen: setQualityBenchmarkOpen,
    setReferenceConfigOpen: setReferenceConfigOpen,
    setReferenceEngineeringOpen: setReferenceEngineeringOpen,
    setRestructurePanelOpen: setRestructurePanelOpen,
    setReviewAnnotationsOpen: setReviewAnnotationsOpen,
    setRightPanelOpen: setRightPanelOpen,
    setRightPanelTab: setRightPanelTab,
    setSelectMode: setSelectMode,
    setSelectedChapterIds: setSelectedChapterIds,
    setSelectedProject: setSelectedProject,
    setShowOnlyDiff: setShowOnlyDiff,
    setStoryStateOpen: setStoryStateOpen,
    setTaskCenterOpen: setTaskCenterOpen,
    setTaskCenterRecoveryFocus: setTaskCenterRecoveryFocus,
    setUnattendedTargetChapter: setUnattendedTargetChapter,
    setWritingBibleOpen: setWritingBibleOpen,
    showOnlyDiff: showOnlyDiff,
    skipChapterGroupStage: skipChapterGroupStage,
    sortedChapters: sortedChapters,
    startFuture100ChapterGroupGeneration: startFuture100ChapterGroupGeneration,
    startReadyChapterGroupGeneration: startReadyChapterGroupGeneration,
    startRepairTaskRevision: startRepairTaskRevision,
    startRunQueueWorker: startRunQueueWorker,
    startUnattendedWritingGoal: startUnattendedWritingGoal,
    stopRunQueueWorker: stopRunQueueWorker,
    storyStateForm: storyStateForm,
    storyStateOpen: storyStateOpen,
    styleSampleCandidateLoading: styleSampleCandidateLoading,
    styleSampleEffectiveness: styleSampleEffectiveness,
    styleSampleEffectivenessItems: styleSampleEffectivenessItems,
    styleSampleEffectivenessLoading: styleSampleEffectivenessLoading,
    styleSamplePatchLoadingKey: styleSamplePatchLoadingKey,
    submitEditor: submitEditor,
    taskCenterOpen: taskCenterOpen,
    taskCenterRecoveryFocus: taskCenterRecoveryFocus,
    unattendedTargetChapter: unattendedTargetChapter,
    undoStyleSampleAdjustmentPatch: undoStyleSampleAdjustmentPatch,
    updateRepairTaskStatus: updateRepairTaskStatus,
    worldbuilding: worldbuilding,
    writingBibleForm: writingBibleForm,
    writingBibleGenerating: writingBibleGenerating,
    writingBibleOpen: writingBibleOpen,
    chapterId: chapterId,
    future100Draft: future100Draft,
    future100SelectedNos: future100SelectedNos,
    id: id,
  }
}
