export type NovelWorkspaceDeferredSurfacesProps = {
  acceptChapterVersion: any
  activeChapter: any
  activeChapterId: any
  activeTasks: any
  agentAuditOpen: any
  agentExecution: any
  applyEditorRevision: any
  applyFuture100SkeletonDraft: any
  approveChapterGroupStage: any
  backupImportOpen: any
  backupImportText: any
  bulkUpdateRepairTaskStatus: any
  cancelEditorRevision: any
  cancelKnowledgeIngestJob: any
  chapterDrawerOpen: any
  chapterGroupExecutingId: any
  chapterSearch: any
  chapterSortMode: any
  chapterStatusFilter: any
  chapterTreeData: any
  chapterVersionDetail: any
  chapters: any
  characters: any
  commercialToolLoading: any
  commercialToolsOpen: any
  consistencyGraphOpen: any
  continuityAudit: any
  continuityAuditLoading: any
  createBackupSnapshot: any
  createFirst30RetentionRepairQueue: any
  createLongformProductionRepairQueue: any
  createMechanicalQaRepairQueue: any
  createRecoveryEvidenceGovernanceQueue: any
  creativeCardsOpen: any
  creativeCommandOpen: any
  creativeCommandPlan: any
  creativeCommandText: any
  deleteChapter: any
  downloadBackupPackage: any
  editorForm: any
  editorKind: any
  executeChapterGroupRun: any
  executeReleaseRepairRun: any
  executeTypedRepairTask: any
  exportDeliveryOpen: any
  extractStyleSampleCandidates: any
  fillDefaultStyleSampleBank: any
  filteredChapters: any
  flushPendingSave: any
  future100ApplyLoading: any
  future100FocusOutlineIds: any
  generateCurrentChapterProse: any
  generateFuture100Skeleton: any
  generateLongformRepairAuditSummary: any
  generateWritingBibleEditor: any
  generatingProse: any
  handleOutlineGenerate: any
  handleRestructure: any
  importBackupPackage: any
  knowledgeIngestJobs: any
  knowledgeJobsLoading: any
  loadEditorRevisionDiagnostics: any
  loadKnowledgeIngestJobs: any
  loadProductionTasks: any
  loadProjectModules: any
  loading: any
  locateRepairTaskChapter: any
  mergeChapterVersion: any
  openAgentConfigEditor: any
  openApprovalPolicyEditor: any
  openChapterQualityCard: any
  openContinuityAudit: any
  openEditor: any
  openGenreTemplates: any
  openLongformProductionTrends: any
  openMaterialRepairPlan: any
  openModelDiagnostics: any
  openProductionDesk: any
  openProductionMetrics: any
  openReferenceKnowledgeDiagnosis: any
  openRepairTaskChapterEditor: any
  openRunQueue: any
  openStoryStateEditor: any
  openWritingBibleEditor: any
  outlinePanelOpen: any
  outlineTreeOpen: any
  outlines: any
  pauseKnowledgeIngestJob: any
  previewStyleSampleAdjustmentBatch: any
  previewStyleSampleAdjustmentPatch: any
  productionMode: any
  productionModeOptions: any
  productionTasks: any
  productionTasksLoading: any
  projectId: any
  proseChapters: any
  qualityBenchmarkOpen: any
  recheckRepairTaskConvergence: any
  recheckStyleSampleTaskBookReviewTasks: any
  recoverRunQueue: any
  referenceConfigOpen: any
  referenceEngineeringOpen: any
  referenceReports: any
  refreshConsistencyAudit: any
  refreshPropagationDebt: any
  releaseRepairExecutingId: any
  restructurePanelOpen: any
  resumeKnowledgeIngestJob: any
  retryEditorRevision: any
  retryChapterGroupStage: any
  reviewAnnotationsOpen: any
  reviewStyleSampleAdjustmentPatch: any
  reviews: any
  rollingBackVersionId: any
  runCreativeCommand: any
  runFirst30RetentionDiagnosis: any
  runFuture100SkeletonAudit: any
  runLongformCreationDiagnosis: any
  runLongformPressureTest: any
  runMechanicalQa: any
  runMechanicalQaLlmReview: any
  runPropagationDebtLlmPlan: any
  runQualityBenchmark: any
  runRecords: any
  runReferenceMigrationPlan: any
  runRollingPlan: any
  runSimilarityForActiveChapter: any
  runTopicValidation: any
  runVersionReviewForActiveChapter: any
  saveStoryStateEditor: any
  saveWritingBibleEditor: any
  selectChapterForWriting: any
  selectMode: any
  selectedChapterIds: any
  selectedChaptersList: any
  selectedModelId: any
  selectedProject: any
  setAgentAuditOpen: any
  setAgentExecution: any
  setBackupImportOpen: any
  setBackupImportText: any
  setChapterDrawerOpen: any
  setChapterSearch: any
  setChapterSortMode: any
  setChapterStatusFilter: any
  setChapterVersionDetail: any
  setCommercialToolsOpen: any
  setConsistencyGraphOpen: any
  setCreativeCardsOpen: any
  setCreativeCommandOpen: any
  setCreativeCommandText: any
  setEditorItem: any
  setEditorKind: any
  setExportDeliveryOpen: any
  setFuture100Draft: any
  setFuture100FocusOutlineIds: any
  setFuture100SelectedNos: any
  setOutlinePanelOpen: any
  setOutlineTreeOpen: any
  setProductionMode: any
  setQualityBenchmarkOpen: any
  setReferenceConfigOpen: any
  setReferenceEngineeringOpen: any
  setRestructurePanelOpen: any
  setReviewAnnotationsOpen: any
  setRightPanelOpen: any
  setRightPanelTab: any
  setSelectMode: any
  setSelectedChapterIds: any
  setSelectedProject: any
  setShowOnlyDiff: any
  setStoryStateOpen: any
  setTaskCenterOpen: any
  setTaskCenterRecoveryFocus: any
  setUnattendedTargetChapter: any
  setWritingBibleOpen: any
  showOnlyDiff: any
  skipChapterGroupStage: any
  sortedChapters: any
  startFuture100ChapterGroupGeneration: any
  startReadyChapterGroupGeneration: any
  startRepairTaskRevision: any
  startRunQueueWorker: any
  startUnattendedWritingGoal: any
  stopRunQueueWorker: any
  storyStateForm: any
  storyStateOpen: any
  styleSampleCandidateLoading: any
  styleSampleEffectiveness: any
  styleSampleEffectivenessItems: any
  styleSampleEffectivenessLoading: any
  styleSamplePatchLoadingKey: any
  submitEditor: any
  taskCenterOpen: any
  taskCenterRecoveryFocus: any
  unattendedTargetChapter: any
  undoStyleSampleAdjustmentPatch: any
  updateRepairTaskStatus: any
  worldbuilding: any
  writingBibleForm: any
  writingBibleGenerating: any
  writingBibleOpen: any
  chapterId: any
  future100Draft: any
  future100SelectedNos: any
  id: any
}
