export function buildNovelWorkspaceAreaViewProps(deps: Record<string, any>) {
  const {
    activeChapter,
    activeChapterDiagnosticsData,
    activeChapterId,
    applyStyleSampleActionForActiveChapter,
    autoCreationDirectorModel,
    autoDirectorActionLoadingKey,
    bookReviewLoading,
    buildPreDraftBriefForActiveChapter,
    chapterTargetWordCount,
    chapterWordTargetMode,
    characters,
    commercialToolLoading,
    confirmPreDraftBriefForActiveChapter,
    continuityAudit,
    createEditorReport,
    dashboardLoading,
    diagnosticsLoading,
    editorReportLoading,
    generateCurrentChapterProse,
    generateSceneCardsForActiveChapter,
    generatingProse,
    generatingSceneCards,
    generationPipeline,
    handleAutoCreationDirectorAction,
    handlePlanningAction,
    handleWritingCockpitAction,
    id,
    incubatingOriginal,
    isEmptyProject,
    isImmersiveShell,
    loadProjectModules,
    openChapterQualityCard,
    openContinuityAudit,
    openEditor,
    openGenerationDiagnostics,
    openProductionDashboard,
    openProductionDesk,
    openProductionMetrics,
    openRunQueue,
    openStoryAssetsWorkspace,
    openStoryStateEditor,
    openWritingBibleEditor,
    outlines,
    pipelineLoading,
    planning,
    planningLoadingKey,
    planningWorkspaceModel,
    projectId,
    projectSettings,
    proseEditorRef,
    proseQualityLoading,
    repairActiveDeslopGate,
    repairContextAndGenerateCurrentChapter,
    repairWritingQueuePlan,
    repairWritingQueuePlanBatch,
    runBookReview,
    runOriginalIncubator,
    runPlan,
    runReferenceMigrationPlan,
    savePreDraftBriefForActiveChapter,
    saveStatus,
    scheduleSave,
    selectChapterForWriting,
    selectedModelId,
    selectedProject,
    setAgentAuditOpen,
    setChapterTargetWordCount,
    setChapterWordTargetMode,
    setChapters,
    setCommercialToolsOpen,
    setConsistencyGraphOpen,
    setCreativeCardsOpen,
    setExportDeliveryOpen,
    setQualityBenchmarkOpen,
    setReferenceConfigOpen,
    setReferenceEngineeringOpen,
    setReviewAnnotationsOpen,
    setTaskCenterOpen,
    setUnattendedTargetChapter,
    setWorkspaceArea,
    sortedChapters,
    startChapterGroupGeneration,
    startChapterPipeline,
    startReadyChapterGroupGeneration,
    startUnattendedWritingGoal,
    storyAssetsFocusDiscoveredToken,
    streamingChapterId,
    streamingEndRef,
    streamingPercent,
    streamingProgress,
    streamingText,
    unattendedTargetChapter,
    workspaceArea,
    worldbuilding,
    writingCockpitModel,
    writingRecommendation,
  } = deps
  return {
    activeChapter: activeChapter,
    activeChapterDiagnosticsData: activeChapterDiagnosticsData,
    activeChapterId: activeChapterId,
    applyStyleSampleActionForActiveChapter: applyStyleSampleActionForActiveChapter,
    autoCreationDirectorModel: autoCreationDirectorModel,
    autoDirectorActionLoadingKey: autoDirectorActionLoadingKey,
    bookReviewLoading: bookReviewLoading,
    buildPreDraftBriefForActiveChapter: buildPreDraftBriefForActiveChapter,
    chapterTargetWordCount: chapterTargetWordCount,
    chapterWordTargetMode: chapterWordTargetMode,
    characters: characters,
    commercialToolLoading: commercialToolLoading,
    confirmPreDraftBriefForActiveChapter: confirmPreDraftBriefForActiveChapter,
    continuityAudit: continuityAudit,
    createEditorReport: createEditorReport,
    dashboardLoading: dashboardLoading,
    diagnosticsLoading: diagnosticsLoading,
    editorReportLoading: editorReportLoading,
    generateCurrentChapterProse: generateCurrentChapterProse,
    generateSceneCardsForActiveChapter: generateSceneCardsForActiveChapter,
    generatingProse: generatingProse,
    generatingSceneCards: generatingSceneCards,
    generationPipeline: generationPipeline,
    handleAutoCreationDirectorAction: handleAutoCreationDirectorAction,
    handlePlanningAction: handlePlanningAction,
    handleWritingCockpitAction: handleWritingCockpitAction,
    id: id,
    incubatingOriginal: incubatingOriginal,
    isEmptyProject: isEmptyProject,
    isImmersiveShell: isImmersiveShell,
    loadProjectModules: loadProjectModules,
    openChapterQualityCard: openChapterQualityCard,
    openContinuityAudit: openContinuityAudit,
    openEditor: openEditor,
    openGenerationDiagnostics: openGenerationDiagnostics,
    openProductionDashboard: openProductionDashboard,
    openProductionDesk: openProductionDesk,
    openProductionMetrics: openProductionMetrics,
    openRunQueue: openRunQueue,
    openStoryAssetsWorkspace: openStoryAssetsWorkspace,
    openStoryStateEditor: openStoryStateEditor,
    openWritingBibleEditor: openWritingBibleEditor,
    outlines: outlines,
    pipelineLoading: pipelineLoading,
    planning: planning,
    planningLoadingKey: planningLoadingKey,
    planningWorkspaceModel: planningWorkspaceModel,
    projectId: projectId,
    projectSettings: projectSettings,
    proseEditorRef: proseEditorRef,
    proseQualityLoading: proseQualityLoading,
    repairActiveDeslopGate: repairActiveDeslopGate,
    repairContextAndGenerateCurrentChapter: repairContextAndGenerateCurrentChapter,
    repairWritingQueuePlan: repairWritingQueuePlan,
    repairWritingQueuePlanBatch: repairWritingQueuePlanBatch,
    runBookReview: runBookReview,
    runOriginalIncubator: runOriginalIncubator,
    runPlan: runPlan,
    runReferenceMigrationPlan: runReferenceMigrationPlan,
    savePreDraftBriefForActiveChapter: savePreDraftBriefForActiveChapter,
    saveStatus: saveStatus,
    scheduleSave: scheduleSave,
    selectChapterForWriting: selectChapterForWriting,
    selectedModelId: selectedModelId,
    selectedProject: selectedProject,
    setAgentAuditOpen: setAgentAuditOpen,
    setChapterTargetWordCount: setChapterTargetWordCount,
    setChapterWordTargetMode: setChapterWordTargetMode,
    setChapters: setChapters,
    setCommercialToolsOpen: setCommercialToolsOpen,
    setConsistencyGraphOpen: setConsistencyGraphOpen,
    setCreativeCardsOpen: setCreativeCardsOpen,
    setExportDeliveryOpen: setExportDeliveryOpen,
    setQualityBenchmarkOpen: setQualityBenchmarkOpen,
    setReferenceConfigOpen: setReferenceConfigOpen,
    setReferenceEngineeringOpen: setReferenceEngineeringOpen,
    setReviewAnnotationsOpen: setReviewAnnotationsOpen,
    setTaskCenterOpen: setTaskCenterOpen,
    setUnattendedTargetChapter: setUnattendedTargetChapter,
    setWorkspaceArea: setWorkspaceArea,
    sortedChapters: sortedChapters,
    startChapterGroupGeneration: startChapterGroupGeneration,
    startChapterPipeline: startChapterPipeline,
    startReadyChapterGroupGeneration: startReadyChapterGroupGeneration,
    startUnattendedWritingGoal: startUnattendedWritingGoal,
    storyAssetsFocusDiscoveredToken: storyAssetsFocusDiscoveredToken,
    streamingChapterId: streamingChapterId,
    streamingEndRef: streamingEndRef,
    streamingPercent: streamingPercent,
    streamingProgress: streamingProgress,
    streamingText: streamingText,
    unattendedTargetChapter: unattendedTargetChapter,
    workspaceArea: workspaceArea,
    worldbuilding: worldbuilding,
    writingCockpitModel: writingCockpitModel,
    writingRecommendation: writingRecommendation,
  }
}

export function buildNovelWorkspaceBodyProps(deps: Record<string, any>) {
  const {
    activeChapter,
    activeChapterDiagnosticsData,
    activeChapterId,
    activeContextPackageData,
    activeKnowledgeJobCount,
    activeTasks,
    applyEditorRevision,
    bookReviews,
    chapterId,
    chapterVersions,
    chapterVersionsLoading,
    characters,
    cockpitPrimaryActionOverride,
    commercialReadiness,
    commercialToolLoading,
    contextPackage,
    contextPackageLoading,
    copyCreativeAssistantCard,
    creativeAssistantError,
    creativeAssistantLoading,
    creativeAssistantMode,
    creativeAssistantOpen,
    creativeAssistantResult,
    creativeAssistantSelectedText,
    diagnosticsLoading,
    directoryCollapsed,
    directoryShellClassName,
    editorReports,
    editorRevisionReports,
    generatingProse,
    generatingSceneCards,
    handleDirectoryCollapsedChange,
    handleWritingCockpitAction,
    isImmersiveShell,
    openEditor,
    openStoryStateEditor,
    outlines,
    projectId,
    proseChapters,
    proseProgress,
    proseQualityLoading,
    proseQualityReports,
    referenceReports,
    refreshActiveProseQuality,
    renderSerialPipeline,
    renderWorkspaceArea,
    reviews,
    rightPanelOpen,
    rightPanelTab,
    rollbackChapterVersion,
    rollingBackVersionId,
    runCreativeAssistant,
    runRecords,
    selectChapterForWriting,
    selectedModelId,
    selectedProject,
    setChapterDrawerOpen,
    setChapterVersionDetail,
    setCreativeAssistantMode,
    setCreativeAssistantOpen,
    setCreativeCardsOpen,
    setOutlineTreeOpen,
    setRightPanelOpen,
    setRightPanelTab,
    setTaskCenterOpen,
    setWorkspaceArea,
    showGlobalWritingGuidance,
    sortedChapters,
    stepProseLoading,
    workspaceArea,
    worldbuilding,
    writingCockpitModel,
  } = deps
  return {
    activeChapter: activeChapter,
    activeChapterDiagnosticsData: activeChapterDiagnosticsData,
    activeChapterId: activeChapterId,
    activeContextPackageData: activeContextPackageData,
    activeKnowledgeJobCount: activeKnowledgeJobCount,
    activeTasks: activeTasks,
    applyEditorRevision: applyEditorRevision,
    bookReviews: bookReviews,
    chapterId: chapterId,
    chapterVersions: chapterVersions,
    chapterVersionsLoading: chapterVersionsLoading,
    characters: characters,
    cockpitPrimaryActionOverride: cockpitPrimaryActionOverride,
    commercialReadiness: commercialReadiness,
    commercialToolLoading: commercialToolLoading,
    contextPackage: contextPackage,
    contextPackageLoading: contextPackageLoading,
    copyCreativeAssistantCard: copyCreativeAssistantCard,
    creativeAssistantError: creativeAssistantError,
    creativeAssistantLoading: creativeAssistantLoading,
    creativeAssistantMode: creativeAssistantMode,
    creativeAssistantOpen: creativeAssistantOpen,
    creativeAssistantResult: creativeAssistantResult,
    creativeAssistantSelectedText: creativeAssistantSelectedText,
    diagnosticsLoading: diagnosticsLoading,
    directoryCollapsed: directoryCollapsed,
    directoryShellClassName: directoryShellClassName,
    editorReports: editorReports,
    editorRevisionReports: editorRevisionReports,
    generatingProse: generatingProse,
    generatingSceneCards: generatingSceneCards,
    handleDirectoryCollapsedChange: handleDirectoryCollapsedChange,
    handleWritingCockpitAction: handleWritingCockpitAction,
    isImmersiveShell: isImmersiveShell,
    openEditor: openEditor,
    openStoryStateEditor: openStoryStateEditor,
    outlines: outlines,
    projectId: projectId,
    proseChapters: proseChapters,
    proseProgress: proseProgress,
    proseQualityLoading: proseQualityLoading,
    proseQualityReports: proseQualityReports,
    referenceReports: referenceReports,
    refreshActiveProseQuality: refreshActiveProseQuality,
    renderSerialPipeline: renderSerialPipeline,
    renderWorkspaceArea: renderWorkspaceArea,
    reviews: reviews,
    rightPanelOpen: rightPanelOpen,
    rightPanelTab: rightPanelTab,
    rollbackChapterVersion: rollbackChapterVersion,
    rollingBackVersionId: rollingBackVersionId,
    runCreativeAssistant: runCreativeAssistant,
    runRecords: runRecords,
    selectChapterForWriting: selectChapterForWriting,
    selectedModelId: selectedModelId,
    selectedProject: selectedProject,
    setChapterDrawerOpen: setChapterDrawerOpen,
    setChapterVersionDetail: setChapterVersionDetail,
    setCreativeAssistantMode: setCreativeAssistantMode,
    setCreativeAssistantOpen: setCreativeAssistantOpen,
    setCreativeCardsOpen: setCreativeCardsOpen,
    setOutlineTreeOpen: setOutlineTreeOpen,
    setRightPanelOpen: setRightPanelOpen,
    setRightPanelTab: setRightPanelTab,
    setTaskCenterOpen: setTaskCenterOpen,
    setWorkspaceArea: setWorkspaceArea,
    showGlobalWritingGuidance: showGlobalWritingGuidance,
    sortedChapters: sortedChapters,
    stepProseLoading: stepProseLoading,
    workspaceArea: workspaceArea,
    worldbuilding: worldbuilding,
    writingCockpitModel: writingCockpitModel,
  }
}

export function buildNovelWorkspaceDeferredSurfacesProps(deps: Record<string, any>) {
  const {
    acceptChapterVersion,
    activeChapter,
    activeChapterId,
    activeTasks,
    agentAuditOpen,
    agentExecution,
    applyEditorRevision,
    applyFuture100SkeletonDraft,
    approveChapterGroupStage,
    backupImportOpen,
    backupImportText,
    bulkUpdateRepairTaskStatus,
    cancelKnowledgeIngestJob,
    chapterDrawerOpen,
    chapterGroupExecutingId,
    chapterSearch,
    chapterSortMode,
    chapterStatusFilter,
    chapterTreeData,
    chapterVersionDetail,
    chapters,
    characters,
    commercialToolsOpen,
    consistencyGraphOpen,
    continuityAudit,
    continuityAuditLoading,
    createBackupSnapshot,
    createFirst30RetentionRepairQueue,
    createLongformProductionRepairQueue,
    createMechanicalQaRepairQueue,
    createRecoveryEvidenceGovernanceQueue,
    creativeCardsOpen,
    creativeCommandOpen,
    creativeCommandText,
    deleteChapter,
    downloadBackupPackage,
    editorForm,
    editorKind,
    executeChapterGroupRun,
    executeReleaseRepairRun,
    executeTypedRepairTask,
    exportDeliveryOpen,
    extractStyleSampleCandidates,
    fillDefaultStyleSampleBank,
    filteredChapters,
    flushPendingSave,
    future100ApplyLoading,
    future100FocusOutlineIds,
    generateCurrentChapterProse,
    generateFuture100Skeleton,
    generateLongformRepairAuditSummary,
    generateWritingBibleEditor,
    generatingProse,
    handleOutlineGenerate,
    handleRestructure,
    importBackupPackage,
    knowledgeIngestJobs,
    knowledgeJobsLoading,
    loadKnowledgeIngestJobs,
    loadProductionTasks,
    loadProjectModules,
    locateRepairTaskChapter,
    mergeChapterVersion,
    openAgentConfigEditor,
    openApprovalPolicyEditor,
    openChapterQualityCard,
    openContinuityAudit,
    openEditor,
    openGenreTemplates,
    openLongformProductionTrends,
    openMaterialRepairPlan,
    openModelDiagnostics,
    openProductionDesk,
    openProductionMetrics,
    openReferenceKnowledgeDiagnosis,
    openRepairTaskChapterEditor,
    openRunQueue,
    openStoryStateEditor,
    openWritingBibleEditor,
    outlinePanelOpen,
    outlineTreeOpen,
    outlines,
    pauseKnowledgeIngestJob,
    previewStyleSampleAdjustmentBatch,
    previewStyleSampleAdjustmentPatch,
    productionMode,
    productionModeOptions,
    productionTasks,
    projectId,
    proseChapters,
    qualityBenchmarkOpen,
    recheckRepairTaskConvergence,
    recheckStyleSampleTaskBookReviewTasks,
    recoverRunQueue,
    referenceConfigOpen,
    referenceEngineeringOpen,
    referenceReports,
    refreshConsistencyAudit,
    refreshPropagationDebt,
    releaseRepairExecutingId,
    restructurePanelOpen,
    resumeKnowledgeIngestJob,
    retryChapterGroupStage,
    reviewAnnotationsOpen,
    reviewStyleSampleAdjustmentPatch,
    reviews,
    rollingBackVersionId,
    runCreativeCommand,
    runFirst30RetentionDiagnosis,
    runFuture100SkeletonAudit,
    runLongformCreationDiagnosis,
    runLongformPressureTest,
    runMechanicalQa,
    runMechanicalQaLlmReview,
    runPropagationDebtLlmPlan,
    runQualityBenchmark,
    runRecords,
    runReferenceMigrationPlan,
    runRollingPlan,
    runSimilarityForActiveChapter,
    runTopicValidation,
    runVersionReviewForActiveChapter,
    saveStoryStateEditor,
    saveWritingBibleEditor,
    selectChapterForWriting,
    selectMode,
    selectedChapterIds,
    selectedChaptersList,
    selectedModelId,
    selectedProject,
    setAgentAuditOpen,
    setAgentExecution,
    setBackupImportOpen,
    setBackupImportText,
    setChapterDrawerOpen,
    setChapterSearch,
    setChapterSortMode,
    setChapterStatusFilter,
    setChapterVersionDetail,
    setCommercialToolsOpen,
    setConsistencyGraphOpen,
    setCreativeCardsOpen,
    setCreativeCommandOpen,
    setCreativeCommandText,
    setEditorItem,
    setEditorKind,
    setExportDeliveryOpen,
    setFuture100Draft,
    setFuture100FocusOutlineIds,
    setFuture100SelectedNos,
    setOutlinePanelOpen,
    setOutlineTreeOpen,
    setProductionMode,
    setQualityBenchmarkOpen,
    setReferenceConfigOpen,
    setReferenceEngineeringOpen,
    setRestructurePanelOpen,
    setReviewAnnotationsOpen,
    setRightPanelOpen,
    setRightPanelTab,
    setSelectMode,
    setSelectedChapterIds,
    setSelectedProject,
    setShowOnlyDiff,
    setStoryStateOpen,
    setTaskCenterOpen,
    setTaskCenterRecoveryFocus,
    setUnattendedTargetChapter,
    setWritingBibleOpen,
    showOnlyDiff,
    skipChapterGroupStage,
    sortedChapters,
    startFuture100ChapterGroupGeneration,
    startReadyChapterGroupGeneration,
    startRepairTaskRevision,
    startRunQueueWorker,
    startUnattendedWritingGoal,
    stopRunQueueWorker,
    storyStateForm,
    storyStateOpen,
    styleSampleCandidateLoading,
    submitEditor,
    taskCenterOpen,
    taskCenterRecoveryFocus,
    unattendedTargetChapter,
    undoStyleSampleAdjustmentPatch,
    updateRepairTaskStatus,
    worldbuilding,
    writingBibleForm,
    writingBibleGenerating,
    writingBibleOpen,
  } = deps
  return {
    acceptChapterVersion: acceptChapterVersion,
    activeChapter: activeChapter,
    activeChapterId: activeChapterId,
    activeTasks: activeTasks,
    agentAuditOpen: agentAuditOpen,
    agentExecution: agentExecution,
    applyEditorRevision: applyEditorRevision,
    applyFuture100SkeletonDraft: applyFuture100SkeletonDraft,
    approveChapterGroupStage: approveChapterGroupStage,
    backupImportOpen: backupImportOpen,
    backupImportText: backupImportText,
    bulkUpdateRepairTaskStatus: bulkUpdateRepairTaskStatus,
    cancelKnowledgeIngestJob: cancelKnowledgeIngestJob,
    chapterDrawerOpen: chapterDrawerOpen,
    chapterGroupExecutingId: chapterGroupExecutingId,
    chapterSearch: chapterSearch,
    chapterSortMode: chapterSortMode,
    chapterStatusFilter: chapterStatusFilter,
    chapterTreeData: chapterTreeData,
    chapterVersionDetail: chapterVersionDetail,
    chapters: chapters,
    characters: characters,
    commercialToolsOpen: commercialToolsOpen,
    consistencyGraphOpen: consistencyGraphOpen,
    continuityAudit: continuityAudit,
    continuityAuditLoading: continuityAuditLoading,
    createBackupSnapshot: createBackupSnapshot,
    createFirst30RetentionRepairQueue: createFirst30RetentionRepairQueue,
    createLongformProductionRepairQueue: createLongformProductionRepairQueue,
    createMechanicalQaRepairQueue: createMechanicalQaRepairQueue,
    createRecoveryEvidenceGovernanceQueue: createRecoveryEvidenceGovernanceQueue,
    creativeCardsOpen: creativeCardsOpen,
    creativeCommandOpen: creativeCommandOpen,
    creativeCommandText: creativeCommandText,
    deleteChapter: deleteChapter,
    downloadBackupPackage: downloadBackupPackage,
    editorForm: editorForm,
    editorKind: editorKind,
    executeChapterGroupRun: executeChapterGroupRun,
    executeReleaseRepairRun: executeReleaseRepairRun,
    executeTypedRepairTask: executeTypedRepairTask,
    exportDeliveryOpen: exportDeliveryOpen,
    extractStyleSampleCandidates: extractStyleSampleCandidates,
    fillDefaultStyleSampleBank: fillDefaultStyleSampleBank,
    filteredChapters: filteredChapters,
    flushPendingSave: flushPendingSave,
    future100ApplyLoading: future100ApplyLoading,
    future100FocusOutlineIds: future100FocusOutlineIds,
    generateCurrentChapterProse: generateCurrentChapterProse,
    generateFuture100Skeleton: generateFuture100Skeleton,
    generateLongformRepairAuditSummary: generateLongformRepairAuditSummary,
    generateWritingBibleEditor: generateWritingBibleEditor,
    generatingProse: generatingProse,
    handleOutlineGenerate: handleOutlineGenerate,
    handleRestructure: handleRestructure,
    importBackupPackage: importBackupPackage,
    knowledgeIngestJobs: knowledgeIngestJobs,
    knowledgeJobsLoading: knowledgeJobsLoading,
    loadKnowledgeIngestJobs: loadKnowledgeIngestJobs,
    loadProductionTasks: loadProductionTasks,
    loadProjectModules: loadProjectModules,
    locateRepairTaskChapter: locateRepairTaskChapter,
    mergeChapterVersion: mergeChapterVersion,
    openAgentConfigEditor: openAgentConfigEditor,
    openApprovalPolicyEditor: openApprovalPolicyEditor,
    openChapterQualityCard: openChapterQualityCard,
    openContinuityAudit: openContinuityAudit,
    openEditor: openEditor,
    openGenreTemplates: openGenreTemplates,
    openLongformProductionTrends: openLongformProductionTrends,
    openMaterialRepairPlan: openMaterialRepairPlan,
    openModelDiagnostics: openModelDiagnostics,
    openProductionDesk: openProductionDesk,
    openProductionMetrics: openProductionMetrics,
    openReferenceKnowledgeDiagnosis: openReferenceKnowledgeDiagnosis,
    openRepairTaskChapterEditor: openRepairTaskChapterEditor,
    openRunQueue: openRunQueue,
    openStoryStateEditor: openStoryStateEditor,
    openWritingBibleEditor: openWritingBibleEditor,
    outlinePanelOpen: outlinePanelOpen,
    outlineTreeOpen: outlineTreeOpen,
    outlines: outlines,
    pauseKnowledgeIngestJob: pauseKnowledgeIngestJob,
    previewStyleSampleAdjustmentBatch: previewStyleSampleAdjustmentBatch,
    previewStyleSampleAdjustmentPatch: previewStyleSampleAdjustmentPatch,
    productionMode: productionMode,
    productionModeOptions: productionModeOptions,
    productionTasks: productionTasks,
    projectId: projectId,
    proseChapters: proseChapters,
    qualityBenchmarkOpen: qualityBenchmarkOpen,
    recheckRepairTaskConvergence: recheckRepairTaskConvergence,
    recheckStyleSampleTaskBookReviewTasks: recheckStyleSampleTaskBookReviewTasks,
    recoverRunQueue: recoverRunQueue,
    referenceConfigOpen: referenceConfigOpen,
    referenceEngineeringOpen: referenceEngineeringOpen,
    referenceReports: referenceReports,
    refreshConsistencyAudit: refreshConsistencyAudit,
    refreshPropagationDebt: refreshPropagationDebt,
    releaseRepairExecutingId: releaseRepairExecutingId,
    restructurePanelOpen: restructurePanelOpen,
    resumeKnowledgeIngestJob: resumeKnowledgeIngestJob,
    retryChapterGroupStage: retryChapterGroupStage,
    reviewAnnotationsOpen: reviewAnnotationsOpen,
    reviewStyleSampleAdjustmentPatch: reviewStyleSampleAdjustmentPatch,
    reviews: reviews,
    rollingBackVersionId: rollingBackVersionId,
    runCreativeCommand: runCreativeCommand,
    runFirst30RetentionDiagnosis: runFirst30RetentionDiagnosis,
    runFuture100SkeletonAudit: runFuture100SkeletonAudit,
    runLongformCreationDiagnosis: runLongformCreationDiagnosis,
    runLongformPressureTest: runLongformPressureTest,
    runMechanicalQa: runMechanicalQa,
    runMechanicalQaLlmReview: runMechanicalQaLlmReview,
    runPropagationDebtLlmPlan: runPropagationDebtLlmPlan,
    runQualityBenchmark: runQualityBenchmark,
    runRecords: runRecords,
    runReferenceMigrationPlan: runReferenceMigrationPlan,
    runRollingPlan: runRollingPlan,
    runSimilarityForActiveChapter: runSimilarityForActiveChapter,
    runTopicValidation: runTopicValidation,
    runVersionReviewForActiveChapter: runVersionReviewForActiveChapter,
    saveStoryStateEditor: saveStoryStateEditor,
    saveWritingBibleEditor: saveWritingBibleEditor,
    selectChapterForWriting: selectChapterForWriting,
    selectMode: selectMode,
    selectedChapterIds: selectedChapterIds,
    selectedChaptersList: selectedChaptersList,
    selectedModelId: selectedModelId,
    selectedProject: selectedProject,
    setAgentAuditOpen: setAgentAuditOpen,
    setAgentExecution: setAgentExecution,
    setBackupImportOpen: setBackupImportOpen,
    setBackupImportText: setBackupImportText,
    setChapterDrawerOpen: setChapterDrawerOpen,
    setChapterSearch: setChapterSearch,
    setChapterSortMode: setChapterSortMode,
    setChapterStatusFilter: setChapterStatusFilter,
    setChapterVersionDetail: setChapterVersionDetail,
    setCommercialToolsOpen: setCommercialToolsOpen,
    setConsistencyGraphOpen: setConsistencyGraphOpen,
    setCreativeCardsOpen: setCreativeCardsOpen,
    setCreativeCommandOpen: setCreativeCommandOpen,
    setCreativeCommandText: setCreativeCommandText,
    setEditorItem: setEditorItem,
    setEditorKind: setEditorKind,
    setExportDeliveryOpen: setExportDeliveryOpen,
    setFuture100Draft: setFuture100Draft,
    setFuture100FocusOutlineIds: setFuture100FocusOutlineIds,
    setFuture100SelectedNos: setFuture100SelectedNos,
    setOutlinePanelOpen: setOutlinePanelOpen,
    setOutlineTreeOpen: setOutlineTreeOpen,
    setProductionMode: setProductionMode,
    setQualityBenchmarkOpen: setQualityBenchmarkOpen,
    setReferenceConfigOpen: setReferenceConfigOpen,
    setReferenceEngineeringOpen: setReferenceEngineeringOpen,
    setRestructurePanelOpen: setRestructurePanelOpen,
    setReviewAnnotationsOpen: setReviewAnnotationsOpen,
    setRightPanelOpen: setRightPanelOpen,
    setRightPanelTab: setRightPanelTab,
    setSelectMode: setSelectMode,
    setSelectedChapterIds: setSelectedChapterIds,
    setSelectedProject: setSelectedProject,
    setShowOnlyDiff: setShowOnlyDiff,
    setStoryStateOpen: setStoryStateOpen,
    setTaskCenterOpen: setTaskCenterOpen,
    setTaskCenterRecoveryFocus: setTaskCenterRecoveryFocus,
    setUnattendedTargetChapter: setUnattendedTargetChapter,
    setWritingBibleOpen: setWritingBibleOpen,
    showOnlyDiff: showOnlyDiff,
    skipChapterGroupStage: skipChapterGroupStage,
    sortedChapters: sortedChapters,
    startFuture100ChapterGroupGeneration: startFuture100ChapterGroupGeneration,
    startReadyChapterGroupGeneration: startReadyChapterGroupGeneration,
    startRepairTaskRevision: startRepairTaskRevision,
    startRunQueueWorker: startRunQueueWorker,
    startUnattendedWritingGoal: startUnattendedWritingGoal,
    stopRunQueueWorker: stopRunQueueWorker,
    storyStateForm: storyStateForm,
    storyStateOpen: storyStateOpen,
    styleSampleCandidateLoading: styleSampleCandidateLoading,
    submitEditor: submitEditor,
    taskCenterOpen: taskCenterOpen,
    taskCenterRecoveryFocus: taskCenterRecoveryFocus,
    unattendedTargetChapter: unattendedTargetChapter,
    undoStyleSampleAdjustmentPatch: undoStyleSampleAdjustmentPatch,
    updateRepairTaskStatus: updateRepairTaskStatus,
    worldbuilding: worldbuilding,
    writingBibleForm: writingBibleForm,
    writingBibleGenerating: writingBibleGenerating,
    writingBibleOpen: writingBibleOpen,
  }
}

export function buildNovelWorkspaceTopBarProps(deps: Record<string, any>) {
  const {
    activeKnowledgeJobCount,
    activeTasks,
    flushPendingSave,
    isImmersiveShell,
    loadProjectModules,
    modelOptions,
    navigate,
    openCreativeAssistant,
    referenceSummary,
    selectedModelId,
    selectedProject,
    setSelectedModelId,
    setShellMode,
    setTaskCenterOpen,
    setWorkspaceArea,
    workspaceArea,
    workspaceAreaTabs,
  } = deps
  return {
    activeKnowledgeJobCount: activeKnowledgeJobCount,
    activeTasks: activeTasks,
    flushPendingSave: flushPendingSave,
    isImmersiveShell: isImmersiveShell,
    loadProjectModules: loadProjectModules,
    modelOptions: modelOptions,
    navigate: navigate,
    openCreativeAssistant: openCreativeAssistant,
    referenceSummary: referenceSummary,
    selectedModelId: selectedModelId,
    selectedProject: selectedProject,
    setSelectedModelId: setSelectedModelId,
    setShellMode: setShellMode,
    setTaskCenterOpen: setTaskCenterOpen,
    setWorkspaceArea: setWorkspaceArea,
    workspaceArea: workspaceArea,
    workspaceAreaTabs: workspaceAreaTabs,
  }
}
