/** Reverse-free late action handler binding for NovelProjectWorkspaceView. */
import { createStorylineDecisionHandlers } from './workspace-chapter-version-handlers'
import { createWorkspaceActionHandlers } from './workspace-action-handlers'

export function bindNovelWorkspaceActionHandlers(deps: Record<string, any>) {
  const {
    activeChapter,
    activeChapterId,
    apiClient,
    applyEditorRevision,
    autoCreationDirectorModel,
    chapterHasProse,
    chapters,
    createDeliveryRiskRepairQueue,
    createEditorReport,
    createEditorReportForChapter,
    createFirst30RetentionRepairQueue,
    createReaderTrialRepairQueue,
    createRecoveryEvidenceGovernanceQueue,
    createSafeBatchRiskRepairQueue,
    createScriptRoomRepairQueue,
    createStyleSampleBatchRepairQueue,
    generateCurrentChapterProse,
    generateSceneCardsForChapter,
    loadProductionTasks,
    loadProjectModules,
    openChapterQualityCard,
    openContinuityAudit,
    openGenerationDiagnostics,
    openLongformProductionTrends,
    openStoryAssetsWorkspace,
    openStoryStateEditor,
    openWritingBibleEditor,
    projectId,
    recentFatigueRollingPlanIntent,
    refreshActiveProseQuality,
    runRecords,
    runRollingPlan,
    selectChapterForWriting,
    selectTargetChapterForWriting,
    serialPipelineModel,
    setAutoDirectorActionLoadingKey,
    setOutlinePanelOpen,
    setOutlineTreeOpen,
    setRightPanelOpen,
    setRightPanelTab,
    setTaskCenterOpen,
    setWorkspaceArea,
    sortedChapters,
    stepGenerateProse,
    syncStoryStateForChapter,
    writingCockpitModel,
  } = deps

  const {
    recordStorylineDiffDecision,
    createStorylineDecisionTasks,
  } = createStorylineDecisionHandlers({
    apiClient,
    loadProductionTasks,
    loadProjectModules,
    projectId,
    setAutoDirectorActionLoadingKey,
    setTaskCenterOpen,
  })

  const {
    handlePlanningAction,
    acceptCockpitChapterAndContinue,
    handleWritingCockpitAction,
    runAutoCreationRepairAction,
    runAutoCreationRepairPlan,
    handleAutoCreationDirectorAction,
    handleSerialPipelineAction,
  } = createWorkspaceActionHandlers({
    activeChapter,
    activeChapterId,
    applyEditorRevision,
    autoCreationDirectorModel,
    chapterHasProse,
    chapters,
    createDeliveryRiskRepairQueue,
    createEditorReport,
    createEditorReportForChapter,
    createFirst30RetentionRepairQueue,
    createReaderTrialRepairQueue,
    createRecoveryEvidenceGovernanceQueue,
    createSafeBatchRiskRepairQueue,
    createScriptRoomRepairQueue,
    createStyleSampleBatchRepairQueue,
    generateCurrentChapterProse,
    generateSceneCardsForChapter,
    loadProductionTasks,
    loadProjectModules,
    openChapterQualityCard,
    openContinuityAudit,
    openGenerationDiagnostics,
    openLongformProductionTrends,
    openStoryAssetsWorkspace,
    openStoryStateEditor,
    openWritingBibleEditor,
    recentFatigueRollingPlanIntent,
    refreshActiveProseQuality,
    runRecords,
    runRollingPlan,
    selectChapterForWriting,
    selectTargetChapterForWriting,
    serialPipelineModel,
    setAutoDirectorActionLoadingKey,
    setOutlinePanelOpen,
    setOutlineTreeOpen,
    setRightPanelOpen,
    setRightPanelTab,
    setTaskCenterOpen,
    setWorkspaceArea,
    sortedChapters,
    stepGenerateProse,
    syncStoryStateForChapter,
    writingCockpitModel,
  })

  return {
    acceptCockpitChapterAndContinue,
    createStorylineDecisionTasks,
    handleAutoCreationDirectorAction,
    handlePlanningAction,
    handleSerialPipelineAction,
    handleWritingCockpitAction,
    recordStorylineDiffDecision,
    runAutoCreationRepairAction,
    runAutoCreationRepairPlan,
  }
}
