export function buildNovelWorkspaceTopBarProps(deps: Record<string, any>) {
  const {
    activeKnowledgeJobCount,
    activeTasks,
    assertChapterSourceOperationCurrent,
    beginChapterSourceOperation,
    chapterGenerationSourceAuthority,
    chapterSourceLocallyBusy,
    chapterSourcePendingState,
    flushPendingSave,
    isImmersiveShell,
    loadProjectModules,
    modelOptions,
    navigate,
    openCreativeAssistant,
    referenceSummary,
    selectedModelId,
    selectedProject,
    setChapterGenerationSourceAuthority,
    setChapterSourceMutationPending,
    setFictionHumanizerMode,
    setSelectedModelId,
    setShellMode,
    setTaskCenterOpen,
    setWorkspaceArea,
    setWritingSkillsEnabled,
    setWritingSkillsCatalog,
    workspaceArea,
    workspaceAreaTabs,
  } = deps
  return {
    activeKnowledgeJobCount: activeKnowledgeJobCount,
    activeTasks: activeTasks,
    assertChapterSourceOperationCurrent: assertChapterSourceOperationCurrent,
    beginChapterSourceOperation: beginChapterSourceOperation,
    chapterGenerationSourceAuthority: chapterGenerationSourceAuthority,
    chapterSourceLocallyBusy: chapterSourceLocallyBusy,
    chapterSourcePendingState: chapterSourcePendingState,
    flushPendingSave: flushPendingSave,
    isImmersiveShell: isImmersiveShell,
    loadProjectModules: loadProjectModules,
    modelOptions: modelOptions,
    navigate: navigate,
    openCreativeAssistant: openCreativeAssistant,
    referenceSummary: referenceSummary,
    selectedModelId: selectedModelId,
    selectedProject: selectedProject,
    setChapterGenerationSourceAuthority: setChapterGenerationSourceAuthority,
    setChapterSourceMutationPending: setChapterSourceMutationPending,
    setFictionHumanizerMode: setFictionHumanizerMode,
    setSelectedModelId: setSelectedModelId,
    setShellMode: setShellMode,
    setTaskCenterOpen: setTaskCenterOpen,
    setWorkspaceArea: setWorkspaceArea,
    setWritingSkillsEnabled: setWritingSkillsEnabled,
    setWritingSkillsCatalog: setWritingSkillsCatalog,
    workspaceArea: workspaceArea,
    workspaceAreaTabs: workspaceAreaTabs,
  }
}
