import type { PlanningActionKey, PlanningWorkspaceModel } from '../../planningWorkspaceModel'
import type { WritingCockpitActionKey, WritingCockpitModel } from '../../writingCockpitModel'
import { parseWorkspacePayload, type WorkspacePayloadParseOptions } from '../../payloadParseCache'
import type {
  AnyRecord,
  AutoCreationDirectorStatus,
  AutoCreationDirectorArea,
  AutoCreationDirectorActionKey,
  AutoCreationPipelineStatus,
  AutoCreationContractStatus,
  AutoCreationBatchGuardrailStatus,
  AutoCreationBatchGuardrailSignalStatus,
  AutoCreationBatchReviewStatus,
  AutoCreationBatchReviewItemStatus,
  AutoCreationBatchRiskStatus,
  AutoCreationBatchCompletionStatus,
  AutoCreationBatchCompletionMetricStatus,
  AutoCreationBatchHandoffStatus,
  AutoCreationChapterLaunchGateStatus,
  AutoCreationLongformCapacityStatus,
  AutoCreationDeliveryRiskGateStatus,
  AutoCreationManualTestReadinessStatus,
  AutoCreationDailyBattleStepKey,
  AutoCreationRollingScriptRoomStatus,
  AutoCreationRollingScriptLayerKey,
  AutoCreationMillionWordRunwayStatus,
  AutoCreationProductionLicenseStatus,
  AutoCreationDirectorAction,
  AutoCreationRepairPlan,
  AutoCreationPipelineStep,
  AutoCreationSerialStageKey,
  AutoCreationSerialWorkflowStage,
  AutoCreationDirectorCreationPipelineStage,
  AutoCreationDirectorCreationPipeline,
  AutoCreationSerialWorkflow,
  AutoCreationContractItem,
  AutoCreationLongformCompassAxis,
  AutoCreationLongformCompass,
  AutoCreationManualTestGate,
  AutoCreationManualTestReadiness,
  AutoCreationBatchGuardrailSignal,
  AutoCreationRecoveryEvidenceTrendSource,
  AutoCreationStrengthenedRepairAcceptanceTrend,
  AutoCreationRecoveryEvidenceTrend,
  AutoCreationBatchReleaseChapter,
  AutoCreationBatchReleaseWindow,
  AutoCreationBatchPreflight,
  AutoCreationBatchBriefRepair,
  AutoCreationBatchBriefRecovery,
  AutoCreationNextBatchBriefChapter,
  AutoCreationNextBatchBriefStartChecklistKey,
  AutoCreationNextBatchBriefStartChecklistItem,
  AutoCreationNextBatchBrief,
  AutoCreationLongformCapacitySignal,
  AutoCreationLongformFuelItem,
  AutoCreationLongformCapacity,
  AutoCreationChapterLaunchSignal,
  AutoCreationChapterLaunchGate,
  AutoCreationBatchGuardrail,
  AutoCreationBatchReviewItem,
  AutoCreationBatchRiskSignal,
  AutoCreationBatchChecklistExecutionItem,
  AutoCreationBatchChecklistExecution,
  AutoCreationBatchRiskRadar,
  AutoCreationBatchCompletionMetric,
  AutoCreationBatchCompletionDashboard,
  AutoCreationBatchHandoff,
  AutoCreationBatchReviewQueue,
  AutoCreationDeliveryRiskGateCategory,
  AutoCreationDeliveryRiskResolution,
  AutoCreationDeliveryRiskGate,
  AutoCreationStorylineDecisionGate,
  AutoCreationGovernanceClosureBrief,
  AutoCreationWritingQueueFocus,
  AutoCreationDailyBattleStep,
  AutoCreationDailyBattlePlan,
  AutoCreationProductionLicense,
  AutoCreationTodayCommandFlowItem,
  AutoCreationTodayQualityGate,
  AutoCreationGovernanceRecheckMemoryStatus,
  AutoCreationGovernanceRecheckMemory,
  AutoCreationReleaseRationale,
  AutoCreationTodayCommandDeck,
  AutoCreationSerialCockpitStatus,
  AutoCreationChapterChainStatus,
  AutoCreationSerialGuardrail,
  AutoCreationChapterChainStep,
  AutoCreationRiskQueueItem,
  AutoCreationSerialCockpit,
  AutoCreationMillionWordRunwayGate,
  AutoCreationMillionWordRunwayQuestion,
  AutoCreationMillionWordRunway,
  AutoCreationRollingScriptLayer,
  AutoCreationRollingScriptRoom,
  AutoCreationDirectorModel,
  BuildAutoCreationDirectorModelInput
} from './types'
import {
  BATCH_DELIVERY_QUALITY_THRESHOLD,
  batchRepairTask,
  batchRiskIssueResolved,
  batchRiskIssueResolvedForBatch,
  buildAssetGrowthReview,
  buildBatchPlanReview,
  buildChapterAttractionReview,
  buildChapterBenchmarkReview,
  buildChapterHandoffReview,
  buildCharacterArcReview,
  buildContractSyncReview,
  buildInnovationExecutionReview,
  buildReaderPullReview,
  buildRecoveryEvidenceReview,
  buildSerialRhythmReview,
  buildStoryDriveReview,
  buildStrengthenedRepairAcceptanceReview,
  buildStyleSampleReview,
  buildVolumeSegmentReview,
  chapterAttractionRiskCount,
  chapterBenchmarkRiskCount,
  characterArcRiskCount,
  contractSyncRiskCount,
  coreRiskCount,
  expectationRiskCount,
  findChapter,
  innovationRiskCount,
  latestQualityReviewForChapter,
  latestReaderTrialReview,
  latestReviewForChapter,
  numberValue,
  payoffDebtCount,
  qualityPayload,
  readabilityRiskCount,
  readerTrialAppliesToBatch,
  readerTrialBatchReview,
  recoveryEvidenceReview,
  retentionRiskCount,
  riskPayload,
  runwayRiskCount,
  signal,
  signatureSceneRiskCount,
  storyDriveRiskCount,
  storylineRiskCount,
  styleSampleRiskCount,
  volumeSegmentRiskCount,
} from './helpers-main'
import {
  buildDefaultFiveChapterLaneTemplateRedesignQueue,
  buildDefaultFiveChapterLaneTemplateRepair,
  buildSafeBatchExpansionStructureReview,
  buildSafeBatchExpansionStructureValidationResult,
  safeBatchExpansionRollbackPolicy,
  safeBatchExpansionSegmentReviewSnapshot,
} from './helpers-safe-batch-recovery'
import {
  batchBriefAppliesToItem,
  batchBriefVisible,
  buildBatchChecklistExecution,
  buildBatchPlanContext,
  buildRecoveryEvidenceRegovernanceQueue,
  buildSafeBatchExpansionSegmentReview,
  buildSafeBatchExpansionStructureDecisionExecutionReview,
  first30RetentionRisk,
  normalizePostBatchQualityCheck,
  safeBatchExpansionSegmentResolvedForItems,
} from './helpers-safe-batch-expansion-structure'
import {
  arrayValue,
  firstText,
  text,
} from './helpers-basics'

import { buildBatchRiskRadarCompute } from './helpers-batch-risk-radar-compute'
import { buildBatchRiskRadarFromCompute } from './helpers-batch-risk-radar-signals'

export function buildBatchRiskRadar(args: {
  items: AutoCreationBatchReviewItem[]
  chapters: AnyRecord[]
  reviews: AnyRecord[]
  planning?: PlanningWorkspaceModel | null
  resolvedIssueKeys?: Set<string>
  nextBatchBrief?: AnyRecord | null
  batchPreflight?: AnyRecord | null
  expansionFeedback?: AnyRecord | null
  postBatchQualityCheck?: AnyRecord | null
}): AutoCreationBatchRiskRadar {
  const ctx = buildBatchRiskRadarCompute(args)
  return buildBatchRiskRadarFromCompute(args, ctx)
}
