export const UI_COPY = {
  appName: 'MangaForge Studio',
  dashboardTitle: '我的创作空间',
  dashboardSubtitle: '集中管理你的项目、灵感和创作进度。',
  newProject: '新建项目',
  projectListEmpty: '暂无项目，点击右上角创建一个。',
  enterWorkspace: '进入工作台',
  novelStudioTitle: '小说工作台',
  novelStudioSubtitle: '左侧目录，右侧正文编辑区。',
  pipelineTitle: '流程工作台',
  pipelineSubtitle: '用于预检工作区，并执行完整流程。',
  canvasTitle: '画布工作台',
  canvasSubtitle: '可拖拽资产到画布，或双击空白处呼出搜索菜单。',
  save: '保存',
  refresh: '刷新',
  create: '创建',
  update: '保存修改',
  running: '运行中',
  completed: '已完成',
  failed: '失败',
  stopped: '已停止',
  saved: '已保存',
  unsaved: '未保存',
  realProse: '真实正文',
  pendingProse: '待生成正文',
  placeholderProse: '占位正文',
  executeGeneration: '执行生成',
  generatePlan: '生成规划',
  executeRepair: '执行修复',
  globalRun: '全局运行',
  continueRun: '继续运行',
  comicGenerate: '漫剧生成',
} as const

export const STATUS_LABELS = {
  content: {
    real: UI_COPY.realProse,
    pending: UI_COPY.pendingProse,
    placeholder: UI_COPY.placeholderProse,
  },
  runtime: {
    running: UI_COPY.running,
    completed: UI_COPY.completed,
    failed: UI_COPY.failed,
    stopped: UI_COPY.stopped,
  },
  editor: {
    saved: UI_COPY.saved,
    unsaved: UI_COPY.unsaved,
  },
} as const
