/** Compatibility barrel for novel persistence internals. */
export * from './json'
export * from './paths'
export * from './storage-compaction'
export * from './lock'
export * from './db'
export * from './row-mappers'
export * from './legacy-store'
export * from './sql-rows'
export * from './normalize'
export * from './pipeline-sql'
export * from './chapter-helpers'
export * from './acceptance-helpers'
export type * from './types'
