import {
  mergeSceneCardStringList,
} from './scene-card-delivery-risk'
import {
  applyDeliveryRiskCarryOverPhaseA,
} from './scene-card-delivery-risk-apply-card-phase-a'
import {
  applyDeliveryRiskCarryOverPhaseB,
} from './scene-card-delivery-risk-apply-card-phase-b'

export function applyDeliveryRiskCarryOverToSceneCard(
  card: any,
  index: number,
  ctx: Record<string, any>,
) {
  const {
    openingActions,
    middleActions,
    endingActions,
    forbiddenRepeats,
    styleDirectiveActions,
    dialogueGoalActions,
    characterBehaviorActions,
    benchmarkRecallDirectiveActions,
    proseCraftDirectiveActions,
    wordCountActions,
    qualityAuditDirectiveActions,
    assetLinkageActions,
    settingViolationActions,
    assetIntakeActions,
    ipSceneIntakeActions,
    stateTrackingActions,
    statusFilterActions,
    informationFlowActions,
    expectationHookActions,
    chapterHookQualityActions,
    suspenseActions,
    reversalActions,
    showdownActions,
    bridgeUnitActions,
    beatCoolingActions,
    plotDynamicsActions,
    characterRelationActions,
    storyLoopActions,
    emotionalArcActions,
    readerRetentionActions,
    readerPayoffActions,
    chapterAttractionActions,
    storyDriveActions,
    storylineActions,
    characterArcActions,
    innovationActions,
    volumeBeatActions,
    coreDriftActions,
    timelineDeltaActions,
    characterStateDeltaActions,
    assetStateDeltaActions,
    relationshipDeltaActions,
    chapterHandoffDeltaActions,
    revisionCascadeActions,
    revisionContextActions,
    proseRevisionReceiptActions,
    revisionReceiptCheckActions,
    deliveryReceiptActions,
    revisionScopeGuardActions,
    revisionDirectiveActions,
    focusedRevisionModeActions,
    focusedRevisionHookActions,
    focusedRevisionSettingActions,
    craftMetricActions,
    craftMetricActionActions,
    craftMetricDescriptionActions,
    craftMetricSettingActions,
    fiveDimensionScoreActions,
    fiveDimensionCoreActions,
    fiveDimensionSurfaceActions,
    fiveDimensionLogicActions,
    qualitySpecialtyActions,
    qualityStructureActions,
    qualityProgressionActions,
    qualityInformationActions,
    platformContentRubricActions,
    platformRubricActions,
    contentRubricActions,
    deterministicCleanupActions,
    bannedWordActions,
    deslopRepairReceiptActions,
    readabilityActions,
    governanceRecheckActions,
    chapterTitleActions,
    qualityGateActions,
    qualityAuditRepairReceiptActions,
    qualityPlanReceiptActions,
    serialRiskRepairActions,
    sceneCardReceiptActions,
    perspectiveReviewActions,
    targetReaderActions,
    conflictStructureActions,
    genrePositioningActions,
    upgradeRhythmActions,
    continuityHeatActions,
    sourceReadinessActions,
    writePreparationActions,
    intentConfirmationActions,
    chapterBlueprintActions,
    blueprintConsumptionActions,
    coreContractActions,
    femaleAudienceActions,
    chapterBenchmarkActions,
    runwayActions,
    longformActions,
    signatureSceneActions,
    storyUnitActions,
    chapterHandoffActions,
    openingDesignActions,
    paragraphHookActions,
    proseMetaActions,
    punctuationToneActions,
    styleBoundaryActions,
    styleSampleReceiptActions,
    payoffSetupActions,
    spectatorReactionActions,
    foreshadowingDeltaActions,
    conceptAnchorActions,
    firstIndex,
    middleIndex,
    lastIndex,
    qualityTags,
    actionIndexes,
  } = ctx

    if (!actionIndexes.has(index) && !styleDirectiveActions.length && !dialogueGoalActions.length && !characterBehaviorActions.length && !characterRelationActions.length && !benchmarkRecallDirectiveActions.length && !proseCraftDirectiveActions.length && !qualityAuditDirectiveActions.length && !assetLinkageActions.length && !assetIntakeActions.length && !ipSceneIntakeActions.length && !stateTrackingActions.length && !statusFilterActions.length && !informationFlowActions.length && !expectationHookActions.length && !suspenseActions.length && !reversalActions.length && !showdownActions.length && !bridgeUnitActions.length && !beatCoolingActions.length && !plotDynamicsActions.length && !storyLoopActions.length && !emotionalArcActions.length && !readerRetentionActions.length && !readerPayoffActions.length && !chapterAttractionActions.length && !storyDriveActions.length && !storylineActions.length && !characterArcActions.length && !innovationActions.length && !volumeBeatActions.length && !coreDriftActions.length && !timelineDeltaActions.length && !characterStateDeltaActions.length && !assetStateDeltaActions.length && !relationshipDeltaActions.length && !chapterHandoffDeltaActions.length && !revisionCascadeActions.length && !revisionContextActions.length && !proseRevisionReceiptActions.length && !deliveryReceiptActions.length && !revisionScopeGuardActions.length && !revisionDirectiveActions.length && !focusedRevisionModeActions.length && !craftMetricActions.length && !fiveDimensionScoreActions.length && !qualitySpecialtyActions.length && !platformContentRubricActions.length && !deterministicCleanupActions.length && !bannedWordActions.length && !deslopRepairReceiptActions.length && !readabilityActions.length && !governanceRecheckActions.length && !chapterTitleActions.length && !qualityGateActions.length && !qualityAuditRepairReceiptActions.length && !qualityPlanReceiptActions.length && !serialRiskRepairActions.length && !sceneCardReceiptActions.length && !perspectiveReviewActions.length && !targetReaderActions.length && !conflictStructureActions.length && !genrePositioningActions.length && !upgradeRhythmActions.length && !continuityHeatActions.length && !sourceReadinessActions.length && !writePreparationActions.length && !intentConfirmationActions.length && !chapterBlueprintActions.length && !coreContractActions.length && !femaleAudienceActions.length && !chapterBenchmarkActions.length && !runwayActions.length && !signatureSceneActions.length && !storyUnitActions.length && !chapterHandoffActions.length && !openingDesignActions.length && !paragraphHookActions.length && !proseMetaActions.length && !punctuationToneActions.length && !styleBoundaryActions.length && !styleSampleReceiptActions.length && !payoffSetupActions.length && !spectatorReactionActions.length && !foreshadowingDeltaActions.length && !conceptAnchorActions.length) return card
    let next = { ...card }
    const stagedActions = [
      ...(index === firstIndex ? openingActions : []),
      ...(index === middleIndex ? middleActions : []),
      ...(index === lastIndex ? endingActions : []),
    ]

  const phaseCtx = { ...ctx, stagedActions }
  next = applyDeliveryRiskCarryOverPhaseA(next, index, phaseCtx)
  next = applyDeliveryRiskCarryOverPhaseB(next, index, phaseCtx)
  return next
}
